.TH "_lv_obj_class_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_obj_class_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_obj_class\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const struct \fB_lv_obj_class_t\fP * \fBbase_class\fP"
.br
.ti -1c
.RI "void(* \fBconstructor_cb\fP )(const struct \fB_lv_obj_class_t\fP *class_p, struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "void(* \fBdestructor_cb\fP )(const struct \fB_lv_obj_class_t\fP *class_p, struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "void(* \fBevent_cb\fP )(const struct \fB_lv_obj_class_t\fP *class_p, struct \fB_lv_event_t\fP *e)"
.br
.ti -1c
.RI "lv_coord_t \fBwidth_def\fP"
.br
.ti -1c
.RI "lv_coord_t \fBheight_def\fP"
.br
.ti -1c
.RI "uint32_t \fBeditable\fP: 2"
.br
.ti -1c
.RI "uint32_t \fBgroup_def\fP: 2"
.br
.ti -1c
.RI "uint32_t \fBinstance_size\fP: 16"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describe the common methods of every object\&. Similar to a C++ class\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint32_t _lv_obj_class_t::editable"
Value from \fBlv_obj_class_editable_t\fP 
.SS "void(* _lv_obj_class_t::event_cb) (const struct \fB_lv_obj_class_t\fP *class_p, struct \fB_lv_event_t\fP *e)"
Widget type specific event function 
.SS "uint32_t _lv_obj_class_t::group_def"
Value from \fBlv_obj_class_group_def_t\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
