.TH "_lv_disp_draw_buf_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_disp_draw_buf_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_hal_disp\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBbuf1\fP"
.br
.ti -1c
.RI "void * \fBbuf2\fP"
.br
.ti -1c
.RI "void * \fBbuf_act\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "volatile int \fBflushing\fP"
.br
.ti -1c
.RI "volatile int \fBflushing_last\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBlast_area\fP: 1"
.br
.ti -1c
.RI "volatile uint32_t \fBlast_part\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for holding display buffer information\&. 
.SH "Member Data Documentation"
.PP 
.SS "void* _lv_disp_draw_buf_t::buf1"
First display buffer\&. 
.SS "void* _lv_disp_draw_buf_t::buf2"
Second display buffer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
