.TH "_lv_draw_label_hint_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_draw_label_hint_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_draw_label\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBline_start\fP"
.br
.ti -1c
.RI "int32_t \fBy\fP"
.br
.ti -1c
.RI "int32_t \fBcoord_y\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Store some info to speed up drawing of very large texts It takes a lot of time to get the first visible character because all the previous characters needs to be checked to calculate the positions\&. This structure stores an earlier (e\&.g\&. at -1000 px) coordinate and the index of that line\&. Therefore the calculations can start from here\&. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t _lv_draw_label_hint_t::coord_y"
The 'y1' coordinate of the label when the hint was saved\&. Used to invalidate the hint if the label has moved too much\&. 
.SS "int32_t _lv_draw_label_hint_t::line_start"
Index of the line at \fR\fBy\fP\fP coordinate 
.SS "int32_t _lv_draw_label_hint_t::y"
Give the \fR\fBy\fP\fP coordinate of the first letter at \fRline start\fP index\&. Relative to the label's coordinates 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
