.TH "_lv_obj_style_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_obj_style_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlv_style_t\fP * \fBstyle\fP"
.br
.ti -1c
.RI "uint32_t \fBselector\fP: 24"
.br
.ti -1c
.RI "uint32_t \fBis_local\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBis_trans\fP: 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
