.TH "_lv_fs_drv_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_fs_drv_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBletter\fP"
.br
.ti -1c
.RI "uint16_t \fBcache_size\fP"
.br
.ti -1c
.RI "bool(* \fBready_cb\fP )(struct \fB_lv_fs_drv_t\fP *drv)"
.br
.ti -1c
.RI "void *(* \fBopen_cb\fP )(struct \fB_lv_fs_drv_t\fP *drv, const char *path, lv_fs_mode_t mode)"
.br
.ti -1c
.RI "lv_fs_res_t(* \fBclose_cb\fP )(struct \fB_lv_fs_drv_t\fP *drv, void *file_p)"
.br
.ti -1c
.RI "lv_fs_res_t(* \fBread_cb\fP )(struct \fB_lv_fs_drv_t\fP *drv, void *file_p, void *buf, uint32_t btr, uint32_t *br)"
.br
.ti -1c
.RI "lv_fs_res_t(* \fBwrite_cb\fP )(struct \fB_lv_fs_drv_t\fP *drv, void *file_p, const void *buf, uint32_t btw, uint32_t *bw)"
.br
.ti -1c
.RI "lv_fs_res_t(* \fBseek_cb\fP )(struct \fB_lv_fs_drv_t\fP *drv, void *file_p, uint32_t pos, \fBlv_fs_whence_t\fP whence)"
.br
.ti -1c
.RI "lv_fs_res_t(* \fBtell_cb\fP )(struct \fB_lv_fs_drv_t\fP *drv, void *file_p, uint32_t *pos_p)"
.br
.ti -1c
.RI "void *(* \fBdir_open_cb\fP )(struct \fB_lv_fs_drv_t\fP *drv, const char *path)"
.br
.ti -1c
.RI "lv_fs_res_t(* \fBdir_read_cb\fP )(struct \fB_lv_fs_drv_t\fP *drv, void *rddir_p, char *fn)"
.br
.ti -1c
.RI "lv_fs_res_t(* \fBdir_close_cb\fP )(struct \fB_lv_fs_drv_t\fP *drv, void *rddir_p)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
