.TH "_lv_timer_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_timer_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_timer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBperiod\fP"
.br
.ti -1c
.RI "uint32_t \fBlast_run\fP"
.br
.ti -1c
.RI "\fBlv_timer_cb_t\fP \fBtimer_cb\fP"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "int32_t \fBrepeat_count\fP"
.br
.ti -1c
.RI "uint32_t \fBpaused\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Descriptor of a lv_timer 
.SH "Member Data Documentation"
.PP 
.SS "uint32_t _lv_timer_t::last_run"
Last time the timer ran 
.SS "uint32_t _lv_timer_t::period"
How often the timer should run 
.SS "int32_t _lv_timer_t::repeat_count"
1: One time; -1 : infinity; n>0: residual times 
.SS "\fBlv_timer_cb_t\fP _lv_timer_t::timer_cb"
Timer function 
.SS "void* _lv_timer_t::user_data"
Custom user data 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
