.TH "_lv_obj_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_obj_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBlv_obj_class_t\fP * \fBclass_p\fP"
.br
.ti -1c
.RI "struct \fB_lv_obj_t\fP * \fBparent\fP"
.br
.ti -1c
.RI "\fB_lv_obj_spec_attr_t\fP * \fBspec_attr\fP"
.br
.ti -1c
.RI "\fB_lv_obj_style_t\fP * \fBstyles\fP"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "\fBlv_area_t\fP \fBcoords\fP"
.br
.ti -1c
.RI "lv_obj_flag_t \fBflags\fP"
.br
.ti -1c
.RI "lv_state_t \fBstate\fP"
.br
.ti -1c
.RI "uint16_t \fBlayout_inv\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBscr_layout_inv\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBskip_trans\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBstyle_cnt\fP: 6"
.br
.ti -1c
.RI "uint16_t \fBh_layout\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBw_layout\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/core/lv_event\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
