.TH "_lv_img_decoder_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_img_decoder_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlv_img_decoder_info_f_t\fP \fBinfo_cb\fP"
.br
.ti -1c
.RI "\fBlv_img_decoder_open_f_t\fP \fBopen_cb\fP"
.br
.ti -1c
.RI "\fBlv_img_decoder_read_line_f_t\fP \fBread_line_cb\fP"
.br
.ti -1c
.RI "\fBlv_img_decoder_close_f_t\fP \fBclose_cb\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
