.TH "_lv_event_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_event_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fB_lv_obj_t\fP * \fBtarget\fP"
.br
.ti -1c
.RI "struct \fB_lv_obj_t\fP * \fBcurrent_target\fP"
.br
.ti -1c
.RI "\fBlv_event_code_t\fP \fBcode\fP"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "void * \fBparam\fP"
.br
.ti -1c
.RI "struct \fB_lv_event_t\fP * \fBprev\fP"
.br
.ti -1c
.RI "uint8_t \fBdeleted\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBstop_processing\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBstop_bubbling\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/core/lv_event\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
