.TH "_lv_indev_drv_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_indev_drv_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_hal_indev\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlv_indev_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "void(* \fBread_cb\fP )(struct \fB_lv_indev_drv_t\fP *indev_drv, \fBlv_indev_data_t\fP *data)"
.br
.ti -1c
.RI "void(* \fBfeedback_cb\fP )(struct \fB_lv_indev_drv_t\fP *, uint8_t)"
.br
.ti -1c
.RI "struct \fB_lv_disp_t\fP * \fBdisp\fP"
.br
.ti -1c
.RI "\fBlv_timer_t\fP * \fBread_timer\fP"
.br
.ti -1c
.RI "uint8_t \fBscroll_limit\fP"
.br
.ti -1c
.RI "uint8_t \fBscroll_throw\fP"
.br
.ti -1c
.RI "uint8_t \fBgesture_min_velocity\fP"
.br
.ti -1c
.RI "uint8_t \fBgesture_limit\fP"
.br
.ti -1c
.RI "uint16_t \fBlong_press_time\fP"
.br
.ti -1c
.RI "uint16_t \fBlong_press_repeat_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Initialized by the user and registered by 'lv_indev_add()' 
.SH "Member Data Documentation"
.PP 
.SS "struct \fB_lv_disp_t\fP* _lv_indev_drv_t::disp"
Timer to periodically read the input device 
.SS "void(* _lv_indev_drv_t::feedback_cb) (struct \fB_lv_indev_drv_t\fP *, uint8_t)"
Called when an action happened on the input device\&. The second parameter is the event from \fRlv_event_t\fP Pointer to the assigned display 
.SS "uint8_t _lv_indev_drv_t::gesture_limit"
Long press time in milliseconds 
.SS "uint8_t _lv_indev_drv_t::gesture_min_velocity"
At least this difference should be to send a gesture 
.SS "uint16_t _lv_indev_drv_t::long_press_time"
Repeated trigger period in long press [ms] 
.SS "\fBlv_timer_t\fP* _lv_indev_drv_t::read_timer"
Number of pixels to slide before actually drag the object 
.SS "uint8_t _lv_indev_drv_t::scroll_limit"
Drag throw slow-down in [%]\&. Greater value means faster slow-down 
.SS "uint8_t _lv_indev_drv_t::scroll_throw"
At least this difference should be between two points to evaluate as gesture 
.SS "\fBlv_indev_type_t\fP _lv_indev_drv_t::type"
< Input device type Function pointer to read input device data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
