.TH "_lv_theme_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_theme_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_theme_apply_cb_t \fBapply_cb\fP"
.br
.ti -1c
.RI "struct \fB_lv_theme_t\fP * \fBparent\fP"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "struct \fB_lv_disp_t\fP * \fBdisp\fP"
.br
.ti -1c
.RI "lv_color_t \fBcolor_primary\fP"
.br
.ti -1c
.RI "lv_color_t \fBcolor_secondary\fP"
.br
.ti -1c
.RI "const \fBlv_font_t\fP * \fBfont_small\fP"
.br
.ti -1c
.RI "const \fBlv_font_t\fP * \fBfont_normal\fP"
.br
.ti -1c
.RI "const \fBlv_font_t\fP * \fBfont_large\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fB_lv_theme_t\fP* _lv_theme_t::parent"
Apply the current theme's style on top of this theme\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
