.TH "_lv_draw_layer_ctx_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_draw_layer_ctx_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlv_area_t\fP \fBarea_full\fP"
.br
.ti -1c
.RI "\fBlv_area_t\fP \fBarea_act\fP"
.br
.ti -1c
.RI "lv_coord_t \fBmax_row_with_alpha\fP"
.br
.ti -1c
.RI "lv_coord_t \fBmax_row_with_no_alpha\fP"
.br
.ti -1c
.RI "void * \fBbuf\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   const \fBlv_area_t\fP * \fBclip_area\fP"
.br
.ti -1c
.RI "   \fBlv_area_t\fP * \fBbuf_area\fP"
.br
.ti -1c
.RI "   void * \fBbuf\fP"
.br
.ti -1c
.RI "   bool \fBscreen_transp\fP"
.br
.ti -1c
.RI "} \fBoriginal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
