.TH "_lv_draw_sdl_layer_ctx_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lv_draw_sdl_layer_ctx_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_draw_layer_ctx_t \fBbase\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBorig_target\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBtarget\fP"
.br
.ti -1c
.RI "SDL_Rect \fBtarget_rect\fP"
.br
.ti -1c
.RI "lv_draw_layer_flags_t \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
