.TH "include/pros/abstract_motor.hpp" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/abstract_motor.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include 'pros/device\&.hpp'\fP
.br
\fR#include 'pros/motors\&.h'\fP
.br
\fR#include 'rtos\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::v5::AbstractMotor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpros\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBpros::MotorUnits\fP = MotorEncoderUnits"
.br
.ti -1c
.RI "using \fBpros::MotorGearset\fP = MotorGears"
.br
.ti -1c
.RI "using \fBpros::MotorCart\fP = MotorGears"
.br
.ti -1c
.RI "using \fBpros::MotorCartridge\fP = MotorGears"
.br
.ti -1c
.RI "using \fBpros::MotorGear\fP = MotorGears"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBpros::MotorBrake\fP { \fBpros::coast\fP = 0, \fBpros::brake\fP = 1, \fBpros::hold\fP = 2, \fBpros::invalid\fP = INT32_MAX }"
.br
.ti -1c
.RI "enum class \fBpros::MotorEncoderUnits\fP { \fBpros::degrees\fP = 0, \fBpros::deg\fP = 0, \fBpros::rotations\fP = 1, \fBpros::counts\fP = 2, \fBpros::invalid\fP = INT32_MAX }"
.br
.ti -1c
.RI "enum class \fBpros::MotorGears\fP { \fBpros::ratio_36_to_1\fP = 0, \fBpros::red\fP = ratio_36_to_1, \fBpros::rpm_100\fP = ratio_36_to_1, \fBpros::ratio_18_to_1\fP = 1, \fBpros::green\fP = ratio_18_to_1, \fBpros::rpm_200\fP = ratio_18_to_1, \fBpros::ratio_6_to_1\fP = 2, \fBpros::blue\fP = ratio_6_to_1, \fBpros::rpm_600\fP = ratio_6_to_1, \fBpros::invalid\fP = INT32_MAX }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains prototypes for AbstractMotor, the abstract base class of both motors and motor groups\&. Abstract motors cannot be directly constructed, but you can use motors and motor groups as abstract motors\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2017-2023, Purdue University ACM SIGBots\&. All rights reserved\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
