.TH "include/api.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/api.h
.SH SYNOPSIS
.br
.PP
\fR#include <errno\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include 'pros/adi\&.h'\fP
.br
\fR#include 'pros/colors\&.h'\fP
.br
\fR#include 'pros/device\&.h'\fP
.br
\fR#include 'pros/distance\&.h'\fP
.br
\fR#include 'pros/error\&.h'\fP
.br
\fR#include 'pros/ext_adi\&.h'\fP
.br
\fR#include 'pros/gps\&.h'\fP
.br
\fR#include 'pros/imu\&.h'\fP
.br
\fR#include 'pros/link\&.h'\fP
.br
\fR#include 'pros/llemu\&.h'\fP
.br
\fR#include 'pros/misc\&.h'\fP
.br
\fR#include 'pros/motors\&.h'\fP
.br
\fR#include 'pros/optical\&.h'\fP
.br
\fR#include 'pros/rotation\&.h'\fP
.br
\fR#include 'pros/rtos\&.h'\fP
.br
\fR#include 'pros/screen\&.h'\fP
.br
\fR#include 'pros/vision\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPROS_VERSION_MAJOR\fP   4"
.br
.ti -1c
.RI "#define \fBPROS_VERSION_MINOR\fP   1"
.br
.ti -1c
.RI "#define \fBPROS_VERSION_PATCH\fP   1"
.br
.ti -1c
.RI "#define \fBPROS_VERSION_STRING\fP   '4\&.1\&.1'"
.br
.in -1c
.SH "Detailed Description"
.PP 
PROS API header provides high-level user functionality

.PP
Contains declarations for use by typical VEX programmers using PROS\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2017-2023, Purdue University ACM SIGBots\&. All rights reserved\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
