.TH "c-device" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c-device \- VEX Generic Device C API (For Advanced Users)
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBv5_device_e\fP \fBv5_device_e_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBv5_device_e\fP { \fBE_DEVICE_NONE\fP = 0, \fBE_DEVICE_MOTOR\fP = 2, \fBE_DEVICE_ROTATION\fP = 4, \fBE_DEVICE_IMU\fP = 6, \fBE_DEVICE_DISTANCE\fP = 7, \fBE_DEVICE_RADIO\fP = 8, \fBE_DEVICE_VISION\fP = 11, \fBE_DEVICE_ADI\fP = 12, \fBE_DEVICE_OPTICAL\fP = 16, \fBE_DEVICE_GPS\fP = 20, \fBE_DEVICE_SERIAL\fP = 129, \fB__attribute__\fP =((deprecated("use E_DEVICE_SERIAL instead"))) = E_DEVICE_SERIAL, \fBE_DEVICE_UNDEFINED\fP = 255 }"
.br
.RI "List of possible v5 devices\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "v5_device_e_t \fBget_plugged_type\fP (uint8_t port)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBNote\fP
.RS 4
These functions can be used for dynamic device instantiation\&.   
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBv5_device_e\fP"

.PP
List of possible v5 devices\&. This list contains all current V5 Devices, and mirrors V5_DeviceType from the api\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIE_DEVICE_NONE \fP
No device is plugged into the port\&. 
.TP
\f(BIE_DEVICE_MOTOR \fP
A motor is plugged into the port\&. 
.TP
\f(BIE_DEVICE_ROTATION \fP
A rotation sensor is plugged into the port\&. 
.TP
\f(BIE_DEVICE_IMU \fP
An inertial sensor is plugged into the port\&. 
.TP
\f(BIE_DEVICE_DISTANCE \fP
A distance sensor is plugged into the port\&. 
.TP
\f(BIE_DEVICE_RADIO \fP
A radio is plugged into the port\&. 
.TP
\f(BIE_DEVICE_VISION \fP
A vision sensor is plugged into the port\&. 
.TP
\f(BIE_DEVICE_ADI \fP
This port is an ADI expander\&. 
.TP
\f(BIE_DEVICE_OPTICAL \fP
An optical sensor is plugged into the port\&. 
.TP
\f(BIE_DEVICE_GPS \fP
A GPS sensor is plugged into the port\&. 
.TP
\f(BIE_DEVICE_SERIAL \fP
A serial device is plugged into the port\&. 
.TP
\f(BIE_DEVICE_UNDEFINED \fP
The device type is not defined, or is not a valid device\&. 
.SH "Function Documentation"
.PP 
.SS "v5_device_e_t get_plugged_type (uint8_t port)"
Gets the type of device on given port\&.

.PP
\fBReturns\fP
.RS 4
The device type as an enum\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
