.TH "c-gps" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c-gps \- VEX GPS Sensor C API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgps\&.h\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBgps_raw_s\fP"
.br
.ti -1c
.RI "struct \fBgps_position_s_t\fP"
.br
.ti -1c
.RI "struct \fBgps_status_s_t\fP"
.br
.ti -1c
.RI "struct \fBgps_orientation_s_t\fP"
.br
.ti -1c
.RI "struct \fBgps_accel_s_t\fP"
.br
.ti -1c
.RI "struct \fBgps_gyro_s_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBgps_raw_s\fP \fBgps_accel_s_t\fP"
.br
.ti -1c
.RI "typedef struct \fBgps_raw_s\fP \fBgps_gyro_s_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__)) gps_position_s"
.br
.ti -1c
.RI "int32_t \fBgps_initialize_full\fP (uint8_t port, double xInitial, double yInitial, double headingInitial, double xOffset, double yOffset)"
.br
.ti -1c
.RI "int32_t \fBgps_set_offset\fP (uint8_t port, double xOffset, double yOffset)"
.br
.ti -1c
.RI "\fBgps_position_s_t\fP \fBgps_get_offset\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBgps_set_position\fP (uint8_t port, double xInitial, double yInitial, double headingInitial)"
.br
.ti -1c
.RI "int32_t \fBgps_set_data_rate\fP (uint8_t port, uint32_t rate)"
.br
.ti -1c
.RI "double \fBgps_get_error\fP (uint8_t port)"
.br
.ti -1c
.RI "\fBgps_status_s_t\fP \fBgps_get_position_and_orientation\fP (uint8_t port)"
.br
.ti -1c
.RI "\fBgps_position_s_t\fP \fBgps_get_position\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_position_x\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_position_y\fP (uint8_t port)"
.br
.ti -1c
.RI "\fBgps_orientation_s_t\fP \fBgps_get_orientation\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_pitch\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_roll\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_yaw\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_heading\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_heading_raw\fP (uint8_t port)"
.br
.ti -1c
.RI "\fBgps_gyro_s_t\fP \fBgps_get_gyro_rate\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_gyro_rate_x\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_gyro_rate_y\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_gyro_rate_z\fP (uint8_t port)"
.br
.ti -1c
.RI "\fBgps_accel_s_t\fP \fBgps_get_accel\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_accel_x\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_accel_y\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBgps_get_accel_z\fP (uint8_t port)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgps_position_s_t\fP"
.br
.ti -1c
.RI "\fBgps_status_s_t\fP"
.br
.ti -1c
.RI "\fBgps_orientation_s_t\fP"
.br
.ti -1c
.RI "double \fBgps_raw_s::x\fP"
.br
.RI "Perceived Pitch based on GPS + IMU\&. "
.ti -1c
.RI "double \fBgps_raw_s::y\fP"
.br
.RI "Perceived Roll based on GPS + IMU\&. "
.ti -1c
.RI "double \fBgps_raw_s::z\fP"
.br
.RI "Perceived Yaw based on GPS + IMU\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBNote\fP
.RS 4
For a pros-specific usage guide on the GPS, please check out our article \fBhere\&.\fP
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "struct __attribute__ ((__packed__) )"
X Position (meters)

.PP
Y Position (meters)

.PP
X Position (meters)

.PP
Y Position (meters)

.PP
Perceived Pitch based on GPS + IMU

.PP
Perceived Roll based on GPS + IMU

.PP
Perceived Yaw based on GPS + IMU

.PP
Perceived Pitch based on GPS + IMU

.PP
Perceived Roll based on GPS + IMU

.PP
Perceived Yaw based on GPS + IMU
.SS "\fBgps_accel_s_t\fP gps_get_accel (uint8_t port)"
Get the GPS's raw accelerometer values

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS's port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
A struct (\fBgps_accel_s_t\fP) containing values mentioned above\&. If the operation failed, all the structure's members are filled with PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_accel_x (uint8_t port)"
Get the GPS's raw accelerometer value in x-axis

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS's port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The raw accelerometer value in x-axis\&. If the operation fails, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_accel_y (uint8_t port)"
Get the GPS's raw accelerometer value in y-axis

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS's port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The raw accelerometer value in y-axis\&. If the operation fails, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_accel_z (uint8_t port)"
Get the GPS's raw accelerometer value in z-axis

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS's port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The raw accelerometer value in z-axis\&. If the operation fails, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_error (uint8_t port)"
Get the possible RMS (Root Mean Squared) error in meters for GPS position\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
Possible RMS (Root Mean Squared) error in meters for GPS position\&. If the operation failed, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBgps_gyro_s_t\fP gps_get_gyro_rate (uint8_t port)"
Get the GPS's raw gyroscope values

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
A struct (\fBgps_gyro_s_t\fP) containing values mentioned above\&. If the operation failed, all the structure's members are filled with PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_gyro_rate_x (uint8_t port)"
Get the GPS's raw gyroscope value in x-axis

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The raw gyroscope value in x-axis\&. If the operation fails, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_gyro_rate_y (uint8_t port)"
Get the GPS's raw gyroscope value in y-axis

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The raw gyroscope value in y-axis\&. If the operation fails, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_gyro_rate_z (uint8_t port)"
Get the GPS's raw gyroscope value in z-axis

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The raw gyroscope value in z-axis\&. If the operation fails, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_heading (uint8_t port)"
Get the heading in [0,360) degree values\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
The heading in [0,360) degree values\&. If the operation failed, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_heading_raw (uint8_t port)"
Get the heading in the max double value and min double value scale\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
The heading in [DOUBLE_MIN, DOUBLE_MAX] values\&. If the operation fails, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBgps_position_s_t\fP gps_get_offset (uint8_t port)"
Get the GPS's cartesian location relative to the center of turning/origin in meters\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
A struct (\fBgps_position_s_t\fP) containing the X and Y values if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBgps_orientation_s_t\fP gps_get_orientation (uint8_t port)"
Gets the pitch, roll, and yaw of the GPS relative to the starting orientation\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
A struct (\fBgps_orientation_s_t\fP) containing values mentioned above\&. If the operation failed, all the structure's members are filled with PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_pitch (uint8_t port)"
Gets the pitch of the robot in degrees relative to the starting oreintation\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
The pitch in [0,360) degree values\&. If the operation failed, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBgps_position_s_t\fP gps_get_position (uint8_t port)"
Gets the x and y position on the field of the GPS in meters\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
A struct (\fBgps_position_s_t\fP) containing values mentioned above\&. If the operation failed, all the structure's members are filled with PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBgps_status_s_t\fP gps_get_position_and_orientation (uint8_t port)"
Gets the position and roll, yaw, and pitch of the GPS\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
A struct (\fBgps_status_s_t\fP) containing values mentioned above\&. If the operation failed, all the structure's members are filled with PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_position_x (uint8_t port)"
Gets the X position in meters of the robot relative to the starting position\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
The X position in meters\&. If the operation failed, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_position_y (uint8_t port)"
Gets the Y position in meters of the robot relative to the starting position\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
The Y position in meters\&. If the operation failed, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_roll (uint8_t port)"
Gets the roll of the robot in degrees relative to the starting oreintation\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
The roll in [0,360) degree values\&. If the operation failed, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double gps_get_yaw (uint8_t port)"
Gets the yaw of the robot in degrees relative to the starting oreintation\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
The yaw in [0,360) degree values\&. If the operation failed, returns PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t gps_initialize_full (uint8_t port, double xInitial, double yInitial, double headingInitial, double xOffset, double yOffset)"
Set the GPS's offset relative to the center of turning in meters, as well as its initial position\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21 
.br
\fIxOffset\fP Cartesian 4-Quadrant X offset from center of turning (meters) 
.br
\fIyOffset\fP Cartesian 4-Quadrant Y offset from center of turning (meters) 
.br
\fIxInitial\fP Initial 4-Quadrant X Position, with (0,0) being at the center of the field (meters) 
.br
\fIyInitial\fP Initial 4-Quadrant Y Position, with (0,0) being at the center of the field (meters) 
.br
\fIheadingInitial\fP Heading with 0 being north on the field, in degrees [0,360) going clockwise 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t gps_set_data_rate (uint8_t port, uint32_t rate)"
Set the GPS sensor's data rate in milliseconds, only applies to IMU on GPS\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21 
.br
\fIrate\fP Data rate in milliseconds (Minimum: 5 ms) 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t gps_set_offset (uint8_t port, double xOffset, double yOffset)"
Set the GPS's offset relative to the center of turning in meters\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21 
.br
\fIxOffset\fP Cartesian 4-Quadrant X offset from center of turning (meters) 
.br
\fIyOffset\fP Cartesian 4-Quadrant Y offset from center of turning (meters) 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t gps_set_position (uint8_t port, double xInitial, double yInitial, double headingInitial)"
Sets the robot's location relative to the center of the field in meters\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a GPS EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 GPS port number from 1-21 
.br
\fIxInitial\fP Initial 4-Quadrant X Position, with (0,0) being at the center of the field (meters) 
.br
\fIyInitial\fP Initial 4-Quadrant Y Position, with (0,0) being at the center of the field (meters) 
.br
\fIheadingInitial\fP Heading with 0 being north on the field, in degrees [0,360) going clockwise 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
