.TH "c-llemu" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c-llemu \- LLEMU C API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBllemu\&.h\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBlcd_text_align_e\fP \fBtext_align_e_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlcd_text_align_e\fP { \fBLCD_TEXT_ALIGN_LEFT\fP = 0, \fBLCD_TEXT_ALIGN_CENTER\fP = 1, \fBLCD_TEXT_ALIGN_RIGHT\fP = 2 }"
.br
.RI "Represents how to align the text in the LCD\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBlcd_is_initialized\fP (void)"
.br
.ti -1c
.RI "bool \fBlcd_initialize\fP (void)"
.br
.ti -1c
.RI "bool \fBlcd_shutdown\fP (void)"
.br
.ti -1c
.RI "bool \fBlcd_print\fP (int16_t line, const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "bool \fBlcd_set_text\fP (int16_t line, const char *text)"
.br
.ti -1c
.RI "bool \fBlcd_clear\fP (void)"
.br
.ti -1c
.RI "bool \fBlcd_clear_line\fP (int16_t line)"
.br
.ti -1c
.RI "bool \fBlcd_register_btn0_cb\fP (lcd_btn_cb_fn_t cb)"
.br
.ti -1c
.RI "bool \fBlcd_register_btn1_cb\fP (lcd_btn_cb_fn_t cb)"
.br
.ti -1c
.RI "bool \fBlcd_register_btn2_cb\fP (lcd_btn_cb_fn_t cb)"
.br
.ti -1c
.RI "uint8_t \fBlcd_read_buttons\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_set_text_align\fP (text_align_e_t alignment)"
.br
.in -1c
.SH "Detailed Description"
.PP 
LLEMU - \fBL\fPegacy \fBL\fPcd \fBEMU\fPlator

.PP

.PP
LLEMU provides a virtual 40x8 LCD screen with 3 buttons\&. The user can set the text of the screen and set create functions that are run when the buttons are pressed\&.

.PP
LLEMU is a emulation of the UART-based LCD screens that were available with VEX's cortex product line\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBlcd_text_align_e\fP"

.PP
Represents how to align the text in the LCD\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILCD_TEXT_ALIGN_LEFT \fP
Align the text to the left side of LCD line\&. 
.TP
\f(BILCD_TEXT_ALIGN_CENTER \fP
Align the text to the center of the LCD line\&. 
.TP
\f(BILCD_TEXT_ALIGN_RIGHT \fP
Align the text to the right side of the LCD line\&. 
.SH "Function Documentation"
.PP 
.SS "bool lcd_clear (void )"
Clears the contents of the emulated three-button LCD screen\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&. EINVAL - The line number specified is not in the range [0-7]

.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.h"

void initialize() {
  pros::c::lcd_initialize();
  pros::c::lcd_clear(); // Clear the LCD screen
}

.fi
.PP
 
.SS "bool lcd_clear_line (int16_t line)"
Clears the contents of a line of the emulated three-button LCD screen\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&. EINVAL - The line number specified is not in the range [0-7]

.PP
\fBParameters\fP
.RS 4
\fIline\fP The line to clear
.RE
.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.h"

void initialize() {
  pros::c::lcd_initialize();
  pros::c::lcd_clear_line(0); // Clear line 0
}

.fi
.PP
 
.SS "bool lcd_initialize (void )"
Creates an emulation of the three-button, UART-based VEX LCD on the display\&.

.PP
\fBReturns\fP
.RS 4
True if the LCD was successfully initialized, or false if it has already been initialized\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.h"

void initialize() {
  if (pros::c::lcd_initialize()) {
    pros::c::lcd_print("LLEMU!");   
  }
  else {
       printf("Error: LLEMU could not initailize\\n");
  }
}

.fi
.PP
 
.SS "bool lcd_is_initialized (void )"
Checks whether the emulated three-button LCD has already been initialized\&.

.PP
\fBReturns\fP
.RS 4
True if the LCD has been initialized or false if not\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
if (pros::c::lcd_is_initialized()) {
  pros::c::lcd_print("LLEMU!");
}
else {
  printf("Error: LLEMU is not initialized\\n");
}

.fi
.PP
 
.SS "bool lcd_print (int16_t line, const char * fmt,  \&.\&.\&.)"
Displays a formatted string on the emulated three-button LCD screen\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&. EINVAL - The line number specified is not in the range [0-7]

.PP
\fBParameters\fP
.RS 4
\fIline\fP The line on which to display the text [0-7] 
.br
\fIfmt\fP Format string 
.br
\fI\&.\&.\&.\fP Optional list of arguments for the format string
.RE
.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.h"

void initialize() {
  pros::c::lcd_initialize();
  pros::c::lcd_print(0, "My formatted text: %d!", 2);
}

.fi
.PP
 
.SS "uint8_t lcd_read_buttons (void )"
Gets the button status from the emulated three-button LCD\&.

.PP
The value returned is a 3-bit integer where 1 0 0 indicates the left button is pressed, 0 1 0 indicates the center button is pressed, and 0 0 1 indicates the right button is pressed\&. 0 is returned if no buttons are currently being pressed\&.

.PP
Note that this function is provided for legacy API compatibility purposes, with the caveat that the V5 touch screen does not actually support pressing multiple points on the screen at the same time\&.

.PP
\fBReturns\fP
.RS 4
The buttons pressed as a bit mask 
.RE
.PP

.SS "bool lcd_register_btn0_cb (lcd_btn_cb_fn_t cb)"
Registers a callback function for the leftmost button\&.

.PP
When the leftmost button on the emulated three-button LCD is pressed, the user-provided callback function will be invoked\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&.

.PP
\fBParameters\fP
.RS 4
\fIcb\fP A callback function of type lcd_btn_cb_fn_t (void (*cb)(void))
.RE
.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.h"

void left_callback() {
  static int i = 0;
  
  i++;
  pros::c::lcd_print(0, "Left button pressed %i times", i);
}

void initialize() {
  pros::c::lcd_initialize();
  pros::c::lcd_register_btn0_cb();
}

.fi
.PP
 
.SS "bool lcd_register_btn1_cb (lcd_btn_cb_fn_t cb)"
Registers a callback function for the center button\&.

.PP
When the center button on the emulated three-button LCD is pressed, the user-provided callback function will be invoked\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&.

.PP
\fBParameters\fP
.RS 4
\fIcb\fP A callback function of type lcd_btn_cb_fn_t (void (*cb)(void))
.RE
.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.h"

void center_callback() {
  static int i = 0;
  
  i++;
  pros::c::lcd_print(0, "Center button pressed %i times", i);
}

void initialize() {
  pros::c::lcd_initialize();
  pros::c::lcd_register_btn1_cb();
}

.fi
.PP
 
.SS "bool lcd_register_btn2_cb (lcd_btn_cb_fn_t cb)"
Registers a callback function for the rightmost button\&.

.PP
When the rightmost button on the emulated three-button LCD is pressed, the user-provided callback function will be invoked\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&.

.PP
\fBParameters\fP
.RS 4
\fIcb\fP A callback function of type lcd_btn_cb_fn_t (void (*cb)(void))
.RE
.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.h"

void right_callback() {
  static int i = 0;
  
  i++;
  pros::c::lcd_print(0, "Right button pressed %i times", i);
}

void initialize() {
  pros::c::lcd_initialize();
  pros::c::lcd_register_btn2_cb();
}

.fi
.PP
 
.SS "bool lcd_set_text (int16_t line, const char * text)"
Displays a string on the emulated three-button LCD screen\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&. EINVAL - The line number specified is not in the range [0-7]

.PP
\fBParameters\fP
.RS 4
\fIline\fP The line on which to display the text [0-7] 
.br
\fItext\fP The text to display
.RE
.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.h"

void initialize() {
  pros::c::lcd_initialize();
  pros::c::lcd_set_text(0, "My custom LLEMU text!");
}

.fi
.PP
 
.SS "void lcd_set_text_align (text_align_e_t alignment)"
Changes the alignment of text on the LCD background

.PP
\fBParameters\fP
.RS 4
\fIalignment\fP An enum specifying the alignment\&. Available alignments are: TEXT_ALIGN_LEFT TEXT_ALIGN_RIGHT TEXT_ALIGN_CENTER
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.h"

void initialize() {
  pros::c::lcd_initialize();
  pros::c::lcd_set_alignment(pros::c::lcd_Text_Align::LEFT);
  pros::c::lcd_print(0, "Left Aligned Text");
  pros::c::lcd_set_alignment(pros::c::lcd_Text_Align::CENTER);
  pros::c::lcd_print(1, "Center Aligned Text");
  pros::c::lcd_set_alignment(pros::c::lcd_Text_Align::RIGHT);
  pros::c::lcd_print(2, "Right Aligned Text");
}

.fi
.PP
 
.SS "bool lcd_shutdown (void )"
Turns off the Legacy LCD Emulator\&.

.PP
Calling this function will clear the entire display, and you will not be able to call any further LLEMU functions until another call to lcd_initialize\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&.

.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.h"

void disabled() {
  pros::c::lcd_shutdown();
}

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
