.TH "c-motors" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c-motors \- Motors C API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmotors\&.h\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmotor_pid_full_s\fP"
.br
.ti -1c
.RI "struct \fBmotor_pid_s\fP"
.br
.ti -1c
.RI "struct \fBmotor_pid_full_s_t\fP"
.br
.ti -1c
.RI "struct \fBmotor_pid_s_t\fP"
.br
.in -1c
.SS "Motor telemetry functions"
These functions allow programmers to collect telemetry from motors 
.in +1c
.ti -1c
.RI "enum \fBmotor_fault_e\fP { \fBE_MOTOR_FAULT_NO_FAULTS\fP = 0x00, \fBE_MOTOR_FAULT_MOTOR_OVER_TEMP\fP = 0x01, \fBE_MOTOR_FAULT_DRIVER_FAULT\fP = 0x02, \fBE_MOTOR_FAULT_OVER_CURRENT\fP = 0x04, \fBE_MOTOR_FAULT_DRV_OVER_CURRENT\fP = 0x08 }"
.br
.ti -1c
.RI "enum \fBmotor_flag_e\fP { \fBE_MOTOR_FLAGS_NONE\fP = 0x00, \fBE_MOTOR_FLAGS_BUSY\fP = 0x01, \fBE_MOTOR_FLAGS_ZERO_VELOCITY\fP = 0x02, \fBE_MOTOR_FLAGS_ZERO_POSITION\fP = 0x04 }"
.br
.ti -1c
.RI "typedef enum \fBmotor_fault_e\fP \fBmotor_fault_e_t\fP"
.br
.ti -1c
.RI "typedef enum \fBmotor_flag_e\fP \fBmotor_flag_e_t\fP"
.br
.ti -1c
.RI "double \fBmotor_get_actual_velocity\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_current_draw\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_direction\fP (int8_t port)"
.br
.ti -1c
.RI "double \fBmotor_get_efficiency\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_is_over_current\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_is_over_temp\fP (int8_t port)"
.br
.ti -1c
.RI "uint32_t \fBmotor_get_faults\fP (int8_t port)"
.br
.ti -1c
.RI "uint32_t \fBmotor_get_flags\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_raw_position\fP (int8_t port, uint32_t *const timestamp)"
.br
.ti -1c
.RI "double \fBmotor_get_position\fP (int8_t port)"
.br
.ti -1c
.RI "double \fBmotor_get_power\fP (int8_t port)"
.br
.ti -1c
.RI "double \fBmotor_get_temperature\fP (int8_t port)"
.br
.ti -1c
.RI "double \fBmotor_get_torque\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_voltage\fP (int8_t port)"
.br
.in -1c
.SS "Motor configuration functions"
These functions allow programmers to configure the behavior of motors 
.in +1c
.ti -1c
.RI "enum \fBmotor_brake_mode_e\fP { \fBE_MOTOR_BRAKE_COAST\fP = 0, \fBE_MOTOR_BRAKE_BRAKE\fP = 1, \fBE_MOTOR_BRAKE_HOLD\fP = 2, \fBE_MOTOR_BRAKE_INVALID\fP = INT32_MAX }"
.br
.ti -1c
.RI "enum \fBmotor_encoder_units_e\fP { \fBE_MOTOR_ENCODER_DEGREES\fP = 0, \fBE_MOTOR_ENCODER_ROTATIONS\fP = 1, \fBE_MOTOR_ENCODER_COUNTS\fP = 2, \fBE_MOTOR_ENCODER_INVALID\fP = INT32_MAX }"
.br
.ti -1c
.RI "enum \fBmotor_gearset_e\fP { \fBE_MOTOR_GEARSET_36\fP = 0, \fBE_MOTOR_GEAR_RED\fP = E_MOTOR_GEARSET_36, \fBE_MOTOR_GEAR_100\fP = E_MOTOR_GEARSET_36, \fBE_MOTOR_GEARSET_18\fP = 1, \fBE_MOTOR_GEAR_GREEN\fP = E_MOTOR_GEARSET_18, \fBE_MOTOR_GEAR_200\fP = E_MOTOR_GEARSET_18, \fBE_MOTOR_GEARSET_06\fP = 2, \fBE_MOTOR_GEAR_BLUE\fP = E_MOTOR_GEARSET_06, \fBE_MOTOR_GEAR_600\fP = E_MOTOR_GEARSET_06, \fBE_MOTOR_GEARSET_INVALID\fP = INT32_MAX }"
.br
.ti -1c
.RI "typedef enum \fBmotor_brake_mode_e\fP \fBmotor_brake_mode_e_t\fP"
.br
.ti -1c
.RI "typedef enum \fBmotor_encoder_units_e\fP \fBmotor_encoder_units_e_t\fP"
.br
.ti -1c
.RI "typedef enum motor_gearset_e \fBmotor_gearset_e_t\fP"
.br
.ti -1c
.RI "typedef struct \fBmotor_pid_full_s\fP \fBmotor_pid_full_s_t\fP"
.br
.ti -1c
.RI "typedef struct \fBmotor_pid_s\fP \fBmotor_pid_s_t\fP"
.br
.ti -1c
.RI "int32_t \fBmotor_set_zero_position\fP (int8_t port, const double position)"
.br
.ti -1c
.RI "int32_t \fBmotor_tare_position\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_set_brake_mode\fP (int8_t port, const motor_brake_mode_e_t mode)"
.br
.ti -1c
.RI "int32_t \fBmotor_set_current_limit\fP (int8_t port, const int32_t limit)"
.br
.ti -1c
.RI "int32_t \fBmotor_set_encoder_units\fP (int8_t port, const motor_encoder_units_e_t units)"
.br
.ti -1c
.RI "int32_t \fBmotor_set_gearing\fP (int8_t port, const motor_gearset_e_t gearset)"
.br
.ti -1c
.RI "int32_t \fBmotor_set_voltage_limit\fP (int8_t port, const int32_t limit)"
.br
.ti -1c
.RI "motor_brake_mode_e_t \fBmotor_get_brake_mode\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_current_limit\fP (int8_t port)"
.br
.ti -1c
.RI "motor_encoder_units_e_t \fBmotor_get_encoder_units\fP (int8_t port)"
.br
.ti -1c
.RI "motor_gearset_e_t \fBmotor_get_gearing\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_voltage_limit\fP (int8_t port)"
.br
.in -1c
.SS "Motor movement functions"
These functions allow programmers to make motors move 
.in +1c
.ti -1c
.RI "int32_t \fBmotor_move\fP (int8_t port, int32_t voltage)"
.br
.ti -1c
.RI "int32_t \fBmotor_brake\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_move_absolute\fP (int8_t port, double position, const int32_t velocity)"
.br
.ti -1c
.RI "int32_t \fBmotor_move_relative\fP (int8_t port, double position, const int32_t velocity)"
.br
.ti -1c
.RI "int32_t \fBmotor_move_velocity\fP (int8_t port, const int32_t velocity)"
.br
.ti -1c
.RI "int32_t \fBmotor_move_voltage\fP (int8_t port, const int32_t voltage)"
.br
.ti -1c
.RI "int32_t \fBmotor_modify_profiled_velocity\fP (int8_t port, const int32_t velocity)"
.br
.ti -1c
.RI "double \fBmotor_get_target_position\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_target_velocity\fP (int8_t port)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBNote\fP
.RS 4
Additional example code for this module can be found in its \fBTutorial\fP\&.
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBmotor_brake_mode_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIE_MOTOR_BRAKE_COAST \fP
Motor coasts when stopped, traditional behavior\&. 
.TP
\f(BIE_MOTOR_BRAKE_BRAKE \fP
Motor brakes when stopped\&. 
.TP
\f(BIE_MOTOR_BRAKE_HOLD \fP
Motor actively holds position when stopped\&. 
.TP
\f(BIE_MOTOR_BRAKE_INVALID \fP
Invalid brake mode\&. 
.SS "enum \fBmotor_encoder_units_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIE_MOTOR_ENCODER_DEGREES \fP
Position is recorded as angle in degrees as a floating point number\&. 
.TP
\f(BIE_MOTOR_ENCODER_ROTATIONS \fP
Position is recorded as angle in rotations as a floating point number\&. 
.TP
\f(BIE_MOTOR_ENCODER_COUNTS \fP
Position is recorded as raw encoder ticks as a whole number\&. 
.TP
\f(BIE_MOTOR_ENCODER_INVALID \fP
Invalid motor encoder units\&. 
.SS "enum \fBmotor_fault_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIE_MOTOR_FAULT_NO_FAULTS \fP
No faults\&. 
.TP
\f(BIE_MOTOR_FAULT_MOTOR_OVER_TEMP \fP
Analogous to \fBmotor_is_over_temp()\fP\&. 
.TP
\f(BIE_MOTOR_FAULT_DRIVER_FAULT \fP
Indicates a motor h-bridge fault\&. 
.TP
\f(BIE_MOTOR_FAULT_OVER_CURRENT \fP
Analogous to \fBmotor_is_over_current()\fP\&. 
.TP
\f(BIE_MOTOR_FAULT_DRV_OVER_CURRENT \fP
Indicates an h-bridge over current\&. 
.SS "enum \fBmotor_flag_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIE_MOTOR_FLAGS_NONE \fP
There are no flags raised\&. 
.TP
\f(BIE_MOTOR_FLAGS_BUSY \fP
Cannot currently communicate to the motor\&. 
.TP
\f(BIE_MOTOR_FLAGS_ZERO_VELOCITY \fP
Analogous to motor_is_stopped()\&. 
.TP
\f(BIE_MOTOR_FLAGS_ZERO_POSITION \fP
Analogous to motor_get_zero_position_flag()\&. 
.SH "Function Documentation"
.PP 
.SS "int32_t motor_brake (int8_t port)"
Stops the motor using the currently configured brake mode\&.

.PP
This function sets motor velocity to zero, which will cause it to act according to the set brake mode\&. If brake mode is set to MOTOR_BRAKE_HOLD, this function may behave differently than calling motor_move_absolute(port, 0) or motor_move_relative(port, 0)\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double motor_get_actual_velocity (int8_t port)"
Gets the actual velocity of the motor\&.

.PP
\fBNote\fP
.RS 4
A negative port negates the return value
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The motor's actual velocity in RPM or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "motor_brake_mode_e_t motor_get_brake_mode (int8_t port)"
Gets the brake mode that was set for the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
One of motor_brake_mode_e_t, according to what was set for the motor, or E_MOTOR_BRAKE_INVALID if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_get_current_draw (int8_t port)"
Gets the current drawn by the motor in mA\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The motor's current in mA or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_get_current_limit (int8_t port)"
Gets the current limit for the motor in mA\&.

.PP
The default value is 2500 mA\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The motor's current limit in mA or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_get_direction (int8_t port)"
Gets the direction of movement for the motor\&.

.PP
\fBNote\fP
.RS 4
A negative port number negates the return value\&.
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
1 for moving in the positive direction, -1 for moving in the negative direction, or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double motor_get_efficiency (int8_t port)"
Gets the efficiency of the motor in percent\&.

.PP
An efficiency of 100% means that the motor is moving electrically while drawing no electrical power, and an efficiency of 0% means that the motor is drawing power but not moving\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The motor's efficiency in percent or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "motor_encoder_units_e_t motor_get_encoder_units (int8_t port)"
Gets the encoder units that were set for the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
One of motor_encoder_units_e_t according to what is set for the motor or E_MOTOR_ENCODER_INVALID if the operation failed\&. 
.RE
.PP

.SS "uint32_t motor_get_faults (int8_t port)"
Gets the faults experienced by the motor\&.

.PP
Compare this bitfield to the bitmasks in motor_fault_e_t\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
A bitfield containing the motor's faults\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "uint32_t motor_get_flags (int8_t port)"
Gets the flags set by the motor's operation\&.

.PP
Compare this bitfield to the bitmasks in motor_flag_e_t\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
A bitfield containing the motor's flags\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "motor_gearset_e_t motor_get_gearing (int8_t port)"
Gets the gearset that was set for the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
One of motor_gearset_e_t according to what is set for the motor, or E_GEARSET_INVALID if the operation failed\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double motor_get_position (int8_t port)"
Gets the absolute position of the motor in its encoder units\&.

.PP
\fBNote\fP
.RS 4
A negative port value negates the return value
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The motor's absolute position in its encoder units or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double motor_get_power (int8_t port)"
Gets the power drawn by the motor in Watts\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The motor's power draw in Watts or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_get_raw_position (int8_t port, uint32_t *const timestamp)"
Gets the raw encoder count of the motor at a given timestamp\&.

.PP
\fBNote\fP
.RS 4
A negative port value negates the return value
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fItimestamp\fP A pointer to a time in milliseconds for which the encoder count will be returned\&. If NULL, the timestamp at which the encoder count was read will not be supplied
.RE
.PP
\fBReturns\fP
.RS 4
The raw encoder count at the given timestamp or PROS_ERR if the operation failed\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double motor_get_target_position (int8_t port)"
Gets the target position set for the motor by the user\&.

.PP
\fBNote\fP
.RS 4
A negative port negates the return value
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The target position in its encoder units or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_get_target_velocity (int8_t port)"
Gets the velocity commanded to the motor by the user\&.

.PP
\fBNote\fP
.RS 4
A negative port negates the return value
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The commanded motor velocity from +-100, +-200, or +-600, or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double motor_get_temperature (int8_t port)"
Gets the temperature of the motor in degrees Celsius\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The motor's temperature in degrees Celsius or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "double motor_get_torque (int8_t port)"
Gets the torque generated by the motor in Newton Meters (Nm)\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The motor's torque in Nm or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_get_voltage (int8_t port)"
Gets the voltage delivered to the motor in millivolts\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The motor's voltage in mV or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_get_voltage_limit (int8_t port)"
Gets the voltage limit set by the user\&.

.PP
Default value is 0V, which means that there is no software limitation imposed on the voltage\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
The motor's voltage limit in V or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_is_over_current (int8_t port)"
Checks if the motor is drawing over its current limit\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
1 if the motor's current limit is being exceeded and 0 if the current limit is not exceeded, or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_is_over_temp (int8_t port)"
Checks if the motor's temperature is above its limit\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
1 if the temperature limit is exceeded and 0 if the the temperature is below the limit, or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_modify_profiled_velocity (int8_t port, const int32_t velocity)"
Changes the output velocity for a profiled movement (motor_move_absolute or motor_move_relative)\&. This will have no effect if the motor is not following a profiled movement\&.

.PP
\fBNote\fP
.RS 4
A negative port negates the velocity
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIvelocity\fP The new motor velocity from +-100, +-200, or +-600 depending on the motor's gearset
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_move (int8_t port, int32_t voltage)"
Sets the voltage for the motor from -127 to 127\&.

.PP
This is designed to map easily to the input from the controller's analog stick for simple opcontrol use\&. The actual behavior of the motor is analogous to use of \fBmotor_move_voltage()\fP\&.

.PP
\fBNote\fP
.RS 4
This function will not respect brake modes, and simply sets the voltage to the desired value\&.

.PP
A negative port will negate the input voltage
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIvoltage\fP The new motor voltage from -127 to 127
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_move_absolute (int8_t port, double position, const int32_t velocity)"
Sets the target absolute position for the motor to move to\&.

.PP
This movement is relative to the position of the motor when initialized or the position when it was most recently reset with \fBmotor_set_zero_position()\fP\&.

.PP
\fBNote\fP
.RS 4
This function simply sets the target for the motor, it does not block program execution until the movement finishes\&. The example code shows how to block until a movement is finished\&.

.PP
A negative port number will negate the target position
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIposition\fP The absolute position to move to in the motor's encoder units 
.br
\fIvelocity\fP The maximum allowable velocity for the movement in RPM
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_move_relative (int8_t port, double position, const int32_t velocity)"
Sets the relative target position for the motor to move to\&.

.PP
This movement is relative to the current position of the motor as given in \fBmotor_get_position()\fP\&. Providing 10\&.0 as the position parameter would result in the motor moving clockwise 10 units, no matter what the current position is\&.

.PP
\fBNote\fP
.RS 4
This function simply sets the target for the motor, it does not block program execution until the movement finishes\&. The example code shows how to block until a movement is finished\&.

.PP
A negative port will negate the target position
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIposition\fP The relative position to move to in the motor's encoder units 
.br
\fIvelocity\fP The maximum allowable velocity for the movement in RPM
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_move_velocity (int8_t port, const int32_t velocity)"
Sets the velocity for the motor\&.

.PP
This velocity corresponds to different actual speeds depending on the gearset used for the motor\&. This results in a range of +-100 for E_MOTOR_GEARSET_36, +-200 for E_MOTOR_GEARSET_18, and +-600 for E_MOTOR_GEARSET_6\&. The velocity is held with PID to ensure consistent speed, as opposed to setting the motor's voltage\&.

.PP
\fBNote\fP
.RS 4
A negative port will negate the velocity
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIvelocity\fP The new motor velocity from +-100, +-200, or +-600 depending on the motor's gearset
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_move_voltage (int8_t port, const int32_t voltage)"
Sets the output voltage for the motor from -12000 to 12000 in millivolts\&.

.PP
\fBNote\fP
.RS 4
A negative port negates the voltage
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBNote\fP
.RS 4
This function will not respect brake modes, and simply sets the voltage to the desired value\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIvoltage\fP The new voltage value from -12000 to 12000
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_set_brake_mode (int8_t port, const motor_brake_mode_e_t mode)"
Sets one of motor_brake_mode_e_t to the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fImode\fP The motor_brake_mode_e_t to set for the motor
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_set_current_limit (int8_t port, const int32_t limit)"
Sets the current limit for the motor in mA\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIlimit\fP The new current limit in mA
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_set_encoder_units (int8_t port, const motor_encoder_units_e_t units)"
Sets one of motor_encoder_units_e_t for the motor encoder\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIunits\fP The new motor encoder units
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_set_gearing (int8_t port, const motor_gearset_e_t gearset)"
Sets one of motor_gearset_e_t for the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIgearset\fP The new motor gearset
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_set_voltage_limit (int8_t port, const int32_t limit)"
Sets the voltage limit for the motor in Volts\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIlimit\fP The new voltage limit in Volts
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t motor_set_zero_position (int8_t port, const double position)"
Sets the position for the motor in its encoder units\&.

.PP
This will be the future reference point for the motor's "absolute" position\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors 
.br
\fIposition\fP The new reference position in its encoder units
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 

.PP
.PP
.nf
.fi
.PP
 
.SS "int32_t motor_tare_position (int8_t port)"
Sets the "absolute" zero position of the motor to its current position\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports |1-21|\&. ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1 to 21, or from -21 to -1 for reversed motors
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
