.TH "c-rotation" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c-rotation \- VEX Rotation Sensor C API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrotation\&.h\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBROTATION_MINIMUM_DATA_RATE\fP   5"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int32_t \fBrotation_reset\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBrotation_set_data_rate\fP (uint8_t port, uint32_t rate)"
.br
.ti -1c
.RI "int32_t \fBrotation_set_position\fP (uint8_t port, uint32_t position)"
.br
.ti -1c
.RI "int32_t \fBrotation_reset_position\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBrotation_get_position\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBrotation_get_velocity\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBrotation_get_angle\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBrotation_set_reversed\fP (uint8_t port, bool value)"
.br
.ti -1c
.RI "int32_t \fBrotation_reverse\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBrotation_init_reverse\fP (uint8_t port, bool reverse_flag)"
.br
.ti -1c
.RI "int32_t \fBrotation_get_reversed\fP (uint8_t port)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "int32_t rotation_get_angle (uint8_t port)"
Get the Rotation Sensor's current angle in centidegrees (0-36000)

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The angle value (0-36000) or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t rotation_get_position (uint8_t port)"
Get the Rotation Sensor's current position in centidegrees

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The position value or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t rotation_get_reversed (uint8_t port)"
Get the Rotation Sensor's reversed flag

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
Boolean value of if the Rotation Sensor's direction is reversed or not or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t rotation_get_velocity (uint8_t port)"
Get the Rotation Sensor's current velocity in centidegrees per second

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The velocity value or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t rotation_init_reverse (uint8_t port, bool reverse_flag)"
Initialize the Rotation Sensor with a reverse flag

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21 
.br
\fIreverse_flag\fP Determines if the Rotation Sensor is reversed or not\&.
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t rotation_reset (uint8_t port)"
Reset Rotation Sensor

.PP
Reset the current absolute position to be the same as the Rotation Sensor angle\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t rotation_reset_position (uint8_t port)"
Reset the Rotation Sensor position to 0

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t rotation_reverse (uint8_t port)"
Reverse the Rotation Sensor's direction

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t rotation_set_data_rate (uint8_t port, uint32_t rate)"
Set the Rotation Sensor's refresh interval in milliseconds\&.

.PP
The rate may be specified in increments of 5ms, and will be rounded down to the nearest increment\&. The minimum allowable refresh rate is 5ms\&. The default rate is 10ms\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21 
.br
\fIrate\fP The data refresh interval in milliseconds 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t rotation_set_position (uint8_t port, uint32_t position)"
Set the Rotation Sensor position reading to a desired rotation value

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21 
.br
\fIposition\fP The position in terms of ticks 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t rotation_set_reversed (uint8_t port, bool value)"
Set the Rotation Sensor's direction reversed flag

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Rotation Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Rotation Sensor port number from 1-21 
.br
\fIvalue\fP Determines if the direction of the Rotation Sensor is reversed or not\&.
.RE
.PP
\fBReturns\fP
.RS 4
1 if operation succeeded or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
