.TH "c-vision" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c-vision \- Vision Sensor C API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBvision\&.h\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvision_signature_s_t\fP"
.br
.ti -1c
.RI "struct \fBvision_object_s_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum vision_object_type \fBvision_object_type_e_t\fP"
.br
.ti -1c
.RI "typedef uint16_t \fBvision_color_code_t\fP"
.br
.ti -1c
.RI "typedef enum \fBvision_zero\fP \fBvision_zero_e_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvision_object_type\fP { \fBE_VISION_OBJECT_NORMAL\fP = 0, \fBE_VISION_OBJECT_COLOR_CODE\fP = 1, \fBE_VISION_OBJECT_LINE\fP = 2 }"
.br
.ti -1c
.RI "enum \fBvision_zero\fP { \fBE_VISION_ZERO_TOPLEFT\fP = 0, \fBE_VISION_ZERO_CENTER\fP = 1 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__)) vision_signature"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBvision_signature_s_t\fP"
.br
.ti -1c
.RI "\fBvision_object_s_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int32_t \fBvision_clear_led\fP (uint8_t port)"
.br
.ti -1c
.RI "\fBvision_signature_s_t\fP \fBvision_signature_from_utility\fP (const int32_t id, const int32_t u_min, const int32_t u_max, const int32_t u_mean, const int32_t v_min, const int32_t v_max, const int32_t v_mean, const float range, const int32_t type)"
.br
.ti -1c
.RI "\fBvision_color_code_t\fP \fBvision_create_color_code\fP (uint8_t port, const uint32_t sig_id1, const uint32_t sig_id2, const uint32_t sig_id3, const uint32_t sig_id4, const uint32_t sig_id5)"
.br
.ti -1c
.RI "\fBvision_object_s_t\fP \fBvision_get_by_size\fP (uint8_t port, const uint32_t size_id)"
.br
.ti -1c
.RI "\fBvision_object_s_t\fP \fBvision_get_by_sig\fP (uint8_t port, const uint32_t size_id, const uint32_t sig_id)"
.br
.ti -1c
.RI "\fBvision_object_s_t\fP \fBvision_get_by_code\fP (uint8_t port, const uint32_t size_id, const \fBvision_color_code_t\fP color_code)"
.br
.ti -1c
.RI "int32_t \fBvision_get_exposure\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBvision_get_object_count\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBvision_get_white_balance\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBvision_print_signature\fP (const \fBvision_signature_s_t\fP sig)"
.br
.ti -1c
.RI "int32_t \fBvision_read_by_size\fP (uint8_t port, const uint32_t size_id, const uint32_t object_count, \fBvision_object_s_t\fP *const object_arr)"
.br
.ti -1c
.RI "int32_t \fBvision_read_by_sig\fP (uint8_t port, const uint32_t size_id, const uint32_t sig_id, const uint32_t object_count, \fBvision_object_s_t\fP *const object_arr)"
.br
.ti -1c
.RI "int32_t \fBvision_read_by_code\fP (uint8_t port, const uint32_t size_id, const \fBvision_color_code_t\fP color_code, const uint32_t object_count, \fBvision_object_s_t\fP *const object_arr)"
.br
.ti -1c
.RI "\fBvision_signature_s_t\fP \fBvision_get_signature\fP (uint8_t port, const uint8_t signature_id)"
.br
.ti -1c
.RI "int32_t \fBvision_set_signature\fP (uint8_t port, const uint8_t signature_id, \fBvision_signature_s_t\fP *const signature_ptr)"
.br
.ti -1c
.RI "int32_t \fBvision_set_auto_white_balance\fP (uint8_t port, const uint8_t enable)"
.br
.ti -1c
.RI "int32_t \fBvision_set_exposure\fP (uint8_t port, const uint8_t exposure)"
.br
.ti -1c
.RI "int32_t \fBvision_set_led\fP (uint8_t port, const int32_t rgb)"
.br
.ti -1c
.RI "int32_t \fBvision_set_white_balance\fP (uint8_t port, const int32_t rgb)"
.br
.ti -1c
.RI "int32_t \fBvision_set_zero_point\fP (uint8_t port, vision_zero_e_t zero_point)"
.br
.ti -1c
.RI "int32_t \fBvision_set_wifi_mode\fP (uint8_t port, const uint8_t enable)"
.br
.in -1c
.SS "Macros"
Parameters given by VEX 
.in +1c
.ti -1c
.RI "#define \fBVISION_OBJECT_ERR_SIG\fP   255"
.br
.ti -1c
.RI "#define \fBVISION_FOV_WIDTH\fP   316"
.br
.ti -1c
.RI "#define \fBVISION_FOV_HEIGHT\fP   212"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBNote\fP
.RS 4
Additional example code for this module can be found in its \fBTutorial\&.\fP
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define VISION_FOV_HEIGHT   212"
The height of the Vision Sensor’s field of view\&. 
.SS "#define VISION_FOV_WIDTH   316"
The width of the Vision Sensor’s field of view\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef uint16_t \fBvision_color_code_t\fP"
Color codes are just signatures with multiple IDs and a different type\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBvision_zero\fP"
This enumeration defines different zero points for returned vision objects\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIE_VISION_ZERO_TOPLEFT \fP
(0,0) coordinate is the top left of the FOV 
.TP
\f(BIE_VISION_ZERO_CENTER \fP
(0,0) coordinate is the center of the FOV 
.SH "Function Documentation"
.PP 
.SS "struct __attribute__ ((__packed__) )"
Object signature

.PP
Object type, e\&.g\&. normal, color code, or line detection

.PP
Left boundary coordinate of the object

.PP
Top boundary coordinate of the object

.PP
Width of the object

.PP
Height of the object

.PP
Angle of a color code object in 0\&.1 degree units (e\&.g\&. 10 -> 1 degree, 155 -> 15\&.5 degrees)

.PP
Coordinates of the middle of the object (computed from the values above)

.PP
Coordinates of the middle of the object (computed from the values above)
.SS "int32_t vision_clear_led (uint8_t port)"
Clears the vision sensor LED color, reseting it back to its default behavior, displaying the most prominent object signature color\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_color_code_t\fP vision_create_color_code (uint8_t port, const uint32_t sig_id1, const uint32_t sig_id2, const uint32_t sig_id3, const uint32_t sig_id4, const uint32_t sig_id5)"
Creates a color code that represents a combination of the given signature IDs\&. If fewer than 5 signatures are to be a part of the color code, pass 0 for the additional function parameters\&.

.PP
This function uses the following values of errno when an error state is reached: EINVAL - Fewer than two signatures have been provided or one of the signatures is out of its [1-7] range (or 0 when omitted)\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIsig_id1\fP The first signature id [1-7] to add to the color code 
.br
\fIsig_id2\fP The second signature id [1-7] to add to the color code 
.br
\fIsig_id3\fP The third signature id [1-7] to add to the color code 
.br
\fIsig_id4\fP The fourth signature id [1-7] to add to the color code 
.br
\fIsig_id5\fP The fifth signature id [1-7] to add to the color code
.RE
.PP
\fBReturns\fP
.RS 4
A \fBvision_color_code_t\fP object containing the color code information\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_object_s_t\fP vision_get_by_code (uint8_t port, const uint32_t size_id, const \fBvision_color_code_t\fP color_code)"
Gets the nth largest object of the given color code according to size_id\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor EAGAIN - Reading the vision sensor failed for an unknown reason\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.) 
.br
\fIcolor_code\fP The \fBvision_color_code_t\fP for which an object will be returned
.RE
.PP
\fBReturns\fP
.RS 4
The \fBvision_object_s_t\fP object corresponding to the given color code and size_id, or PROS_ERR if an error occurred\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_object_s_t\fP vision_get_by_sig (uint8_t port, const uint32_t size_id, const uint32_t sig_id)"
Gets the nth largest object of the given signature according to size_id\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor EINVAL - sig_id is outside the range [1-8] EDOM - size_id is greater than the number of available objects\&. EAGAIN - Reading the vision sensor failed for an unknown reason\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.) 
.br
\fIsignature\fP The signature ID [1-7] for which an object will be returned\&.
.RE
.PP
\fBReturns\fP
.RS 4
The \fBvision_object_s_t\fP object corresponding to the given signature and size_id, or PROS_ERR if an error occurred\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_object_s_t\fP vision_get_by_size (uint8_t port, const uint32_t size_id)"
Gets the nth largest object according to size_id\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor EDOM - size_id is greater than the number of available objects\&. EHOSTDOWN - Reading the vision sensor failed for an unknown reason\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.)
.RE
.PP
\fBReturns\fP
.RS 4
The \fBvision_object_s_t\fP object corresponding to the given size id, or PROS_ERR if an error occurred\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_get_exposure (uint8_t port)"
Gets the exposure parameter of the Vision Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
The current exposure setting from [0,150], PROS_ERR if an error occurred
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_get_object_count (uint8_t port)"
Gets the number of objects currently detected by the Vision Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
The number of objects detected on the specified vision sensor\&. Returns PROS_ERR if the port was invalid or an error occurred\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_signature_s_t\fP vision_get_signature (uint8_t port, const uint8_t signature_id)"
Gets the object detection signature with the given id number\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIsignature_id\fP The signature id to read
.RE
.PP
\fBReturns\fP
.RS 4
A \fBvision_signature_s_t\fP containing information about the signature\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_get_white_balance (uint8_t port)"
Get the white balance parameter of the Vision Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21
.RE
.PP
\fBReturns\fP
.RS 4
The current RGB white balance setting of the sensor
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_print_signature (const \fBvision_signature_s_t\fP sig)"
Prints the contents of the signature as an initializer list to the terminal\&.

.PP
\fBParameters\fP
.RS 4
\fIsig\fP The signature for which the contents will be printed
.RE
.PP
\fBReturns\fP
.RS 4
1 if no errors occured, PROS_ERR otherwise
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_read_by_code (uint8_t port, const uint32_t size_id, const \fBvision_color_code_t\fP color_code, const uint32_t object_count, \fBvision_object_s_t\fP *const object_arr)"
Reads up to object_count object descriptors into object_arr\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21), or fewer than object_count number of objects were found\&. ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIobject_count\fP The number of objects to read 
.br
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.) 
.br
\fIcolor_code\fP The \fBvision_color_code_t\fP for which objects will be returned 
.br
\fIobject_arr\fP A pointer to copy the objects into
.RE
.PP
\fBReturns\fP
.RS 4
The number of object signatures copied\&. This number will be less than object_count if there are fewer objects detected by the vision sensor\&. Returns PROS_ERR if the port was invalid, an error occurred, or fewer objects than size_id were found\&. All objects in object_arr that were not found are given VISION_OBJECT_ERR_SIG as their signature\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_read_by_sig (uint8_t port, const uint32_t size_id, const uint32_t sig_id, const uint32_t object_count, \fBvision_object_s_t\fP *const object_arr)"
Reads up to object_count object descriptors into object_arr\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21), or fewer than object_count number of objects were found\&. ENODEV - The port cannot be configured as a vision sensor EDOM - size_id is greater than the number of available objects\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIobject_count\fP The number of objects to read 
.br
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.) 
.br
\fIsignature\fP The signature ID [1-7] for which objects will be returned\&. 
.br
\fIobject_arr\fP A pointer to copy the objects into
.RE
.PP
\fBReturns\fP
.RS 4
The number of object signatures copied\&. This number will be less than object_count if there are fewer objects detected by the vision sensor\&. Returns PROS_ERR if the port was invalid, an error occurred, or fewer objects than size_id were found\&. All objects in object_arr that were not found are given VISION_OBJECT_ERR_SIG as their signature\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_read_by_size (uint8_t port, const uint32_t size_id, const uint32_t object_count, \fBvision_object_s_t\fP *const object_arr)"
Reads up to object_count object descriptors into object_arr\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21), or fewer than object_count number of objects were found\&. ENODEV - The port cannot be configured as a vision sensor EDOM - size_id is greater than the number of available objects\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.) 
.br
\fIobject_count\fP The number of objects to read 
.br
\fIobject_arr\fP A pointer to copy the objects into
.RE
.PP
\fBReturns\fP
.RS 4
The number of object signatures copied\&. This number will be less than object_count if there are fewer objects detected by the vision sensor\&. Returns PROS_ERR if the port was invalid, an error occurred, or fewer objects than size_id were found\&. All objects in object_arr that were not found are given VISION_OBJECT_ERR_SIG as their signature\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_set_auto_white_balance (uint8_t port, const uint8_t enable)"
Enables/disables auto white-balancing on the Vision Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor EINVAL - enable was not 0 or 1

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIenabled\fP Pass 0 to disable, 1 to enable
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_set_exposure (uint8_t port, const uint8_t exposure)"
Sets the exposure parameter of the Vision Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIpercent\fP The new exposure setting from [0,150]
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_set_led (uint8_t port, const int32_t rgb)"
Sets the vision sensor LED color, overriding the automatic behavior\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIrgb\fP An RGB code to set the LED to
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_set_signature (uint8_t port, const uint8_t signature_id, \fBvision_signature_s_t\fP *const signature_ptr)"
Stores the supplied object detection signature onto the vision sensor\&.

.PP
\fBNote\fP
.RS 4
This saves the signature in volatile memory, and the signature will be lost as soon as the sensor is powered down\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIsignature_id\fP The signature id to store into 
.br
\fIsignature_ptr\fP A pointer to the signature to save
.RE
.PP
\fBReturns\fP
.RS 4
1 if no errors occured, PROS_ERR otherwise
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_set_white_balance (uint8_t port, const int32_t rgb)"
Sets the white balance parameter of the Vision Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIrgb\fP The new RGB white balance setting of the sensor
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_set_wifi_mode (uint8_t port, const uint8_t enable)"
Sets the Wi-Fi mode of the Vision sensor

.PP
This functions uses the following values of errno when an error state is reached: ENXIO - The given port is not within the range of V5 ports (1-21) EACCESS - Anothe resources is currently trying to access the port

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIenable\fP Disable Wi-Fi on the Vision sensor if 0, enable otherwise (e\&.g\&. 1)
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t vision_set_zero_point (uint8_t port, vision_zero_e_t zero_point)"
Sets the (0,0) coordinate for the Field of View\&.

.PP
This will affect the coordinates returned for each request for a \fBvision_object_s_t\fP from the sensor, so it is recommended that this function only be used to configure the sensor at the beginning of its use\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIzero_point\fP One of vision_zero_e_t to set the (0,0) coordinate for the FOV
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_signature_s_t\fP vision_signature_from_utility (const int32_t id, const int32_t u_min, const int32_t u_max, const int32_t u_mean, const int32_t v_min, const int32_t v_max, const int32_t v_mean, const float range, const int32_t type)"
Creates a signature from the vision sensor utility

.PP
\fBParameters\fP
.RS 4
\fIid\fP The signature ID 
.br
\fIu_min\fP Minimum value on U axis 
.br
\fIu_max\fP Maximum value on U axis 
.br
\fIu_mean\fP Mean value on U axis 
.br
\fIv_min\fP Minimum value on V axis 
.br
\fIv_max\fP Maximum value on V axis 
.br
\fIv_mean\fP Mean value on V axis 
.br
\fIrange\fP Scale factor 
.br
\fItype\fP Signature type
.RE
.PP
\fBReturns\fP
.RS 4
A \fBvision_signature_s_t\fP that can be set using vision_set_signature
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
