.TH "cpp-screen" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp-screen \- Simplified Brain Screen C++ API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBscreen\&.hpp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::uint32_t \fBpros::screen::set_pen\fP (\fBpros::Color\fP color)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::set_pen\fP (std::uint32_t color)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::set_eraser\fP (\fBpros::Color\fP color)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::set_eraser\fP (std::uint32_t color)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::get_pen\fP ()"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::get_eraser\fP ()"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::erase\fP ()"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::scroll\fP (const std::int16_t start_line, const std::int16_t lines)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::scroll_area\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1, std::int16_t lines)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::copy_area\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1, uint32_t *buf, const std::int32_t stride)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::draw_pixel\fP (const std::int16_t x, const std::int16_t y)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::erase_pixel\fP (const std::int16_t x, const std::int16_t y)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::draw_line\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::erase_line\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::draw_rect\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::erase_rect\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::fill_rect\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::draw_circle\fP (const std::int16_t x, const std::int16_t y, const std::int16_t radius)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::erase_circle\fP (const std::int16_t x, const std::int16_t y, const std::int16_t radius)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::fill_circle\fP (const std::int16_t x, const std::int16_t y, const std::int16_t radius)"
.br
.ti -1c
.RI "\fBscreen_touch_status_s_t\fP \fBpros::screen::touch_status\fP ()"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::touch_callback\fP (touch_event_cb_fn_t cb, \fBlast_touch_e_t\fP event_type)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "std::uint32_t pros::screen::copy_area (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1, uint32_t * buf, const std::int32_t stride)"
Copy a screen region (designated by a rectangle) from an off-screen buffer to the screen

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx0,y0\fP The (x,y) coordinates of the first corner of the rectangular region of the screen 
.br
\fIx1,y1\fP The (x,y) coordinates of the second corner of the rectangular region of the screen 
.br
\fIbuf\fP Off-screen buffer containing screen data 
.br
\fIstride\fP Off-screen buffer width in pixels, such that image size is stride-padding
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::draw_circle (const std::int16_t x, const std::int16_t y, const std::int16_t radius)"
Draw a circle on the screen using the current pen color

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx,y\fP The (x,y) coordinates of the center of the circle 
.br
\fIr\fP The radius of the circle
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::draw_line (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
Draw a line on the screen using the current pen color

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx0,y0\fP The (x, y) coordinates of the first point of the line 
.br
\fIx1,y1\fP The (x, y) coordinates of the second point of the line
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::draw_pixel (const std::int16_t x, const std::int16_t y)"
Draw a single pixel on the screen using the current pen color

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx,y\fP The (x,y) coordinates of the pixel
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::draw_rect (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
Draw a rectangle on the screen using the current pen color

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx0,y0\fP The (x,y) coordinates of the first point of the rectangle 
.br
\fIx1,y1\fP The (x,y) coordinates of the second point of the rectangle
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::erase ()"
Clear display with eraser color

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
.IP "\(bu" 2
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.PP

.SS "std::uint32_t pros::screen::erase_circle (const std::int16_t x, const std::int16_t y, const std::int16_t radius)"
Erase a circle on the screen using the current eraser color

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx,y\fP The (x,y) coordinates of the center of the circle 
.br
\fIr\fP The radius of the circle
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::erase_line (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
Erase a line on the screen using the current eraser color

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx0,y0\fP The (x, y) coordinates of the first point of the line 
.br
\fIx1,y1\fP The (x, y) coordinates of the second point of the line
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::erase_pixel (const std::int16_t x, const std::int16_t y)"
Erase a pixel from the screen (Sets the location)

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx,y\fP The (x,y) coordinates of the erased
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::erase_rect (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
Erase a rectangle on the screen using the current eraser color

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx0,y0\fP The (x,y) coordinates of the first point of the rectangle 
.br
\fIx1,y1\fP The (x,y) coordinates of the second point of the rectangle
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::fill_circle (const std::int16_t x, const std::int16_t y, const std::int16_t radius)"
Fill a circular region of the screen using the current pen color

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx,y\fP The (x,y) coordinates of the center of the circle 
.br
\fIr\fP The radius of the circle
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::fill_rect (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
Fill a rectangular region of the screen using the current pen color

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx0,y0\fP The (x,y) coordinates of the first point of the rectangle 
.br
\fIx1,y1\fP The (x,y) coordinates of the second point of the rectangle
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::get_eraser ()"
Get the current eraser color\&.

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBReturns\fP
.RS 4
The current eraser color in the form of a value from the enum defined in \fBcolors\&.h\fP, or PROS_ERR if there was an error taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::get_pen ()"
Get the current pen color\&.

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBReturns\fP
.RS 4
The current pen color in the form of a value from the enum defined in \fBcolors\&.h\fP, or PROS_ERR if there was an error taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::scroll (const std::int16_t start_line, const std::int16_t lines)"
Scroll lines on the display upwards\&.

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIstart_line\fP The line from which scrolling will start 
.br
\fIlines\fP The number of lines to scroll up
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::scroll_area (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1, std::int16_t lines)"
Scroll lines within a region on the display

.PP
This function behaves in the same way as \fR\fBscreen_scroll\fP\fP, except that you specify a rectangular region within which to scroll lines instead of a start line\&.

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIx0,y0\fP The (x,y) coordinates of the first corner of the rectangular region 
.br
\fIx1,y1\fP The (x,y) coordinates of the second corner of the rectangular region 
.br
\fIlines\fP The number of lines to scroll upwards
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::set_eraser (\fBpros::Color\fP color)"
Set the eraser color for erasing and the current background\&.

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIcolor\fP The background color to set (it is recommended to use values from the enum defined in \fBcolors\&.hpp\fP)
.RE
.PP
\fBReturns\fP
.RS 4
Returns 1 if the mutex was successfully returned, or PROS_ERR if there was an error either taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::set_eraser (std::uint32_t color)"
Set the eraser color for erasing and the current background\&.

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIcolor\fP The background color to set to set (in hex form)
.RE
.PP
\fBReturns\fP
.RS 4
Returns 1 if the mutex was successfully returned, or PROS_ERR if there was an error either taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::set_pen (\fBpros::Color\fP color)"
Screen Graphical Display Functions These functions allow programmers to display shapes on the v5 screen Set the pen color for subsequent graphics operations

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIcolor\fP The pen color to set (it is recommended to use values from the enum defined in \fBcolors\&.hpp\fP)
.RE
.PP
\fBReturns\fP
.RS 4
Returns 1 if the mutex was successfully returned, or PROS_ERR if there was an error either taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::set_pen (std::uint32_t color)"
Set the pen color for subsequent graphics operations

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIcolor\fP The pen color to set (in hex form)
.RE
.PP
\fBReturns\fP
.RS 4
Returns 1 if the mutex was successfully returned, or PROS_ERR if there was an error either taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::uint32_t pros::screen::touch_callback (touch_event_cb_fn_t cb, \fBlast_touch_e_t\fP event_type)"
Assigns a callback function to be called when a certain touch event happens\&.

.PP
This function uses the following values of errno when an error state is reached: EACCESS - Another resource is currently trying to access the screen mutex\&.

.PP
\fBParameters\fP
.RS 4
\fIcb\fP Function pointer to callback when event type happens 
.br
\fIevent_type\fP Touch event that will trigger the callback\&.
.RE
.PP
\fBReturns\fP
.RS 4
1 if there were no errors, or PROS_ERR if an error occured while taking or returning the screen mutex\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBscreen_touch_status_s_t\fP pros::screen::touch_status ()"
Screen Text Display Functions These functions allow programmers to display text on the v5 screen Print a formatted string to the screen, overwrite available for printing at location too\&.

.PP
Will default to a medium sized font by default if invalid txt_fmt is given\&.

.PP
\fBParameters\fP
.RS 4
\fItxt_fmt\fP Text format enum that determines if the text is medium, large, medium_center, or large_center\&. (DOES NOT SUPPORT SMALL) 
.br
\fIline\fP The line number on which to print 
.br
\fIx\fP The (x,y) coordinates of the top left corner of the string 
.br
\fIy\fP The (x,y) coordinates of the top left corner of the string 
.br
\fIfmt\fP Format string 
.br
\fI\&.\&.\&.\fP Optional list of arguments for the format string
.RE
.PP
\fBExample\fP 
.PP
.nf

 /******************************************************************************/
 
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
