.TH "cpp-vision" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp-vision \- Vision Sensor C++ API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBvision\&.hpp\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::v5::Vision\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpros::v5::Vision::Vision\fP (std::uint8_t port, vision_zero_e_t zero_point=\fBE_VISION_ZERO_TOPLEFT\fP)"
.br
.ti -1c
.RI "\fBpros::v5::Vision::Vision\fP (const \fBDevice\fP &device)"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::clear_led\fP (void) const"
.br
.ti -1c
.RI "static \fBvision_signature_s_t\fP \fBpros::v5::Vision::signature_from_utility\fP (const std::int32_t id, const std::int32_t u_min, const std::int32_t u_max, const std::int32_t u_mean, const std::int32_t v_min, const std::int32_t v_max, const std::int32_t v_mean, const float range, const std::int32_t type)"
.br
.ti -1c
.RI "\fBvision_color_code_t\fP \fBpros::v5::Vision::create_color_code\fP (const std::uint32_t sig_id1, const std::uint32_t sig_id2, const std::uint32_t sig_id3=0, const std::uint32_t sig_id4=0, const std::uint32_t sig_id5=0) const"
.br
.ti -1c
.RI "static std::vector< \fBVision\fP > \fBpros::v5::Vision::get_all_devices\fP ()"
.br
.ti -1c
.RI "\fBvision_object_s_t\fP \fBpros::v5::Vision::get_by_size\fP (const std::uint32_t size_id) const"
.br
.ti -1c
.RI "\fBvision_object_s_t\fP \fBpros::v5::Vision::get_by_sig\fP (const std::uint32_t size_id, const std::uint32_t sig_id) const"
.br
.ti -1c
.RI "\fBvision_object_s_t\fP \fBpros::v5::Vision::get_by_code\fP (const std::uint32_t size_id, const \fBvision_color_code_t\fP color_code) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::get_exposure\fP (void) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::get_object_count\fP (void) const"
.br
.ti -1c
.RI "\fBvision_signature_s_t\fP \fBpros::v5::Vision::get_signature\fP (const std::uint8_t signature_id) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::get_white_balance\fP (void) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::read_by_size\fP (const std::uint32_t size_id, const std::uint32_t object_count, \fBvision_object_s_t\fP *const object_arr) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::read_by_sig\fP (const std::uint32_t size_id, const std::uint32_t sig_id, const std::uint32_t object_count, \fBvision_object_s_t\fP *const object_arr) const"
.br
.ti -1c
.RI "int32_t \fBpros::v5::Vision::read_by_code\fP (const std::uint32_t size_id, const \fBvision_color_code_t\fP color_code, const std::uint32_t object_count, \fBvision_object_s_t\fP *const object_arr) const"
.br
.ti -1c
.RI "static std::int32_t \fBpros::v5::Vision::print_signature\fP (const \fBvision_signature_s_t\fP sig)"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::set_auto_white_balance\fP (const std::uint8_t enable) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::set_exposure\fP (const std::uint8_t exposure) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::set_led\fP (const std::int32_t rgb) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::set_signature\fP (const std::uint8_t signature_id, \fBvision_signature_s_t\fP *const signature_ptr) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::set_white_balance\fP (const std::int32_t rgb) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::set_zero_point\fP (vision_zero_e_t zero_point) const"
.br
.ti -1c
.RI "std::int32_t \fBpros::v5::Vision::set_wifi_mode\fP (const std::uint8_t enable) const"
.br
.ti -1c
.RI "static \fBVision\fP \fBpros::v5::Vision::get_vision\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBNote\fP
.RS 4
Additional example code for this module can be found in its \fBTutorial\&.\fP
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "std::int32_t pros::v5::Vision::clear_led (void ) const"
Clears the vision sensor LED color, reseting it back to its default behavior, displaying the most prominent object signature color\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_color_code_t\fP pros::v5::Vision::create_color_code (const std::uint32_t sig_id1, const std::uint32_t sig_id2, const std::uint32_t sig_id3 = \fR0\fP, const std::uint32_t sig_id4 = \fR0\fP, const std::uint32_t sig_id5 = \fR0\fP) const"
Creates a color code that represents a combination of the given signature IDs\&.

.PP
This function uses the following values of errno when an error state is reached: EINVAL - Fewer than two signatures have been provided or one of the signatures is out of its [1-7] range (or 0 when omitted)\&.

.PP
\fBParameters\fP
.RS 4
\fIsig_id1\fP The first signature id [1-7] to add to the color code 
.br
\fIsig_id2\fP The second signature id [1-7] to add to the color code 
.br
\fIsig_id3\fP The third signature id [1-7] to add to the color code 
.br
\fIsig_id4\fP The fourth signature id [1-7] to add to the color code 
.br
\fIsig_id5\fP The fifth signature id [1-7] to add to the color code
.RE
.PP
\fBReturns\fP
.RS 4
A \fBvision_color_code_t\fP object containing the color code information\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::vector< \fBVision\fP > pros::v5::Vision::get_all_devices ()\fR [static]\fP"
Gets all vision sensors\&.

.PP
\fBReturns\fP
.RS 4
A vector of \fBVision\fP sensor objects\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_object_s_t\fP pros::v5::Vision::get_by_code (const std::uint32_t size_id, const \fBvision_color_code_t\fP color_code) const"
Gets the nth largest object of the given color code according to size_id\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor EAGAIN - Reading the \fBVision\fP Sensor failed for an unknown reason\&.

.PP
\fBParameters\fP
.RS 4
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.) 
.br
\fIcolor_code\fP The \fBvision_color_code_t\fP for which an object will be returned
.RE
.PP
\fBReturns\fP
.RS 4
The \fBvision_object_s_t\fP object corresponding to the given color code and size_id, or PROS_ERR if an error occurred\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_object_s_t\fP pros::v5::Vision::get_by_sig (const std::uint32_t size_id, const std::uint32_t sig_id) const"
Gets the nth largest object of the given signature according to size_id\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor EDOM - size_id is greater than the number of available objects\&. EINVAL - sig_id is outside the range [1-8] EAGAIN - Reading the vision sensor failed for an unknown reason\&.

.PP
\fBParameters\fP
.RS 4
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.) 
.br
\fIsignature\fP The \fBvision_signature_s_t\fP signature for which an object will be returned\&.
.RE
.PP
\fBReturns\fP
.RS 4
The \fBvision_object_s_t\fP object corresponding to the given signature and size_id, or PROS_ERR if an error occurred\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_object_s_t\fP pros::v5::Vision::get_by_size (const std::uint32_t size_id) const"
Gets the nth largest object according to size_id\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor EDOM - size_id is greater than the number of available objects\&. EAGAIN - Reading the vision sensor failed for an unknown reason\&.

.PP
\fBParameters\fP
.RS 4
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.)
.RE
.PP
\fBReturns\fP
.RS 4
The \fBvision_object_s_t\fP object corresponding to the given size id, or PROS_ERR if an error occurred\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::get_exposure (void ) const"
Gets the exposure parameter of the \fBVision\fP Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBReturns\fP
.RS 4
The current exposure parameter from [0,150], PROS_ERR if an error occurred
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::get_object_count (void ) const"
Gets the number of objects currently detected by the \fBVision\fP Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBReturns\fP
.RS 4
The number of objects detected on the specified vision sensor\&. Returns PROS_ERR if the port was invalid or an error occurred\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_signature_s_t\fP pros::v5::Vision::get_signature (const std::uint8_t signature_id) const"
Gets the object detection signature with the given id number\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIsignature_id\fP The signature id to read
.RE
.PP
\fBReturns\fP
.RS 4
A \fBvision_signature_s_t\fP containing information about the signature\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBVision\fP pros::v5::Vision::get_vision ()\fR [static]\fP"
Gets a vision sensor that is plugged in to the brain

.PP
\fBNote\fP
.RS 4
The first time this function is called it returns the vision sensor at the lowest port If this function is called multiple times, it will cycle through all the ports\&. For example, if you have 1 vision sensor on the robot this function will always return a vision sensor object for that port\&. If you have 2 vision sensors, all the odd numered calls to this function will return objects for the lower port number, all the even number calls will return vision objects for the higher port number
.RE
.PP
This functions uses the following values of errno when an error state is reached: ENODEV - No vision sensor is plugged into the brain

.PP
\fBReturns\fP
.RS 4
A vision object corresponding to a port that a vision sensor is connected to the brain If no vision sensor is plugged in, it returns a vision sensor on port PROS_ERR_BYTE 
.RE
.PP

.SS "std::int32_t pros::v5::Vision::get_white_balance (void ) const"
Get the white balance parameter of the \fBVision\fP Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBReturns\fP
.RS 4
The current RGB white balance setting of the sensor
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::print_signature (const \fBvision_signature_s_t\fP sig)\fR [static]\fP"
Prints the contents of the signature as an initializer list to the terminal\&.

.PP
\fBParameters\fP
.RS 4
\fIsig\fP The signature for which the contents will be printed
.RE
.PP
\fBReturns\fP
.RS 4
1 if no errors occured, PROS_ERR otherwise
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "int32_t pros::v5::Vision::read_by_code (const std::uint32_t size_id, const \fBvision_color_code_t\fP color_code, const std::uint32_t object_count, \fBvision_object_s_t\fP *const object_arr) const"
Reads up to object_count object descriptors into object_arr\&.

.PP
This function uses the following values of errno when an error state is reached: EDOM - size_id is greater than the number of available objects\&. ENODEV - The port cannot be configured as a vision sensor EAGAIN - Reading the vision sensor failed for an unknown reason\&.

.PP
\fBParameters\fP
.RS 4
\fIobject_count\fP The number of objects to read 
.br
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.) 
.br
\fIcolor_code\fP The \fBvision_color_code_t\fP for which objects will be returned 
.br
\fIobject_arr\fP A pointer to copy the objects into
.RE
.PP
\fBReturns\fP
.RS 4
The number of object signatures copied\&. This number will be less than object_count if there are fewer objects detected by the vision sensor\&. Returns PROS_ERR if the port was invalid, an error occurred, or fewer objects than size_id were found\&. All objects in object_arr that were not found are given VISION_OBJECT_ERR_SIG as their signature\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::read_by_sig (const std::uint32_t size_id, const std::uint32_t sig_id, const std::uint32_t object_count, \fBvision_object_s_t\fP *const object_arr) const"
Reads up to object_count object descriptors into object_arr\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor EDOM - size_id is greater than the number of available objects\&. EINVAL - sig_id is outside the range [1-8] EAGAIN - Reading the vision sensor failed for an unknown reason\&.

.PP
\fBParameters\fP
.RS 4
\fIobject_count\fP The number of objects to read 
.br
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.) 
.br
\fIsignature\fP The \fBvision_signature_s_t\fP signature for which an object will be returned\&. 
.br
\fIobject_arr\fP A pointer to copy the objects into
.RE
.PP
\fBReturns\fP
.RS 4
The number of object signatures copied\&. This number will be less than object_count if there are fewer objects detected by the vision sensor\&. Returns PROS_ERR if the port was invalid, an error occurred, or fewer objects than size_id were found\&. All objects in object_arr that were not found are given VISION_OBJECT_ERR_SIG as their signature\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::read_by_size (const std::uint32_t size_id, const std::uint32_t object_count, \fBvision_object_s_t\fP *const object_arr) const"
Reads up to object_count object descriptors into object_arr\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor EDOM - size_id is greater than the number of available objects\&. EAGAIN - Reading the vision sensor failed for an unknown reason\&.

.PP
\fBParameters\fP
.RS 4
\fIsize_id\fP The object to read from a list roughly ordered by object size (0 is the largest item, 1 is the second largest, etc\&.) 
.br
\fIobject_count\fP The number of objects to read 
.br
\fIobject_arr\fP A pointer to copy the objects into
.RE
.PP
\fBReturns\fP
.RS 4
The number of object signatures copied\&. This number will be less than object_count if there are fewer objects detected by the vision sensor\&. Returns PROS_ERR if the port was invalid, an error occurred, or fewer objects than size_id were found\&. All objects in object_arr that were not found are given VISION_OBJECT_ERR_SIG as their signature\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::set_auto_white_balance (const std::uint8_t enable) const"
Enables/disables auto white-balancing on the \fBVision\fP Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIenabled\fP Pass 0 to disable, 1 to enable
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::set_exposure (const std::uint8_t exposure) const"
Sets the exposure parameter of the \fBVision\fP Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIpercent\fP The new exposure setting from [0,150]\&.
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::set_led (const std::int32_t rgb) const"
Sets the vision sensor LED color, overriding the automatic behavior\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIrgb\fP An RGB code to set the LED to
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::set_signature (const std::uint8_t signature_id, \fBvision_signature_s_t\fP *const signature_ptr) const"
Stores the supplied object detection signature onto the vision sensor\&.

.PP
NOTE: This saves the signature in volatile memory, and the signature will be lost as soon as the sensor is powered down\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor EINVAL - sig_id is outside the range [1-8]

.PP
\fBParameters\fP
.RS 4
\fIsignature_id\fP The signature id to store into 
.br
\fIsignature_ptr\fP A pointer to the signature to save
.RE
.PP
\fBReturns\fP
.RS 4
1 if no errors occured, PROS_ERR otherwise
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::set_white_balance (const std::int32_t rgb) const"
Sets the white balance parameter of the \fBVision\fP Sensor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIrgb\fP The new RGB white balance setting of the sensor
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::set_wifi_mode (const std::uint8_t enable) const"
Sets the Wi-Fi mode of the \fBVision\fP sensor

.PP
This functions uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIenable\fP Disable Wi-Fi on the \fBVision\fP sensor if 0, enable otherwise (e\&.g\&. 1)
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t pros::v5::Vision::set_zero_point (vision_zero_e_t zero_point) const"
Sets the (0,0) coordinate for the Field of View\&.

.PP
This will affect the coordinates returned for each request for a \fBvision_object_s_t\fP from the sensor, so it is recommended that this function only be used to configure the sensor at the beginning of its use\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIzero_point\fP One of vision_zero_e_t to set the (0,0) coordinate for the FOV
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBvision_signature_s_t\fP pros::v5::Vision::signature_from_utility (const std::int32_t id, const std::int32_t u_min, const std::int32_t u_max, const std::int32_t u_mean, const std::int32_t v_min, const std::int32_t v_max, const std::int32_t v_mean, const float range, const std::int32_t type)\fR [static]\fP"
Creates a signature from the vision sensor utility

.PP
\fBParameters\fP
.RS 4
\fIid\fP The signature ID 
.br
\fIu_min\fP Minimum value on U axis 
.br
\fIu_max\fP Maximum value on U axis 
.br
\fIu_mean\fP Mean value on U axis 
.br
\fIv_min\fP Minimum value on V axis 
.br
\fIv_max\fP Maximum value on V axis 
.br
\fIv_mean\fP Mean value on V axis 
.br
\fIrgb\fP Scale factor 
.br
\fItype\fP Signature type
.RE
.PP
\fBReturns\fP
.RS 4
A \fBvision_signature_s_t\fP that can be set using \fBVision::set_signature\fP
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "pros::v5::Vision::Vision (std::uint8_t port, vision_zero_e_t zero_point = \fR\fBE_VISION_ZERO_TOPLEFT\fP\fP)"
Create a \fBVision\fP Sensor object on the given port\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a vision sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIzero_point\fP One of vision_zero_e_t to set the (0,0) coordinate for the FOV
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
