.TH "cpp-llemu" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp-llemu \- LLEMU C++ API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBllemu\&.hpp\fP"
.br
.ti -1c
.RI "file \fBllemu\&.hpp\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLCD_BTN_LEFT\fP   4"
.br
.ti -1c
.RI "#define \fBLCD_BTN_CENTER\fP   2"
.br
.ti -1c
.RI "#define \fBLCD_BTN_RIGHT\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBpros::lcd::lcd_btn_cb_fn_t\fP = void (*)(void)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBpros::lcd::Text_Align\fP { \fBText_Align::LEFT\fP = 0, \fBText_Align::CENTER\fP = 1, \fBText_Align::RIGHT\fP = 2 }"
.br
.RI "Represents how to align the text in the LCD\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBpros::lcd::is_initialized\fP (void)"
.br
.ti -1c
.RI "bool \fBpros::lcd::initialize\fP (void)"
.br
.ti -1c
.RI "bool \fBpros::lcd::shutdown\fP (void)"
.br
.ti -1c
.RI "bool \fBpros::lcd::set_text\fP (std::int16_t line, std::string text)"
.br
.ti -1c
.RI "bool \fBpros::lcd::clear\fP (void)"
.br
.ti -1c
.RI "bool \fBpros::lcd::clear_line\fP (std::int16_t line)"
.br
.ti -1c
.RI "void \fBpros::lcd::register_btn0_cb\fP (lcd_btn_cb_fn_t cb)"
.br
.ti -1c
.RI "void \fBpros::lcd::register_btn1_cb\fP (lcd_btn_cb_fn_t cb)"
.br
.ti -1c
.RI "void \fBpros::lcd::register_btn2_cb\fP (lcd_btn_cb_fn_t cb)"
.br
.ti -1c
.RI "void \fBpros::lcd::set_text_align\fP (\fBText_Align\fP alignment)"
.br
.ti -1c
.RI "std::uint8_t \fBpros::lcd::read_buttons\fP (void)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Params> bool \fBpros::lcd::print\fP (std::int16_t line, const char *fmt, Params\&.\&.\&. args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
LLEMU - \fBL\fPegacy \fBL\fPcd \fBEMU\fPlator

.PP

.PP
LLEMU provides a virtual 40x8 LCD screen with 3 buttons\&. The user can set the text of the screen and set create functions that are run when the buttons are pressed\&.

.PP
LLEMU is a emulation of the UART-based LCD screens that were available with VEX's cortex product line\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBpros::lcd::Text_Align\fP\fR [strong]\fP"

.PP
Represents how to align the text in the LCD\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILEFT \fP
Align the text to the left side of LCD line\&. 
.TP
\f(BICENTER \fP
Align the text to the center of the LCD line\&. 
.TP
\f(BIRIGHT \fP
Align the text to the right side of the LCD line\&. 
.SH "Function Documentation"
.PP 
.SS "bool pros::lcd::clear (void )"
Clears the contents of the emulated three-button LCD screen\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&. EINVAL - The line number specified is not in the range [0-7]

.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void initialize() {
  pros::lcd::initialize();
  pros::lcd::clear(); // Clear the LCD screen
}

.fi
.PP
 
.SS "bool pros::lcd::clear_line (std::int16_t line)"
Clears the contents of a line of the emulated three-button LCD screen\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&. EINVAL - The line number specified is not in the range [0-7]

.PP
\fBParameters\fP
.RS 4
\fIline\fP The line to clear
.RE
.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void initialize() {
  pros::lcd::initialize();
  pros::lcd::clear_line(0); // Clear line 0
}

.fi
.PP
 
.SS "bool pros::lcd::initialize (void )"
Creates an emulation of the three-button, UART-based VEX LCD on the display\&.

.PP
\fBReturns\fP
.RS 4
True if the LCD was successfully initialized, or false if it has already been initialized\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void initialize() {
  if (pros::lcd::initialize()) {
    pros::lcd::print("LLEMU!"); 
  }
  else {
       printf("Error: LLEMU could not initailize\\n");
  }
}

.fi
.PP
 
.SS "bool pros::lcd::is_initialized (void )"
Checks whether the emulated three-button LCD has already been initialized\&.

.PP
\fBReturns\fP
.RS 4
True if the LCD has been initialized or false if not\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
if (pros::lcd::is_initialized()) {
  pros::lcd::print("LLEMU!");
}
else {
  printf("Error: LLEMU is not initialized\\n");
}

.fi
.PP
 
.SS "template<typename\&.\&.\&. Params> bool pros::lcd::print (std::int16_t line, const char * fmt, Params\&.\&.\&. args)"
Displays a formatted string on the emulated three-button LCD screen\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&. EINVAL - The line number specified is not in the range [0-7]

.PP
\fBParameters\fP
.RS 4
\fIline\fP The line on which to display the text [0-7] 
.br
\fIfmt\fP Format string 
.br
\fI\&.\&.\&.args\fP Optional list of arguments for the format string
.RE
.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void initialize() {
  pros::lcd::initialize();
  pros::lcd::print(0, "My formatted text: %d!", 2);
}

.fi
.PP
 
.SS "std::uint8_t pros::lcd::read_buttons (void )"
Gets the button status from the emulated three-button LCD\&.

.PP
The value returned is a 3-bit integer where 1 0 0 indicates the left button is pressed, 0 1 0 indicates the center button is pressed, and 0 0 1 indicates the right button is pressed\&. 0 is returned if no buttons are currently being pressed\&.

.PP
Note that this function is provided for legacy API compatibility purposes, with the caveat that the V5 touch screen does not actually support pressing multiple points on the screen at the same time\&.

.PP
\fBReturns\fP
.RS 4
The buttons pressed as a bit mask
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void initialize() {
  pros::lcd::initialize();
}

void opcontrol() {
  while(true) {
    std::uint8_t state = pros::lcd::read_buttons();
    pros::lcd::print(0, "%d %d %d", 
      (state & LCD_BTN_LEFT) >> 2
      (state & LCD_BTN_CENTER) >> 1,
      (state & LCD_BTN_RIGHT) >> 0
    );
    
    pros::delay(10);
  }
}

.fi
.PP
 
.SS "void pros::lcd::register_btn0_cb (lcd_btn_cb_fn_t cb)"
Registers a callback function for the leftmost button\&.

.PP
When the leftmost button on the emulated three-button LCD is pressed, the user-provided callback function will be invoked\&.

.PP
\fBParameters\fP
.RS 4
\fIcb\fP A callback function of type lcd_btn_cb_fn_t(void (*cb)(void))
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void left_callback() {
  static int i = 0;
  
  pros::lcd::print(0, "Left button pressed %i times", i);
  i++
}

void initialize() {
  pros::lcd::initialize();
  pros::lcd::register_btn0_cb();
}

.fi
.PP
 
.SS "void pros::lcd::register_btn1_cb (lcd_btn_cb_fn_t cb)"
Registers a callback function for the center button\&.

.PP
When the center button on the emulated three-button LCD is pressed, the user-provided callback function will be invoked\&.

.PP
\fBParameters\fP
.RS 4
\fIcb\fP A callback function of type lcd_btn_cb_fn_t(void (*cb)(void))
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void center_callback() {
  static int i = 0;
  
  pros::lcd::print(0, "Center button pressed %i times", i);
  i++
}

void initialize() {
  pros::lcd::initialize();
  pros::lcd::register_btn1_cb();
}

.fi
.PP
 
.SS "void pros::lcd::register_btn2_cb (lcd_btn_cb_fn_t cb)"
Registers a callback function for the rightmost button\&.

.PP
When the rightmost button on the emulated three-button LCD is pressed, the user-provided callback function will be invoked\&.

.PP
\fBParameters\fP
.RS 4
\fIcb\fP A callback function of type lcd_btn_cb_fn_t(void (*cb)(void))
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void right_callback() {
  static int i = 0;
  
  pros::lcd::print(0, "Right button pressed %i times", i);
  i++
}

void initialize() {
  pros::lcd::initialize();
  pros::lcd::register_btn2_cb();
}

.fi
.PP
 
.SS "bool pros::lcd::set_text (std::int16_t line, std::string text)"
Displays a string on the emulated three-button LCD screen\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&. EINVAL - The line number specified is not in the range [0-7]

.PP
\fBParameters\fP
.RS 4
\fIline\fP The line on which to display the text [0-7] 
.br
\fItext\fP The text to display
.RE
.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void initialize() {
  pros::lcd::initialize();
  pros::lcd::set_text(0, "My custom LLEMU text!");
}

.fi
.PP
 
.SS "void pros::lcd::set_text_align (\fBText_Align\fP alignment)"
Sets the alignment to use for subsequent calls that print text to a line\&.

.PP
\fBParameters\fP
.RS 4
\fIalignment\fP An enum specifying the alignment\&. Available alignments are: TEXT_ALIGN_LEFT TEXT_ALIGN_RIGHT TEXT_ALIGN_CENTER
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void initialize() {
  pros::lcd::initialize();
  pros::lcd::set_alignment(pros::lcd::Text_Align::LEFT);
  pros::lcd::print(0, "Left Aligned Text");
  pros::lcd::set_alignment(pros::lcd::Text_Align::CENTER);
  pros::lcd::print(1, "Center Aligned Text");
  pros::lcd::set_alignment(pros::lcd::Text_Align::RIGHT);
  pros::lcd::print(2, "Right Aligned Text");
}

.fi
.PP
 
.SS "bool pros::lcd::shutdown (void )"
Turns off the Legacy LCD Emulator\&.

.PP
Calling this function will clear the entire display, and you will not be able to call any further LLEMU functions until another call to lcd_initialize\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The LCD has not been initialized\&. Call \fBlcd_initialize()\fP first\&.

.PP
\fBReturns\fP
.RS 4
True if the operation was successful, or false otherwise, setting errno values as specified above\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
#include "pros/llemu\&.hpp"

void disabled() {
  pros::lcd::shutdown();
}

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
