.TH "cpp-distance" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp-distance \- VEX Distance Sensor C++ API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdistance\&.hpp\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::v5::Distance\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpros::v5::Distance::Distance\fP (const std::uint8_t port)"
.br
.ti -1c
.RI "\fBpros::v5::Distance::Distance\fP (const \fBDevice\fP &device)"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Distance::get\fP ()"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Distance::get_distance\fP ()"
.br
.ti -1c
.RI "static std::vector< \fBDistance\fP > \fBpros::v5::Distance::get_all_devices\fP ()"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Distance::get_confidence\fP ()"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Distance::get_object_size\fP ()"
.br
.ti -1c
.RI "virtual double \fBpros::v5::Distance::get_object_velocity\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBpros::v5::Distance::operator<<\fP (std::ostream &os, \fBpros::Distance\fP &distance)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "pros::v5::Distance::Distance (const std::uint8_t port)"
Creates a \fBDistance\fP Sensor object for the given port\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as a \fBDistance\fP Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Distance::get ()\fR [virtual]\fP"
Get the currently measured distance from the sensor in mm

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an \fBDistance\fP Sensor

.PP
\fBReturns\fP
.RS 4
The distance value or PROS_ERR if the operation failed, setting errno\&. Will return 9999 if the sensor can not detect an object\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::vector< \fBDistance\fP > pros::v5::Distance::get_all_devices ()\fR [static]\fP"
Gets all distance sensors\&.

.PP
\fBReturns\fP
.RS 4
A vector of \fBDistance\fP sensor objects\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Distance::get_confidence ()\fR [virtual]\fP"
Get the confidence in the distance reading

.PP
This is a value that has a range of 0 to 63\&. 63 means high confidence, lower values imply less confidence\&. Confidence is only available when distance is > 200mm\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an \fBDistance\fP Sensor

.PP
\fBReturns\fP
.RS 4
The confidence value or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Distance::get_distance ()\fR [virtual]\fP"
Get the currently measured distance from the sensor in mm\&. 
.PP
\fBNote\fP
.RS 4
This function is identical to \fBget()\fP\&.
.RE
.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an \fBDistance\fP Sensor

.PP
\fBReturns\fP
.RS 4
The distance value or PROS_ERR if the operation failed, setting errno\&. Will return 9999 if the sensor can not detect an object\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Distance::get_object_size ()\fR [virtual]\fP"
Get the current guess at relative object size

.PP
This is a value that has a range of 0 to 400\&. A 18" x 30" grey card will return a value of approximately 75 in typical room lighting\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an \fBDistance\fP Sensor

.PP
\fBReturns\fP
.RS 4
The size value or PROS_ERR if the operation failed, setting errno\&. Will return -1 if the sensor is not able to determine object size\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual double pros::v5::Distance::get_object_velocity ()\fR [virtual]\fP"
Get the object velocity in m/s

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an \fBDistance\fP Sensor

.PP
\fBReturns\fP
.RS 4
The velocity value or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SH "Friends"
.PP 
.SS "std::ostream & operator<< (std::ostream & os, \fBpros::Distance\fP & distance)\fR [friend]\fP"
This is the overload for the << operator for printing to streams

.PP
Prints in format(this below is all in one line with no new line): \fBDistance\fP [port: (port number), distance: (distance), confidence: (confidence), object size: (object size), object velocity: (object velocity)] 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
