.TH "cpp-imu" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp-imu \- VEX Inertial Sensor C++ API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBimu\&.hpp\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::v5::Imu\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBpros::IMU\fP = \fBImu\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBpros::ImuStatus\fP { \fBready\fP = 0, \fBpros::ImuStatus::calibrating\fP = 19, \fBpros::ImuStatus::error\fP = 0xFF }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpros::v5::Imu::Imu\fP (const std::uint8_t port)"
.br
.ti -1c
.RI "\fBpros::v5::Imu::Imu\fP (const \fBDevice\fP &device)"
.br
.ti -1c
.RI "static \fBImu\fP \fBpros::v5::Imu::get_imu\fP ()"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::reset\fP (bool blocking=false) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::set_data_rate\fP (std::uint32_t rate) const"
.br
.ti -1c
.RI "static std::vector< \fBImu\fP > \fBpros::v5::Imu::get_all_devices\fP ()"
.br
.ti -1c
.RI "virtual double \fBpros::v5::Imu::get_rotation\fP () const"
.br
.ti -1c
.RI "virtual double \fBpros::v5::Imu::get_heading\fP () const"
.br
.ti -1c
.RI "virtual pros::quaternion_s_t \fBpros::v5::Imu::get_quaternion\fP () const"
.br
.ti -1c
.RI "virtual pros::euler_s_t \fBpros::v5::Imu::get_euler\fP () const"
.br
.ti -1c
.RI "virtual double \fBpros::v5::Imu::get_pitch\fP () const"
.br
.ti -1c
.RI "virtual double \fBpros::v5::Imu::get_roll\fP () const"
.br
.ti -1c
.RI "virtual double \fBpros::v5::Imu::get_yaw\fP () const"
.br
.ti -1c
.RI "virtual pros::imu_gyro_s_t \fBpros::v5::Imu::get_gyro_rate\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::tare_rotation\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::tare_heading\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::tare_pitch\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::tare_yaw\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::tare_roll\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::tare\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::tare_euler\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::set_heading\fP (const double target) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::set_rotation\fP (const double target) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::set_yaw\fP (const double target) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::set_pitch\fP (const double target) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::set_roll\fP (const double target) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::Imu::set_euler\fP (const pros::euler_s_t target) const"
.br
.ti -1c
.RI "virtual pros::imu_accel_s_t \fBpros::v5::Imu::get_accel\fP () const"
.br
.ti -1c
.RI "virtual \fBpros::ImuStatus\fP \fBpros::v5::Imu::get_status\fP () const"
.br
.ti -1c
.RI "virtual bool \fBpros::v5::Imu::is_calibrating\fP () const"
.br
.ti -1c
.RI "virtual imu_orientation_e_t \fBpros::v5::Imu::get_physical_orientation\fP () const"
.br
.ti -1c
.RI "const \fBpros::Imu\fP \fBpros::v5::literals::operator''_imu\fP (const unsigned long long int i)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBpros::v5::Imu::operator<<\fP (std::ostream &os, const \fBpros::Imu\fP &imu)"
.br
.in -1c
.SH "Detailed Description"
.PP 
/// 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBpros::ImuStatus\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIcalibrating \fP
The IMU is calibrating 
.TP
\f(BIerror \fP
Used to indicate that an error state was reached in the imu_get_status function,\\ not that the IMU is necessarily in an error state 
.SH "Function Documentation"
.PP 
.SS "virtual pros::imu_accel_s_t pros::v5::Imu::get_accel () const\fR [virtual]\fP"
Get the Inertial Sensor's raw accelerometer values

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The raw accelerometer values\&. If the operation failed, all the structure's members are filled with PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::vector< \fBImu\fP > pros::v5::Imu::get_all_devices ()\fR [static]\fP"
Gets all IMU sensors\&.

.PP
\fBReturns\fP
.RS 4
A vector of \fBImu\fP sensor objects\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual pros::euler_s_t pros::v5::Imu::get_euler () const\fR [virtual]\fP"
Get the Euler angles representing the Inertial Sensor's orientation

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The Euler angles representing the sensor's orientation\&. If the operation failed, all the structure's members are filled with PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual pros::imu_gyro_s_t pros::v5::Imu::get_gyro_rate () const\fR [virtual]\fP"
Get the Inertial Sensor's raw gyroscope values

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The raw gyroscope values\&. If the operation failed, all the structure's members are filled with PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual double pros::v5::Imu::get_heading () const\fR [virtual]\fP"
Get the Inertial Sensor's heading relative to the initial direction of its x-axis

.PP
This value is bounded by [0,360)\&. Clockwise rotations are represented with positive degree values, while counterclockwise rotations are represented with negative ones\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The degree value or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "\fBImu\fP pros::v5::Imu::get_imu ()\fR [static]\fP"
Gets a IMU sensor that is plugged in to the brain

.PP
\fBNote\fP
.RS 4
The first time this function is called it returns the IMU sensor at the lowest port If this function is called multiple times, it will cycle through all the ports\&. For example, if you have 1 IMU sensor on the robot this function will always return a IMU sensor object for that port\&. If you have 2 IMU sensors, all the odd numered calls to this function will return objects for the lower port number, all the even number calls will return IMU objects for the higher port number
.RE
.PP
This functions uses the following values of errno when an error state is reached: ENODEV - No IMU sensor is plugged into the brain

.PP
\fBReturns\fP
.RS 4
A IMU object corresponding to a port that a IMU sensor is connected to the brain If no IMU sensor is plugged in, it returns a IMU sensor on port PROS_ERR_BYTE 
.RE
.PP

.SS "virtual imu_orientation_e_t pros::v5::Imu::get_physical_orientation () const\fR [virtual]\fP"
Returns the physical orientation of the IMU

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The physical orientation of the Inertial Sensor or PROS_ERR if an error occured\&. 
.RE
.PP

.SS "virtual double pros::v5::Imu::get_pitch () const\fR [virtual]\fP"
Get the Inertial Sensor's pitch angle bounded by (-180,180)

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The pitch angle, or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual pros::quaternion_s_t pros::v5::Imu::get_quaternion () const\fR [virtual]\fP"
Get a quaternion representing the Inertial Sensor's orientation

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The quaternion representing the sensor's orientation\&. If the operation failed, all the quaternion's members are filled with PROS_ERR_F and errno is set\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual double pros::v5::Imu::get_roll () const\fR [virtual]\fP"
Get the Inertial Sensor's roll angle bounded by (-180,180)

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The roll angle, or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual double pros::v5::Imu::get_rotation () const\fR [virtual]\fP"
Get the total number of degrees the Inertial Sensor has spun about the z-axis

.PP
This value is theoretically unbounded\&. Clockwise rotations are represented with positive degree values, while counterclockwise rotations are represented with negative ones\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The degree value or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual \fBpros::ImuStatus\fP pros::v5::Imu::get_status () const\fR [virtual]\fP"
Get the Inertial Sensor's status

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The Inertial Sensor's status code, or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual double pros::v5::Imu::get_yaw () const\fR [virtual]\fP"
Get the Inertial Sensor's yaw angle bounded by (-180,180)

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
The yaw angle, or PROS_ERR_F if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "pros::v5::Imu::Imu (const std::uint8_t port)\fR [inline]\fP"
Creates an \fBImu\fP object for the given port

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual bool pros::v5::Imu::is_calibrating () const\fR [virtual]\fP"
Check whether the IMU is calibrating

.PP
\fBReturns\fP
.RS 4
true if the V5 Inertial Sensor is calibrating or false false if it is not\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "const \fBpros::Imu\fP pros::v5::literals::operator''_imu (const unsigned long long int i)"
Constructs a \fBImu\fP from a literal ending in _imu via calling the constructor

.PP
\fBReturns\fP
.RS 4
a \fBpros::Imu\fP for the corresponding port
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::reset (bool blocking = \fRfalse\fP) const\fR [virtual]\fP"
Calibrate IMU

.PP
Calibration takes approximately 2 seconds and blocks during this period if the blocking param is true, with a timeout for this operation being set a 3 seconds as a safety margin\&. This function also blocks until the IMU status flag is set properly to E_IMU_STATUS_CALIBRATING, with a minimum blocking time of 5ms and a timeout of 1 second if it's never set\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is already calibrating, or time out setting the status flag\&.

.PP
\fBParameters\fP
.RS 4
\fIblocking\fP Whether this function blocks during calibration\&. 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::set_data_rate (std::uint32_t rate) const\fR [virtual]\fP"
Set the Inertial Sensor's refresh interval in milliseconds\&.

.PP
The rate may be specified in increments of 5ms, and will be rounded down to the nearest increment\&. The minimum allowable refresh rate is 5ms\&. The default rate is 10ms\&.

.PP
As values are copied into the shared memory buffer only at 10ms intervals, setting this value to less than 10ms does not mean that you can poll the sensor's values any faster\&. However, it will guarantee that the data is as recent as possible\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIrate\fP The data refresh interval in milliseconds 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::set_euler (const pros::euler_s_t target) const\fR [virtual]\fP"
Sets the current reading of the Inertial Sensor's euler values to target euler values\&. Will default to +/- 180 if target exceeds +/- 180\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.br
\fItarget\fP Target euler values for the euler values to be set to 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::set_heading (const double target) const\fR [virtual]\fP"
Sets the current reading of the Inertial Sensor's heading to target value Target will default to 360 if above 360 and default to 0 if below 0\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.br
\fItarget\fP Target value for the heading value to be set to 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::set_pitch (const double target) const\fR [virtual]\fP"
Sets the current reading of the Inertial Sensor's pitch to target value

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.br
\fItarget\fP Target value for the pitch value to be set to 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::set_roll (const double target) const\fR [virtual]\fP"
Sets the current reading of the Inertial Sensor's roll to target value Will default to +/- 180 if target exceeds +/- 180\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.br
\fItarget\fP Target euler values for the euler values to be set to 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::set_rotation (const double target) const\fR [virtual]\fP"
Sets the current reading of the Inertial Sensor's rotation to target value

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.br
\fItarget\fP Target value for the rotation value to be set to 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::set_yaw (const double target) const\fR [virtual]\fP"
Sets the current reading of the Inertial Sensor's yaw to target value Will default to +/- 180 if target exceeds +/- 180\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.br
\fItarget\fP Target value for yaw value to be set to 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::tare () const\fR [virtual]\fP"
Resets all 5 values of the Inertial Sensor to 0\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::tare_euler () const\fR [virtual]\fP"
Reset all 3 euler values of the Inertial Sensor to 0\&.

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::tare_heading () const\fR [virtual]\fP"
Resets the current reading of the Inertial Sensor's heading to zero

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::tare_pitch () const\fR [virtual]\fP"
Resets the current reading of the Inertial Sensor's pitch to zero

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::tare_roll () const\fR [virtual]\fP"
Resets the current reading of the Inertial Sensor's roll to zero

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::tare_rotation () const\fR [virtual]\fP"
Resets the current reading of the Inertial Sensor's rotation to zero

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::v5::Imu::tare_yaw () const\fR [virtual]\fP"
Resets the current reading of the Inertial Sensor's yaw to zero

.PP
This function uses the following values of errno when an error state is reached: ENXIO - The given value is not within the range of V5 ports (1-21)\&. ENODEV - The port cannot be configured as an Inertial Sensor EAGAIN - The sensor is still calibrating

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 Inertial Sensor port number from 1-21 
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SH "Friends"
.PP 
.SS "std::ostream & operator<< (std::ostream & os, const \fBpros::Imu\fP & imu)\fR [friend]\fP"
This is the overload for the << operator for printing to streams

.PP
Prints in format(this below is all in one line with no new line): \fBImu\fP [port: imu\&._port, rotation: (rotation), heading: (heading), pitch: (pitch angle), roll: (roll angle), yaw: (yaw angle), gyro rate: {x,y,z}, get accel: {x,y,z}, calibrating: (calibrating boolean)] 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
