.TH "cpp-motor-configuration" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp-motor-configuration \- Cpp-motor-configuration
.SH SYNOPSIS
.br
.PP
.SS "Motor configuration functions"

.in +1c
.ti -1c
.RI "virtual \fBMotorBrake\fP \fBpros::v5::AbstractMotor::get_brake_mode\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< \fBMotorBrake\fP > \fBpros::v5::AbstractMotor::get_brake_mode_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::get_current_limit\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int32_t > \fBpros::v5::AbstractMotor::get_current_limit_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual \fBMotorUnits\fP \fBpros::v5::AbstractMotor::get_encoder_units\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< \fBMotorUnits\fP > \fBpros::v5::AbstractMotor::get_encoder_units_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual \fBMotorGears\fP \fBpros::v5::AbstractMotor::get_gearing\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< \fBMotorGears\fP > \fBpros::v5::AbstractMotor::get_gearing_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int8_t > \fBpros::v5::AbstractMotor::get_port_all\fP (void) const =0"
.br
.RI "Gets returns a vector with all the port numbers in the motor group\&. "
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::get_voltage_limit\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int32_t > \fBpros::v5::AbstractMotor::get_voltage_limit_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::is_reversed\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int32_t > \fBpros::v5::AbstractMotor::is_reversed_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_brake_mode\fP (const \fBMotorBrake\fP mode, const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_brake_mode\fP (const pros::motor_brake_mode_e_t mode, const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_brake_mode_all\fP (const \fBMotorBrake\fP mode) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_brake_mode_all\fP (const pros::motor_brake_mode_e_t mode) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_current_limit\fP (const std::int32_t limit, const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_current_limit_all\fP (const std::int32_t limit) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_encoder_units\fP (const \fBMotorUnits\fP units, const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_encoder_units\fP (const pros::motor_encoder_units_e_t units, const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_encoder_units_all\fP (const \fBMotorUnits\fP units) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_encoder_units_all\fP (const pros::motor_encoder_units_e_t units) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_gearing\fP (const \fBMotorGears\fP gearset, const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_gearing\fP (const pros::motor_gearset_e_t gearset, const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_gearing_all\fP (const \fBMotorGears\fP gearset) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_gearing_all\fP (const pros::motor_gearset_e_t gearset) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_reversed\fP (const bool reverse, const std::uint8_t index=0)=0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_reversed_all\fP (const bool reverse)=0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_voltage_limit\fP (const std::int32_t limit, const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_voltage_limit_all\fP (const std::int32_t limit) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_zero_position\fP (const double position, const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::set_zero_position_all\fP (const double position) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::tare_position\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::tare_position_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int8_t \fBpros::v5::AbstractMotor::get_port\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::int8_t \fBpros::v5::AbstractMotor::size\fP (void) const =0"
.br
.RI "Returns the number of objects\&. "
.in -1c
.SH "Detailed Description"
.PP 
These functions allow programmers to configure the behavior of motors 
.SH "Function Documentation"
.PP 
.SS "virtual \fBMotorBrake\fP pros::v5::AbstractMotor::get_brake_mode (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the brake mode that was set for the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
One of \fBMotorBrake\fP, according to what was set for the motor, or E_MOTOR_BRAKE_INVALID if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< \fBMotorBrake\fP > pros::v5::AbstractMotor::get_brake_mode_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the brake mode(s) that was set for the motor(s)\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
A vector containing \fBMotorBrake(s)\fP, according to what was set for the motor(s), or E_MOTOR_BRAKE_INVALID if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::get_current_limit (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the current limit for the motor in mA\&.

.PP
The default value is 2500 mA\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The motor's current limit in mA or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int32_t > pros::v5::AbstractMotor::get_current_limit_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the current limit(s) for the motor(s) in mA\&.

.PP
The default value is 2500 mA\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
A vector containing the motor's/motors' current limit(s) in mA or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual \fBMotorUnits\fP pros::v5::AbstractMotor::get_encoder_units (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the encoder units that were set for the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
One of MotorUnits according to what is set for the motor or E_MOTOR_ENCODER_INVALID if the operation failed\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< \fBMotorUnits\fP > pros::v5::AbstractMotor::get_encoder_units_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the encoder units that were set for the motor(s)\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
A vector of MotorUnits according to what is set for the motor(s) or E_MOTOR_ENCODER_INVALID if the operation failed\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual \fBMotorGears\fP pros::v5::AbstractMotor::get_gearing (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the gearset that was set for the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
One of \fBMotorGears\fP according to what is set for the motor, or \fBpros::MotorGears::invalid\fP if the operation failed\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< \fBMotorGears\fP > pros::v5::AbstractMotor::get_gearing_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the gearset(s) that was/were set for the motor(s)\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
A vector of \fBMotorGears\fP according to what is set for the motor(s), or \fBpros::MotorGears::invalid\fP if the operation failed\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int8_t pros::v5::AbstractMotor::get_port (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int8_t > pros::v5::AbstractMotor::get_port_all (void ) const\fR [pure virtual]\fP"

.PP
Gets returns a vector with all the port numbers in the motor group\&. 
.PP
\fBReturns\fP
.RS 4
std::vector<std::int8_t> 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::get_voltage_limit (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the voltage limit set by the user\&.

.PP
Default value is 0V, which means that there is no software limitation imposed on the voltage\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The motor's voltage limit in V or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int32_t > pros::v5::AbstractMotor::get_voltage_limit_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the voltage limit(s) set by the user\&.

.PP
Default value is 0V, which means that there is no software limitation imposed on the voltage\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
A vector containing the motor's/motors' voltage limit(s) in V or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::is_reversed (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the operation direction of the motor as set by the user\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the motor has been reversed and 0 if the motor was not reversed, or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int32_t > pros::v5::AbstractMotor::is_reversed_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the operation direction(s) of the motor(s) as set by the user\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the motor has been reversed and 0 if the motor was not reversed, or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_brake_mode (const \fBMotorBrake\fP mode, const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Sets one of \fBMotorBrake\fP to the motor\&. Works with the C enum and the C++ enum class\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fImode\fP The \fBMotorBrake\fP to set for the motor
.br
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_brake_mode (const pros::motor_brake_mode_e_t mode, const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_brake_mode_all (const \fBMotorBrake\fP mode) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_brake_mode_all (const pros::motor_brake_mode_e_t mode) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_current_limit (const std::int32_t limit, const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Sets the current limit for the motor in mA\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIlimit\fP The new current limit in mA
.br
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_current_limit_all (const std::int32_t limit) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_encoder_units (const \fBMotorUnits\fP units, const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Sets one of MotorUnits for the motor encoder\&. Works with the C enum and the C++ enum class\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIunits\fP The new motor encoder units
.br
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_encoder_units (const pros::motor_encoder_units_e_t units, const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_encoder_units_all (const \fBMotorUnits\fP units) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_encoder_units_all (const pros::motor_encoder_units_e_t units) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_gearing (const \fBMotorGears\fP gearset, const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Sets one of the gear cartridge (red, green, blue) for the motor\&. Usable with the C++ enum class and the C enum\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIgearset\fP The new motor gearset
.br
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_gearing (const pros::motor_gearset_e_t gearset, const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_gearing_all (const \fBMotorGears\fP gearset) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_gearing_all (const pros::motor_gearset_e_t gearset) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_reversed (const bool reverse, const std::uint8_t index = \fR0\fP)\fR [pure virtual]\fP"
Sets the reverse flag for the motor\&.

.PP
This will invert its movements and the values returned for its position\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIreverse\fP True reverses the motor, false is default
.br
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_reversed_all (const bool reverse)\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_voltage_limit (const std::int32_t limit, const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Sets the voltage limit for the motor in Volts\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIlimit\fP The new voltage limit in Volts
.br
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_voltage_limit_all (const std::int32_t limit) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_zero_position (const double position, const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Sets the position for the motor in its encoder units\&.

.PP
This will be the future reference point for the motor's "absolute" position\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIposition\fP The new reference position in its encoder units
.br
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::set_zero_position_all (const double position) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int8_t pros::v5::AbstractMotor::size (void ) const\fR [pure virtual]\fP"

.PP
Returns the number of objects\&. 
.PP
\fBReturns\fP
.RS 4
std::int8_t 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::tare_position (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Sets the "absolute" zero position of the motor to its current position\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::tare_position_all (void ) const\fR [pure virtual]\fP"

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
