.TH "cpp-motor-telemetry" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp-motor-telemetry \- Cpp-motor-telemetry
.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "Cpp-motor-configuration "
.br
.in -1c
.SS "Motor telemetry functions"

.in +1c
.ti -1c
.RI "virtual double \fBpros::v5::AbstractMotor::get_actual_velocity\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< double > \fBpros::v5::AbstractMotor::get_actual_velocity_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::get_current_draw\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int32_t > \fBpros::v5::AbstractMotor::get_current_draw_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::get_direction\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int32_t > \fBpros::v5::AbstractMotor::get_direction_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual double \fBpros::v5::AbstractMotor::get_efficiency\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< double > \fBpros::v5::AbstractMotor::get_efficiency_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::uint32_t \fBpros::v5::AbstractMotor::get_faults\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::uint32_t > \fBpros::v5::AbstractMotor::get_faults_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::uint32_t \fBpros::v5::AbstractMotor::get_flags\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::uint32_t > \fBpros::v5::AbstractMotor::get_flags_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual double \fBpros::v5::AbstractMotor::get_position\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< double > \fBpros::v5::AbstractMotor::get_position_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual double \fBpros::v5::AbstractMotor::get_power\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< double > \fBpros::v5::AbstractMotor::get_power_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::get_raw_position\fP (std::uint32_t *const timestamp, const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int32_t > \fBpros::v5::AbstractMotor::get_raw_position_all\fP (std::uint32_t *const timestamp) const =0"
.br
.ti -1c
.RI "virtual double \fBpros::v5::AbstractMotor::get_temperature\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< double > \fBpros::v5::AbstractMotor::get_temperature_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual double \fBpros::v5::AbstractMotor::get_torque\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< double > \fBpros::v5::AbstractMotor::get_torque_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::get_voltage\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int32_t > \fBpros::v5::AbstractMotor::get_voltage_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::is_over_current\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int32_t > \fBpros::v5::AbstractMotor::is_over_current_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::is_over_temp\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int32_t > \fBpros::v5::AbstractMotor::is_over_temp_all\fP (void) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
These functions allow programmers to collect telemetry from motors 
.SH "Function Documentation"
.PP 
.SS "virtual double pros::v5::AbstractMotor::get_actual_velocity (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the actual velocity of the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The motor's actual velocity in RPM or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< double > pros::v5::AbstractMotor::get_actual_velocity_all (void ) const\fR [pure virtual]\fP"
Gets a vector containing the actual velocity/velocities of the motor(s)

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBReturns\fP
.RS 4
A vector containing the motor's/motors' actual velocity/velocities in RPM or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::get_current_draw (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the current drawn by the motor in mA\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The motor's current in mA or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int32_t > pros::v5::AbstractMotor::get_current_draw_all (void ) const\fR [pure virtual]\fP"
Gets a vector containing the current(s) drawn by the motor(s) in mA\&.

.PP
This function uses the following values of errno when an error state is reached:

.PP
ENODEV - The port cannot be configured as a motor

.PP
\fBReturns\fP
.RS 4
A vector conatining the motor's/motors' current(s) in mA or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::get_direction (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the direction of movement for the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 for moving in the positive direction, -1 for moving in the negative direction, and PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int32_t > pros::v5::AbstractMotor::get_direction_all (void ) const\fR [pure virtual]\fP"
Gets a vector containing the direction(s) of movement for the motor(s)\&.

.PP
This function uses the following values of errno when an error state is reached:

.PP
ENODEV - The port cannot be configured as a motor

.PP
\fBReturns\fP
.RS 4
A vector containing 1 for moving in the positive direction, -1 for moving in the negative direction, and PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual double pros::v5::AbstractMotor::get_efficiency (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the efficiency of the motor in percent\&.

.PP
An efficiency of 100% means that the motor is moving electrically while drawing no electrical power, and an efficiency of 0% means that the motor is drawing power but not moving\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The motor's efficiency in percent or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< double > pros::v5::AbstractMotor::get_efficiency_all (void ) const\fR [pure virtual]\fP"
Gets a vector containing the efficiency/efficiencies of the motor(s) in percent\&.

.PP
An efficiency of 100% means that the motor is moving electrically while drawing no electrical power, and an efficiency of 0% means that the motor is drawing power but not moving\&.

.PP
This function uses the following values of errno when an error state is reached:

.PP
ENODEV - The port cannot be configured as a motor

.PP
\fBReturns\fP
.RS 4
A vector containing the motor's/motors' efficiency/efficiencies in percent or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::uint32_t pros::v5::AbstractMotor::get_faults (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the faults experienced by the motor\&.

.PP
Compare this bitfield to the bitmasks in pros::motor_fault_e_t\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
A bitfield containing the motor's faults\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::uint32_t > pros::v5::AbstractMotor::get_faults_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the faults experienced by the motor(s)\&.

.PP
Compare this bitfield to the bitmasks in pros::motor_fault_e_t\&.

.PP
This function uses the following values of errno when an error state is reached:

.PP
ENODEV - The port cannot be configured as a motor

.PP
\fBReturns\fP
.RS 4
A bitfield containing the motor's/motors' faults\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::uint32_t pros::v5::AbstractMotor::get_flags (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the flags set by the motor's operation\&.

.PP
Compare this bitfield to the bitmasks in pros::motor_flag_e_t\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
A bitfield containing the motor's flags\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::uint32_t > pros::v5::AbstractMotor::get_flags_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the flags set by the motor's/motors' operation\&.

.PP
Compare this bitfield to the bitmasks in pros::motor_flag_e_t\&.

.PP
This function uses the following values of errno when an error state is reached:

.PP
ENODEV - The port cannot be configured as a motor

.PP
\fBReturns\fP
.RS 4
A bitfield containing the motor's/motors' flags\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual double pros::v5::AbstractMotor::get_position (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the absolute position of the motor in its encoder units\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The motor's absolute position in its encoder units or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< double > pros::v5::AbstractMotor::get_position_all (void ) const\fR [pure virtual]\fP"
Gets a vector containing the absolute position(s) of the motor(s) in its encoder units\&.

.PP
This function uses the following values of errno when an error state is reached:

.PP
ENODEV - The port cannot be configured as a motor

.PP
\fBReturns\fP
.RS 4
A vector containing the motor's/motors' absolute position(s) in its encoder units or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual double pros::v5::AbstractMotor::get_power (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the power drawn by the motor in Watts\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The motor's power draw in Watts or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< double > pros::v5::AbstractMotor::get_power_all (void ) const\fR [pure virtual]\fP"
Gets a vector containing the power(s) drawn by the motor(s) in Watts\&.

.PP
This function uses the following values of errno when an error state is reached:

.PP
ENODEV - The port cannot be configured as a motor

.PP
\fBReturns\fP
.RS 4
A vector containing the motor's/motors' power draw in Watts or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::get_raw_position (std::uint32_t *const timestamp, const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the raw encoder count of the motor at a given timestamp\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fItimestamp\fP A pointer to a time in milliseconds for which the encoder count will be returned\&. If NULL, the timestamp at which the encoder count was read will not be supplied
.br
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The raw encoder count at the given timestamp or PROS_ERR if the operation failed\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int32_t > pros::v5::AbstractMotor::get_raw_position_all (std::uint32_t *const timestamp) const\fR [pure virtual]\fP"
Gets a vector of the raw encoder count(s) of the motor(s) at a given timestamp\&.

.PP
This function uses the following values of errno when an error state is reached:

.PP
ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fItimestamp\fP A pointer to a time in milliseconds for which the encoder count will be returned\&. If NULL, the timestamp at which the encoder count was read will not be supplied
.RE
.PP
\fBReturns\fP
.RS 4
A vector containing the raw encoder count(s) at the given timestamp or PROS_ERR if the operation failed\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual double pros::v5::AbstractMotor::get_temperature (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the temperature of the motor in degrees Celsius\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The motor's temperature in degrees Celsius or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< double > pros::v5::AbstractMotor::get_temperature_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the temperature(s) of the motor(s) in degrees Celsius\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
A vector containing the motor's/motors' temperature(s) in degrees Celsius or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual double pros::v5::AbstractMotor::get_torque (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the torque generated by the motor in Newton Meters (Nm)\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The motor's torque in Nm or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< double > pros::v5::AbstractMotor::get_torque_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the torque(s) generated by the motor(s) in Newton Meters (Nm)\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
A vector containing the motor's/motors' torque(s) in Nm or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::get_voltage (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the voltage delivered to the motor in millivolts\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The motor's voltage in mV or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int32_t > pros::v5::AbstractMotor::get_voltage_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the voltage(s) delivered to the motor(s) in millivolts\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
A vector containing the motor's/motors' voltage(s) in mV or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::is_over_current (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Checks if the motor is drawing over its current limit\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the motor's current limit is being exceeded and 0 if the current limit is not exceeded, or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int32_t > pros::v5::AbstractMotor::is_over_current_all (void ) const\fR [pure virtual]\fP"
Gets a vector of whether each motor is drawing over its current limit\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the motor's current limit is being exceeded and 0 if the current limit is not exceeded, or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::is_over_temp (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the temperature limit flag for the motor\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the temperature limit is exceeded and 0 if the temperature is below the limit, or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int32_t > pros::v5::AbstractMotor::is_over_temp_all (void ) const\fR [pure virtual]\fP"
Gets a vector of the temperature limit flag(s) for the motor(s)\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
1 if the temperature limit is exceeded and 0 if the temperature is below the limit, or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
