.TH "cpp-serial" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp-serial \- Generic Serial C++ API
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBserial\&.hpp\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::Serial\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpros::Serial::Serial\fP (std::uint8_t port, std::int32_t baudrate)"
.br
.ti -1c
.RI "\fBpros::Serial::Serial\fP (std::uint8_t port)"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::Serial::set_baudrate\fP (std::int32_t baudrate) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::Serial::flush\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::Serial::get_read_avail\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::Serial::get_write_free\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::Serial::peek_byte\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::Serial::read_byte\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::Serial::read\fP (std::uint8_t *buffer, std::int32_t length) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::Serial::write_byte\fP (std::uint8_t buffer) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::Serial::write\fP (std::uint8_t *buffer, std::int32_t length) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "virtual std::int32_t pros::Serial::flush () const\fR [virtual]\fP"
Clears the internal input and output FIFO buffers\&.

.PP
This can be useful to reset state and remove old, potentially unneeded data from the input FIFO buffer or to cancel sending any data in the output FIFO buffer\&.

.PP
\fBNote\fP
.RS 4
This function does not cause the data in the output buffer to be written, it simply clears the internal buffers\&. Unlike stdout, generic serial does not use buffered IO (the FIFO buffers are written as soon as possible)\&.
.RE
.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&.

.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::Serial::get_read_avail () const\fR [virtual]\fP"
Returns the number of bytes available to be read in the the port's FIFO input buffer\&.

.PP
\fBNote\fP
.RS 4
This function does not actually read any bytes, is simply returns the number of bytes available to be read\&.
.RE
.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&.

.PP
\fBReturns\fP
.RS 4
The number of bytes avaliable to be read or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::Serial::get_write_free () const\fR [virtual]\fP"
Returns the number of bytes free in the port's FIFO output buffer\&.

.PP
\fBNote\fP
.RS 4
This function does not actually write any bytes, is simply returns the number of bytes free in the port's buffer\&.
.RE
.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&.

.PP
\fBReturns\fP
.RS 4
The number of bytes free or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::Serial::peek_byte () const\fR [virtual]\fP"
Reads the next byte avaliable in the port's input buffer without removing it\&.

.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&.

.PP
\fBReturns\fP
.RS 4
The next byte avaliable to be read, -1 if none are available, or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::Serial::read (std::uint8_t * buffer, std::int32_t length) const\fR [virtual]\fP"
Reads up to the next length bytes from the port's input buffer and places them in the user supplied buffer\&.

.PP
\fBNote\fP
.RS 4
This function will only return bytes that are currently avaliable to be read and will not block waiting for any to arrive\&.
.RE
.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&.

.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The location to place the data read 
.br
\fIlength\fP The maximum number of bytes to read
.RE
.PP
\fBReturns\fP
.RS 4
The number of bytes read or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::Serial::read_byte () const\fR [virtual]\fP"
Reads the next byte avaliable in the port's input buffer\&.

.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&.

.PP
\fBReturns\fP
.RS 4
The next byte avaliable to be read, -1 if none are available, or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SS "pros::Serial::Serial (std::uint8_t port)\fR [explicit]\fP"
Creates a \fBSerial\fP object for the given port without a set baudrate\&.

.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SS "pros::Serial::Serial (std::uint8_t port, std::int32_t baudrate)\fR [explicit]\fP"
Creates a \fBSerial\fP object for the given port and specifications\&.

.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIbaudrate\fP The baudrate to run the port at
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::Serial::set_baudrate (std::int32_t baudrate) const\fR [virtual]\fP"
\fBSerial\fP communication functions These functions allow programmers to communicate using UART over RS485 Sets the baudrate for the serial port to operate at\&.

.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&.

.PP
\fBParameters\fP
.RS 4
\fIbaudrate\fP The baudrate to operate at
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::Serial::write (std::uint8_t * buffer, std::int32_t length) const\fR [virtual]\fP"
Writes up to length bytes from the user supplied buffer to the port's output buffer\&.

.PP
\fBNote\fP
.RS 4
Data in the port's output buffer is written to the serial port as soon as possible on a FIFO basis and can not be done manually by the user\&.
.RE
.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&. EIO - Serious internal write error\&.

.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The data to write 
.br
\fIlength\fP The maximum number of bytes to write
.RE
.PP
\fBReturns\fP
.RS 4
The number of bytes written or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SS "virtual std::int32_t pros::Serial::write_byte (std::uint8_t buffer) const\fR [virtual]\fP"
Write the given byte to the port's output buffer\&.

.PP
\fBNote\fP
.RS 4
Data in the port's output buffer is written to the serial port as soon as possible on a FIFO basis and can not be done manually by the user\&.
.RE
.PP
This function uses the following values of errno when an error state is reached: EINVAL - The given value is not within the range of V5 ports (1-21)\&. EACCES - Another resource is currently trying to access the port\&. EIO - Serious internal write error\&.

.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The byte to write
.RE
.PP
\fBReturns\fP
.RS 4
The number of bytes written or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample:\fP 
.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
