.TH "cpp-abstract-motor" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp-abstract-motor \- Cpp-abstract-motor
.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "Cpp-motor-telemetry "
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBabstract_motor\&.hpp\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::v5::AbstractMotor\fP"
.br
.in -1c
.SS "Motor movement functions"
These functions allow programmers to make motors move 
.in +1c
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::move\fP (std::int32_t voltage) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::move_absolute\fP (const double position, const std::int32_t velocity) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::move_relative\fP (const double position, const std::int32_t velocity) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::move_velocity\fP (const std::int32_t velocity) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::move_voltage\fP (const std::int32_t voltage) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::brake\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::modify_profiled_velocity\fP (const std::int32_t velocity) const =0"
.br
.ti -1c
.RI "virtual double \fBpros::v5::AbstractMotor::get_target_position\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< double > \fBpros::v5::AbstractMotor::get_target_position_all\fP (void) const =0"
.br
.ti -1c
.RI "virtual std::int32_t \fBpros::v5::AbstractMotor::get_target_velocity\fP (const std::uint8_t index=0) const =0"
.br
.ti -1c
.RI "virtual std::vector< std::int32_t > \fBpros::v5::AbstractMotor::get_target_velocity_all\fP (void) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "virtual std::int32_t pros::v5::AbstractMotor::brake (void ) const\fR [pure virtual]\fP"
Stops the motor using the currently configured brake mode\&.

.PP
This function sets motor velocity to zero, which will cause it to act according to the set brake mode\&. If brake mode is set to MOTOR_BRAKE_HOLD, this function may behave differently than calling move_absolute(0) or motor_move_relative(0)\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor 
.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual double pros::v5::AbstractMotor::get_target_position (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the target position set for the motor by the user, with a parameter for the motor index\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The target position in its encoder units or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< double > pros::v5::AbstractMotor::get_target_position_all (void ) const\fR [pure virtual]\fP"
Gets a vector containing the target position(s) set for the motor(s) by the user

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBReturns\fP
.RS 4
A vector containing the target position(s) in its encoder units or PROS_ERR_F if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::get_target_velocity (const std::uint8_t index = \fR0\fP) const\fR [pure virtual]\fP"
Gets the velocity commanded to the motor by the user\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIindex\fP Optional parameter\&. The index of the motor to get the target position of\&. By default index is 0, and will return an error for an out of bounds index
.RE
.PP
\fBReturns\fP
.RS 4
The commanded motor velocity from +-100, +-200, or +-600, or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::vector< std::int32_t > pros::v5::AbstractMotor::get_target_velocity_all (void ) const\fR [pure virtual]\fP"
Gets a vector containing the velocity/velocities commanded to the motor(s) by the user

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBReturns\fP
.RS 4
A vector containing the commanded motor velocity/velocities from +-100, +-200, or +-600, or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::modify_profiled_velocity (const std::int32_t velocity) const\fR [pure virtual]\fP"
Changes the output velocity for a profiled movement (motor_move_absolute or motor_move_relative)\&. This will have no effect if the motor is not following a profiled movement\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIvelocity\fP The new motor velocity from +-100, +-200, or +-600 depending on the motor's gearset
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::move (std::int32_t voltage) const\fR [pure virtual]\fP"
Sets the voltage for the motor from -127 to 127\&.

.PP
This is designed to map easily to the input from the controller's analog stick for simple opcontrol use\&. The actual behavior of the motor is analogous to use of \fBmotor_move()\fP, or motorSet() from the PROS 2 API\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIvoltage\fP The new motor voltage from -127 to 127
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::move_absolute (const double position, const std::int32_t velocity) const\fR [pure virtual]\fP"
Sets the target absolute position for the motor to move to\&.

.PP
This movement is relative to the position of the motor when initialized or the position when it was most recently reset with \fBpros::Motor::set_zero_position()\fP\&.

.PP
\fBNote\fP
.RS 4
This function simply sets the target for the motor, it does not block program execution until the movement finishes\&.
.RE
.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIposition\fP The absolute position to move to in the motor's encoder units 
.br
\fIvelocity\fP The maximum allowable velocity for the movement in RPM
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::move_relative (const double position, const std::int32_t velocity) const\fR [pure virtual]\fP"
Sets the relative target position for the motor to move to\&.

.PP
This movement is relative to the current position of the motor as given in pros::Motor::motor_get_position()\&. Providing 10\&.0 as the position parameter would result in the motor moving clockwise 10 units, no matter what the current position is\&.

.PP
\fBNote\fP
.RS 4
This function simply sets the target for the motor, it does not block program execution until the movement finishes\&.
.RE
.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIposition\fP The relative position to move to in the motor's encoder units 
.br
\fIvelocity\fP The maximum allowable velocity for the movement in RPM
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::move_velocity (const std::int32_t velocity) const\fR [pure virtual]\fP"
Sets the velocity for the motor\&.

.PP
This velocity corresponds to different actual speeds depending on the gearset used for the motor\&. This results in a range of +-100 for E_MOTOR_GEARSET_36, +-200 for E_MOTOR_GEARSET_18, and +-600 for E_MOTOR_GEARSET_6\&. The velocity is held with PID to ensure consistent speed, as opposed to setting the motor's voltage\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIvelocity\fP The new motor velocity from -+-100, +-200, or +-600 depending on the motor's gearset
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SS "virtual std::int32_t pros::v5::AbstractMotor::move_voltage (const std::int32_t voltage) const\fR [pure virtual]\fP"
Sets the output voltage for the motor from -12000 to 12000 in millivolts\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port cannot be configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIport\fP The V5 port number from 1-21 
.br
\fIvoltage\fP The new voltage value from -12000 to 12000
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&. 
.RE
.PP

.PP
Implemented in \fBpros::v5::Motor\fP, and \fBpros::v5::MotorGroup\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
