.TH "include/pros/device.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/device.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBv5_device_e\fP \fBv5_device_e_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBv5_device_e\fP { \fBE_DEVICE_NONE\fP = 0, \fBE_DEVICE_MOTOR\fP = 2, \fBE_DEVICE_ROTATION\fP = 4, \fBE_DEVICE_IMU\fP = 6, \fBE_DEVICE_DISTANCE\fP = 7, \fBE_DEVICE_RADIO\fP = 8, \fBE_DEVICE_VISION\fP = 11, \fBE_DEVICE_ADI\fP = 12, \fBE_DEVICE_OPTICAL\fP = 16, \fBE_DEVICE_GPS\fP = 20, \fBE_DEVICE_SERIAL\fP = 129, \fB__attribute__\fP =((deprecated("use E_DEVICE_SERIAL instead"))) = E_DEVICE_SERIAL, \fBE_DEVICE_UNDEFINED\fP = 255 }"
.br
.RI "List of possible v5 devices\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "v5_device_e_t \fBget_plugged_type\fP (uint8_t port)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains functions for interacting with VEX devices\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
\fBCopyright\fP
.RS 4
(c) 2017-2021, Purdue University ACM SIGBots\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
