.TH "include/pros/distance.hpp" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/distance.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include 'pros/device\&.hpp'\fP
.br
\fR#include 'pros/distance\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::v5::Distance\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpros\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBpros::Distance\fP \fBpros::v5::literals::operator''_dist\fP (const unsigned long long int d)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains prototypes for the V5 Distance Sensor-related functions\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
\fBCopyright\fP
.RS 4
(c) 2017-2023, Purdue University ACM SIGBots\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Function Documentation"
.PP 
.SS "const \fBpros::Distance\fP pros::v5::literals::operator''_dist (const unsigned long long int d)"
Constructs a Distance sensor object from a literal ending in _dist via calling the constructor

.PP
\fBReturns\fP
.RS 4
a \fBpros::Distance\fP for the corresponding port
.RE
.PP
\fBExample\fP 
.PP
.nf
using namespace pros::literals;
void opcontrol() {
 pros::Distance dist = 2_dist; //Makes an dist object on port 2
}

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
