.TH "DSRDS" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DSRDS
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDSRDS\fP (int port, Dir direction, double x_offset, double y_offset)"
.br
.ti -1c
.RI "double \fBread_in\fP ()"
.br
.ti -1c
.RI "void \fBset_x_offset\fP (double x)"
.br
.ti -1c
.RI "void \fBset_y_offset\fP (double y)"
.br
.ti -1c
.RI "void \fBset_offsets\fP (double x, double y)"
.br
.ti -1c
.RI "void \fBset_dir\fP (Dir direction)"
.br
.ti -1c
.RI "double \fBget_x_offset\fP ()"
.br
.ti -1c
.RI "double \fBget_y_offset\fP ()"
.br
.ti -1c
.RI "ez::pose \fBget_offsets\fP ()"
.br
.ti -1c
.RI "Dir \fBget_dir\fP ()"
.br
.ti -1c
.RI "std::string \fBget_dir_string\fP ()"
.br
.ti -1c
.RI "void \fBmeasure_offsets\fP (double read45, double read30, double read0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
