.TH "ez::AutonSelector" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ez::AutonSelector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutonSelector\fP (std::vector< \fBAuton\fP > autons)"
.br
.ti -1c
.RI "void \fBselected_auton_call\fP ()"
.br
.ti -1c
.RI "void \fBselected_auton_print\fP ()"
.br
.ti -1c
.RI "void \fBautons_add\fP (std::vector< \fBAuton\fP > autons)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBAuton\fP > \fBAutons\fP"
.br
.ti -1c
.RI "int \fBauton_page_current\fP"
.br
.ti -1c
.RI "int \fBauton_count\fP"
.br
.ti -1c
.RI "int \fBlast_auton_page_current\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
