.TH "ez::Drive::const_and_name" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ez::Drive::const_and_name
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP = ''"
.br
.ti -1c
.RI "\fBPID::Constants\fP * \fBconsts\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
