.TH "ez::Piston" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ez::Piston
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPiston\fP (int input_port, bool default_state=false)"
.br
.ti -1c
.RI "\fBPiston\fP (int input_port, int expander_smart_port, bool default_state=false)"
.br
.ti -1c
.RI "void \fBset\fP (bool input)"
.br
.ti -1c
.RI "bool \fBget\fP ()"
.br
.ti -1c
.RI "void \fBbutton_toggle\fP (int toggle)"
.br
.ti -1c
.RI "void \fBbuttons\fP (int active, int deactive)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpros::adi::DigitalOut\fP \fBpiston\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ez::Piston::Piston (int input_port, bool default_state = \fRfalse\fP)"
\fBPiston\fP constructor\&.

.PP
The starting position of your piston defaults to false\&.

.PP
\fBParameters\fP
.RS 4
\fIinput_port\fP the ports of your pistons 
.br
\fIdefault_state\fP starting state of your piston 
.RE
.PP

.SS "ez::Piston::Piston (int input_port, int expander_smart_port, bool default_state = \fRfalse\fP)"
\fBPiston\fP constructor in 3 wire expander\&.

.PP
The starting position of your piston defaults to false\&.

.PP
\fBParameters\fP
.RS 4
\fIinput_ports\fP the ports of your pistons 
.br
\fIdefault_state\fP starting state of your piston 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void ez::Piston::button_toggle (int toggle)"
One button toggle for the piston\&.

.PP
\fBParameters\fP
.RS 4
\fItoggle\fP an input button 
.RE
.PP

.SS "void ez::Piston::buttons (int active, int deactive)"
Two buttons trigger the piston\&. Active is enabled, deactive is disabled\&.

.PP
\fBParameters\fP
.RS 4
\fIactive\fP sets piston to true 
.br
\fIactive\fP sets piston to false 
.RE
.PP

.SS "bool ez::Piston::get ()"
Returns current piston state\&. 
.SS "void ez::Piston::set (bool input)"
Sets the piston to the input\&.

.PP
\fBParameters\fP
.RS 4
\fIinput\fP true sets to the opposite of the starting position 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBpros::adi::DigitalOut\fP ez::Piston::piston"
\fBPiston\fP used throughout\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
