.TH "ez::PID::exit_condition_" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ez::PID::exit_condition_
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PID\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsmall_exit_time\fP = 0"
.br
.ti -1c
.RI "double \fBsmall_error\fP = 0"
.br
.ti -1c
.RI "int \fBbig_exit_time\fP = 0"
.br
.ti -1c
.RI "double \fBbig_error\fP = 0"
.br
.ti -1c
.RI "int \fBvelocity_exit_time\fP = 0"
.br
.ti -1c
.RI "int \fBmA_timeout\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for exit condition\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
