.TH "ez::slew::Constants" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ez::slew::Constants
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <slew\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmin_speed\fP = 0"
.br
.ti -1c
.RI "double \fBdistance_to_travel\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for constants\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
