.TH "ez::slew" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ez::slew
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBConstants\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBslew\fP (double distance, int minimum_speed)"
.br
.ti -1c
.RI "void \fBconstants_set\fP (double distance, int minimum_speed)"
.br
.ti -1c
.RI "\fBConstants\fP \fBconstants_get\fP ()"
.br
.ti -1c
.RI "void \fBinitialize\fP (bool \fBenabled\fP, double maximum_speed, double target, double current)"
.br
.ti -1c
.RI "double \fBiterate\fP (double current)"
.br
.ti -1c
.RI "bool \fBenabled\fP ()"
.br
.ti -1c
.RI "double \fBoutput\fP ()"
.br
.ti -1c
.RI "void \fBspeed_max_set\fP (double speed)"
.br
.ti -1c
.RI "double \fBspeed_max_get\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBConstants\fP \fBconstants\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ez::slew::slew (double distance, int minimum_speed)"
Sets constants for slew\&. Slew ramps up the speed of the robot until the set distance is traveled\&.

.PP
\fBParameters\fP
.RS 4
\fIdistance\fP the distance the robot travels before reaching max speed 
.br
\fIminimum_speed\fP the starting speed for the movement 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void ez::slew::constants_set (double distance, int minimum_speed)"
Sets constants for slew\&. Slew ramps up the speed of the robot until the set distance is traveled\&.

.PP
\fBParameters\fP
.RS 4
\fIdistance\fP the distance the robot travels before reaching max speed 
.br
\fIminimum_speed\fP the starting speed for the movement 
.RE
.PP

.SS "bool ez::slew::enabled ()"
Returns true if slew is enabled, and false if it isn't\&. 
.SS "void ez::slew::initialize (bool enabled, double maximum_speed, double target, double current)"
Initializes slew for the motion\&.

.PP
\fBParameters\fP
.RS 4
\fIenabled\fP true enables slew, false disables slew 
.br
\fImaximum_speed\fP the target speed the robot will ramp up too 
.br
\fItarget\fP the target position for the motion 
.br
\fIcurrent\fP the position at the start of the motion 
.RE
.PP

.SS "double ez::slew::iterate (double current)"
Iterates slew and ramps up speed the farther along the motion the robot gets\&.

.PP
\fBParameters\fP
.RS 4
\fIcurrent\fP current sensor value 
.RE
.PP

.SS "double ez::slew::output ()"
Returns the last output of iterate\&. 
.SS "double ez::slew::speed_max_get ()"
Returns the max speed the slew can be\&. 
.SS "void ez::slew::speed_max_set (double speed)"
Sets the max speed the slew can be\&.

.PP
\fBParameters\fP
.RS 4
\fIspeed\fP maximum speed 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
