.TH "ez::tracking_wheel" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ez::tracking_wheel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtracking_wheel\fP (std::vector< int > ports, double wheel_diameter, double distance_to_center=0\&.0, double ratio=1\&.0)"
.br
.ti -1c
.RI "\fBtracking_wheel\fP (int smart_port, std::vector< int > ports, double wheel_diameter, double distance_to_center=0\&.0, double ratio=1\&.0)"
.br
.ti -1c
.RI "\fBtracking_wheel\fP (int port, double wheel_diameter, double distance_to_center=0\&.0, double ratio=1\&.0)"
.br
.ti -1c
.RI "double \fBget\fP ()"
.br
.ti -1c
.RI "double \fBget_raw\fP ()"
.br
.ti -1c
.RI "void \fBdistance_to_center_set\fP (double input)"
.br
.ti -1c
.RI "double \fBdistance_to_center_get\fP ()"
.br
.ti -1c
.RI "void \fBdistance_to_center_flip_set\fP (bool input)"
.br
.ti -1c
.RI "bool \fBdistance_to_center_flip_get\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "double \fBticks_per_inch\fP ()"
.br
.ti -1c
.RI "void \fBticks_per_rev_set\fP (double input)"
.br
.ti -1c
.RI "double \fBticks_per_rev_get\fP ()"
.br
.ti -1c
.RI "void \fBratio_set\fP (double input)"
.br
.ti -1c
.RI "double \fBratio_get\fP ()"
.br
.ti -1c
.RI "void \fBwheel_diameter_set\fP (double input)"
.br
.ti -1c
.RI "double \fBwheel_diameter_get\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpros::adi::Encoder\fP \fBadi_encoder\fP"
.br
.ti -1c
.RI "\fBpros::Rotation\fP \fBsmart_encoder\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ez::tracking_wheel::tracking_wheel (std::vector< int > ports, double wheel_diameter, double distance_to_center = \fR0\&.0\fP, double ratio = \fR1\&.0\fP)"
Creates a new tracking wheel with an ADI Encoder\&.

.PP
\fBParameters\fP
.RS 4
\fIports\fP {'A', 'B'}\&. make the encoder negative if reversed 
.br
\fIwheel_diameter\fP assumed inches, this is the diameter of your wheel 
.br
\fIdistance_to_center\fP the distance to the center of your robot, this is used for tracking 
.br
\fIratio\fP the gear ratio of your tracking wheel\&. if it's not geared, this should be 1\&.0 
.RE
.PP

.SS "ez::tracking_wheel::tracking_wheel (int smart_port, std::vector< int > ports, double wheel_diameter, double distance_to_center = \fR0\&.0\fP, double ratio = \fR1\&.0\fP)"
Creates a new tracking wheel with an ADI Encoder plugged into a 3-wire expander\&.

.PP
\fBParameters\fP
.RS 4
\fIsmart_port\fP the smart port your ADI Expander is plugged into 
.br
\fIports\fP {'A', 'B'}\&. make the encoder negative if reversed 
.br
\fIwheel_diameter\fP assumed inches, this is the diameter of your wheel 
.br
\fIdistance_to_center\fP the distance to the center of your robot, this is used for tracking 
.br
\fIratio\fP the gear ratio of your tracking wheel\&. if it's not geared, this should be 1\&.0 
.RE
.PP

.SS "ez::tracking_wheel::tracking_wheel (int port, double wheel_diameter, double distance_to_center = \fR0\&.0\fP, double ratio = \fR1\&.0\fP)"
Creates a new tracking wheel with a Rotation sensor\&.

.PP
\fBParameters\fP
.RS 4
\fIport\fP the port your Rotation sensor is plugged into, make this negative if reversed 
.br
\fIwheel_diameter\fP assumed inches, this is the diameter of your wheel 
.br
\fIdistance_to_center\fP the distance to the center of your robot, this is used for tracking 
.br
\fIratio\fP the gear ratio of your tracking wheel\&. if it's not geared, this should be 1\&.0 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool ez::tracking_wheel::distance_to_center_flip_get ()"
Returns if the distance to center is flipped or not\&. False is not, true is\&. 
.SS "void ez::tracking_wheel::distance_to_center_flip_set (bool input)"
Sets the distance to the center to be flipped to negative or not\&.

.PP
\fBParameters\fP
.RS 4
\fIinput\fP flips distance to center to negative\&. false leaves it alone, true flips it 
.RE
.PP

.SS "double ez::tracking_wheel::distance_to_center_get ()"
Returns the distance to the center of the robot\&. 
.SS "void ez::tracking_wheel::distance_to_center_set (double input)"
Sets the distance to the center of the robot\&.

.PP
\fBParameters\fP
.RS 4
\fIinput\fP distance to the center of your robot in inches 
.RE
.PP

.SS "double ez::tracking_wheel::get ()"
Returns how far the wheel has traveled in inches\&. 
.SS "double ez::tracking_wheel::get_raw ()"
Returns the raw sensor value\&. 
.SS "double ez::tracking_wheel::ratio_get ()"
Returns the gear ratio for your tracking wheel\&. 
.SS "void ez::tracking_wheel::ratio_set (double input)"
Sets the gear ratio for your tracking wheel\&.

.PP
\fBParameters\fP
.RS 4
\fIinput\fP gear ratio of tracking wheel 
.RE
.PP

.SS "void ez::tracking_wheel::reset ()"
Resets your sensor\&. 
.SS "double ez::tracking_wheel::ticks_per_inch ()"
Returns the constant for how many ticks is 1 inch\&. 
.SS "double ez::tracking_wheel::ticks_per_rev_get ()"
Returns the amount of ticks per revolution of your sensor\&. 
.SS "void ez::tracking_wheel::ticks_per_rev_set (double input)"
Sets the amount of ticks per revolution of your sensor\&.

.PP
This is useful for custom encoders\&.

.PP
\fBParameters\fP
.RS 4
\fIinput\fP ticks per revolution 
.RE
.PP

.SS "double ez::tracking_wheel::wheel_diameter_get ()"
Returns the diameter of your wheel\&. 
.SS "void ez::tracking_wheel::wheel_diameter_set (double input)"
Sets the diameter of your wheel\&.

.PP
\fBParameters\fP
.RS 4
\fIinput\fP wheel diameter 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
