.TH "include/pros/gps.hpp" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/gps.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <stdbool\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include 'pros/device\&.hpp'\fP
.br
\fR#include 'pros/gps\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::v5::Gps\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpros\fP"
.br
.in -1c
.SS "Typedefs"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBpros::GPS\fP = \fBGps\fP"
.br
.RI "Alias for \fBGps\fP is \fBGPS\fP for user convenience\&. "
.in -1c
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBpros::Gps\fP \fBpros::v5::literals::operator''_gps\fP (const unsigned long long int g)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains prototypes for functions related to the VEX GPS\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
\fBCopyright\fP
.RS 4
(c) 2017-2023, Purdue University ACM SIGBots\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Function Documentation"
.PP 
.SS "const \fBpros::Gps\fP pros::v5::literals::operator''_gps (const unsigned long long int g)"
Constructs a Gps object with the given port number

.PP
\fBExample\fP 
.PP
.nf
using namespace literals;

void opcontrol() {
     pros::Gps gps = 1_gps;
  while (true) {
    pos = gps\&.get_position();
    screen_print(TEXT_MEDIUM, 1, "X Position: %4d, Y Position: %4d", pos\&.x, pos\&.y);
    delay(20);
  }
}

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
