.TH "gps_raw_s" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gps_raw_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.RI "Perceived Pitch based on GPS + IMU\&. "
.ti -1c
.RI "double \fBy\fP"
.br
.RI "Perceived Roll based on GPS + IMU\&. "
.ti -1c
.RI "double \fBz\fP"
.br
.RI "Perceived Yaw based on GPS + IMU\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
