.TH "include/pros/imu.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/imu.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBimu_raw_s\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMU_MINIMUM_DATA_RATE\fP   5"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBimu_status_e\fP \fBimu_status_e_t\fP"
.br
.ti -1c
.RI "typedef enum imu_orientation_e \fBimu_orientation_e_t\fP"
.br
.ti -1c
.RI "typedef struct \fBimu_raw_s\fP \fBimu_gyro_s_t\fP"
.br
.ti -1c
.RI "typedef struct \fBimu_raw_s\fP \fBimu_accel_s_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBimu_status_e\fP { \fBE_IMU_STATUS_READY\fP = 0, \fBE_IMU_STATUS_CALIBRATING\fP = 1, \fBE_IMU_STATUS_ERROR\fP = 0xFF }"
.br
.ti -1c
.RI "enum \fBimu_orientation_e\fP { \fBE_IMU_Z_UP\fP = 0, \fBE_IMU_Z_DOWN\fP = 1, \fBE_IMU_X_UP\fP = 2, \fBE_IMU_X_DOWN\fP = 3, \fBE_IMU_Y_UP\fP = 4, \fBE_IMU_Y_DOWN\fP = 5, \fBE_IMU_ORIENTATION_ERROR\fP = 0xFF }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__)) quaternion_s"
.br
.ti -1c
.RI "int32_t \fBimu_reset\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBimu_reset_blocking\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBimu_set_data_rate\fP (uint8_t port, uint32_t rate)"
.br
.ti -1c
.RI "double \fBimu_get_rotation\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBimu_get_heading\fP (uint8_t port)"
.br
.ti -1c
.RI "\fBquaternion_s_t\fP \fBimu_get_quaternion\fP (uint8_t port)"
.br
.ti -1c
.RI "\fBeuler_s_t\fP \fBimu_get_euler\fP (uint8_t port)"
.br
.ti -1c
.RI "\fBimu_gyro_s_t\fP \fBimu_get_gyro_rate\fP (uint8_t port)"
.br
.ti -1c
.RI "\fBimu_accel_s_t\fP \fBimu_get_accel\fP (uint8_t port)"
.br
.ti -1c
.RI "imu_status_e_t \fBimu_get_status\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBimu_get_pitch\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBimu_get_roll\fP (uint8_t port)"
.br
.ti -1c
.RI "double \fBimu_get_yaw\fP (uint8_t port)"
.br
.in -1c
.PP
.RI "\fBValue Set Functions\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "int32_t \fBimu_set_euler\fP (uint8_t port, \fBeuler_s_t\fP target)"
.br
.ti -1c
.RI "int32_t \fBimu_set_rotation\fP (uint8_t port, double target)"
.br
.ti -1c
.RI "int32_t \fBimu_set_heading\fP (uint8_t port, double target)"
.br
.ti -1c
.RI "int32_t \fBimu_set_pitch\fP (uint8_t port, double target)"
.br
.ti -1c
.RI "int32_t \fBimu_set_roll\fP (uint8_t port, double target)"
.br
.ti -1c
.RI "int32_t \fBimu_set_yaw\fP (uint8_t port, double target)"
.br
.ti -1c
.RI "imu_orientation_e_t \fBimu_get_physical_orientation\fP (uint8_t port)"
.br
.in -1c
.in -1c
.PP
.RI "\fBValue Reset Functions\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "int32_t \fBimu_tare_heading\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBimu_tare_rotation\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBimu_tare_pitch\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBimu_tare_roll\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBimu_tare_yaw\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBimu_tare_euler\fP (uint8_t port)"
.br
.ti -1c
.RI "int32_t \fBimu_tare\fP (uint8_t port)"
.br
.in -1c
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBquaternion_s_t\fP"
.br
.ti -1c
.RI "\fBeuler_s_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains prototypes for functions related to the VEX Inertial sensor\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
\fBCopyright\fP
.RS 4
(c) 2017-2023, Purdue University ACM SIGBots\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
