.TH "lcd_s" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lcd_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_obj_t * \fBframe\fP"
.br
.ti -1c
.RI "lv_obj_t * \fBscreen\fP"
.br
.ti -1c
.RI "lv_obj_t * \fBlcd_text\fP [8]"
.br
.ti -1c
.RI "lv_obj_t * \fBbtn_container\fP"
.br
.ti -1c
.RI "lv_obj_t * \fBbtns\fP [3]"
.br
.ti -1c
.RI "lcd_btn_cb_fn_t \fBcallbacks\fP [3]"
.br
.ti -1c
.RI "volatile uint8_t \fBtouch_bits\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
