.TH "include/pros/link.hpp" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/link.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'pros/link\&.h'\fP
.br
\fR#include 'pros/device\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::Link\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpros\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains prototypes for functions related to robot to robot communications\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
Copyright (c) 2017-2021, Purdue University ACM SIGBots\&.

.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
