.TH "include/pros/llemu.hpp" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/llemu.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpros\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLCD_BTN_LEFT\fP   4"
.br
.ti -1c
.RI "#define \fBLCD_BTN_CENTER\fP   2"
.br
.ti -1c
.RI "#define \fBLCD_BTN_RIGHT\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "__attribute__((weak)) bool \fBset_text\fP(std __attribute__((weak)) bool \fBclear_line\fP(std \fBpros::lcd::__attribute__\fP ((weak)) bool \fBinitialize\fP(void)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Params> bool \fBpros::lcd::print\fP (std::int16_t line, const char *fmt, Params\&.\&.\&. args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Legacy LCD Emulator

.PP
This file defines a high-level API for emulating the three-button, UART-based VEX LCD, containing a set of functions that facilitate the use of a software- emulated version of the classic VEX LCD module\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
\fBCopyright\fP
.RS 4
(c) 2017-2023, Purdue University ACM SIGBots\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
