.TH "include/liblvgl/lv_api_map.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/lv_api_map.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lvgl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV_NO_TASK_READY\fP   LV_NO_TIMER_READY"
.br
.ti -1c
.RI "#define \fBLV_INDEV_STATE_REL\fP   LV_INDEV_STATE_RELEASED"
.br
.ti -1c
.RI "#define \fBLV_INDEV_STATE_PR\fP   LV_INDEV_STATE_PRESSED"
.br
.ti -1c
.RI "#define \fBLV_OBJ_FLAG_SNAPABLE\fP   \fBLV_OBJ_FLAG_SNAPPABLE\fP   /*Fixed typo*/"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
