.TH "include/liblvgl/misc/lv_async.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/misc/lv_async.h
.SH SYNOPSIS
.br
.PP
\fR#include 'lv_types\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBlv_async_cb_t\fP) (void *)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "lv_res_t \fBlv_async_call\fP (\fBlv_async_cb_t\fP async_xcb, void *user_data)"
.br
.ti -1c
.RI "lv_res_t \fBlv_async_call_cancel\fP (\fBlv_async_cb_t\fP async_xcb, void *user_data)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* lv_async_cb_t) (void *)"
Type for async callback\&. 
.SH "Function Documentation"
.PP 
.SS "lv_res_t lv_async_call (\fBlv_async_cb_t\fP async_xcb, void * user_data)"
Call an asynchronous function the next time lv_timer_handler() is run\&. This function is likely to return \fBbefore\fP the call actually happens! 
.PP
\fBParameters\fP
.RS 4
\fIasync_xcb\fP a callback which is the task itself\&. (the 'x' in the argument name indicates that it's not a fully generic function because it not follows the \fRfunc_name(object, callback, \&.\&.\&.)\fP convention) 
.br
\fIuser_data\fP custom parameter 
.RE
.PP

.SS "lv_res_t lv_async_call_cancel (\fBlv_async_cb_t\fP async_xcb, void * user_data)"
Cancel an asynchronous function call 
.PP
\fBParameters\fP
.RS 4
\fIasync_xcb\fP a callback which is the task itself\&. 
.br
\fIuser_data\fP custom parameter 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
