.TH "lv_cover_check_info_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_cover_check_info_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_event\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlv_cover_res_t\fP \fBres\fP"
.br
.ti -1c
.RI "const \fBlv_area_t\fP * \fBarea\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used as the event parameter of \fBLV_EVENT_COVER_CHECK\fP to check if an area is covered by the object or not\&. In the event use \fRconst \fBlv_area_t\fP * area = lv_event_get_cover_area(e)\fP to get the area to check and \fRlv_event_set_cover_res(e, res)\fP to set the result\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/core/lv_event\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
