.TH "include/liblvgl/lv_conf_kconfig.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/lv_conf_kconfig.h
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
* Configs that need special handling when LVGL is used with Kconfig 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
