.TH "lv_color32_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_color32_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBblue\fP"
.br
.ti -1c
.RI "   uint8_t \fBgreen\fP"
.br
.ti -1c
.RI "   uint8_t \fBred\fP"
.br
.ti -1c
.RI "   uint8_t \fBalpha\fP"
.br
.ti -1c
.RI "} \fBch\fP"
.br
.ti -1c
.RI "uint32_t \fBfull\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
