.TH "lv_draw_label_dsc_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_draw_label_dsc_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBlv_font_t\fP * \fBfont\fP"
.br
.ti -1c
.RI "uint32_t \fBsel_start\fP"
.br
.ti -1c
.RI "uint32_t \fBsel_end\fP"
.br
.ti -1c
.RI "lv_color_t \fBcolor\fP"
.br
.ti -1c
.RI "lv_color_t \fBsel_color\fP"
.br
.ti -1c
.RI "lv_color_t \fBsel_bg_color\fP"
.br
.ti -1c
.RI "lv_coord_t \fBline_space\fP"
.br
.ti -1c
.RI "lv_coord_t \fBletter_space\fP"
.br
.ti -1c
.RI "lv_coord_t \fBofs_x\fP"
.br
.ti -1c
.RI "lv_coord_t \fBofs_y\fP"
.br
.ti -1c
.RI "lv_opa_t \fBopa\fP"
.br
.ti -1c
.RI "lv_base_dir_t \fBbidi_dir\fP"
.br
.ti -1c
.RI "lv_text_align_t \fBalign\fP"
.br
.ti -1c
.RI "lv_text_flag_t \fBflag\fP"
.br
.ti -1c
.RI "lv_text_decor_t \fBdecor\fP: 3"
.br
.ti -1c
.RI "lv_blend_mode_t \fBblend_mode\fP: 3"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
