.TH "include/liblvgl/draw/lv_draw_arc.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/lv_draw_arc.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_color\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_area\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_style\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlv_draw_arc_dsc_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlv_draw_arc_dsc_init\fP (\fBlv_draw_arc_dsc_t\fP *dsc)"
.br
.ti -1c
.RI "void \fBlv_draw_arc\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, const \fBlv_draw_arc_dsc_t\fP *dsc, const \fBlv_point_t\fP *center, uint16_t radius, uint16_t start_angle, uint16_t end_angle)"
.br
.ti -1c
.RI "void \fBlv_draw_arc_get_area\fP (lv_coord_t x, lv_coord_t y, uint16_t radius, uint16_t start_angle, uint16_t end_angle, lv_coord_t w, bool rounded, \fBlv_area_t\fP *area)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void lv_draw_arc (struct \fB_lv_draw_ctx_t\fP * draw_ctx, const \fBlv_draw_arc_dsc_t\fP * dsc, const \fBlv_point_t\fP * center, uint16_t radius, uint16_t start_angle, uint16_t end_angle)"
Draw an arc\&. (Can draw pie too with great thickness\&.) 
.PP
\fBParameters\fP
.RS 4
\fIcenter_x\fP the x coordinate of the center of the arc 
.br
\fIcenter_y\fP the y coordinate of the center of the arc 
.br
\fIradius\fP the radius of the arc 
.br
\fImask\fP the arc will be drawn only in this mask 
.br
\fIstart_angle\fP the start angle of the arc (0 deg on the bottom, 90 deg on the right) 
.br
\fIend_angle\fP the end angle of the arc 
.br
\fIclip_area\fP the arc will be drawn only in this area 
.br
\fIdsc\fP pointer to an initialized \fR\fBlv_draw_line_dsc_t\fP\fP variable 
.RE
.PP

.SS "void lv_draw_arc_get_area (lv_coord_t x, lv_coord_t y, uint16_t radius, uint16_t start_angle, uint16_t end_angle, lv_coord_t w, bool rounded, \fBlv_area_t\fP * area)"
Get an area the should be invalidated when the arcs angle changed between start_angle and end_ange 
.PP
\fBParameters\fP
.RS 4
\fIx\fP the x coordinate of the center of the arc 
.br
\fIy\fP the y coordinate of the center of the arc 
.br
\fIradius\fP the radius of the arc 
.br
\fIstart_angle\fP the start angle of the arc (0 deg on the bottom, 90 deg on the right) 
.br
\fIend_angle\fP the end angle of the arc 
.br
\fIw\fP width of the arc 
.br
\fIrounded\fP true: the arc is rounded 
.br
\fIarea\fP store the area to invalidate here 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
