.TH "include/liblvgl/draw/lv_draw.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/lv_draw.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_style\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_txt\&.h'\fP
.br
\fR#include 'lv_img_decoder\&.h'\fP
.br
\fR#include 'lv_img_cache\&.h'\fP
.br
\fR#include 'lv_draw_rect\&.h'\fP
.br
\fR#include 'lv_draw_label\&.h'\fP
.br
\fR#include 'lv_draw_img\&.h'\fP
.br
\fR#include 'lv_draw_line\&.h'\fP
.br
\fR#include 'lv_draw_triangle\&.h'\fP
.br
\fR#include 'lv_draw_arc\&.h'\fP
.br
\fR#include 'lv_draw_mask\&.h'\fP
.br
\fR#include 'lv_draw_transform\&.h'\fP
.br
\fR#include 'lv_draw_layer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlv_draw_mask_t\fP"
.br
.ti -1c
.RI "struct \fB_lv_draw_layer_ctx_t\fP"
.br
.ti -1c
.RI "struct \fB_lv_draw_ctx_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_lv_draw_layer_ctx_t\fP \fBlv_draw_layer_ctx_t\fP"
.br
.ti -1c
.RI "typedef struct \fB_lv_draw_ctx_t\fP \fBlv_draw_ctx_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlv_draw_init\fP (void)"
.br
.ti -1c
.RI "void \fBlv_draw_wait_for_finish\fP (lv_draw_ctx_t *draw_ctx)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
