.TH "include/liblvgl/draw/sdl/lv_draw_sdl_composite.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/sdl/lv_draw_sdl_composite.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include 'lv_draw_sdl\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_area\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_color\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum lv_draw_sdl_composite_texture_id_t \fBlv_draw_sdl_composite_texture_id_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlv_draw_sdl_composite_texture_id_t\fP { \fBLV_DRAW_SDL_COMPOSITE_TEXTURE_ID_STREAM0\fP, \fBLV_DRAW_SDL_COMPOSITE_TEXTURE_ID_STREAM1\fP, \fBLV_DRAW_SDL_COMPOSITE_TEXTURE_ID_TARGET0\fP, \fBLV_DRAW_SDL_COMPOSITE_TEXTURE_ID_TARGET1\fP, \fBLV_DRAW_SDL_COMPOSITE_TEXTURE_ID_TRANSFORM0\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBlv_draw_sdl_composite_begin\fP (lv_draw_sdl_ctx_t *ctx, const \fBlv_area_t\fP *coords_in, const \fBlv_area_t\fP *clip_in, const \fBlv_area_t\fP *extension, lv_blend_mode_t blend_mode, \fBlv_area_t\fP *coords_out, \fBlv_area_t\fP *clip_out, \fBlv_area_t\fP *apply_area)"
.br
.ti -1c
.RI "void \fBlv_draw_sdl_composite_end\fP (lv_draw_sdl_ctx_t *ctx, const \fBlv_area_t\fP *apply_area, lv_blend_mode_t blend_mode)"
.br
.ti -1c
.RI "SDL_Texture * \fBlv_draw_sdl_composite_texture_obtain\fP (lv_draw_sdl_ctx_t *ctx, lv_draw_sdl_composite_texture_id_t id, lv_coord_t w, lv_coord_t h)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool lv_draw_sdl_composite_begin (lv_draw_sdl_ctx_t * ctx, const \fBlv_area_t\fP * coords_in, const \fBlv_area_t\fP * clip_in, const \fBlv_area_t\fP * extension, lv_blend_mode_t blend_mode, \fBlv_area_t\fP * coords_out, \fBlv_area_t\fP * clip_out, \fBlv_area_t\fP * apply_area)"
Begin drawing with mask\&. Render target will be switched to a temporary texture, and drawing coordinates may get clipped or translated 
.PP
\fBParameters\fP
.RS 4
\fIcoords_in\fP Original coordinates 
.br
\fIclip_in\fP Original clip area 
.br
\fIextension\fP Useful for shadows or outlines, can be NULL 
.br
\fIcoords_out\fP Translated coords 
.br
\fIclip_out\fP Translated clip area 
.br
\fIapply_area\fP Area of actual composited texture will be drawn 
.RE
.PP
\fBReturns\fP
.RS 4
true if there are any mask needs to be drawn, false otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
