.TH "lv_draw_arc_dsc_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_draw_arc_dsc_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_color_t \fBcolor\fP"
.br
.ti -1c
.RI "lv_coord_t \fBwidth\fP"
.br
.ti -1c
.RI "uint16_t \fBstart_angle\fP"
.br
.ti -1c
.RI "uint16_t \fBend_angle\fP"
.br
.ti -1c
.RI "const void * \fBimg_src\fP"
.br
.ti -1c
.RI "lv_opa_t \fBopa\fP"
.br
.ti -1c
.RI "lv_blend_mode_t \fBblend_mode\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBrounded\fP: 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
