.TH "include/liblvgl/draw/lv_draw_label.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/lv_draw_label.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/misc/lv_bidi\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_txt\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_color\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_style\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlv_draw_label_dsc_t\fP"
.br
.ti -1c
.RI "struct \fB_lv_draw_label_hint_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV_DRAW_LABEL_NO_TXT_SEL\fP   (0xFFFF)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_lv_draw_label_hint_t\fP \fBlv_draw_label_hint_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "LV_ATTRIBUTE_FAST_MEM void \fBlv_draw_label_dsc_init\fP (\fBlv_draw_label_dsc_t\fP *dsc)"
.br
.ti -1c
.RI "LV_ATTRIBUTE_FAST_MEM void \fBlv_draw_label\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, const \fBlv_draw_label_dsc_t\fP *dsc, const \fBlv_area_t\fP *coords, const char *txt, \fBlv_draw_label_hint_t\fP *hint)"
.br
.ti -1c
.RI "void \fBlv_draw_letter\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, const \fBlv_draw_label_dsc_t\fP *dsc, const \fBlv_point_t\fP *pos_p, uint32_t letter)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_lv_draw_label_hint_t\fP \fBlv_draw_label_hint_t\fP"
Store some info to speed up drawing of very large texts It takes a lot of time to get the first visible character because all the previous characters needs to be checked to calculate the positions\&. This structure stores an earlier (e\&.g\&. at -1000 px) coordinate and the index of that line\&. Therefore the calculations can start from here\&. 
.SH "Function Documentation"
.PP 
.SS "LV_ATTRIBUTE_FAST_MEM void lv_draw_label (struct \fB_lv_draw_ctx_t\fP * draw_ctx, const \fBlv_draw_label_dsc_t\fP * dsc, const \fBlv_area_t\fP * coords, const char * txt, \fBlv_draw_label_hint_t\fP * hint)"
Write a text 
.PP
\fBParameters\fP
.RS 4
\fIcoords\fP coordinates of the label 
.br
\fImask\fP the label will be drawn only in this area 
.br
\fIdsc\fP pointer to draw descriptor 
.br
\fItxt\fP \fR\\0\fP terminated text to write 
.br
\fIhint\fP pointer to a \fR\fBlv_draw_label_hint_t\fP\fP variable\&. It is managed by the draw to speed up the drawing of very long texts (thousands of lines)\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
