.TH "include/liblvgl/draw/lv_draw_line.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/lv_draw_line.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_color\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_area\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_style\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlv_draw_line_dsc_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "LV_ATTRIBUTE_FAST_MEM void \fBlv_draw_line_dsc_init\fP (\fBlv_draw_line_dsc_t\fP *dsc)"
.br
.ti -1c
.RI "void \fBlv_draw_line\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, const \fBlv_draw_line_dsc_t\fP *dsc, const \fBlv_point_t\fP *point1, const \fBlv_point_t\fP *point2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void lv_draw_line (struct \fB_lv_draw_ctx_t\fP * draw_ctx, const \fBlv_draw_line_dsc_t\fP * dsc, const \fBlv_point_t\fP * point1, const \fBlv_point_t\fP * point2)"
Draw a line 
.PP
\fBParameters\fP
.RS 4
\fIpoint1\fP first point of the line 
.br
\fIpoint2\fP second point of the line 
.br
\fIclip\fP the line will be drawn only in this area 
.br
\fIdsc\fP pointer to an initialized \fR\fBlv_draw_line_dsc_t\fP\fP variable 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
