.TH "lv_draw_sw_ctx_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_draw_sw_ctx_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_draw_ctx_t \fBbase_draw\fP"
.br
.ti -1c
.RI "void(* \fBblend\fP )(lv_draw_ctx_t *draw_ctx, const \fBlv_draw_sw_blend_dsc_t\fP *dsc)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void(* lv_draw_sw_ctx_t::blend) (lv_draw_ctx_t *draw_ctx, const \fBlv_draw_sw_blend_dsc_t\fP *dsc)"
Fill an area of the destination buffer with a color 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
