.TH "include/liblvgl/draw/lv_draw_transform.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/lv_draw_transform.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_area\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlv_draw_transform\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, const \fBlv_area_t\fP *dest_area, const void *src_buf, lv_coord_t src_w, lv_coord_t src_h, lv_coord_t src_stride, const \fBlv_draw_img_dsc_t\fP *draw_dsc, lv_img_cf_t cf, lv_color_t *cbuf, lv_opa_t *abuf)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
