.TH "include/liblvgl/core/lv_disp.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/core/lv_disp.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/hal/lv_hal\&.h'\fP
.br
\fR#include 'lv_obj\&.h'\fP
.br
\fR#include 'lv_theme\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV_HOR_RES\fP   \fBlv_disp_get_hor_res\fP(\fBlv_disp_get_default\fP())"
.br
.ti -1c
.RI "#define \fBLV_VER_RES\fP   \fBlv_disp_get_ver_res\fP(\fBlv_disp_get_default\fP())"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlv_scr_load_anim_t\fP { \fBLV_SCR_LOAD_ANIM_NONE\fP, \fBLV_SCR_LOAD_ANIM_OVER_LEFT\fP, \fBLV_SCR_LOAD_ANIM_OVER_RIGHT\fP, \fBLV_SCR_LOAD_ANIM_OVER_TOP\fP, \fBLV_SCR_LOAD_ANIM_OVER_BOTTOM\fP, \fBLV_SCR_LOAD_ANIM_MOVE_LEFT\fP, \fBLV_SCR_LOAD_ANIM_MOVE_RIGHT\fP, \fBLV_SCR_LOAD_ANIM_MOVE_TOP\fP, \fBLV_SCR_LOAD_ANIM_MOVE_BOTTOM\fP, \fBLV_SCR_LOAD_ANIM_FADE_IN\fP, \fBLV_SCR_LOAD_ANIM_FADE_ON\fP = LV_SCR_LOAD_ANIM_FADE_IN, \fBLV_SCR_LOAD_ANIM_FADE_OUT\fP, \fBLV_SCR_LOAD_ANIM_OUT_LEFT\fP, \fBLV_SCR_LOAD_ANIM_OUT_RIGHT\fP, \fBLV_SCR_LOAD_ANIM_OUT_TOP\fP, \fBLV_SCR_LOAD_ANIM_OUT_BOTTOM\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "lv_obj_t * \fBlv_disp_get_scr_act\fP (\fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "lv_obj_t * \fBlv_disp_get_scr_prev\fP (\fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "void \fBlv_disp_load_scr\fP (lv_obj_t *scr)"
.br
.ti -1c
.RI "lv_obj_t * \fBlv_disp_get_layer_top\fP (\fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "lv_obj_t * \fBlv_disp_get_layer_sys\fP (\fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "void \fBlv_disp_set_theme\fP (\fBlv_disp_t\fP *disp, lv_theme_t *th)"
.br
.ti -1c
.RI "lv_theme_t * \fBlv_disp_get_theme\fP (\fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "void \fBlv_disp_set_bg_color\fP (\fBlv_disp_t\fP *disp, lv_color_t color)"
.br
.ti -1c
.RI "void \fBlv_disp_set_bg_image\fP (\fBlv_disp_t\fP *disp, const void *img_src)"
.br
.ti -1c
.RI "void \fBlv_disp_set_bg_opa\fP (\fBlv_disp_t\fP *disp, lv_opa_t opa)"
.br
.ti -1c
.RI "void \fBlv_scr_load_anim\fP (lv_obj_t *scr, lv_scr_load_anim_t anim_type, uint32_t time, uint32_t \fBdelay\fP, bool auto_del)"
.br
.ti -1c
.RI "uint32_t \fBlv_disp_get_inactive_time\fP (const \fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "void \fBlv_disp_trig_activity\fP (\fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "void \fBlv_disp_clean_dcache\fP (\fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "void \fBlv_disp_enable_invalidation\fP (\fBlv_disp_t\fP *disp, bool en)"
.br
.ti -1c
.RI "bool \fBlv_disp_is_invalidation_enabled\fP (\fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "\fBlv_timer_t\fP * \fB_lv_disp_get_refr_timer\fP (\fBlv_disp_t\fP *disp)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LV_HOR_RES   \fBlv_disp_get_hor_res\fP(\fBlv_disp_get_default\fP())"
The horizontal resolution of the currently active display\&. 
.SS "#define LV_VER_RES   \fBlv_disp_get_ver_res\fP(\fBlv_disp_get_default\fP())"
The vertical resolution of the currently active display\&. 
.SH "Function Documentation"
.PP 
.SS "\fBlv_timer_t\fP * _lv_disp_get_refr_timer (\fBlv_disp_t\fP * disp)"
Get a pointer to the screen refresher timer to modify its parameters with \fRlv_timer_\&.\&.\&.\fP functions\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the display refresher timer\&. (NULL on error) 
.RE
.PP

.SS "void lv_disp_clean_dcache (\fBlv_disp_t\fP * disp)"
Clean any CPU cache that is related to the display\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display (NULL to use the default display) 
.RE
.PP

.SS "void lv_disp_enable_invalidation (\fBlv_disp_t\fP * disp, bool en)"
Temporarily enable and disable the invalidation of the display\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display (NULL to use the default display) 
.br
\fIen\fP true: enable invalidation; false: invalidation 
.RE
.PP

.SS "uint32_t lv_disp_get_inactive_time (const \fBlv_disp_t\fP * disp)"
Get elapsed time since last user activity on a display (e\&.g\&. click) 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display (NULL to get the overall smallest inactivity) 
.RE
.PP
\fBReturns\fP
.RS 4
elapsed ticks (milliseconds) since the last activity 
.RE
.PP

.SS "lv_obj_t * lv_disp_get_layer_sys (\fBlv_disp_t\fP * disp)"
Return with the sys\&. layer\&. (Same on every screen and it is above the normal screen and the top layer) 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to display which sys\&. layer should be retrieved\&. (NULL to use the default screen) 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the sys layer object (transparent screen sized lv_obj) 
.RE
.PP

.SS "lv_obj_t * lv_disp_get_layer_top (\fBlv_disp_t\fP * disp)"
Return with the top layer\&. (Same on every screen and it is above the normal screen layer) 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to display which top layer should be get\&. (NULL to use the default screen) 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the top layer object (transparent screen sized lv_obj) 
.RE
.PP

.SS "lv_obj_t * lv_disp_get_scr_act (\fBlv_disp_t\fP * disp)"
Return with a pointer to the active screen 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to display which active screen should be get\&. (NULL to use the default screen) 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the active screen object (loaded by 'lv_scr_load()') 
.RE
.PP

.SS "lv_obj_t * lv_disp_get_scr_prev (\fBlv_disp_t\fP * disp)"
Return with a pointer to the previous screen\&. Only used during screen transitions\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to display which previous screen should be get\&. (NULL to use the default screen) 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the previous screen object or NULL if not used now 
.RE
.PP

.SS "lv_theme_t * lv_disp_get_theme (\fBlv_disp_t\fP * disp)"
Get the theme of a display 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display 
.RE
.PP
\fBReturns\fP
.RS 4
the display's theme (can be NULL) 
.RE
.PP

.SS "bool lv_disp_is_invalidation_enabled (\fBlv_disp_t\fP * disp)"
Get display invalidation is enabled\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display (NULL to use the default display) 
.RE
.PP
\fBReturns\fP
.RS 4
return true if invalidation is enabled 
.RE
.PP

.SS "void lv_disp_load_scr (lv_obj_t * scr)"
Make a screen active 
.PP
\fBParameters\fP
.RS 4
\fIscr\fP pointer to a screen 
.RE
.PP

.SS "void lv_disp_set_bg_color (\fBlv_disp_t\fP * disp, lv_color_t color)"
Set the background color of a display 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display 
.br
\fIcolor\fP color of the background 
.RE
.PP

.SS "void lv_disp_set_bg_image (\fBlv_disp_t\fP * disp, const void * img_src)"
Set the background image of a display 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display 
.br
\fIimg_src\fP path to file or pointer to an \fR\fBlv_img_dsc_t\fP\fP variable 
.RE
.PP

.SS "void lv_disp_set_bg_opa (\fBlv_disp_t\fP * disp, lv_opa_t opa)"
Set opacity of the background 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display 
.br
\fIopa\fP opacity (0\&.\&.255) 
.RE
.PP

.SS "void lv_disp_set_theme (\fBlv_disp_t\fP * disp, lv_theme_t * th)"
Set the theme of a display 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display 
.RE
.PP

.SS "void lv_disp_trig_activity (\fBlv_disp_t\fP * disp)"
Manually trigger an activity on a display 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to a display (NULL to use the default display) 
.RE
.PP

.SS "void lv_scr_load_anim (lv_obj_t * scr, lv_scr_load_anim_t anim_type, uint32_t time, uint32_t delay, bool auto_del)"
Switch screen with animation 
.PP
\fBParameters\fP
.RS 4
\fIscr\fP pointer to the new screen to load 
.br
\fIanim_type\fP type of the animation from \fRlv_scr_load_anim_t\fP, e\&.g\&. \fRLV_SCR_LOAD_ANIM_MOVE_LEFT\fP 
.br
\fItime\fP time of the animation 
.br
\fIdelay\fP delay before the transition 
.br
\fIauto_del\fP true: automatically delete the old screen 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
