.TH "include/liblvgl/draw/lv_draw_layer.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/lv_draw_layer.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlv_draw_layer_flags_t\fP { \fBLV_DRAW_LAYER_FLAG_NONE\fP, \fBLV_DRAW_LAYER_FLAG_HAS_ALPHA\fP, \fBLV_DRAW_LAYER_FLAG_CAN_SUBDIVIDE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fB_lv_draw_layer_ctx_t\fP * \fBlv_draw_layer_create\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, const \fBlv_area_t\fP *layer_area, lv_draw_layer_flags_t flags)"
.br
.ti -1c
.RI "void \fBlv_draw_layer_adjust\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, struct \fB_lv_draw_layer_ctx_t\fP *layer_ctx, lv_draw_layer_flags_t flags)"
.br
.ti -1c
.RI "void \fBlv_draw_layer_blend\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, struct \fB_lv_draw_layer_ctx_t\fP *layer_ctx, \fBlv_draw_img_dsc_t\fP *draw_dsc)"
.br
.ti -1c
.RI "void \fBlv_draw_layer_destroy\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, struct \fB_lv_draw_layer_ctx_t\fP *layer_ctx)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void lv_draw_layer_adjust (struct \fB_lv_draw_ctx_t\fP * draw_ctx, struct \fB_lv_draw_layer_ctx_t\fP * layer_ctx, lv_draw_layer_flags_t flags)"
Adjust the layer_ctx and/or draw_ctx based on the \fRlayer_ctx->area_act\fP\&. It's called only if flags has \fRLV_DRAW_LAYER_FLAG_CAN_SUBDIVIDE\fP 
.PP
\fBParameters\fP
.RS 4
\fIdraw_ctx\fP pointer to the current draw context 
.br
\fIlayer_ctx\fP pointer to a layer context 
.br
\fIflags\fP OR-ed flags from @lv_draw_layer_flags_t 
.RE
.PP

.SS "void lv_draw_layer_blend (struct \fB_lv_draw_ctx_t\fP * draw_ctx, struct \fB_lv_draw_layer_ctx_t\fP * layer_ctx, \fBlv_draw_img_dsc_t\fP * draw_dsc)"
Blend a rendered layer to \fRlayer_ctx->area_act\fP 
.PP
\fBParameters\fP
.RS 4
\fIdraw_ctx\fP pointer to the current draw context 
.br
\fIlayer_ctx\fP pointer to a layer context 
.br
\fIdraw_dsc\fP pointer to an image draw descriptor 
.RE
.PP

.SS "struct \fB_lv_draw_layer_ctx_t\fP * lv_draw_layer_create (struct \fB_lv_draw_ctx_t\fP * draw_ctx, const \fBlv_area_t\fP * layer_area, lv_draw_layer_flags_t flags)"
Create a new layer context\&. It is used to start and independent rendering session with the current draw_ctx 
.PP
\fBParameters\fP
.RS 4
\fIdraw_ctx\fP pointer to the current draw context 
.br
\fIlayer_area\fP the coordinates of the layer 
.br
\fIflags\fP OR-ed flags from @lv_draw_layer_flags_t 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the layer context, or NULL on error 
.RE
.PP

.SS "void lv_draw_layer_destroy (struct \fB_lv_draw_ctx_t\fP * draw_ctx, struct \fB_lv_draw_layer_ctx_t\fP * layer_ctx)"
Destroy a layer context\&. 
.PP
\fBParameters\fP
.RS 4
\fIdraw_ctx\fP pointer to the current draw context 
.br
\fIlayer_ctx\fP pointer to a layer context 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
