.TH "include/liblvgl/draw/sw/lv_draw_sw_dither.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/sw/lv_draw_sw_dither.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/core/lv_obj_pos\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_DITHER_GRADIENT\fP   0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
