.TH "lv_draw_sw_layer_ctx_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_draw_sw_layer_ctx_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_draw_layer_ctx_t \fBbase_draw\fP"
.br
.ti -1c
.RI "uint32_t \fBbuf_size_bytes\fP: 31"
.br
.ti -1c
.RI "uint32_t \fBhas_alpha\fP: 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
