.TH "include/liblvgl/draw/sdl/lv_draw_sdl_mask.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/sdl/lv_draw_sdl_mask.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include 'lv_draw_sdl\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_area\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_color\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "lv_opa_t * \fBlv_draw_sdl_mask_dump_opa\fP (const \fBlv_area_t\fP *coords, const int16_t *ids, int16_t ids_count)"
.br
.ti -1c
.RI "SDL_Texture * \fBlv_draw_sdl_mask_dump_texture\fP (SDL_Renderer *renderer, const \fBlv_area_t\fP *coords, const int16_t *ids, int16_t ids_count)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
