.TH "include/liblvgl/draw/lv_draw_mask.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/lv_draw_mask.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdbool\&.h>\fP
.br
\fR#include 'liblvgl/misc/lv_area\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_color\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_math\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_lv_draw_mask_saved_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV_MASK_ID_INV\fP   (\-1)"
.br
.ti -1c
.RI "#define \fB_LV_MASK_MAX_NUM\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBlv_draw_mask_res_t\fP"
.br
.ti -1c
.RI "typedef \fB_lv_draw_mask_saved_t\fP \fB_lv_draw_mask_saved_arr_t\fP[_LV_MASK_MAX_NUM]"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBLV_DRAW_MASK_RES_TRANSP\fP, \fBLV_DRAW_MASK_RES_FULL_COVER\fP, \fBLV_DRAW_MASK_RES_CHANGED\fP, \fBLV_DRAW_MASK_RES_UNKNOWN\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
