.TH "include/liblvgl/draw/lv_draw_triangle.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/lv_draw_triangle.h
.SH SYNOPSIS
.br
.PP
\fR#include 'lv_draw_rect\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlv_draw_polygon\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, const \fBlv_draw_rect_dsc_t\fP *draw_dsc, const \fBlv_point_t\fP points[], uint16_t point_cnt)"
.br
.ti -1c
.RI "void \fBlv_draw_triangle\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, const \fBlv_draw_rect_dsc_t\fP *draw_dsc, const \fBlv_point_t\fP points[])"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
