.TH "lv_draw_rect_dsc_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_draw_rect_dsc_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_coord_t \fBradius\fP"
.br
.ti -1c
.RI "lv_blend_mode_t \fBblend_mode\fP"
.br
.ti -1c
.RI "lv_opa_t \fBbg_opa\fP"
.br
.ti -1c
.RI "lv_color_t \fBbg_color\fP"
.br
.ti -1c
.RI "\fBlv_grad_dsc_t\fP \fBbg_grad\fP"
.br
.ti -1c
.RI "const void * \fBbg_img_src\fP"
.br
.ti -1c
.RI "const void * \fBbg_img_symbol_font\fP"
.br
.ti -1c
.RI "lv_color_t \fBbg_img_recolor\fP"
.br
.ti -1c
.RI "lv_opa_t \fBbg_img_opa\fP"
.br
.ti -1c
.RI "lv_opa_t \fBbg_img_recolor_opa\fP"
.br
.ti -1c
.RI "uint8_t \fBbg_img_tiled\fP"
.br
.ti -1c
.RI "lv_color_t \fBborder_color\fP"
.br
.ti -1c
.RI "lv_coord_t \fBborder_width\fP"
.br
.ti -1c
.RI "lv_opa_t \fBborder_opa\fP"
.br
.ti -1c
.RI "uint8_t \fBborder_post\fP: 1"
.br
.ti -1c
.RI "lv_border_side_t \fBborder_side\fP: 5"
.br
.ti -1c
.RI "lv_color_t \fBoutline_color\fP"
.br
.ti -1c
.RI "lv_coord_t \fBoutline_width\fP"
.br
.ti -1c
.RI "lv_coord_t \fBoutline_pad\fP"
.br
.ti -1c
.RI "lv_opa_t \fBoutline_opa\fP"
.br
.ti -1c
.RI "lv_color_t \fBshadow_color\fP"
.br
.ti -1c
.RI "lv_coord_t \fBshadow_width\fP"
.br
.ti -1c
.RI "lv_coord_t \fBshadow_ofs_x\fP"
.br
.ti -1c
.RI "lv_coord_t \fBshadow_ofs_y\fP"
.br
.ti -1c
.RI "lv_coord_t \fBshadow_spread\fP"
.br
.ti -1c
.RI "lv_opa_t \fBshadow_opa\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "lv_color_t lv_draw_rect_dsc_t::bg_color"
First element of a gradient is a color, so it maps well here 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
