.TH "include/liblvgl/draw/sw/lv_draw_sw_gradient.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/sw/lv_draw_sw_gradient.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/misc/lv_color\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_style\&.h'\fP
.br
\fR#include 'lv_draw_sw_dither\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_lv_gradient_cache_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef lv_color_t \fBlv_grad_color_t\fP"
.br
.ti -1c
.RI "typedef struct \fB_lv_gradient_cache_t\fP \fBlv_grad_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "LV_ATTRIBUTE_FAST_MEM lv_grad_color_t \fBlv_gradient_calculate\fP (const \fBlv_grad_dsc_t\fP *dsc, lv_coord_t range, lv_coord_t frac)"
.br
.ti -1c
.RI "void \fBlv_gradient_set_cache_size\fP (size_t max_bytes)"
.br
.ti -1c
.RI "void \fBlv_gradient_free_cache\fP (void)"
.br
.ti -1c
.RI "\fBlv_grad_t\fP * \fBlv_gradient_get\fP (const \fBlv_grad_dsc_t\fP *gradient, lv_coord_t w, lv_coord_t h)"
.br
.ti -1c
.RI "void \fBlv_gradient_cleanup\fP (\fBlv_grad_t\fP *grad)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_lv_gradient_cache_t\fP \fBlv_grad_t\fP"
To avoid recomputing gradient for each draw operation, it's possible to cache the computation in this structure instance\&. Whenever possible, this structure is reused instead of recomputing the gradient map 
.SH "Function Documentation"
.PP 
.SS "LV_ATTRIBUTE_FAST_MEM lv_grad_color_t lv_gradient_calculate (const \fBlv_grad_dsc_t\fP * dsc, lv_coord_t range, lv_coord_t frac)"
Compute the color in the given gradient and fraction Gradient are specified in a virtual [0-255] range, so this function scales the virtual range to the given range 
.PP
\fBParameters\fP
.RS 4
\fIdsc\fP The gradient descriptor to use 
.br
\fIrange\fP The range to use in computation\&. 
.br
\fIfrac\fP The current part used in the range\&. frac is in [0; range] 
.RE
.PP

.SS "void lv_gradient_cleanup (\fBlv_grad_t\fP * grad)"
Clean up the gradient item after it was get with \fRlv_grad_get_from_cache\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIgrad\fP pointer to a gradient 
.RE
.PP

.SS "void lv_gradient_free_cache (void )"
Free the gradient cache 
.SS "\fBlv_grad_t\fP * lv_gradient_get (const \fBlv_grad_dsc_t\fP * gradient, lv_coord_t w, lv_coord_t h)"
Get a gradient cache from the given parameters 
.SS "void lv_gradient_set_cache_size (size_t max_bytes)"
Set the gradient cache size 
.PP
\fBParameters\fP
.RS 4
\fImax_bytes\fP Max cahce size 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
