.TH "include/liblvgl/draw/lv_draw_rect.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/lv_draw_rect.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_color\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_area\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_style\&.h'\fP
.br
\fR#include 'sw/lv_draw_sw_gradient\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlv_draw_rect_dsc_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV_RADIUS_CIRCLE\fP   0x7FFF"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLV_EXPORT_CONST_INT\fP (\fBLV_RADIUS_CIRCLE\fP)"
.br
.ti -1c
.RI "LV_ATTRIBUTE_FAST_MEM void \fBlv_draw_rect_dsc_init\fP (\fBlv_draw_rect_dsc_t\fP *dsc)"
.br
.ti -1c
.RI "void \fBlv_draw_rect\fP (struct \fB_lv_draw_ctx_t\fP *draw_ctx, const \fBlv_draw_rect_dsc_t\fP *dsc, const \fBlv_area_t\fP *coords)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LV_RADIUS_CIRCLE   0x7FFF"
A very big radius to always draw as circle 
.SH "Function Documentation"
.PP 
.SS "void lv_draw_rect (struct \fB_lv_draw_ctx_t\fP * draw_ctx, const \fBlv_draw_rect_dsc_t\fP * dsc, const \fBlv_area_t\fP * coords)"
Draw a rectangle 
.PP
\fBParameters\fP
.RS 4
\fIcoords\fP the coordinates of the rectangle 
.br
\fIclip\fP the rectangle will be drawn only in this area 
.br
\fIdsc\fP pointer to an initialized \fR\fBlv_draw_rect_dsc_t\fP\fP variable 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
