.TH "include/liblvgl/extra/lv_extra.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/extra/lv_extra.h
.SH SYNOPSIS
.br
.PP
\fR#include 'layouts/lv_layouts\&.h'\fP
.br
\fR#include 'libs/lv_libs\&.h'\fP
.br
\fR#include 'others/lv_others\&.h'\fP
.br
\fR#include 'themes/lv_themes\&.h'\fP
.br
\fR#include 'widgets/lv_widgets\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlv_extra_init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void lv_extra_init (void )"
Initialize the extra components 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
