.TH "include/liblvgl/font/lv_font.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/font/lv_font.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include 'lv_symbol_def\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_area\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlv_font_glyph_dsc_t\fP"
.br
.ti -1c
.RI "struct \fB_lv_font_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV_IMGFONT_BPP\fP   9"
.br
.ti -1c
.RI "#define \fBLV_FONT_DECLARE\fP(font_name)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBlv_font_subpx_t\fP"
.br
.ti -1c
.RI "typedef struct \fB_lv_font_t\fP \fBlv_font_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBLV_FONT_SUBPX_NONE\fP, \fBLV_FONT_SUBPX_HOR\fP, \fBLV_FONT_SUBPX_VER\fP, \fBLV_FONT_SUBPX_BOTH\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const uint8_t * \fBlv_font_get_glyph_bitmap\fP (const \fBlv_font_t\fP *font_p, uint32_t letter)"
.br
.ti -1c
.RI "bool \fBlv_font_get_glyph_dsc\fP (const \fBlv_font_t\fP *font_p, \fBlv_font_glyph_dsc_t\fP *dsc_out, uint32_t letter, uint32_t letter_next)"
.br
.ti -1c
.RI "uint16_t \fBlv_font_get_glyph_width\fP (const \fBlv_font_t\fP *font, uint32_t letter, uint32_t letter_next)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LV_FONT_DECLARE( font_name)"
\fBValue:\fP
.nf
extern const lv_font_t font_name;
.PP
.fi

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_lv_font_t\fP \fBlv_font_t\fP"
Describe the properties of a font 
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"
The bitmaps might be upscaled by 3 to achieve subpixel rendering\&. 
.SH "Function Documentation"
.PP 
.SS "const uint8_t * lv_font_get_glyph_bitmap (const \fBlv_font_t\fP * font_p, uint32_t letter)"
Return with the bitmap of a font\&. 
.PP
\fBParameters\fP
.RS 4
\fIfont_p\fP pointer to a font 
.br
\fIletter\fP a UNICODE character code 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the bitmap of the letter 
.RE
.PP

.SS "bool lv_font_get_glyph_dsc (const \fBlv_font_t\fP * font_p, \fBlv_font_glyph_dsc_t\fP * dsc_out, uint32_t letter, uint32_t letter_next)"
Get the descriptor of a glyph 
.PP
\fBParameters\fP
.RS 4
\fIfont_p\fP pointer to font 
.br
\fIdsc_out\fP store the result descriptor here 
.br
\fIletter\fP a UNICODE letter code 
.br
\fIletter_next\fP the next letter after \fRletter\fP\&. Used for kerning 
.RE
.PP
\fBReturns\fP
.RS 4
true: descriptor is successfully loaded into \fRdsc_out\fP\&. false: the letter was not found, no data is loaded to \fRdsc_out\fP 
.RE
.PP

.SS "uint16_t lv_font_get_glyph_width (const \fBlv_font_t\fP * font, uint32_t letter, uint32_t letter_next)"
Get the width of a glyph with kerning 
.PP
\fBParameters\fP
.RS 4
\fIfont\fP pointer to a font 
.br
\fIletter\fP a UNICODE letter 
.br
\fIletter_next\fP the next letter after \fRletter\fP\&. Used for kerning 
.RE
.PP
\fBReturns\fP
.RS 4
the width of the glyph 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
