.TH "lv_font_fmt_txt_glyph_dsc_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_font_fmt_txt_glyph_dsc_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_font_fmt_txt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBbitmap_index\fP: 20"
.br
.ti -1c
.RI "uint32_t \fBadv_w\fP: 12"
.br
.ti -1c
.RI "uint8_t \fBbox_w\fP"
.br
.ti -1c
.RI "uint8_t \fBbox_h\fP"
.br
.ti -1c
.RI "int8_t \fBofs_x\fP"
.br
.ti -1c
.RI "int8_t \fBofs_y\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This describes a glyph\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint32_t lv_font_fmt_txt_glyph_dsc_t::adv_w"
Draw the next glyph after this width\&. 8\&.4 format (real_value * 16 is stored)\&. 
.SS "uint32_t lv_font_fmt_txt_glyph_dsc_t::bitmap_index"
Start index of the bitmap\&. A font can be max 1 MB\&. 
.SS "uint8_t lv_font_fmt_txt_glyph_dsc_t::box_h"
Height of the glyph's bounding box 
.SS "uint8_t lv_font_fmt_txt_glyph_dsc_t::box_w"
Width of the glyph's bounding box 
.SS "int8_t lv_font_fmt_txt_glyph_dsc_t::ofs_x"
x offset of the bounding box 
.SS "int8_t lv_font_fmt_txt_glyph_dsc_t::ofs_y"
y offset of the bounding box\&. Measured from the top of the line 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
