.TH "lv_font_fmt_txt_kern_classes_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_font_fmt_txt_kern_classes_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_font_fmt_txt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int8_t * \fBclass_pair_values\fP"
.br
.ti -1c
.RI "const uint8_t * \fBleft_class_mapping\fP"
.br
.ti -1c
.RI "const uint8_t * \fBright_class_mapping\fP"
.br
.ti -1c
.RI "uint8_t \fBleft_class_cnt\fP"
.br
.ti -1c
.RI "uint8_t \fBright_class_cnt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
More complex but more optimal class based kern value storage 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
