.TH "lv_font_fmt_txt_glyph_cache_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_font_fmt_txt_glyph_cache_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBlast_letter\fP"
.br
.ti -1c
.RI "uint32_t \fBlast_glyph_id\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
