.TH "lv_fs_file_cache_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_fs_file_cache_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBstart\fP"
.br
.ti -1c
.RI "uint32_t \fBend\fP"
.br
.ti -1c
.RI "uint32_t \fBfile_position\fP"
.br
.ti -1c
.RI "void * \fBbuffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
