.TH "lv_font_fmt_txt_cmap_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_font_fmt_txt_cmap_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_font_fmt_txt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBrange_start\fP"
.br
.ti -1c
.RI "uint16_t \fBrange_length\fP"
.br
.ti -1c
.RI "uint16_t \fBglyph_id_start\fP"
.br
.ti -1c
.RI "const uint16_t * \fBunicode_list\fP"
.br
.ti -1c
.RI "const void * \fBglyph_id_ofs_list\fP"
.br
.ti -1c
.RI "uint16_t \fBlist_length\fP"
.br
.ti -1c
.RI "lv_font_fmt_txt_cmap_type_t \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Map codepoints to a \fRglyph_dsc\fPs Several formats are supported to optimize memory usage See https://github.com/lvgl/lv_font_conv/blob/master/doc/font_spec.md 
.SH "Member Data Documentation"
.PP 
.SS "const void* lv_font_fmt_txt_cmap_t::glyph_id_ofs_list"
if(type == LV_FONT_FMT_TXT_CMAP_FORMAT0_\&.\&.\&.) it's \fRuint8_t *\fP if(type == LV_FONT_FMT_TXT_CMAP_SPARSE_\&.\&.\&.) it's \fRuint16_t *\fP 
.SS "uint16_t lv_font_fmt_txt_cmap_t::glyph_id_start"
First glyph ID (array index of \fRglyph_dsc\fP) for this range 
.SS "uint16_t lv_font_fmt_txt_cmap_t::list_length"
Length of \fRunicode_list\fP and/or \fR\fBglyph_id_ofs_list\fP\fP 
.SS "uint16_t lv_font_fmt_txt_cmap_t::range_length"
Number of Unicode characters related to this range\&. Last Unicode character = range_start + range_length - 1 
.SS "uint32_t lv_font_fmt_txt_cmap_t::range_start"
First Unicode character for this range 
.SS "lv_font_fmt_txt_cmap_type_t lv_font_fmt_txt_cmap_t::type"
Type of this character map 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
