.TH "lv_font_fmt_txt_dsc_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_font_fmt_txt_dsc_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const uint8_t * \fBglyph_bitmap\fP"
.br
.ti -1c
.RI "const \fBlv_font_fmt_txt_glyph_dsc_t\fP * \fBglyph_dsc\fP"
.br
.ti -1c
.RI "const \fBlv_font_fmt_txt_cmap_t\fP * \fBcmaps\fP"
.br
.ti -1c
.RI "uint16_t \fBkern_scale\fP"
.br
.ti -1c
.RI "uint16_t \fBcmap_num\fP: 9"
.br
.ti -1c
.RI "uint16_t \fBbpp\fP: 4"
.br
.ti -1c
.RI "uint16_t \fBkern_classes\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBbitmap_format\fP: 2"
.br
.ti -1c
.RI "\fBlv_font_fmt_txt_glyph_cache_t\fP * \fBcache\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint16_t lv_font_fmt_txt_dsc_t::kern_scale"
Store kerning values\&. Can be \fR\fBlv_font_fmt_txt_kern_pair_t\fP * or \fPlv_font_kern_classes_fmt_txt_t *\fR depending on \fPkern_classes` */ const void * kern_dsc;

.PP
/*Scale kern values in 12\&.4 format 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
