.TH "include/liblvgl/extra/others/gridnav/lv_gridnav.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/extra/others/gridnav/lv_gridnav.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/core/lv_obj\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fB_keep_pedantic_happy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
