.TH "include/liblvgl/draw/stm32_dma2d/lv_gpu_stm32_dma2d.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/stm32_dma2d/lv_gpu_stm32_dma2d.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/misc/lv_color\&.h'\fP
.br
\fR#include 'liblvgl/hal/lv_hal_disp\&.h'\fP
.br
\fR#include 'liblvgl/draw/sw/lv_draw_sw\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
