.TH "lv_gradient_stop_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_gradient_stop_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_style\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_color_t \fBcolor\fP"
.br
.ti -1c
.RI "uint8_t \fBfrac\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A gradient stop definition\&. This matches a color and a position in a virtual 0-255 scale\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/misc/lv_style\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "lv_color_t lv_gradient_stop_t::color"
The stop color 
.SS "uint8_t lv_gradient_stop_t::frac"
The stop position in 1/255 unit 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
