.TH "include/liblvgl/hal/lv_hal_tick.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/hal/lv_hal_tick.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBlv_tick_get\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBlv_tick_elaps\fP (uint32_t prev_tick)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provide access to the system tick with 1 millisecond resolution 
.SH "Function Documentation"
.PP 
.SS "uint32_t lv_tick_elaps (uint32_t prev_tick)"
Get the elapsed milliseconds since a previous time stamp 
.PP
\fBParameters\fP
.RS 4
\fIprev_tick\fP a previous time stamp (return value of \fBlv_tick_get()\fP ) 
.RE
.PP
\fBReturns\fP
.RS 4
the elapsed milliseconds since 'prev_tick' 
.RE
.PP

.SS "uint32_t lv_tick_get (void )"
Get the elapsed milliseconds since start up 
.PP
\fBReturns\fP
.RS 4
the elapsed milliseconds 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
