.TH "include/liblvgl/hal/lv_hal.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/hal/lv_hal.h
.SH SYNOPSIS
.br
.PP
\fR#include 'lv_hal_disp\&.h'\fP
.br
\fR#include 'lv_hal_indev\&.h'\fP
.br
\fR#include 'lv_hal_tick\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_LV_DPX_CALC\fP(dpi,  n)"
.br
.ti -1c
.RI "#define \fBLV_DPX\fP(n)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _LV_DPX_CALC( dpi,  n)"
\fBValue:\fP
.nf
((n) == 0 ? 0 :LV_MAX((( (dpi) * (n) + 80) / 160), 1)) /*+80 for rounding*/
.PP
.fi
Same as Android's DIP\&. (Different name is chosen to avoid mistype between LV_DPI and LV_DIP) 1 dip is 1 px on a 160 DPI screen 1 dip is 2 px on a 320 DPI screen https://stackoverflow.com/questions/2025282/what-is-the-difference-between-px-dip-dp-and-sp 
.SS "#define LV_DPX( n)"
\fBValue:\fP
.nf
_LV_DPX_CALC(lv_disp_get_dpi(NULL), n)
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
