.TH "include/liblvgl/draw/lv_img_decoder.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/draw/lv_img_decoder.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include 'lv_img_buf\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_fs\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_types\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_area\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_lv_img_decoder_t\fP"
.br
.ti -1c
.RI "struct \fB_lv_img_decoder_dsc_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBlv_img_src_t\fP"
.br
.ti -1c
.RI "typedef lv_res_t(* \fBlv_img_decoder_info_f_t\fP) (struct \fB_lv_img_decoder_t\fP *decoder, const void *src, \fBlv_img_header_t\fP *header)"
.br
.ti -1c
.RI "typedef lv_res_t(* \fBlv_img_decoder_open_f_t\fP) (struct \fB_lv_img_decoder_t\fP *decoder, struct \fB_lv_img_decoder_dsc_t\fP *dsc)"
.br
.ti -1c
.RI "typedef lv_res_t(* \fBlv_img_decoder_read_line_f_t\fP) (struct \fB_lv_img_decoder_t\fP *decoder, struct \fB_lv_img_decoder_dsc_t\fP *dsc, lv_coord_t x, lv_coord_t y, lv_coord_t len, uint8_t *buf)"
.br
.ti -1c
.RI "typedef void(* \fBlv_img_decoder_close_f_t\fP) (struct \fB_lv_img_decoder_t\fP *decoder, struct \fB_lv_img_decoder_dsc_t\fP *dsc)"
.br
.ti -1c
.RI "typedef struct \fB_lv_img_decoder_t\fP \fBlv_img_decoder_t\fP"
.br
.ti -1c
.RI "typedef struct \fB_lv_img_decoder_dsc_t\fP \fBlv_img_decoder_dsc_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBLV_IMG_SRC_VARIABLE\fP, \fBLV_IMG_SRC_FILE\fP, \fBLV_IMG_SRC_SYMBOL\fP, \fBLV_IMG_SRC_UNKNOWN\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_lv_img_decoder_init\fP (void)"
.br
.ti -1c
.RI "lv_res_t \fBlv_img_decoder_get_info\fP (const void *src, \fBlv_img_header_t\fP *header)"
.br
.ti -1c
.RI "lv_res_t \fBlv_img_decoder_open\fP (\fBlv_img_decoder_dsc_t\fP *dsc, const void *src, lv_color_t color, int32_t frame_id)"
.br
.ti -1c
.RI "lv_res_t \fBlv_img_decoder_read_line\fP (\fBlv_img_decoder_dsc_t\fP *dsc, lv_coord_t x, lv_coord_t y, lv_coord_t len, uint8_t *buf)"
.br
.ti -1c
.RI "void \fBlv_img_decoder_close\fP (\fBlv_img_decoder_dsc_t\fP *dsc)"
.br
.ti -1c
.RI "lv_img_decoder_t * \fBlv_img_decoder_create\fP (void)"
.br
.ti -1c
.RI "void \fBlv_img_decoder_delete\fP (lv_img_decoder_t *decoder)"
.br
.ti -1c
.RI "void \fBlv_img_decoder_set_info_cb\fP (lv_img_decoder_t *decoder, \fBlv_img_decoder_info_f_t\fP info_cb)"
.br
.ti -1c
.RI "void \fBlv_img_decoder_set_open_cb\fP (lv_img_decoder_t *decoder, \fBlv_img_decoder_open_f_t\fP open_cb)"
.br
.ti -1c
.RI "void \fBlv_img_decoder_set_read_line_cb\fP (lv_img_decoder_t *decoder, \fBlv_img_decoder_read_line_f_t\fP read_line_cb)"
.br
.ti -1c
.RI "void \fBlv_img_decoder_set_close_cb\fP (lv_img_decoder_t *decoder, \fBlv_img_decoder_close_f_t\fP close_cb)"
.br
.ti -1c
.RI "lv_res_t \fBlv_img_decoder_built_in_info\fP (lv_img_decoder_t *decoder, const void *src, \fBlv_img_header_t\fP *header)"
.br
.ti -1c
.RI "lv_res_t \fBlv_img_decoder_built_in_open\fP (lv_img_decoder_t *decoder, \fBlv_img_decoder_dsc_t\fP *dsc)"
.br
.ti -1c
.RI "lv_res_t \fBlv_img_decoder_built_in_read_line\fP (lv_img_decoder_t *decoder, \fBlv_img_decoder_dsc_t\fP *dsc, lv_coord_t x, lv_coord_t y, lv_coord_t len, uint8_t *buf)"
.br
.ti -1c
.RI "void \fBlv_img_decoder_built_in_close\fP (lv_img_decoder_t *decoder, \fBlv_img_decoder_dsc_t\fP *dsc)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* lv_img_decoder_close_f_t) (struct \fB_lv_img_decoder_t\fP *decoder, struct \fB_lv_img_decoder_dsc_t\fP *dsc)"
Close the pending decoding\&. Free resources etc\&. 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP pointer to the decoder the function associated with 
.br
\fIdsc\fP pointer to decoder descriptor 
.RE
.PP

.SS "typedef struct \fB_lv_img_decoder_dsc_t\fP \fBlv_img_decoder_dsc_t\fP"
Describe an image decoding session\&. Stores data about the decoding 
.SS "typedef lv_res_t(* lv_img_decoder_info_f_t) (struct \fB_lv_img_decoder_t\fP *decoder, const void *src, \fBlv_img_header_t\fP *header)"
Get info from an image and store in the \fRheader\fP 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP the image source\&. Can be a pointer to a C array or a file name (Use \fR\fBlv_img_src_get_type\fP\fP to determine the type) 
.br
\fIheader\fP store the info here 
.RE
.PP
\fBReturns\fP
.RS 4
LV_RES_OK: info written correctly; LV_RES_INV: failed 
.RE
.PP

.SS "typedef lv_res_t(* lv_img_decoder_open_f_t) (struct \fB_lv_img_decoder_t\fP *decoder, struct \fB_lv_img_decoder_dsc_t\fP *dsc)"
Open an image for decoding\&. Prepare it as it is required to read it later 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP pointer to the decoder the function associated with 
.br
\fIdsc\fP pointer to decoder descriptor\&. \fRsrc\fP, \fRcolor\fP are already initialized in it\&. 
.RE
.PP

.SS "typedef lv_res_t(* lv_img_decoder_read_line_f_t) (struct \fB_lv_img_decoder_t\fP *decoder, struct \fB_lv_img_decoder_dsc_t\fP *dsc, lv_coord_t x, lv_coord_t y, lv_coord_t len, uint8_t *buf)"
Decode \fRlen\fP pixels starting from the given \fRx\fP, \fRy\fP coordinates and store them in \fRbuf\fP\&. Required only if the "open" function can't return with the whole decoded pixel array\&. 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP pointer to the decoder the function associated with 
.br
\fIdsc\fP pointer to decoder descriptor 
.br
\fIx\fP start x coordinate 
.br
\fIy\fP start y coordinate 
.br
\fIlen\fP number of pixels to decode 
.br
\fIbuf\fP a buffer to store the decoded pixels 
.RE
.PP
\fBReturns\fP
.RS 4
LV_RES_OK: ok; LV_RES_INV: failed 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"
Source of image\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILV_IMG_SRC_FILE \fP
Binary/C variable 
.TP
\f(BILV_IMG_SRC_SYMBOL \fP
File in filesystem 
.TP
\f(BILV_IMG_SRC_UNKNOWN \fP
Symbol (\fBlv_symbol_def\&.h\fP) 
.SH "Function Documentation"
.PP 
.SS "void _lv_img_decoder_init (void )"
Initialize the image decoder module 
.SS "void lv_img_decoder_built_in_close (lv_img_decoder_t * decoder, \fBlv_img_decoder_dsc_t\fP * dsc)"
Close the pending decoding\&. Free resources etc\&. 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP pointer to the decoder the function associated with 
.br
\fIdsc\fP pointer to decoder descriptor 
.RE
.PP

.SS "lv_res_t lv_img_decoder_built_in_info (lv_img_decoder_t * decoder, const void * src, \fBlv_img_header_t\fP * header)"
Get info about a built-in image 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP the decoder where this function belongs 
.br
\fIsrc\fP the image source: pointer to an \fR\fBlv_img_dsc_t\fP\fP variable, a file path or a symbol 
.br
\fIheader\fP store the image data here 
.RE
.PP
\fBReturns\fP
.RS 4
LV_RES_OK: the info is successfully stored in \fRheader\fP; LV_RES_INV: unknown format or other error\&. 
.RE
.PP

.SS "lv_res_t lv_img_decoder_built_in_open (lv_img_decoder_t * decoder, \fBlv_img_decoder_dsc_t\fP * dsc)"
Open a built in image 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP the decoder where this function belongs 
.br
\fIdsc\fP pointer to decoder descriptor\&. \fRsrc\fP, \fRstyle\fP are already initialized in it\&. 
.RE
.PP
\fBReturns\fP
.RS 4
LV_RES_OK: the info is successfully stored in \fRheader\fP; LV_RES_INV: unknown format or other error\&. 
.RE
.PP

.SS "lv_res_t lv_img_decoder_built_in_read_line (lv_img_decoder_t * decoder, \fBlv_img_decoder_dsc_t\fP * dsc, lv_coord_t x, lv_coord_t y, lv_coord_t len, uint8_t * buf)"
Decode \fRlen\fP pixels starting from the given \fRx\fP, \fRy\fP coordinates and store them in \fRbuf\fP\&. Required only if the "open" function can't return with the whole decoded pixel array\&. 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP pointer to the decoder the function associated with 
.br
\fIdsc\fP pointer to decoder descriptor 
.br
\fIx\fP start x coordinate 
.br
\fIy\fP start y coordinate 
.br
\fIlen\fP number of pixels to decode 
.br
\fIbuf\fP a buffer to store the decoded pixels 
.RE
.PP
\fBReturns\fP
.RS 4
LV_RES_OK: ok; LV_RES_INV: failed 
.RE
.PP

.SS "void lv_img_decoder_close (\fBlv_img_decoder_dsc_t\fP * dsc)"
Close a decoding session 
.PP
\fBParameters\fP
.RS 4
\fIdsc\fP pointer to \fR\fBlv_img_decoder_dsc_t\fP\fP used in \fR\fBlv_img_decoder_open\fP\fP 
.RE
.PP

.SS "lv_img_decoder_t * lv_img_decoder_create (void )"
Create a new image decoder 
.PP
\fBReturns\fP
.RS 4
pointer to the new image decoder 
.RE
.PP

.SS "void lv_img_decoder_delete (lv_img_decoder_t * decoder)"
Delete an image decoder 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP pointer to an image decoder 
.RE
.PP

.SS "lv_res_t lv_img_decoder_get_info (const void * src, \fBlv_img_header_t\fP * header)"
Get information about an image\&. Try the created image decoder one by one\&. Once one is able to get info that info will be used\&. 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP the image source\&. Can be 1) File name: E\&.g\&. "S:folder/img1\&.png" (The drivers needs to registered via \fR\fBlv_fs_drv_register()\fP\fP) 2) Variable: Pointer to an \fR\fBlv_img_dsc_t\fP\fP variable 3) Symbol: E\&.g\&. \fRLV_SYMBOL_OK\fP 
.br
\fIheader\fP the image info will be stored here 
.RE
.PP
\fBReturns\fP
.RS 4
LV_RES_OK: success; LV_RES_INV: wasn't able to get info about the image 
.RE
.PP

.SS "lv_res_t lv_img_decoder_open (\fBlv_img_decoder_dsc_t\fP * dsc, const void * src, lv_color_t color, int32_t frame_id)"
Open an image\&. Try the created image decoders one by one\&. Once one is able to open the image that decoder is saved in \fRdsc\fP 
.PP
\fBParameters\fP
.RS 4
\fIdsc\fP describes a decoding session\&. Simply a pointer to an \fR\fBlv_img_decoder_dsc_t\fP\fP variable\&. 
.br
\fIsrc\fP the image source\&. Can be 1) File name: E\&.g\&. "S:folder/img1\&.png" (The drivers needs to registered via \fR\fBlv_fs_drv_register()\fP)\fP) 2) Variable: Pointer to an \fR\fBlv_img_dsc_t\fP\fP variable 3) Symbol: E\&.g\&. \fRLV_SYMBOL_OK\fP 
.br
\fIcolor\fP The color of the image with \fRLV_IMG_CF_ALPHA_\&.\&.\&.\fP 
.br
\fIframe_id\fP the index of the frame\&. Used only with animated images, set 0 for normal images 
.RE
.PP
\fBReturns\fP
.RS 4
LV_RES_OK: opened the image\&. \fRdsc->img_data\fP and \fRdsc->header\fP are set\&. LV_RES_INV: none of the registered image decoders were able to open the image\&. 
.RE
.PP

.SS "lv_res_t lv_img_decoder_read_line (\fBlv_img_decoder_dsc_t\fP * dsc, lv_coord_t x, lv_coord_t y, lv_coord_t len, uint8_t * buf)"
Read a line from an opened image 
.PP
\fBParameters\fP
.RS 4
\fIdsc\fP pointer to \fR\fBlv_img_decoder_dsc_t\fP\fP used in \fR\fBlv_img_decoder_open\fP\fP 
.br
\fIx\fP start X coordinate (from left) 
.br
\fIy\fP start Y coordinate (from top) 
.br
\fIlen\fP number of pixels to read 
.br
\fIbuf\fP store the data here 
.RE
.PP
\fBReturns\fP
.RS 4
LV_RES_OK: success; LV_RES_INV: an error occurred 
.RE
.PP

.SS "void lv_img_decoder_set_close_cb (lv_img_decoder_t * decoder, \fBlv_img_decoder_close_f_t\fP close_cb)"
Set a callback to close a decoding session\&. E\&.g\&. close files and free other resources\&. 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP pointer to an image decoder 
.br
\fIclose_cb\fP a function to close a decoding session 
.RE
.PP

.SS "void lv_img_decoder_set_info_cb (lv_img_decoder_t * decoder, \fBlv_img_decoder_info_f_t\fP info_cb)"
Set a callback to get information about the image 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP pointer to an image decoder 
.br
\fIinfo_cb\fP a function to collect info about an image (fill an \fR\fBlv_img_header_t\fP\fP struct) 
.RE
.PP

.SS "void lv_img_decoder_set_open_cb (lv_img_decoder_t * decoder, \fBlv_img_decoder_open_f_t\fP open_cb)"
Set a callback to open an image 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP pointer to an image decoder 
.br
\fIopen_cb\fP a function to open an image 
.RE
.PP

.SS "void lv_img_decoder_set_read_line_cb (lv_img_decoder_t * decoder, \fBlv_img_decoder_read_line_f_t\fP read_line_cb)"
Set a callback to a decoded line of an image 
.PP
\fBParameters\fP
.RS 4
\fIdecoder\fP pointer to an image decoder 
.br
\fIread_line_cb\fP a function to read a line of an image 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
