.TH "include/liblvgl/core/lv_indev_scroll.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/core/lv_indev_scroll.h
.SH SYNOPSIS
.br
.PP
\fR#include 'lv_obj\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_lv_indev_scroll_handler\fP (\fB_lv_indev_proc_t\fP *proc)"
.br
.ti -1c
.RI "void \fB_lv_indev_scroll_throw_handler\fP (\fB_lv_indev_proc_t\fP *proc)"
.br
.ti -1c
.RI "lv_coord_t \fBlv_indev_scroll_throw_predict\fP (\fBlv_indev_t\fP *indev, lv_dir_t dir)"
.br
.ti -1c
.RI "void \fBlv_indev_scroll_get_snap_dist\fP (lv_obj_t *obj, \fBlv_point_t\fP *p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _lv_indev_scroll_handler (\fB_lv_indev_proc_t\fP * proc)"
Handle scrolling\&. Called by LVGL during input device processing 
.PP
\fBParameters\fP
.RS 4
\fIproc\fP pointer to an input device's proc field 
.RE
.PP

.SS "void _lv_indev_scroll_throw_handler (\fB_lv_indev_proc_t\fP * proc)"
Handle throwing after scrolling\&. Called by LVGL during input device processing 
.PP
\fBParameters\fP
.RS 4
\fIproc\fP pointer to an input device's proc field 
.RE
.PP

.SS "void lv_indev_scroll_get_snap_dist (lv_obj_t * obj, \fBlv_point_t\fP * p)"
Get the distance of the nearest snap point 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP the object on which snap points should be found 
.br
\fIp\fP save the distance of the found snap point there 
.RE
.PP

.SS "lv_coord_t lv_indev_scroll_throw_predict (\fBlv_indev_t\fP * indev, lv_dir_t dir)"
Predict where would a scroll throw end 
.PP
\fBParameters\fP
.RS 4
\fIindev\fP pointer to an input device 
.br
\fIdir\fP \fR LV_DIR_VER\fP or \fRLV_DIR_HOR\fP 
.RE
.PP
\fBReturns\fP
.RS 4
the difference compared to the current position when the throw would be finished 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
