.TH "lv_img_dsc_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_img_dsc_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_img_buf\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlv_img_header_t\fP \fBheader\fP"
.br
.ti -1c
.RI "uint32_t \fBdata_size\fP"
.br
.ti -1c
.RI "const uint8_t * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Image header it is compatible with the result from image converter utility 
.SH "Member Data Documentation"
.PP 
.SS "const uint8_t* lv_img_dsc_t::data"
Pointer to the data of the image 
.SS "uint32_t lv_img_dsc_t::data_size"
Size of the image in bytes 
.SS "\fBlv_img_header_t\fP lv_img_dsc_t::header"
A header describing the basics of the image 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
