.TH "lv_indev_data_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_indev_data_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_hal_indev\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlv_point_t\fP \fBpoint\fP"
.br
.ti -1c
.RI "uint32_t \fBkey\fP"
.br
.ti -1c
.RI "uint32_t \fBbtn_id\fP"
.br
.ti -1c
.RI "int16_t \fBenc_diff\fP"
.br
.ti -1c
.RI "\fBlv_indev_state_t\fP \fBstate\fP"
.br
.ti -1c
.RI "bool \fBcontinue_reading\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure passed to an input driver to fill 
.SH "Member Data Documentation"
.PP 
.SS "uint32_t lv_indev_data_t::btn_id"
For LV_INDEV_TYPE_BUTTON the currently pressed button 
.SS "bool lv_indev_data_t::continue_reading"
If set to true, the read callback is invoked again 
.SS "int16_t lv_indev_data_t::enc_diff"
For LV_INDEV_TYPE_ENCODER number of steps since the previous read 
.SS "uint32_t lv_indev_data_t::key"
For LV_INDEV_TYPE_KEYPAD the currently pressed key 
.SS "\fBlv_point_t\fP lv_indev_data_t::point"
For LV_INDEV_TYPE_POINTER the currently pressed point 
.SS "\fBlv_indev_state_t\fP lv_indev_data_t::state"
LV_INDEV_STATE_REL or LV_INDEV_STATE_PR 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
