.TH "include/liblvgl/extra/libs/lv_libs.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/extra/libs/lv_libs.h
.SH SYNOPSIS
.br
.PP
\fR#include 'bmp/lv_bmp\&.h'\fP
.br
\fR#include 'fsdrv/lv_fsdrv\&.h'\fP
.br
\fR#include 'png/lv_png\&.h'\fP
.br
\fR#include 'gif/lv_gif\&.h'\fP
.br
\fR#include 'qrcode/lv_qrcode\&.h'\fP
.br
\fR#include 'sjpg/lv_sjpg\&.h'\fP
.br
\fR#include 'freetype/lv_freetype\&.h'\fP
.br
\fR#include 'rlottie/lv_rlottie\&.h'\fP
.br
\fR#include 'ffmpeg/lv_ffmpeg\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
