.TH "lv_lru_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_lru_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_lru_item_t ** \fBitems\fP"
.br
.ti -1c
.RI "uint64_t \fBaccess_count\fP"
.br
.ti -1c
.RI "size_t \fBfree_memory\fP"
.br
.ti -1c
.RI "size_t \fBtotal_memory\fP"
.br
.ti -1c
.RI "size_t \fBaverage_item_length\fP"
.br
.ti -1c
.RI "size_t \fBhash_table_size\fP"
.br
.ti -1c
.RI "uint32_t \fBseed\fP"
.br
.ti -1c
.RI "lv_lru_free_t * \fBvalue_free\fP"
.br
.ti -1c
.RI "lv_lru_free_t * \fBkey_free\fP"
.br
.ti -1c
.RI "lv_lru_item_t * \fBfree_items\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
