.TH "include/liblvgl/core/lv_obj_draw.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/core/lv_obj_draw.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/draw/lv_draw\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlv_obj_draw_part_dsc_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlv_cover_res_t\fP { \fBLV_COVER_RES_COVER\fP = 0, \fBLV_COVER_RES_NOT_COVER\fP = 1, \fBLV_COVER_RES_MASKED\fP = 2 }"
.br
.ti -1c
.RI "enum \fBlv_layer_type_t\fP { \fBLV_LAYER_TYPE_NONE\fP, \fBLV_LAYER_TYPE_SIMPLE\fP, \fBLV_LAYER_TYPE_TRANSFORM\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlv_obj_init_draw_rect_dsc\fP (struct \fB_lv_obj_t\fP *obj, uint32_t part, \fBlv_draw_rect_dsc_t\fP *draw_dsc)"
.br
.ti -1c
.RI "void \fBlv_obj_init_draw_label_dsc\fP (struct \fB_lv_obj_t\fP *obj, uint32_t part, \fBlv_draw_label_dsc_t\fP *draw_dsc)"
.br
.ti -1c
.RI "void \fBlv_obj_init_draw_img_dsc\fP (struct \fB_lv_obj_t\fP *obj, uint32_t part, \fBlv_draw_img_dsc_t\fP *draw_dsc)"
.br
.ti -1c
.RI "void \fBlv_obj_init_draw_line_dsc\fP (struct \fB_lv_obj_t\fP *obj, uint32_t part, \fBlv_draw_line_dsc_t\fP *draw_dsc)"
.br
.ti -1c
.RI "void \fBlv_obj_init_draw_arc_dsc\fP (struct \fB_lv_obj_t\fP *obj, uint32_t part, \fBlv_draw_arc_dsc_t\fP *draw_dsc)"
.br
.ti -1c
.RI "lv_coord_t \fBlv_obj_calculate_ext_draw_size\fP (struct \fB_lv_obj_t\fP *obj, uint32_t part)"
.br
.ti -1c
.RI "void \fBlv_obj_draw_dsc_init\fP (\fBlv_obj_draw_part_dsc_t\fP *dsc, lv_draw_ctx_t *draw_ctx)"
.br
.ti -1c
.RI "bool \fBlv_obj_draw_part_check_type\fP (\fBlv_obj_draw_part_dsc_t\fP *dsc, const struct \fB_lv_obj_class_t\fP *class_p, uint32_t type)"
.br
.ti -1c
.RI "void \fBlv_obj_refresh_ext_draw_size\fP (struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_coord_t \fB_lv_obj_get_ext_draw_size\fP (const struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_layer_type_t \fB_lv_obj_get_layer_type\fP (const struct \fB_lv_obj_t\fP *obj)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBlv_cover_res_t\fP"
Cover check results\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/core/lv_event\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "lv_coord_t _lv_obj_get_ext_draw_size (const struct \fB_lv_obj_t\fP * obj)"
Get the extended draw area of an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the size extended draw area around the real coordinates 
.RE
.PP

.SS "lv_coord_t lv_obj_calculate_ext_draw_size (struct \fB_lv_obj_t\fP * obj, uint32_t part)"
Get the required extra size (around the object's part) to draw shadow, outline, value etc\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIpart\fP part of the object 
.RE
.PP
\fBReturns\fP
.RS 4
the extra size required around the object 
.RE
.PP

.SS "void lv_obj_draw_dsc_init (\fBlv_obj_draw_part_dsc_t\fP * dsc, lv_draw_ctx_t * draw_ctx)"
Initialize a draw descriptor used in events\&. 
.PP
\fBParameters\fP
.RS 4
\fIdsc\fP pointer to a descriptor\&. Later it should be passed as parameter to an \fRLV_EVENT_DRAW_PART_BEGIN/END\fP event\&. 
.br
\fIdraw\fP the current draw context\&. (usually returned by \fRlv_event_get_draw_ctx(e)\fP) 
.RE
.PP

.SS "bool lv_obj_draw_part_check_type (\fBlv_obj_draw_part_dsc_t\fP * dsc, const struct \fB_lv_obj_class_t\fP * class_p, uint32_t type)"
Check the type obj a part draw descriptor 
.PP
\fBParameters\fP
.RS 4
\fIdsc\fP the descriptor (normally the event parameter) 
.br
\fIclass_p\fP pointer to class to which \fRtype\fP is related 
.br
\fItype\fP element of \fRlv_<name>_draw_part_type_t\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true if ::dsc is related to ::class_p and ::type 
.RE
.PP

.SS "void lv_obj_init_draw_arc_dsc (struct \fB_lv_obj_t\fP * obj, uint32_t part, \fBlv_draw_arc_dsc_t\fP * draw_dsc)"
Initialize an arc draw descriptor from an object's styles in its current state 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIpart\fP part of the object, e\&.g\&. \fR\fBLV_PART_MAIN\fP\fP, \fR\fBLV_PART_SCROLLBAR\fP\fP, \fR\fBLV_PART_KNOB\fP\fP, etc 
.br
\fIdraw_dsc\fP the descriptor to initialize\&. Should be initialized with \fRlv_draw_arc_dsc_init(draw_dsc)\fP\&. 
.RE
.PP

.SS "void lv_obj_init_draw_img_dsc (struct \fB_lv_obj_t\fP * obj, uint32_t part, \fBlv_draw_img_dsc_t\fP * draw_dsc)"
Initialize an image draw descriptor from an object's styles in its current state 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIpart\fP part of the object, e\&.g\&. \fR\fBLV_PART_MAIN\fP\fP, \fR\fBLV_PART_SCROLLBAR\fP\fP, \fR\fBLV_PART_KNOB\fP\fP, etc 
.br
\fIdraw_dsc\fP the descriptor to initialize\&. Should be initialized with \fRlv_draw_image_dsc_init(draw_dsc)\fP\&. 
.RE
.PP

.SS "void lv_obj_init_draw_label_dsc (struct \fB_lv_obj_t\fP * obj, uint32_t part, \fBlv_draw_label_dsc_t\fP * draw_dsc)"
Initialize a label draw descriptor from an object's styles in its current state 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIpart\fP part of the object, e\&.g\&. \fR\fBLV_PART_MAIN\fP\fP, \fR\fBLV_PART_SCROLLBAR\fP\fP, \fR\fBLV_PART_KNOB\fP\fP, etc 
.br
\fIdraw_dsc\fP the descriptor to initialize\&. If the \fRopa\fP field is set to or the property is equal to \fRLV_OPA_TRANSP\fP the rest won't be initialized\&. Should be initialized with \fRlv_draw_label_dsc_init(draw_dsc)\fP\&. 
.RE
.PP

.SS "void lv_obj_init_draw_line_dsc (struct \fB_lv_obj_t\fP * obj, uint32_t part, \fBlv_draw_line_dsc_t\fP * draw_dsc)"
Initialize a line draw descriptor from an object's styles in its current state 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIpart\fP part of the object, e\&.g\&. \fR\fBLV_PART_MAIN\fP\fP, \fR\fBLV_PART_SCROLLBAR\fP\fP, \fR\fBLV_PART_KNOB\fP\fP, etc 
.br
\fIdraw_dsc\fP the descriptor to initialize\&. Should be initialized with \fRlv_draw_line_dsc_init(draw_dsc)\fP\&. 
.RE
.PP

.SS "void lv_obj_init_draw_rect_dsc (struct \fB_lv_obj_t\fP * obj, uint32_t part, \fBlv_draw_rect_dsc_t\fP * draw_dsc)"
Initialize a rectangle draw descriptor from an object's styles in its current state 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIpart\fP part of the object, e\&.g\&. \fR\fBLV_PART_MAIN\fP\fP, \fR\fBLV_PART_SCROLLBAR\fP\fP, \fR\fBLV_PART_KNOB\fP\fP, etc 
.br
\fIdraw_dsc\fP the descriptor to initialize\&. If an \fR\&.\&.\&._opa\fP field is set to \fRLV_OPA_TRANSP\fP the related properties won't be initialized\&. Should be initialized with \fRlv_draw_rect_dsc_init(draw_dsc)\fP\&. 
.RE
.PP
\fBNote\fP
.RS 4
Only the relevant fields will be set\&. E\&.g\&. if \fRborder width == 0\fP the other border properties won't be evaluated\&. 
.RE
.PP

.SS "void lv_obj_refresh_ext_draw_size (struct \fB_lv_obj_t\fP * obj)"
Send a 'LV_EVENT_REFR_EXT_DRAW_SIZE' Call the ancestor's event handler to the object to refresh the value of the extended draw size\&. The result will be saved in \fRobj\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
