.TH "lv_obj_draw_part_dsc_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_obj_draw_part_dsc_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_draw_ctx_t * \fBdraw_ctx\fP"
.br
.ti -1c
.RI "const struct \fB_lv_obj_class_t\fP * \fBclass_p\fP"
.br
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "\fBlv_area_t\fP * \fBdraw_area\fP"
.br
.ti -1c
.RI "\fBlv_draw_rect_dsc_t\fP * \fBrect_dsc\fP"
.br
.ti -1c
.RI "\fBlv_draw_label_dsc_t\fP * \fBlabel_dsc\fP"
.br
.ti -1c
.RI "\fBlv_draw_line_dsc_t\fP * \fBline_dsc\fP"
.br
.ti -1c
.RI "\fBlv_draw_img_dsc_t\fP * \fBimg_dsc\fP"
.br
.ti -1c
.RI "\fBlv_draw_arc_dsc_t\fP * \fBarc_dsc\fP"
.br
.ti -1c
.RI "const \fBlv_point_t\fP * \fBp1\fP"
.br
.ti -1c
.RI "const \fBlv_point_t\fP * \fBp2\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "uint32_t \fBtext_length\fP"
.br
.ti -1c
.RI "uint32_t \fBpart\fP"
.br
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.ti -1c
.RI "lv_coord_t \fBradius\fP"
.br
.ti -1c
.RI "int32_t \fBvalue\fP"
.br
.ti -1c
.RI "const void * \fBsub_part_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/core/lv_event\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBlv_draw_arc_dsc_t\fP* lv_obj_draw_part_dsc_t::arc_dsc"
A draw descriptor that can be modified to changed what LVGL will draw\&. Set only for arc-like parts 
.SS "const struct \fB_lv_obj_class_t\fP* lv_obj_draw_part_dsc_t::class_p"
The class that sent the event 
.SS "\fBlv_area_t\fP* lv_obj_draw_part_dsc_t::draw_area"
The area of the part being drawn 
.SS "lv_draw_ctx_t* lv_obj_draw_part_dsc_t::draw_ctx"
Draw context 
.SS "uint32_t lv_obj_draw_part_dsc_t::id"
The index of the part\&. E\&.g\&. a button's index on button matrix or table cell index\&. 
.SS "\fBlv_draw_img_dsc_t\fP* lv_obj_draw_part_dsc_t::img_dsc"
A draw descriptor that can be modified to changed what LVGL will draw\&. Set only for image-like parts 
.SS "\fBlv_draw_label_dsc_t\fP* lv_obj_draw_part_dsc_t::label_dsc"
A draw descriptor that can be modified to changed what LVGL will draw\&. Set only for text-like parts 
.SS "\fBlv_draw_line_dsc_t\fP* lv_obj_draw_part_dsc_t::line_dsc"
A draw descriptor that can be modified to changed what LVGL will draw\&. Set only for line-like parts 
.SS "const \fBlv_point_t\fP* lv_obj_draw_part_dsc_t::p1"
A point calculated during drawing\&. E\&.g\&. a point of chart or the center of an arc\&. 
.SS "const \fBlv_point_t\fP* lv_obj_draw_part_dsc_t::p2"
A point calculated during drawing\&. E\&.g\&. a point of chart\&. 
.SS "uint32_t lv_obj_draw_part_dsc_t::part"
The current part for which the event is sent 
.SS "lv_coord_t lv_obj_draw_part_dsc_t::radius"
E\&.g\&. the radius of an arc (not the corner radius)\&. 
.SS "\fBlv_draw_rect_dsc_t\fP* lv_obj_draw_part_dsc_t::rect_dsc"
A draw descriptor that can be modified to changed what LVGL will draw\&. Set only for rectangle-like parts 
.SS "const void* lv_obj_draw_part_dsc_t::sub_part_ptr"
A pointer the identifies something in the part\&. E\&.g\&. chart series\&. 
.SS "char* lv_obj_draw_part_dsc_t::text"
A text calculated during drawing\&. Can be modified\&. E\&.g\&. tick labels on a chart axis\&. 
.SS "uint32_t lv_obj_draw_part_dsc_t::text_length"
Size of the text buffer containing null-terminated text string calculated during drawing\&. 
.SS "uint32_t lv_obj_draw_part_dsc_t::type"
The type if part being draw\&. Element of \fRlv_<name>_draw_part_type_t\fP 
.SS "int32_t lv_obj_draw_part_dsc_t::value"
A value calculated during drawing\&. E\&.g\&. Chart's tick line value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
