.TH "include/liblvgl/core/lv_obj_scroll.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/core/lv_obj_scroll.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/misc/lv_area\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_anim\&.h'\fP
.br
\fR#include 'liblvgl/misc/lv_types\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBlv_scrollbar_mode_t\fP"
.br
.ti -1c
.RI "typedef uint8_t \fBlv_scroll_snap_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBLV_SCROLLBAR_MODE_OFF\fP, \fBLV_SCROLLBAR_MODE_ON\fP, \fBLV_SCROLLBAR_MODE_ACTIVE\fP, \fBLV_SCROLLBAR_MODE_AUTO\fP }"
.br
.ti -1c
.RI "enum { \fBLV_SCROLL_SNAP_NONE\fP, \fBLV_SCROLL_SNAP_START\fP, \fBLV_SCROLL_SNAP_END\fP, \fBLV_SCROLL_SNAP_CENTER\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlv_obj_set_scrollbar_mode\fP (struct \fB_lv_obj_t\fP *obj, lv_scrollbar_mode_t mode)"
.br
.ti -1c
.RI "void \fBlv_obj_set_scroll_dir\fP (struct \fB_lv_obj_t\fP *obj, lv_dir_t dir)"
.br
.ti -1c
.RI "void \fBlv_obj_set_scroll_snap_x\fP (struct \fB_lv_obj_t\fP *obj, lv_scroll_snap_t align)"
.br
.ti -1c
.RI "void \fBlv_obj_set_scroll_snap_y\fP (struct \fB_lv_obj_t\fP *obj, lv_scroll_snap_t align)"
.br
.ti -1c
.RI "lv_scrollbar_mode_t \fBlv_obj_get_scrollbar_mode\fP (const struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_dir_t \fBlv_obj_get_scroll_dir\fP (const struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_scroll_snap_t \fBlv_obj_get_scroll_snap_x\fP (const struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_scroll_snap_t \fBlv_obj_get_scroll_snap_y\fP (const struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_coord_t \fBlv_obj_get_scroll_x\fP (const struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_coord_t \fBlv_obj_get_scroll_y\fP (const struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_coord_t \fBlv_obj_get_scroll_top\fP (struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_coord_t \fBlv_obj_get_scroll_bottom\fP (struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_coord_t \fBlv_obj_get_scroll_left\fP (struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "lv_coord_t \fBlv_obj_get_scroll_right\fP (struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "void \fBlv_obj_get_scroll_end\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_point_t\fP *end)"
.br
.ti -1c
.RI "void \fBlv_obj_scroll_by\fP (struct \fB_lv_obj_t\fP *obj, lv_coord_t x, lv_coord_t y, \fBlv_anim_enable_t\fP anim_en)"
.br
.ti -1c
.RI "void \fBlv_obj_scroll_by_bounded\fP (struct \fB_lv_obj_t\fP *obj, lv_coord_t dx, lv_coord_t dy, \fBlv_anim_enable_t\fP anim_en)"
.br
.ti -1c
.RI "void \fBlv_obj_scroll_to\fP (struct \fB_lv_obj_t\fP *obj, lv_coord_t x, lv_coord_t y, \fBlv_anim_enable_t\fP anim_en)"
.br
.ti -1c
.RI "void \fBlv_obj_scroll_to_x\fP (struct \fB_lv_obj_t\fP *obj, lv_coord_t x, \fBlv_anim_enable_t\fP anim_en)"
.br
.ti -1c
.RI "void \fBlv_obj_scroll_to_y\fP (struct \fB_lv_obj_t\fP *obj, lv_coord_t y, \fBlv_anim_enable_t\fP anim_en)"
.br
.ti -1c
.RI "void \fBlv_obj_scroll_to_view\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_anim_enable_t\fP anim_en)"
.br
.ti -1c
.RI "void \fBlv_obj_scroll_to_view_recursive\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_anim_enable_t\fP anim_en)"
.br
.ti -1c
.RI "lv_res_t \fB_lv_obj_scroll_by_raw\fP (struct \fB_lv_obj_t\fP *obj, lv_coord_t x, lv_coord_t y)"
.br
.ti -1c
.RI "bool \fBlv_obj_is_scrolling\fP (const struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "void \fBlv_obj_update_snap\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_anim_enable_t\fP anim_en)"
.br
.ti -1c
.RI "void \fBlv_obj_get_scrollbar_area\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_area_t\fP *hor, \fBlv_area_t\fP *ver)"
.br
.ti -1c
.RI "void \fBlv_obj_scrollbar_invalidate\fP (struct \fB_lv_obj_t\fP *obj)"
.br
.ti -1c
.RI "void \fBlv_obj_readjust_scroll\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_anim_enable_t\fP anim_en)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"
Scrollbar modes: shows when should the scrollbars be visible 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILV_SCROLLBAR_MODE_OFF \fP
Never show scrollbars 
.TP
\f(BILV_SCROLLBAR_MODE_ON \fP
Always show scrollbars 
.TP
\f(BILV_SCROLLBAR_MODE_ACTIVE \fP
Show scroll bars when object is being scrolled 
.TP
\f(BILV_SCROLLBAR_MODE_AUTO \fP
Show scroll bars when the content is large enough to be scrolled 
.SS "anonymous enum"
Scroll span align options\&. Tells where to align the snappable children when scroll stops\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILV_SCROLL_SNAP_NONE \fP
Do not align, leave where it is 
.TP
\f(BILV_SCROLL_SNAP_START \fP
Align to the left/top 
.TP
\f(BILV_SCROLL_SNAP_END \fP
Align to the right/bottom 
.TP
\f(BILV_SCROLL_SNAP_CENTER \fP
Align to the center 
.SH "Function Documentation"
.PP 
.SS "lv_res_t _lv_obj_scroll_by_raw (struct \fB_lv_obj_t\fP * obj, lv_coord_t x, lv_coord_t y)"
Low level function to scroll by given x and y coordinates\&. \fR\fBLV_EVENT_SCROLL\fP\fP is sent\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object to scroll 
.br
\fIx\fP pixels to scroll horizontally 
.br
\fIy\fP pixels to scroll vertically 
.RE
.PP
\fBReturns\fP
.RS 4
\fRLV_RES_INV\fP: to object was deleted in \fR\fBLV_EVENT_SCROLL\fP\fP; \fRLV_RES_OK\fP: if the object is still valid 
.RE
.PP

.SS "lv_coord_t lv_obj_get_scroll_bottom (struct \fB_lv_obj_t\fP * obj)"
Return the height of the area below the object\&. That is the number of pixels the object can be scrolled down\&. Normally positive but can be negative when scrolled inside\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the scrollable area below the object in pixels 
.RE
.PP

.SS "lv_dir_t lv_obj_get_scroll_dir (const struct \fB_lv_obj_t\fP * obj)"
Get the object in which directions can be scrolled 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIdir\fP the allow scroll directions\&. An element or OR-ed values of \fRlv_dir_t\fP 
.RE
.PP

.SS "void lv_obj_get_scroll_end (struct \fB_lv_obj_t\fP * obj, \fBlv_point_t\fP * end)"
Get the X and Y coordinates where the scrolling will end for this object if a scrolling animation is in progress\&. If no scrolling animation, give the current \fRx\fP or \fRy\fP scroll position\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIend\fP pointer to store the result 
.RE
.PP

.SS "lv_coord_t lv_obj_get_scroll_left (struct \fB_lv_obj_t\fP * obj)"
Return the width of the area on the left the object\&. That is the number of pixels the object can be scrolled down\&. Normally positive but can be negative when scrolled inside\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the scrollable area on the left the object in pixels 
.RE
.PP

.SS "lv_coord_t lv_obj_get_scroll_right (struct \fB_lv_obj_t\fP * obj)"
Return the width of the area on the right the object\&. That is the number of pixels the object can be scrolled down\&. Normally positive but can be negative when scrolled inside\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the scrollable area on the right the object in pixels 
.RE
.PP

.SS "lv_scroll_snap_t lv_obj_get_scroll_snap_x (const struct \fB_lv_obj_t\fP * obj)"
Get where to snap the children when scrolling ends horizontally 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the current snap align from \fRlv_scroll_snap_t\fP 
.RE
.PP

.SS "lv_scroll_snap_t lv_obj_get_scroll_snap_y (const struct \fB_lv_obj_t\fP * obj)"
Get where to snap the children when scrolling ends vertically 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the current snap align from \fRlv_scroll_snap_t\fP 
.RE
.PP

.SS "lv_coord_t lv_obj_get_scroll_top (struct \fB_lv_obj_t\fP * obj)"
Return the height of the area above the object\&. That is the number of pixels the object can be scrolled down\&. Normally positive but can be negative when scrolled inside\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the scrollable area above the object in pixels 
.RE
.PP

.SS "lv_coord_t lv_obj_get_scroll_x (const struct \fB_lv_obj_t\fP * obj)"
Get current X scroll position\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the current scroll position from the left edge\&. If the object is not scrolled return 0 If scrolled return > 0 If scrolled in (elastic scroll) return < 0 
.RE
.PP

.SS "lv_coord_t lv_obj_get_scroll_y (const struct \fB_lv_obj_t\fP * obj)"
Get current Y scroll position\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the current scroll position from the top edge\&. If the object is not scrolled return 0 If scrolled return > 0 If scrolled inside return < 0 
.RE
.PP

.SS "void lv_obj_get_scrollbar_area (struct \fB_lv_obj_t\fP * obj, \fBlv_area_t\fP * hor, \fBlv_area_t\fP * ver)"
Get the area of the scrollbars 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIhor\fP pointer to store the area of the horizontal scrollbar 
.br
\fIver\fP pointer to store the area of the vertical scrollbar 
.RE
.PP

.SS "lv_scrollbar_mode_t lv_obj_get_scrollbar_mode (const struct \fB_lv_obj_t\fP * obj)"
Get the current scroll mode (when to hide the scrollbars) 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the current scroll mode from \fRlv_scrollbar_mode_t\fP 
.RE
.PP

.SS "bool lv_obj_is_scrolling (const struct \fB_lv_obj_t\fP * obj)"
Tell whether an object is being scrolled or not at this moment 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
true: \fRobj\fP is being scrolled 
.RE
.PP

.SS "void lv_obj_readjust_scroll (struct \fB_lv_obj_t\fP * obj, \fBlv_anim_enable_t\fP anim_en)"
Checked if the content is scrolled "in" and adjusts it to a normal position\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIanim_en\fP LV_ANIM_ON/OFF 
.RE
.PP

.SS "void lv_obj_scroll_by (struct \fB_lv_obj_t\fP * obj, lv_coord_t x, lv_coord_t y, \fBlv_anim_enable_t\fP anim_en)"
Scroll by a given amount of pixels 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object to scroll 
.br
\fIdx\fP pixels to scroll horizontally 
.br
\fIdy\fP pixels to scroll vertically 
.br
\fIanim_en\fP LV_ANIM_ON: scroll with animation; LV_ANIM_OFF: scroll immediately 
.RE
.PP
\fBNote\fP
.RS 4
> 0 value means scroll right/bottom (show the more content on the right/bottom) 

.PP
e\&.g\&. dy = -20 means scroll down 20 px 
.RE
.PP

.SS "void lv_obj_scroll_by_bounded (struct \fB_lv_obj_t\fP * obj, lv_coord_t dx, lv_coord_t dy, \fBlv_anim_enable_t\fP anim_en)"
Scroll by a given amount of pixels\&. \fRdx\fP and \fRdy\fP will be limited internally to allow scrolling only on the content area\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object to scroll 
.br
\fIdx\fP pixels to scroll horizontally 
.br
\fIdy\fP pixels to scroll vertically 
.br
\fIanim_en\fP LV_ANIM_ON: scroll with animation; LV_ANIM_OFF: scroll immediately 
.RE
.PP
\fBNote\fP
.RS 4
e\&.g\&. dy = -20 means scroll down 20 px 
.RE
.PP

.SS "void lv_obj_scroll_to (struct \fB_lv_obj_t\fP * obj, lv_coord_t x, lv_coord_t y, \fBlv_anim_enable_t\fP anim_en)"
Scroll to a given coordinate on an object\&. \fRx\fP and \fRy\fP will be limited internally to allow scrolling only on the content area\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object to scroll 
.br
\fIx\fP pixels to scroll horizontally 
.br
\fIy\fP pixels to scroll vertically 
.br
\fIanim_en\fP LV_ANIM_ON: scroll with animation; LV_ANIM_OFF: scroll immediately 
.RE
.PP

.SS "void lv_obj_scroll_to_view (struct \fB_lv_obj_t\fP * obj, \fBlv_anim_enable_t\fP anim_en)"
Scroll to an object until it becomes visible on its parent 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object to scroll into view 
.br
\fIanim_en\fP LV_ANIM_ON: scroll with animation; LV_ANIM_OFF: scroll immediately 
.RE
.PP

.SS "void lv_obj_scroll_to_view_recursive (struct \fB_lv_obj_t\fP * obj, \fBlv_anim_enable_t\fP anim_en)"
Scroll to an object until it becomes visible on its parent\&. Do the same on the parent's parent, and so on\&. Therefore the object will be scrolled into view even it has nested scrollable parents 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object to scroll into view 
.br
\fIanim_en\fP LV_ANIM_ON: scroll with animation; LV_ANIM_OFF: scroll immediately 
.RE
.PP

.SS "void lv_obj_scroll_to_x (struct \fB_lv_obj_t\fP * obj, lv_coord_t x, \fBlv_anim_enable_t\fP anim_en)"
Scroll to a given X coordinate on an object\&. \fRx\fP will be limited internally to allow scrolling only on the content area\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object to scroll 
.br
\fIx\fP pixels to scroll horizontally 
.br
\fIanim_en\fP LV_ANIM_ON: scroll with animation; LV_ANIM_OFF: scroll immediately 
.RE
.PP

.SS "void lv_obj_scroll_to_y (struct \fB_lv_obj_t\fP * obj, lv_coord_t y, \fBlv_anim_enable_t\fP anim_en)"
Scroll to a given Y coordinate on an object \fRy\fP will be limited internally to allow scrolling only on the content area\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object to scroll 
.br
\fIy\fP pixels to scroll vertically 
.br
\fIanim_en\fP LV_ANIM_ON: scroll with animation; LV_ANIM_OFF: scroll immediately 
.RE
.PP

.SS "void lv_obj_scrollbar_invalidate (struct \fB_lv_obj_t\fP * obj)"
Invalidate the area of the scrollbars 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP

.SS "void lv_obj_set_scroll_dir (struct \fB_lv_obj_t\fP * obj, lv_dir_t dir)"
Set the object in which directions can be scrolled 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIdir\fP the allow scroll directions\&. An element or OR-ed values of \fRlv_dir_t\fP 
.RE
.PP

.SS "void lv_obj_set_scroll_snap_x (struct \fB_lv_obj_t\fP * obj, lv_scroll_snap_t align)"
Set where to snap the children when scrolling ends horizontally 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIalign\fP the snap align to set from \fRlv_scroll_snap_t\fP 
.RE
.PP

.SS "void lv_obj_set_scroll_snap_y (struct \fB_lv_obj_t\fP * obj, lv_scroll_snap_t align)"
Set where to snap the children when scrolling ends vertically 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIalign\fP the snap align to set from \fRlv_scroll_snap_t\fP 
.RE
.PP

.SS "void lv_obj_set_scrollbar_mode (struct \fB_lv_obj_t\fP * obj, lv_scrollbar_mode_t mode)"
Set how the scrollbars should behave\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fImode\fP LV_SCROLL_MODE_ON/OFF/AUTO/ACTIVE 
.RE
.PP

.SS "void lv_obj_update_snap (struct \fB_lv_obj_t\fP * obj, \fBlv_anim_enable_t\fP anim_en)"
Check the children of \fRobj\fP and scroll \fRobj\fP to fulfill the scroll_snap settings 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP an object whose children needs to checked and snapped 
.br
\fIanim_en\fP LV_ANIM_ON/OFF 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
