.TH "include/liblvgl/core/lv_obj_style.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/core/lv_obj_style.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include 'liblvgl/misc/lv_bidi\&.h'\fP
.br
\fR#include 'lv_obj_style_gen\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_lv_obj_style_t\fP"
.br
.ti -1c
.RI "struct \fB_lv_obj_style_transition_dsc_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint32_t \fBlv_style_selector_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fB_lv_style_state_cmp_t\fP { \fB_LV_STYLE_STATE_CMP_SAME\fP, \fB_LV_STYLE_STATE_CMP_DIFF_REDRAW\fP, \fB_LV_STYLE_STATE_CMP_DIFF_DRAW_PAD\fP, \fB_LV_STYLE_STATE_CMP_DIFF_LAYOUT\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_lv_obj_style_init\fP (void)"
.br
.ti -1c
.RI "void \fBlv_obj_add_style\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_style_t\fP *style, lv_style_selector_t selector)"
.br
.ti -1c
.RI "void \fBlv_obj_remove_style\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_style_t\fP *style, lv_style_selector_t selector)"
.br
.ti -1c
.RI "void \fBlv_obj_report_style_change\fP (\fBlv_style_t\fP *style)"
.br
.ti -1c
.RI "void \fBlv_obj_refresh_style\fP (struct \fB_lv_obj_t\fP *obj, lv_part_t part, \fBlv_style_prop_t\fP prop)"
.br
.ti -1c
.RI "void \fBlv_obj_enable_style_refresh\fP (bool en)"
.br
.ti -1c
.RI "\fBlv_style_value_t\fP \fBlv_obj_get_style_prop\fP (const struct \fB_lv_obj_t\fP *obj, lv_part_t part, \fBlv_style_prop_t\fP prop)"
.br
.ti -1c
.RI "void \fBlv_obj_set_local_style_prop\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_style_prop_t\fP prop, \fBlv_style_value_t\fP value, lv_style_selector_t selector)"
.br
.ti -1c
.RI "void \fBlv_obj_set_local_style_prop_meta\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_style_prop_t\fP prop, uint16_t meta, lv_style_selector_t selector)"
.br
.ti -1c
.RI "lv_style_res_t \fBlv_obj_get_local_style_prop\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_style_prop_t\fP prop, \fBlv_style_value_t\fP *value, lv_style_selector_t selector)"
.br
.ti -1c
.RI "bool \fBlv_obj_remove_local_style_prop\fP (struct \fB_lv_obj_t\fP *obj, \fBlv_style_prop_t\fP prop, lv_style_selector_t selector)"
.br
.ti -1c
.RI "\fBlv_style_value_t\fP \fB_lv_obj_style_apply_color_filter\fP (const struct \fB_lv_obj_t\fP *obj, uint32_t part, \fBlv_style_value_t\fP v)"
.br
.ti -1c
.RI "void \fB_lv_obj_style_create_transition\fP (struct \fB_lv_obj_t\fP *obj, lv_part_t part, lv_state_t prev_state, lv_state_t new_state, const \fB_lv_obj_style_transition_dsc_t\fP *tr)"
.br
.ti -1c
.RI "_lv_style_state_cmp_t \fB_lv_obj_style_state_compare\fP (struct \fB_lv_obj_t\fP *obj, lv_state_t state1, lv_state_t state2)"
.br
.ti -1c
.RI "void \fBlv_obj_fade_in\fP (struct \fB_lv_obj_t\fP *obj, uint32_t time, uint32_t \fBdelay\fP)"
.br
.ti -1c
.RI "void \fBlv_obj_fade_out\fP (struct \fB_lv_obj_t\fP *obj, uint32_t time, uint32_t \fBdelay\fP)"
.br
.ti -1c
.RI "lv_state_t \fBlv_obj_style_get_selector_state\fP (lv_style_selector_t selector)"
.br
.ti -1c
.RI "lv_part_t \fBlv_obj_style_get_selector_part\fP (lv_style_selector_t selector)"
.br
.ti -1c
.RI "lv_text_align_t \fBlv_obj_calculate_style_text_align\fP (const struct \fB_lv_obj_t\fP *obj, lv_part_t part, const char *txt)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlv_style_value_t\fP _lv_obj_style_apply_color_filter (const struct \fB_lv_obj_t\fP * obj, uint32_t part, \fBlv_style_value_t\fP v)"
Used internally for color filtering 
.SS "void _lv_obj_style_create_transition (struct \fB_lv_obj_t\fP * obj, lv_part_t part, lv_state_t prev_state, lv_state_t new_state, const \fB_lv_obj_style_transition_dsc_t\fP * tr)"
Used internally to create a style transition 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP 
.br
\fIpart\fP 
.br
\fIprev_state\fP 
.br
\fInew_state\fP 
.br
\fItr\fP 
.RE
.PP

.SS "void _lv_obj_style_init (void )"
Initialize the object related style manager module\&. Called by LVGL in \fR\fBlv_init()\fP\fP 
.SS "_lv_style_state_cmp_t _lv_obj_style_state_compare (struct \fB_lv_obj_t\fP * obj, lv_state_t state1, lv_state_t state2)"
Used internally to compare the appearance of an object in 2 states 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP 
.br
\fIstate1\fP 
.br
\fIstate2\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "void lv_obj_enable_style_refresh (bool en)"
Enable or disable automatic style refreshing when a new style is added/removed to/from an object or any other style change happens\&. 
.PP
\fBParameters\fP
.RS 4
\fIen\fP true: enable refreshing; false: disable refreshing 
.RE
.PP

.SS "void lv_obj_fade_in (struct \fB_lv_obj_t\fP * obj, uint32_t time, uint32_t delay)"
Fade in an an object and all its children\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP the object to fade in 
.br
\fItime\fP time of fade 
.br
\fIdelay\fP delay to start the animation 
.RE
.PP

.SS "void lv_obj_fade_out (struct \fB_lv_obj_t\fP * obj, uint32_t time, uint32_t delay)"
Fade out an an object and all its children\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP the object to fade out 
.br
\fItime\fP time of fade 
.br
\fIdelay\fP delay to start the animation 
.RE
.PP

.SS "\fBlv_style_value_t\fP lv_obj_get_style_prop (const struct \fB_lv_obj_t\fP * obj, lv_part_t part, \fBlv_style_prop_t\fP prop)"
Get the value of a style property\&. The current state of the object will be considered\&. Inherited properties will be inherited\&. If a property is not set a default value will be returned\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIpart\fP a part from which the property should be get 
.br
\fIprop\fP the property to get 
.RE
.PP
\fBReturns\fP
.RS 4
the value of the property\&. Should be read from the correct field of the \fR\fBlv_style_value_t\fP\fP according to the type of the property\&. 
.RE
.PP

.SS "void lv_obj_refresh_style (struct \fB_lv_obj_t\fP * obj, lv_part_t part, \fBlv_style_prop_t\fP prop)"
Notify an object and its children about its style is modified\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIpart\fP the part whose style was changed\&. E\&.g\&. \fR\fBLV_PART_ANY\fP\fP, \fR\fBLV_PART_MAIN\fP\fP 
.br
\fIprop\fP \fRLV_STYLE_PROP_ANY\fP or an \fRLV_STYLE_\&.\&.\&.\fP property\&. It is used to optimize what needs to be refreshed\&. \fRLV_STYLE_PROP_INV\fP to perform only a style cache update 
.RE
.PP

.SS "bool lv_obj_remove_local_style_prop (struct \fB_lv_obj_t\fP * obj, \fBlv_style_prop_t\fP prop, lv_style_selector_t selector)"
Remove a local style property from a part of an object with a given state\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIprop\fP a style property to remove\&. 
.br
\fIselector\fP OR-ed value of parts and state for which the style should be removed 
.RE
.PP
\fBReturns\fP
.RS 4
true the property was found and removed; false: the property was not found 
.RE
.PP

.SS "void lv_obj_report_style_change (\fBlv_style_t\fP * style)"
Notify all object if a style is modified 
.PP
\fBParameters\fP
.RS 4
\fIstyle\fP pointer to a style\&. Only the objects with this style will be notified (NULL to notify all objects) 
.RE
.PP

.SS "void lv_obj_set_local_style_prop (struct \fB_lv_obj_t\fP * obj, \fBlv_style_prop_t\fP prop, \fBlv_style_value_t\fP value, lv_style_selector_t selector)"
Set local style property on an object's part and state\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.br
\fIprop\fP the property 
.br
\fIvalue\fP value of the property\&. The correct element should be set according to the type of the property 
.br
\fIselector\fP OR-ed value of parts and state for which the style should be set 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
