.TH "lv_point_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_point_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_area\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lv_coord_t \fBx\fP"
.br
.ti -1c
.RI "lv_coord_t \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a point on the screen\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/core/lv_event\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
