.TH "include/liblvgl/core/lv_refr.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/core/lv_refr.h
.SH SYNOPSIS
.br
.PP
\fR#include 'lv_obj\&.h'\fP
.br
\fR#include <stdbool\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV_REFR_TASK_PRIO\fP   LV_TASK_PRIO_MID"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_lv_refr_init\fP (void)"
.br
.ti -1c
.RI "void \fBlv_refr_now\fP (\fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "void \fBlv_obj_redraw\fP (lv_draw_ctx_t *draw_ctx, lv_obj_t *obj)"
.br
.ti -1c
.RI "void \fB_lv_inv_area\fP (\fBlv_disp_t\fP *disp, const \fBlv_area_t\fP *area_p)"
.br
.ti -1c
.RI "\fBlv_disp_t\fP * \fB_lv_refr_get_disp_refreshing\fP (void)"
.br
.ti -1c
.RI "void \fB_lv_refr_set_disp_refreshing\fP (\fBlv_disp_t\fP *disp)"
.br
.ti -1c
.RI "void \fB_lv_disp_refr_timer\fP (\fBlv_timer_t\fP *timer)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _lv_disp_refr_timer (\fBlv_timer_t\fP * timer)"
Called periodically to handle the refreshing 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP pointer to the timer itself 
.RE
.PP

.SS "void _lv_inv_area (\fBlv_disp_t\fP * disp, const \fBlv_area_t\fP * area_p)"
Invalidate an area on display to redraw it 
.PP
\fBParameters\fP
.RS 4
\fIarea_p\fP pointer to area which should be invalidated (NULL: delete the invalidated areas) 
.br
\fIdisp\fP pointer to display where the area should be invalidated (NULL can be used if there is only one display) 
.RE
.PP

.SS "\fBlv_disp_t\fP * _lv_refr_get_disp_refreshing (void )"
Get the display which is being refreshed 
.PP
\fBReturns\fP
.RS 4
the display being refreshed 
.RE
.PP

.SS "void _lv_refr_init (void )"
Initialize the screen refresh subsystem 
.SS "void _lv_refr_set_disp_refreshing (\fBlv_disp_t\fP * disp)"
Set the display which is being refreshed\&. It shouldn't be used directly by the user\&. It can be used to trick the drawing functions about there is an active display\&. 
.PP
\fBParameters\fP
.RS 4
\fIthe\fP display being refreshed 
.RE
.PP

.SS "void lv_obj_redraw (lv_draw_ctx_t * draw_ctx, lv_obj_t * obj)"
Redrawn on object an all its children using the passed draw context 
.PP
\fBParameters\fP
.RS 4
\fIdraw\fP pointer to an initialized draw context 
.br
\fIobj\fP the start object from the redraw should start 
.RE
.PP

.SS "void lv_refr_now (\fBlv_disp_t\fP * disp)"
Redraw the invalidated areas now\&. Normally the redrawing is periodically executed in \fRlv_timer_handler\fP but a long blocking process can prevent the call of \fRlv_timer_handler\fP\&. In this case if the GUI is updated in the process (e\&.g\&. progress bar) this function can be called when the screen should be updated\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisp\fP pointer to display to refresh\&. NULL to refresh all displays\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
