.TH "lv_style_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_style_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_style\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBlv_style_value_t\fP \fBvalue1\fP"
.br
.ti -1c
.RI "   uint8_t * \fBvalues_and_props\fP"
.br
.ti -1c
.RI "   const \fBlv_style_const_prop_t\fP * \fBconst_props\fP"
.br
.ti -1c
.RI "} \fBv_p\fP"
.br
.ti -1c
.RI "uint16_t \fBprop1\fP"
.br
.ti -1c
.RI "uint8_t \fBhas_group\fP"
.br
.ti -1c
.RI "uint8_t \fBprop_cnt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Descriptor of a style (a collection of properties and values)\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/misc/lv_style\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
