.TH "lv_style_transition_dsc_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_style_transition_dsc_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_style\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBlv_style_prop_t\fP * \fBprops\fP"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "\fBlv_anim_path_cb_t\fP \fBpath_xcb\fP"
.br
.ti -1c
.RI "uint32_t \fBtime\fP"
.br
.ti -1c
.RI "uint32_t \fBdelay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Descriptor for style transitions 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/misc/lv_style\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t lv_style_transition_dsc_t::delay"
Delay before the transition in [ms] 
.SS "\fBlv_anim_path_cb_t\fP lv_style_transition_dsc_t::path_xcb"
A path for the animation\&. 
.SS "const \fBlv_style_prop_t\fP* lv_style_transition_dsc_t::props"
An array with the properties to animate\&. 
.SS "uint32_t lv_style_transition_dsc_t::time"
Duration of the transition in [ms] 
.SS "void* lv_style_transition_dsc_t::user_data"
A custom user data that will be passed to the animation's user_data 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
