.TH "lv_style_const_prop_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_style_const_prop_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_style\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlv_style_prop_t\fP \fBprop\fP"
.br
.ti -1c
.RI "\fBlv_style_value_t\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Descriptor of a constant style property\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/misc/lv_style\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
