.TH "lv_style_value_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lv_style_value_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lv_style\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBnum\fP"
.br
.ti -1c
.RI "const void * \fBptr\fP"
.br
.ti -1c
.RI "lv_color_t \fBcolor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A common type to handle all the property types in the same way\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/Leon/OneDrive/robotics/94517A\-bot\-3\-MCL/include/liblvgl/misc/lv_style\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "lv_color_t lv_style_value_t::color"
Colors 
.SS "int32_t lv_style_value_t::num"
Number integer number (opacity, enums, booleans or "normal" numbers) 
.SS "const void* lv_style_value_t::ptr"
Constant pointers (font, cone text, etc) 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
