.TH "include/liblvgl/core/lv_theme.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/core/lv_theme.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/core/lv_obj\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_lv_theme_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBlv_theme_apply_cb_t\fP) (struct \fB_lv_theme_t\fP *, lv_obj_t *)"
.br
.ti -1c
.RI "typedef struct \fB_lv_theme_t\fP \fBlv_theme_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "lv_theme_t * \fBlv_theme_get_from_obj\fP (lv_obj_t *obj)"
.br
.ti -1c
.RI "void \fBlv_theme_apply\fP (lv_obj_t *obj)"
.br
.ti -1c
.RI "void \fBlv_theme_set_parent\fP (lv_theme_t *new_theme, lv_theme_t *parent)"
.br
.ti -1c
.RI "void \fBlv_theme_set_apply_cb\fP (lv_theme_t *theme, lv_theme_apply_cb_t apply_cb)"
.br
.ti -1c
.RI "const \fBlv_font_t\fP * \fBlv_theme_get_font_small\fP (lv_obj_t *obj)"
.br
.ti -1c
.RI "const \fBlv_font_t\fP * \fBlv_theme_get_font_normal\fP (lv_obj_t *obj)"
.br
.ti -1c
.RI "const \fBlv_font_t\fP * \fBlv_theme_get_font_large\fP (lv_obj_t *obj)"
.br
.ti -1c
.RI "lv_color_t \fBlv_theme_get_color_primary\fP (lv_obj_t *obj)"
.br
.ti -1c
.RI "lv_color_t \fBlv_theme_get_color_secondary\fP (lv_obj_t *obj)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void lv_theme_apply (lv_obj_t * obj)"
Apply the active theme on an object 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP

.SS "lv_color_t lv_theme_get_color_primary (lv_obj_t * obj)"
Get the primary color of the theme 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the color 
.RE
.PP

.SS "lv_color_t lv_theme_get_color_secondary (lv_obj_t * obj)"
Get the secondary color of the theme 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
the color 
.RE
.PP

.SS "const \fBlv_font_t\fP * lv_theme_get_font_large (lv_obj_t * obj)"
Get the subtitle font of the theme 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the font 
.RE
.PP

.SS "const \fBlv_font_t\fP * lv_theme_get_font_normal (lv_obj_t * obj)"
Get the normal font of the theme 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the font 
.RE
.PP

.SS "const \fBlv_font_t\fP * lv_theme_get_font_small (lv_obj_t * obj)"
Get the small font of the theme 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to an object 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the font 
.RE
.PP

.SS "lv_theme_t * lv_theme_get_from_obj (lv_obj_t * obj)"
Get the theme assigned to the display of the object 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP pointer to a theme object 
.RE
.PP
\fBReturns\fP
.RS 4
the theme of the object's display (can be NULL) 
.RE
.PP

.SS "void lv_theme_set_apply_cb (lv_theme_t * theme, lv_theme_apply_cb_t apply_cb)"
Set an apply callback for a theme\&. The apply callback is used to add styles to different objects 
.PP
\fBParameters\fP
.RS 4
\fItheme\fP pointer to theme which callback should be set 
.br
\fIapply_cb\fP pointer to the callback 
.RE
.PP

.SS "void lv_theme_set_parent (lv_theme_t * new_theme, lv_theme_t * parent)"
Set a base theme for a theme\&. The styles from the base them will be added before the styles of the current theme\&. Arbitrary long chain of themes can be created by setting base themes\&. 
.PP
\fBParameters\fP
.RS 4
\fInew_theme\fP pointer to theme which base should be set 
.br
\fIparent\fP pointer to the base theme 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
