.TH "include/liblvgl/extra/themes/lv_themes.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/extra/themes/lv_themes.h
.SH SYNOPSIS
.br
.PP
\fR#include 'default/lv_theme_default\&.h'\fP
.br
\fR#include 'mono/lv_theme_mono\&.h'\fP
.br
\fR#include 'basic/lv_theme_basic\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
