.TH "include/liblvgl/misc/lv_timer.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/misc/lv_timer.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lv_conf_internal\&.h'\fP
.br
\fR#include 'liblvgl/hal/lv_hal_tick\&.h'\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_lv_timer_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV_ATTRIBUTE_TIMER_HANDLER\fP"
.br
.ti -1c
.RI "#define \fBLV_NO_TIMER_READY\fP   0xFFFFFFFF"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBlv_timer_cb_t\fP) (struct \fB_lv_timer_t\fP *)"
.br
.ti -1c
.RI "typedef struct \fB_lv_timer_t\fP \fBlv_timer_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_lv_timer_core_init\fP (void)"
.br
.ti -1c
.RI "\fBlv_timer_t\fP * \fBlv_timer_create_basic\fP (void)"
.br
.ti -1c
.RI "\fBlv_timer_t\fP * \fBlv_timer_create\fP (\fBlv_timer_cb_t\fP timer_xcb, uint32_t period, void *user_data)"
.br
.ti -1c
.RI "void \fBlv_timer_del\fP (\fBlv_timer_t\fP *timer)"
.br
.ti -1c
.RI "void \fBlv_timer_pause\fP (\fBlv_timer_t\fP *timer)"
.br
.ti -1c
.RI "void \fBlv_timer_resume\fP (\fBlv_timer_t\fP *timer)"
.br
.ti -1c
.RI "void \fBlv_timer_set_cb\fP (\fBlv_timer_t\fP *timer, \fBlv_timer_cb_t\fP timer_cb)"
.br
.ti -1c
.RI "void \fBlv_timer_set_period\fP (\fBlv_timer_t\fP *timer, uint32_t period)"
.br
.ti -1c
.RI "void \fBlv_timer_ready\fP (\fBlv_timer_t\fP *timer)"
.br
.ti -1c
.RI "void \fBlv_timer_set_repeat_count\fP (\fBlv_timer_t\fP *timer, int32_t repeat_count)"
.br
.ti -1c
.RI "void \fBlv_timer_reset\fP (\fBlv_timer_t\fP *timer)"
.br
.ti -1c
.RI "void \fBlv_timer_enable\fP (bool en)"
.br
.ti -1c
.RI "uint8_t \fBlv_timer_get_idle\fP (void)"
.br
.ti -1c
.RI "\fBlv_timer_t\fP * \fBlv_timer_get_next\fP (\fBlv_timer_t\fP *timer)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* lv_timer_cb_t) (struct \fB_lv_timer_t\fP *)"
Timers execute this type of functions\&. 
.SS "typedef struct \fB_lv_timer_t\fP \fBlv_timer_t\fP"
Descriptor of a lv_timer 
.SH "Function Documentation"
.PP 
.SS "void _lv_timer_core_init (void )"
Init the lv_timer module 
.SS "\fBlv_timer_t\fP * lv_timer_create (\fBlv_timer_cb_t\fP timer_xcb, uint32_t period, void * user_data)"
Create a new lv_timer 
.PP
\fBParameters\fP
.RS 4
\fItimer_xcb\fP a callback to call periodically\&. (the 'x' in the argument name indicates that it's not a fully generic function because it not follows the \fRfunc_name(object, callback, \&.\&.\&.)\fP convention) 
.br
\fIperiod\fP call period in ms unit 
.br
\fIuser_data\fP custom parameter 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the new timer 
.RE
.PP

.SS "\fBlv_timer_t\fP * lv_timer_create_basic (void )"
Create an "empty" timer\&. It needs to initialized with at least \fR\fBlv_timer_set_cb\fP\fP and \fR\fBlv_timer_set_period\fP\fP 
.PP
\fBReturns\fP
.RS 4
pointer to the created timer 
.RE
.PP

.SS "void lv_timer_del (\fBlv_timer_t\fP * timer)"
Delete a lv_timer 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP pointer to an lv_timer 
.RE
.PP

.SS "void lv_timer_enable (bool en)"
Enable or disable the whole lv_timer handling 
.PP
\fBParameters\fP
.RS 4
\fIen\fP true: lv_timer handling is running, false: lv_timer handling is suspended 
.RE
.PP

.SS "uint8_t lv_timer_get_idle (void )"
Get idle percentage 
.PP
\fBReturns\fP
.RS 4
the lv_timer idle in percentage 
.RE
.PP

.SS "\fBlv_timer_t\fP * lv_timer_get_next (\fBlv_timer_t\fP * timer)"
Iterate through the timers 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP NULL to start iteration or the previous return value to get the next timer 
.RE
.PP
\fBReturns\fP
.RS 4
the next timer or NULL if there is no more timer 
.RE
.PP

.SS "void lv_timer_pause (\fBlv_timer_t\fP * timer)"
Pause/resume a timer\&. 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP pointer to an lv_timer 
.RE
.PP

.SS "void lv_timer_ready (\fBlv_timer_t\fP * timer)"
Make a lv_timer ready\&. It will not wait its period\&. 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP pointer to a lv_timer\&. 
.RE
.PP

.SS "void lv_timer_reset (\fBlv_timer_t\fP * timer)"
Reset a lv_timer\&. It will be called the previously set period milliseconds later\&. 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP pointer to a lv_timer\&. 
.RE
.PP

.SS "void lv_timer_set_cb (\fBlv_timer_t\fP * timer, \fBlv_timer_cb_t\fP timer_cb)"
Set the callback the timer (the function to call periodically) 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP pointer to a timer 
.br
\fItimer_cb\fP the function to call periodically 
.RE
.PP

.SS "void lv_timer_set_period (\fBlv_timer_t\fP * timer, uint32_t period)"
Set new period for a lv_timer 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP pointer to a lv_timer 
.br
\fIperiod\fP the new period 
.RE
.PP

.SS "void lv_timer_set_repeat_count (\fBlv_timer_t\fP * timer, int32_t repeat_count)"
Set the number of times a timer will repeat\&. 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP pointer to a lv_timer\&. 
.br
\fIrepeat_count\fP -1 : infinity; 0 : stop ; n>0: residual times 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
