.TH "include/liblvgl/misc/lv_txt_ap.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/misc/lv_txt_ap.h
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br
\fR#include 'lv_txt\&.h'\fP
.br
\fR#include 'liblvgl/draw/lv_draw\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
