.TH "include/liblvgl/misc/lv_utils.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/misc/lv_utils.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fB_lv_utils_bsearch\fP (const void *key, const void *base, uint32_t n, uint32_t size, int32_t(*cmp)(const void *pRef, const void *pElement))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * _lv_utils_bsearch (const void * key, const void * base, uint32_t n, uint32_t size, int32_t(* cmp )(const void *pRef, const void *pElement))"
Searches base[0] to base[n - 1] for an item that matches *key\&.

.PP
\fBNote\fP
.RS 4
The function cmp must return negative if it's first argument (the search key) is less that it's second (a table entry), zero if equal, and positive if greater\&.

.PP
Items in the array must be in ascending order\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIkey\fP Pointer to item being searched for 
.br
\fIbase\fP Pointer to first element to search 
.br
\fIn\fP Number of elements 
.br
\fIsize\fP Size of each element 
.br
\fIcmp\fP Pointer to comparison function (see #unicode_list_compare as a comparison function example)
.RE
.PP
\fBReturns\fP
.RS 4
a pointer to a matching item, or NULL if none exists\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
