.TH "include/liblvgl/extra/widgets/win/lv_win.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/extra/widgets/win/lv_win.h
.SH SYNOPSIS
.br
.PP
\fR#include 'liblvgl/lvgl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlv_win_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "lv_obj_t * \fBlv_win_create\fP (lv_obj_t *parent, lv_coord_t header_height)"
.br
.ti -1c
.RI "lv_obj_t * \fBlv_win_add_title\fP (lv_obj_t *win, const char *txt)"
.br
.ti -1c
.RI "lv_obj_t * \fBlv_win_add_btn\fP (lv_obj_t *win, const void *icon, lv_coord_t btn_w)"
.br
.ti -1c
.RI "lv_obj_t * \fBlv_win_get_header\fP (lv_obj_t *win)"
.br
.ti -1c
.RI "lv_obj_t * \fBlv_win_get_content\fP (lv_obj_t *win)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBlv_obj_class_t\fP \fBlv_win_class\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
