.TH "include/liblvgl/extra/widgets/lv_widgets.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/liblvgl/extra/widgets/lv_widgets.h
.SH SYNOPSIS
.br
.PP
\fR#include 'animimg/lv_animimg\&.h'\fP
.br
\fR#include 'calendar/lv_calendar\&.h'\fP
.br
\fR#include 'calendar/lv_calendar_header_arrow\&.h'\fP
.br
\fR#include 'calendar/lv_calendar_header_dropdown\&.h'\fP
.br
\fR#include 'chart/lv_chart\&.h'\fP
.br
\fR#include 'keyboard/lv_keyboard\&.h'\fP
.br
\fR#include 'list/lv_list\&.h'\fP
.br
\fR#include 'menu/lv_menu\&.h'\fP
.br
\fR#include 'msgbox/lv_msgbox\&.h'\fP
.br
\fR#include 'meter/lv_meter\&.h'\fP
.br
\fR#include 'spinbox/lv_spinbox\&.h'\fP
.br
\fR#include 'spinner/lv_spinner\&.h'\fP
.br
\fR#include 'tabview/lv_tabview\&.h'\fP
.br
\fR#include 'tileview/lv_tileview\&.h'\fP
.br
\fR#include 'win/lv_win\&.h'\fP
.br
\fR#include 'colorwheel/lv_colorwheel\&.h'\fP
.br
\fR#include 'led/lv_led\&.h'\fP
.br
\fR#include 'imgbtn/lv_imgbtn\&.h'\fP
.br
\fR#include 'span/lv_span\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
