.TH "include/pros/misc.hpp" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/misc.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'pros/misc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::v5::Controller\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpros\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBpros::battery::get_capacity\fP (void)"
.br
.ti -1c
.RI "int32_t \fBpros::battery::get_current\fP (void)"
.br
.ti -1c
.RI "double \fBpros::battery::get_temperature\fP (void)"
.br
.ti -1c
.RI "int32_t \fBpros::battery::get_voltage\fP (void)"
.br
.ti -1c
.RI "std::uint8_t \fBpros::competition::get_status\fP (void)"
.br
.ti -1c
.RI "std::uint8_t \fBpros::competition::is_autonomous\fP (void)"
.br
.ti -1c
.RI "std::uint8_t \fBpros::competition::is_connected\fP (void)"
.br
.ti -1c
.RI "std::uint8_t \fBpros::competition::is_disabled\fP (void)"
.br
.ti -1c
.RI "std::uint8_t \fBpros::competition::is_field_control\fP (void)"
.br
.ti -1c
.RI "std::uint8_t \fBpros::competition::is_competition_switch\fP (void)"
.br
.ti -1c
.RI "std::int32_t \fBpros::usd::is_installed\fP (void)"
.br
.ti -1c
.RI "std::int32_t \fBpros::usd::list_files\fP (const char *path, char *buffer, std::int32_t len)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains prototypes for miscellaneous functions pertaining to the controller, battery, and competition control\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
\fBCopyright\fP
.RS 4
(c) 2017-2023, Purdue University ACM SIGBots\&. All rights reservered\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Function Documentation"
.PP 
.SS "std::uint8_t pros::competition::get_status (void )"
Get the current status of the competition control\&.

.PP
\fBReturns\fP
.RS 4
The competition control status as a mask of bits with COMPETITION_{ENABLED,AUTONOMOUS,CONNECTED}\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
void status_display_task(){
    if(!is_connected()) {
     pros::lcd::print(0, "V5 Brain is not connected!");
 }
 if(is_autonomous()) {
     pros::lcd::print(0, "V5 Brain is in autonomous mode!");
 }
 if(!is_disabled()) {
     pros::lcd::print(0, "V5 Brain is disabled!");
 }

.fi
.PP
 
.SS "std::int32_t pros::usd::is_installed (void )"
Checks if the SD card is installed\&.

.PP
\fBReturns\fP
.RS 4
1 if the SD card is installed, 0 otherwise
.RE
.PP
\fBExample\fP 
.PP
.nf
void opcontrol() {
  printf("%i", is_installed());
}

.fi
.PP
 
.SS "std::int32_t pros::usd::list_files (const char * path, char * buffer, std::int32_t len)"
Lists the files in a directory specified by the path Puts the list of file names (NOT DIRECTORIES) into the buffer seperated by newlines

.PP
This function uses the following values of errno when an error state is reached:

.PP
EIO - Hard error occured in the low level disk I/O layer EINVAL - file or directory is invalid, or length is invalid EBUSY - THe physical drinve cannot work ENOENT - cannot find the path or file EINVAL - the path name format is invalid EACCES - Access denied or directory full EEXIST - Access denied EROFS - SD card is write protected ENXIO - drive number is invalid or not a FAT32 drive ENOBUFS - drive has no work area ENFILE - too many open files

.PP
\fBNote\fP
.RS 4
use a path of "\\" to list the files in the main directory NOT "/usd/" DO NOT PREPEND YOUR PATHS WITH "/usd/"\\return 1 on success or PROS_ERR on failure setting errno\\b Example@code void opcontrol() {    char* test = (char*) malloc(128); pros::usd::list_files("/", test, 128); pros::delay(200); printf("s
.br
", test); //Prints the file names in the root directory seperated by newlines pros::delay(100); pros::list_files("/test", test, 128); pros::delay(200); printf("s
.br
", test); //Prints the names of files in the folder named test seperated by newlines pros::delay(100); }  
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
