.TH "motor_pid_full_s_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
motor_pid_full_s_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <motors\&.h>\fP
.SH "Detailed Description"
.PP 
Holds the information about a Motor's position or velocity PID controls\&.

.PP
These values are in 4\&.4 format, meaning that a value of 0x20 represents 2\&.0, 0x21 represents 2\&.0625, 0x22 represents 2\&.125, etc\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
