.TH "include/pros/motors.h" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/motors.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmotor_pid_full_s\fP"
.br
.ti -1c
.RI "struct \fBmotor_pid_s\fP"
.br
.in -1c
.SS "Functions"

.PP
.RI "\fBMotor movement functions\fP"
.br
These functions allow programmers to make motors move 
.PP
.in +1c
.in +1c
.ti -1c
.RI "int32_t \fBmotor_move\fP (int8_t port, int32_t voltage)"
.br
.ti -1c
.RI "int32_t \fBmotor_brake\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_move_absolute\fP (int8_t port, double position, const int32_t velocity)"
.br
.ti -1c
.RI "int32_t \fBmotor_move_relative\fP (int8_t port, double position, const int32_t velocity)"
.br
.ti -1c
.RI "int32_t \fBmotor_move_velocity\fP (int8_t port, const int32_t velocity)"
.br
.ti -1c
.RI "int32_t \fBmotor_move_voltage\fP (int8_t port, const int32_t voltage)"
.br
.ti -1c
.RI "int32_t \fBmotor_modify_profiled_velocity\fP (int8_t port, const int32_t velocity)"
.br
.ti -1c
.RI "double \fBmotor_get_target_position\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_target_velocity\fP (int8_t port)"
.br
.in -1c
.in -1c
.SS "Motor telemetry functions"
These functions allow programmers to collect telemetry from motors 
.in +1c
.ti -1c
.RI "enum \fBmotor_fault_e\fP { \fBE_MOTOR_FAULT_NO_FAULTS\fP = 0x00, \fBE_MOTOR_FAULT_MOTOR_OVER_TEMP\fP = 0x01, \fBE_MOTOR_FAULT_DRIVER_FAULT\fP = 0x02, \fBE_MOTOR_FAULT_OVER_CURRENT\fP = 0x04, \fBE_MOTOR_FAULT_DRV_OVER_CURRENT\fP = 0x08 }"
.br
.ti -1c
.RI "enum \fBmotor_flag_e\fP { \fBE_MOTOR_FLAGS_NONE\fP = 0x00, \fBE_MOTOR_FLAGS_BUSY\fP = 0x01, \fBE_MOTOR_FLAGS_ZERO_VELOCITY\fP = 0x02, \fBE_MOTOR_FLAGS_ZERO_POSITION\fP = 0x04 }"
.br
.ti -1c
.RI "typedef enum \fBmotor_fault_e\fP \fBmotor_fault_e_t\fP"
.br
.ti -1c
.RI "typedef enum \fBmotor_flag_e\fP \fBmotor_flag_e_t\fP"
.br
.ti -1c
.RI "double \fBmotor_get_actual_velocity\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_current_draw\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_direction\fP (int8_t port)"
.br
.ti -1c
.RI "double \fBmotor_get_efficiency\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_is_over_current\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_is_over_temp\fP (int8_t port)"
.br
.ti -1c
.RI "uint32_t \fBmotor_get_faults\fP (int8_t port)"
.br
.ti -1c
.RI "uint32_t \fBmotor_get_flags\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_raw_position\fP (int8_t port, uint32_t *const timestamp)"
.br
.ti -1c
.RI "double \fBmotor_get_position\fP (int8_t port)"
.br
.ti -1c
.RI "double \fBmotor_get_power\fP (int8_t port)"
.br
.ti -1c
.RI "double \fBmotor_get_temperature\fP (int8_t port)"
.br
.ti -1c
.RI "double \fBmotor_get_torque\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_voltage\fP (int8_t port)"
.br
.in -1c
.SS "Motor configuration functions"
These functions allow programmers to configure the behavior of motors 
.in +1c
.ti -1c
.RI "enum \fBmotor_brake_mode_e\fP { \fBE_MOTOR_BRAKE_COAST\fP = 0, \fBE_MOTOR_BRAKE_BRAKE\fP = 1, \fBE_MOTOR_BRAKE_HOLD\fP = 2, \fBE_MOTOR_BRAKE_INVALID\fP = INT32_MAX }"
.br
.ti -1c
.RI "enum \fBmotor_encoder_units_e\fP { \fBE_MOTOR_ENCODER_DEGREES\fP = 0, \fBE_MOTOR_ENCODER_ROTATIONS\fP = 1, \fBE_MOTOR_ENCODER_COUNTS\fP = 2, \fBE_MOTOR_ENCODER_INVALID\fP = INT32_MAX }"
.br
.ti -1c
.RI "enum \fBmotor_gearset_e\fP { \fBE_MOTOR_GEARSET_36\fP = 0, \fBE_MOTOR_GEAR_RED\fP = E_MOTOR_GEARSET_36, \fBE_MOTOR_GEAR_100\fP = E_MOTOR_GEARSET_36, \fBE_MOTOR_GEARSET_18\fP = 1, \fBE_MOTOR_GEAR_GREEN\fP = E_MOTOR_GEARSET_18, \fBE_MOTOR_GEAR_200\fP = E_MOTOR_GEARSET_18, \fBE_MOTOR_GEARSET_06\fP = 2, \fBE_MOTOR_GEAR_BLUE\fP = E_MOTOR_GEARSET_06, \fBE_MOTOR_GEAR_600\fP = E_MOTOR_GEARSET_06, \fBE_MOTOR_GEARSET_INVALID\fP = INT32_MAX }"
.br
.ti -1c
.RI "typedef enum \fBmotor_brake_mode_e\fP \fBmotor_brake_mode_e_t\fP"
.br
.ti -1c
.RI "typedef enum \fBmotor_encoder_units_e\fP \fBmotor_encoder_units_e_t\fP"
.br
.ti -1c
.RI "typedef enum motor_gearset_e \fBmotor_gearset_e_t\fP"
.br
.ti -1c
.RI "typedef struct \fBmotor_pid_full_s\fP \fBmotor_pid_full_s_t\fP"
.br
.ti -1c
.RI "typedef struct \fBmotor_pid_s\fP \fBmotor_pid_s_t\fP"
.br
.ti -1c
.RI "int32_t \fBmotor_set_zero_position\fP (int8_t port, const double position)"
.br
.ti -1c
.RI "int32_t \fBmotor_tare_position\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_set_brake_mode\fP (int8_t port, const motor_brake_mode_e_t mode)"
.br
.ti -1c
.RI "int32_t \fBmotor_set_current_limit\fP (int8_t port, const int32_t limit)"
.br
.ti -1c
.RI "int32_t \fBmotor_set_encoder_units\fP (int8_t port, const motor_encoder_units_e_t units)"
.br
.ti -1c
.RI "int32_t \fBmotor_set_gearing\fP (int8_t port, const motor_gearset_e_t gearset)"
.br
.ti -1c
.RI "int32_t \fBmotor_set_voltage_limit\fP (int8_t port, const int32_t limit)"
.br
.ti -1c
.RI "motor_brake_mode_e_t \fBmotor_get_brake_mode\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_current_limit\fP (int8_t port)"
.br
.ti -1c
.RI "motor_encoder_units_e_t \fBmotor_get_encoder_units\fP (int8_t port)"
.br
.ti -1c
.RI "motor_gearset_e_t \fBmotor_get_gearing\fP (int8_t port)"
.br
.ti -1c
.RI "int32_t \fBmotor_get_voltage_limit\fP (int8_t port)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains prototypes for the V5 Motor-related functions\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
\fBCopyright\fP
.RS 4
(c) 2017-2023, Purdue University ACM SIGBots\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
