.TH "include/pros/motor_group.hpp" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/motor_group.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include 'pros/abstract_motor\&.hpp'\fP
.br
\fR#include 'pros/colors\&.hpp'\fP
.br
\fR#include 'pros/device\&.hpp'\fP
.br
\fR#include 'pros/motors\&.h'\fP
.br
\fR#include 'pros/motors\&.hpp'\fP
.br
\fR#include 'rtos\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpros::v5::MotorGroup\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpros\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains prototypes for the V5 Motor-related functions\&.

.PP
Visit https://pros.cs.purdue.edu/v5/tutorials/topical/motors.html to learn more\&.

.PP
This file should not be modified by users, since it gets replaced whenever a kernel upgrade occurs\&.

.PP
\fBCopyright\fP
.RS 4
(c) 2017-2023, Purdue University ACM SIGBots\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
