.TH "okapi::ControllerInput< T >" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ControllerInput< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual T \fBcontrollerGet\fP ()=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> virtual T \fBokapi::ControllerInput\fP< T >::controllerGet ()\fR [pure virtual]\fP"
Get the sensor value for use in a control loop\&. This method might be automatically called in another thread by the controller\&.

.PP
\fBReturns\fP
.RS 4
the current sensor value, or \fRPROS_ERR\fP on a failure\&. 
.RE
.PP

.PP
Implemented in \fBokapi::AbstractButton\fP, \fBokapi::ADIEncoder\fP, \fBokapi::ADIGyro\fP, \fBokapi::ADIUltrasonic\fP, \fBokapi::DistanceSensor\fP, \fBokapi::FilteredControllerInput< InputType, FilterType >\fP, \fBokapi::IMU\fP, \fBokapi::IntegratedEncoder\fP, \fBokapi::OffsetableControllerInput\fP, \fBokapi::OpticalSensor\fP, \fBokapi::Potentiometer\fP, and \fBokapi::RotationSensor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
