.TH "okapi::OdomChassisController" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::OdomChassisController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::ChassisController\fP\&.
.PP
Inherited by \fBokapi::DefaultOdomChassisController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOdomChassisController\fP (\fBTimeUtil\fP itimeUtil, std::shared_ptr< \fBOdometry\fP > iodometry, const StateMode &imode=StateMode::FRAME_TRANSFORMATION, const QLength &imoveThreshold=0_mm, const QAngle &iturnThreshold=0_deg, std::shared_ptr< \fBLogger\fP > ilogger=\fBLogger::getDefaultLogger\fP())"
.br
.ti -1c
.RI "\fBOdomChassisController\fP (const OdomChassisController &)=delete"
.br
.ti -1c
.RI "\fBOdomChassisController\fP (OdomChassisController &&other)=delete"
.br
.ti -1c
.RI "\fBOdomChassisController\fP & \fBoperator=\fP (const \fBOdomChassisController\fP &other)=delete"
.br
.ti -1c
.RI "\fBOdomChassisController\fP & \fBoperator=\fP (\fBOdomChassisController\fP &&other)=delete"
.br
.ti -1c
.RI "virtual void \fBdriveToPoint\fP (const \fBPoint\fP &ipoint, bool ibackwards=false, const QLength &ioffset=0_mm)=0"
.br
.ti -1c
.RI "virtual void \fBturnToPoint\fP (const \fBPoint\fP &ipoint)=0"
.br
.ti -1c
.RI "virtual void \fBturnToAngle\fP (const QAngle &iangle)=0"
.br
.ti -1c
.RI "virtual \fBOdomState\fP \fBgetState\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetState\fP (const \fBOdomState\fP &istate)"
.br
.ti -1c
.RI "void \fBsetDefaultStateMode\fP (const StateMode &imode)"
.br
.ti -1c
.RI "virtual void \fBsetMoveThreshold\fP (const QLength &imoveThreshold)"
.br
.ti -1c
.RI "virtual void \fBsetTurnThreshold\fP (const QAngle &iturnTreshold)"
.br
.ti -1c
.RI "virtual QLength \fBgetMoveThreshold\fP () const"
.br
.ti -1c
.RI "virtual QAngle \fBgetTurnThreshold\fP () const"
.br
.ti -1c
.RI "void \fBstartOdomThread\fP ()"
.br
.ti -1c
.RI "\fBCrossplatformThread\fP * \fBgetOdomThread\fP () const"
.br
.ti -1c
.RI "std::shared_ptr< \fBOdometry\fP > \fBgetOdometry\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ChassisController\fP
.in +1c
.ti -1c
.RI "\fBChassisController\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBmoveDistance\fP (QLength itarget)=0"
.br
.ti -1c
.RI "virtual void \fBmoveRaw\fP (double itarget)=0"
.br
.ti -1c
.RI "virtual void \fBmoveDistanceAsync\fP (QLength itarget)=0"
.br
.ti -1c
.RI "virtual void \fBmoveRawAsync\fP (double itarget)=0"
.br
.ti -1c
.RI "virtual void \fBturnAngle\fP (QAngle idegTarget)=0"
.br
.ti -1c
.RI "virtual void \fBturnRaw\fP (double idegTarget)=0"
.br
.ti -1c
.RI "virtual void \fBturnAngleAsync\fP (QAngle idegTarget)=0"
.br
.ti -1c
.RI "virtual void \fBturnRawAsync\fP (double idegTarget)=0"
.br
.ti -1c
.RI "virtual void \fBsetTurnsMirrored\fP (bool ishouldMirror)=0"
.br
.ti -1c
.RI "virtual bool \fBisSettled\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBwaitUntilSettled\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBstop\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBsetMaxVelocity\fP (double imaxVelocity)=0"
.br
.ti -1c
.RI "virtual double \fBgetMaxVelocity\fP () const =0"
.br
.ti -1c
.RI "virtual \fBChassisScales\fP \fBgetChassisScales\fP () const =0"
.br
.ti -1c
.RI "virtual \fBAbstractMotor::GearsetRatioPair\fP \fBgetGearsetRatioPair\fP () const =0"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBChassisModel\fP > \fBgetModel\fP ()=0"
.br
.ti -1c
.RI "virtual \fBChassisModel\fP & \fBmodel\fP ()=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBloop\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBtrampoline\fP (void *context)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBLogger\fP > \fBlogger\fP"
.br
.ti -1c
.RI "\fBTimeUtil\fP \fBtimeUtil\fP"
.br
.ti -1c
.RI "QLength \fBmoveThreshold\fP"
.br
.ti -1c
.RI "QAngle \fBturnThreshold\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBOdometry\fP > \fBodom\fP"
.br
.ti -1c
.RI "\fBCrossplatformThread\fP * \fBodomTask\fP {nullptr}"
.br
.ti -1c
.RI "std::atomic_bool \fBdtorCalled\fP {false}"
.br
.ti -1c
.RI "StateMode \fBdefaultStateMode\fP {StateMode::FRAME_TRANSFORMATION}"
.br
.ti -1c
.RI "std::atomic_bool \fBodomTaskRunning\fP {false}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::OdomChassisController::OdomChassisController (\fBTimeUtil\fP itimeUtil, std::shared_ptr< \fBOdometry\fP > iodometry, const StateMode & imode = \fRStateMode::FRAME_TRANSFORMATION\fP, const QLength & imoveThreshold = \fR0_mm\fP, const QAngle & iturnThreshold = \fR0_deg\fP, std::shared_ptr< \fBLogger\fP > ilogger = \fR\fBLogger::getDefaultLogger\fP()\fP)"
\fBOdometry\fP based chassis controller\&. Starts task at the default for odometry when constructed, which calls \fR\fBOdometry::step\fP\fP every \fR10ms\fP\&. The default StateMode is \fRStateMode::FRAME_TRANSFORMATION\fP\&.

.PP
Moves the robot around in the odom frame\&. Instead of telling the robot to drive forward or turn some amount, you instead tell it to drive to a specific point on the field or turn to a specific angle relative to its starting position\&.

.PP
\fBParameters\fP
.RS 4
\fIitimeUtil\fP The \fBTimeUtil\fP\&. 
.br
\fIiodometry\fP The \fBOdometry\fP instance to run in a new task\&. 
.br
\fIimode\fP The new default StateMode used to interpret target points and query the \fBOdometry\fP state\&. 
.br
\fIimoveThreshold\fP minimum length movement (smaller movements will be skipped) 
.br
\fIiturnThreshold\fP minimum angle turn (smaller turns will be skipped) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual void okapi::OdomChassisController::driveToPoint (const \fBPoint\fP & ipoint, bool ibackwards = \fRfalse\fP, const QLength & ioffset = \fR0_mm\fP)\fR [pure virtual]\fP"
Drives the robot straight to a point in the odom frame\&.

.PP
\fBParameters\fP
.RS 4
\fIipoint\fP The target point to navigate to\&. 
.br
\fIibackwards\fP Whether to drive to the target point backwards\&. 
.br
\fIioffset\fP An offset from the target point in the direction pointing towards the robot\&. The robot will stop this far away from the target point\&. 
.RE
.PP

.PP
Implemented in \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual QLength okapi::OdomChassisController::getMoveThreshold () const\fR [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The current move threshold\&. 
.RE
.PP

.SS "std::shared_ptr< \fBOdometry\fP > okapi::OdomChassisController::getOdometry ()"

.PP
\fBReturns\fP
.RS 4
The internal odometry\&. 
.RE
.PP

.SS "\fBCrossplatformThread\fP * okapi::OdomChassisController::getOdomThread () const"

.PP
\fBReturns\fP
.RS 4
The underlying thread handle\&. 
.RE
.PP

.SS "virtual \fBOdomState\fP okapi::OdomChassisController::getState () const\fR [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The current state\&. 
.RE
.PP

.SS "virtual QAngle okapi::OdomChassisController::getTurnThreshold () const\fR [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The current turn threshold\&. 
.RE
.PP

.SS "void okapi::OdomChassisController::setDefaultStateMode (const StateMode & imode)"
Sets a default StateMode that will be used to interpret target points and query the \fBOdometry\fP state\&.

.PP
\fBParameters\fP
.RS 4
\fIimode\fP The new default StateMode\&. 
.RE
.PP

.SS "virtual void okapi::OdomChassisController::setMoveThreshold (const QLength & imoveThreshold)\fR [virtual]\fP"
Set a new move threshold\&. Any requested movements smaller than this threshold will be skipped\&.

.PP
\fBParameters\fP
.RS 4
\fIimoveThreshold\fP new move threshold 
.RE
.PP

.SS "virtual void okapi::OdomChassisController::setState (const \fBOdomState\fP & istate)\fR [virtual]\fP"
Set a new state to be the current state\&. The default StateMode is \fRStateMode::FRAME_TRANSFORMATION\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIistate\fP The new state in the given format\&. 
.br
\fIimode\fP The mode to treat the input state as\&. 
.RE
.PP

.SS "virtual void okapi::OdomChassisController::setTurnThreshold (const QAngle & iturnTreshold)\fR [virtual]\fP"
Set a new turn threshold\&. Any requested turns smaller than this threshold will be skipped\&.

.PP
\fBParameters\fP
.RS 4
\fIiturnTreshold\fP new turn threshold 
.RE
.PP

.SS "void okapi::OdomChassisController::startOdomThread ()"
Starts the internal odometry thread\&. This should not be called by normal users\&. 
.SS "virtual void okapi::OdomChassisController::turnToAngle (const QAngle & iangle)\fR [pure virtual]\fP"
Turns the robot to face an angle in the odom frame\&.

.PP
\fBParameters\fP
.RS 4
\fIiangle\fP The angle to turn to\&. 
.RE
.PP

.PP
Implemented in \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::OdomChassisController::turnToPoint (const \fBPoint\fP & ipoint)\fR [pure virtual]\fP"
Turns the robot to face a point in the odom frame\&.

.PP
\fBParameters\fP
.RS 4
\fIipoint\fP The target point to turn to face\&. 
.RE
.PP

.PP
Implemented in \fBokapi::DefaultOdomChassisController\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
