.TH "okapi::AsyncMotionProfileControllerBuilder" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::AsyncMotionProfileControllerBuilder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP (const std::shared_ptr< \fBLogger\fP > &ilogger=\fBLogger::getDefaultLogger\fP())"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBwithOutput\fP (const \fBMotor\fP &ioutput, const QLength &idiameter, const \fBAbstractMotor::GearsetRatioPair\fP &ipair)"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBwithOutput\fP (const \fBMotorGroup\fP &ioutput, const QLength &idiameter, const \fBAbstractMotor::GearsetRatioPair\fP &ipair)"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBwithOutput\fP (const std::shared_ptr< \fBControllerOutput\fP< double > > &ioutput, const QLength &idiameter, const \fBAbstractMotor::GearsetRatioPair\fP &ipair)"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBwithOutput\fP (\fBChassisController\fP &icontroller)"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBwithOutput\fP (const std::shared_ptr< \fBChassisController\fP > &icontroller)"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBwithOutput\fP (const std::shared_ptr< \fBChassisModel\fP > &imodel, const \fBChassisScales\fP &iscales, const \fBAbstractMotor::GearsetRatioPair\fP &ipair)"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBwithLimits\fP (const \fBPathfinderLimits\fP &ilimits)"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBwithTimeUtilFactory\fP (const \fBTimeUtilFactory\fP &itimeUtilFactory)"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBwithLogger\fP (const std::shared_ptr< \fBLogger\fP > &ilogger)"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBparentedToCurrentTask\fP ()"
.br
.ti -1c
.RI "\fBAsyncMotionProfileControllerBuilder\fP & \fBnotParentedToCurrentTask\fP ()"
.br
.ti -1c
.RI "std::shared_ptr< \fBAsyncLinearMotionProfileController\fP > \fBbuildLinearMotionProfileController\fP ()"
.br
.ti -1c
.RI "std::shared_ptr< \fBAsyncMotionProfileController\fP > \fBbuildMotionProfileController\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::AsyncMotionProfileControllerBuilder::AsyncMotionProfileControllerBuilder (const std::shared_ptr< \fBLogger\fP > & ilogger = \fR\fBLogger::getDefaultLogger\fP()\fP)\fR [explicit]\fP"
A builder that creates async motion profile controllers\&. Use this to build an \fBAsyncMotionProfileController\fP or an \fBAsyncLinearMotionProfileController\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIilogger\fP The logger this instance will log to\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBAsyncLinearMotionProfileController\fP > okapi::AsyncMotionProfileControllerBuilder::buildLinearMotionProfileController ()"
Builds the \fBAsyncLinearMotionProfileController\fP\&.

.PP
\fBReturns\fP
.RS 4
A fully built \fBAsyncLinearMotionProfileController\fP\&. 
.RE
.PP

.SS "std::shared_ptr< \fBAsyncMotionProfileController\fP > okapi::AsyncMotionProfileControllerBuilder::buildMotionProfileController ()"
Builds the \fBAsyncMotionProfileController\fP\&.

.PP
\fBReturns\fP
.RS 4
A fully built \fBAsyncMotionProfileController\fP\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::notParentedToCurrentTask ()"
Prevents parenting the internal tasks started by this builder to the current task, meaning they will not be deleted once the current task is deleted\&. This can cause runaway tasks, but is sometimes the desired behavior (e\&.x\&., if you want to use this builder once in \fR\fBautonomous\fP\fP and then again in \fRopcontrol\fP)\&.

.PP
Read more about this in the [builders and tasks tutorial] (docs/tutorials/concepts/builders-and-tasks\&.md)\&.

.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::parentedToCurrentTask ()"
Parents the internal tasks started by this builder to the current task, meaning they will be deleted once the current task is deleted\&. The \fRinitialize\fP and \fRcompetition_initialize\fP tasks are never parented to\&. This is the default behavior\&.

.PP
Read more about this in the [builders and tasks tutorial] (docs/tutorials/concepts/builders-and-tasks\&.md)\&.

.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::withLimits (const \fBPathfinderLimits\fP & ilimits)"
Sets the limits\&.

.PP
\fBParameters\fP
.RS 4
\fIilimits\fP The limits\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::withLogger (const std::shared_ptr< \fBLogger\fP > & ilogger)"
Sets the logger\&.

.PP
\fBParameters\fP
.RS 4
\fIilogger\fP The logger\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::withOutput (\fBChassisController\fP & icontroller)"
Sets the output\&. This must be used with \fBbuildMotionProfileController()\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIicontroller\fP The chassis controller to use\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::withOutput (const \fBMotor\fP & ioutput, const QLength & idiameter, const \fBAbstractMotor::GearsetRatioPair\fP & ipair)"
Sets the output\&. This must be used with \fBbuildLinearMotionProfileController()\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIioutput\fP The output\&. 
.br
\fIidiameter\fP The diameter of the mechanical part the motor spins\&. 
.br
\fIipair\fP The gearset\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::withOutput (const \fBMotorGroup\fP & ioutput, const QLength & idiameter, const \fBAbstractMotor::GearsetRatioPair\fP & ipair)"
Sets the output\&. This must be used with \fBbuildLinearMotionProfileController()\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIioutput\fP The output\&. 
.br
\fIidiameter\fP The diameter of the mechanical part the motor spins\&. 
.br
\fIipair\fP The gearset\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::withOutput (const std::shared_ptr< \fBChassisController\fP > & icontroller)"
Sets the output\&. This must be used with \fBbuildMotionProfileController()\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIicontroller\fP The chassis controller to use\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::withOutput (const std::shared_ptr< \fBChassisModel\fP > & imodel, const \fBChassisScales\fP & iscales, const \fBAbstractMotor::GearsetRatioPair\fP & ipair)"
Sets the output\&. This must be used with \fBbuildMotionProfileController()\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIimodel\fP The chassis model to use\&. 
.br
\fIiscales\fP The chassis dimensions\&. 
.br
\fIipair\fP The gearset\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::withOutput (const std::shared_ptr< \fBControllerOutput\fP< double > > & ioutput, const QLength & idiameter, const \fBAbstractMotor::GearsetRatioPair\fP & ipair)"
Sets the output\&. This must be used with \fBbuildLinearMotionProfileController()\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIioutput\fP The output\&. 
.br
\fIidiameter\fP The diameter of the mechanical part the motor spins\&. 
.br
\fIipair\fP The gearset\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBAsyncMotionProfileControllerBuilder\fP & okapi::AsyncMotionProfileControllerBuilder::withTimeUtilFactory (const \fBTimeUtilFactory\fP & itimeUtilFactory)"
Sets the \fBTimeUtilFactory\fP used when building the controller\&. The default is the static \fBTimeUtilFactory\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIitimeUtilFactory\fP The \fBTimeUtilFactory\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
