.TH "okapi::PIDTuner" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::PIDTuner
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBOutput\fP"
.br
.ti -1c
.RI "struct \fBParticle\fP"
.br
.ti -1c
.RI "struct \fBParticleSet\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPIDTuner\fP (const std::shared_ptr< \fBControllerInput\fP< double > > &iinput, const std::shared_ptr< \fBControllerOutput\fP< double > > &ioutput, const \fBTimeUtil\fP &itimeUtil, QTime itimeout, std::int32_t igoal, double ikPMin, double ikPMax, double ikIMin, double ikIMax, double ikDMin, double ikDMax, std::size_t inumIterations=5, std::size_t inumParticles=16, double ikSettle=1, double ikITAE=2, const std::shared_ptr< \fBLogger\fP > &ilogger=\fBLogger::getDefaultLogger\fP())"
.br
.ti -1c
.RI "virtual \fBOutput\fP \fBautotune\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBLogger\fP > \fBlogger\fP"
.br
.ti -1c
.RI "\fBTimeUtil\fP \fBtimeUtil\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBControllerInput\fP< double > > \fBinput\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBControllerOutput\fP< double > > \fBoutput\fP"
.br
.ti -1c
.RI "const QTime \fBtimeout\fP"
.br
.ti -1c
.RI "const std::int32_t \fBgoal\fP"
.br
.ti -1c
.RI "const double \fBkPMin\fP"
.br
.ti -1c
.RI "const double \fBkPMax\fP"
.br
.ti -1c
.RI "const double \fBkIMin\fP"
.br
.ti -1c
.RI "const double \fBkIMax\fP"
.br
.ti -1c
.RI "const double \fBkDMin\fP"
.br
.ti -1c
.RI "const double \fBkDMax\fP"
.br
.ti -1c
.RI "const std::size_t \fBnumIterations\fP"
.br
.ti -1c
.RI "const std::size_t \fBnumParticles\fP"
.br
.ti -1c
.RI "const double \fBkSettle\fP"
.br
.ti -1c
.RI "const double \fBkITAE\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static constexpr double \fBinertia\fP = 0\&.5"
.br
.ti -1c
.RI "static constexpr double \fBconfSelf\fP = 1\&.1"
.br
.ti -1c
.RI "static constexpr double \fBconfSwarm\fP = 1\&.2"
.br
.ti -1c
.RI "static constexpr int \fBincrement\fP = 5"
.br
.ti -1c
.RI "static constexpr int \fBdivisor\fP = 5"
.br
.ti -1c
.RI "static constexpr QTime \fBloopDelta\fP = 10_ms"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
