.TH "okapi::ThreeEncoderSkidSteerModel" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ThreeEncoderSkidSteerModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::SkidSteerModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreeEncoderSkidSteerModel\fP (std::shared_ptr< \fBAbstractMotor\fP > ileftSideMotor, std::shared_ptr< \fBAbstractMotor\fP > irightSideMotor, std::shared_ptr< \fBContinuousRotarySensor\fP > ileftEnc, std::shared_ptr< \fBContinuousRotarySensor\fP > irightEnc, std::shared_ptr< \fBContinuousRotarySensor\fP > imiddleEnc, double imaxVelocity, double imaxVoltage)"
.br
.ti -1c
.RI "std::valarray< std::int32_t > \fBgetSensorVals\fP () const override"
.br
.ti -1c
.RI "void \fBresetSensors\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBokapi::SkidSteerModel\fP
.in +1c
.ti -1c
.RI "\fBSkidSteerModel\fP (std::shared_ptr< \fBAbstractMotor\fP > ileftSideMotor, std::shared_ptr< \fBAbstractMotor\fP > irightSideMotor, std::shared_ptr< \fBContinuousRotarySensor\fP > ileftEnc, std::shared_ptr< \fBContinuousRotarySensor\fP > irightEnc, double imaxVelocity, double imaxVoltage)"
.br
.ti -1c
.RI "void \fBforward\fP (double ispeed) override"
.br
.ti -1c
.RI "void \fBdriveVector\fP (double iySpeed, double izRotation) override"
.br
.ti -1c
.RI "void \fBdriveVectorVoltage\fP (double iforwardSpeed, double iyaw) override"
.br
.ti -1c
.RI "void \fBrotate\fP (double ispeed) override"
.br
.ti -1c
.RI "void \fBstop\fP () override"
.br
.ti -1c
.RI "void \fBtank\fP (double ileftSpeed, double irightSpeed, double ithreshold=0) override"
.br
.ti -1c
.RI "void \fBarcade\fP (double iforwardSpeed, double iyaw, double ithreshold=0) override"
.br
.ti -1c
.RI "void \fBcurvature\fP (double iforwardSpeed, double icurvature, double ithreshold=0) override"
.br
.ti -1c
.RI "void \fBleft\fP (double ispeed) override"
.br
.ti -1c
.RI "void \fBright\fP (double ispeed) override"
.br
.ti -1c
.RI "void \fBsetBrakeMode\fP (\fBAbstractMotor::brakeMode\fP mode) override"
.br
.ti -1c
.RI "void \fBsetEncoderUnits\fP (\fBAbstractMotor::encoderUnits\fP units) override"
.br
.ti -1c
.RI "void \fBsetGearing\fP (\fBAbstractMotor::gearset\fP gearset) override"
.br
.ti -1c
.RI "void \fBsetMaxVelocity\fP (double imaxVelocity) override"
.br
.ti -1c
.RI "double \fBgetMaxVelocity\fP () const override"
.br
.ti -1c
.RI "void \fBsetMaxVoltage\fP (double imaxVoltage) override"
.br
.ti -1c
.RI "double \fBgetMaxVoltage\fP () const override"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBgetLeftSideMotor\fP () const"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBgetRightSideMotor\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ChassisModel\fP
.in +1c
.ti -1c
.RI "\fBChassisModel\fP (const ChassisModel &)=delete"
.br
.ti -1c
.RI "ChassisModel & \fBoperator=\fP (const ChassisModel &)=delete"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBContinuousRotarySensor\fP > \fBmiddleSensor\fP"
.br
.in -1c

Protected Attributes inherited from \fBokapi::SkidSteerModel\fP
.in +1c
.ti -1c
.RI "double \fBmaxVelocity\fP"
.br
.ti -1c
.RI "double \fBmaxVoltage\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBleftSideMotor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBrightSideMotor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBContinuousRotarySensor\fP > \fBleftSensor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBContinuousRotarySensor\fP > \fBrightSensor\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::ThreeEncoderSkidSteerModel::ThreeEncoderSkidSteerModel (std::shared_ptr< \fBAbstractMotor\fP > ileftSideMotor, std::shared_ptr< \fBAbstractMotor\fP > irightSideMotor, std::shared_ptr< \fBContinuousRotarySensor\fP > ileftEnc, std::shared_ptr< \fBContinuousRotarySensor\fP > irightEnc, std::shared_ptr< \fBContinuousRotarySensor\fP > imiddleEnc, double imaxVelocity, double imaxVoltage)"
Model for a skid steer drive (wheels parallel with robot's direction of motion)\&. When all motors are powered +127, the robot should move forward in a straight line\&.

.PP
\fBParameters\fP
.RS 4
\fIileftSideMotor\fP left side motor 
.br
\fIirightSideMotor\fP right side motor 
.br
\fIileftEnc\fP left side encoder 
.br
\fIimiddleEnc\fP middle encoder (mounted perpendicular to the left and right side encoders) 
.br
\fIirightEnc\fP right side encoder 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::valarray< std::int32_t > okapi::ThreeEncoderSkidSteerModel::getSensorVals () const\fR [override]\fP, \fR [virtual]\fP"
Read the sensors\&.

.PP
\fBReturns\fP
.RS 4
sensor readings in the format {left, right, middle} 
.RE
.PP

.PP
Reimplemented from \fBokapi::SkidSteerModel\fP\&.
.SS "void okapi::ThreeEncoderSkidSteerModel::resetSensors ()\fR [override]\fP, \fR [virtual]\fP"
Reset the sensors to their zero point\&. 
.PP
Reimplemented from \fBokapi::SkidSteerModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
