.TH "okapi::ControllerRunner< Input, Output >" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ControllerRunner< Input, Output >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControllerRunner\fP (const \fBTimeUtil\fP &itimeUtil, const std::shared_ptr< \fBLogger\fP > &ilogger=\fBLogger::getDefaultLogger\fP())"
.br
.ti -1c
.RI "virtual Output \fBrunUntilSettled\fP (const Input itarget, \fBAsyncController\fP< Input, Output > &icontroller)"
.br
.ti -1c
.RI "virtual Output \fBrunUntilSettled\fP (const Input itarget, \fBIterativeController\fP< Input, Output > &icontroller, \fBControllerOutput\fP< Output > &ioutput)"
.br
.ti -1c
.RI "virtual Output \fBrunUntilAtTarget\fP (const Input itarget, \fBAsyncController\fP< Input, Output > &icontroller)"
.br
.ti -1c
.RI "virtual Output \fBrunUntilAtTarget\fP (const Input itarget, \fBIterativeController\fP< Input, Output > &icontroller, \fBControllerOutput\fP< Output > &ioutput)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBLogger\fP > \fBlogger\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBAbstractRate\fP > \fBrate\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Input, typename Output> \fBokapi::ControllerRunner\fP< Input, Output >::ControllerRunner (const \fBTimeUtil\fP & itimeUtil, const std::shared_ptr< \fBLogger\fP > & ilogger = \fR\fBLogger::getDefaultLogger\fP()\fP)\fR [inline]\fP, \fR [explicit]\fP"
A utility class that runs a closed-loop controller\&.

.PP
\fBParameters\fP
.RS 4
\fIitimeUtil\fP The \fBTimeUtil\fP\&. 
.br
\fIilogger\fP The logger this instance will log to\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename Input, typename Output> virtual Output \fBokapi::ControllerRunner\fP< Input, Output >::runUntilAtTarget (const Input itarget, \fBAsyncController\fP< Input, Output > & icontroller)\fR [inline]\fP, \fR [virtual]\fP"
Runs the controller until it has reached its target, but not necessarily settled\&.

.PP
\fBParameters\fP
.RS 4
\fIitarget\fP the new target 
.br
\fIicontroller\fP the controller to run 
.RE
.PP
\fBReturns\fP
.RS 4
the error when settled 
.RE
.PP

.SS "template<typename Input, typename Output> virtual Output \fBokapi::ControllerRunner\fP< Input, Output >::runUntilAtTarget (const Input itarget, \fBIterativeController\fP< Input, Output > & icontroller, \fBControllerOutput\fP< Output > & ioutput)\fR [inline]\fP, \fR [virtual]\fP"
Runs the controller until it has reached its target, but not necessarily settled\&.

.PP
\fBParameters\fP
.RS 4
\fIitarget\fP the new target 
.br
\fIicontroller\fP the controller to run 
.br
\fIioutput\fP the output to write to 
.RE
.PP
\fBReturns\fP
.RS 4
the error when settled 
.RE
.PP

.SS "template<typename Input, typename Output> virtual Output \fBokapi::ControllerRunner\fP< Input, Output >::runUntilSettled (const Input itarget, \fBAsyncController\fP< Input, Output > & icontroller)\fR [inline]\fP, \fR [virtual]\fP"
Runs the controller until it has settled\&.

.PP
\fBParameters\fP
.RS 4
\fIitarget\fP the new target 
.br
\fIicontroller\fP the controller to run 
.RE
.PP
\fBReturns\fP
.RS 4
the error when settled 
.RE
.PP

.SS "template<typename Input, typename Output> virtual Output \fBokapi::ControllerRunner\fP< Input, Output >::runUntilSettled (const Input itarget, \fBIterativeController\fP< Input, Output > & icontroller, \fBControllerOutput\fP< Output > & ioutput)\fR [inline]\fP, \fR [virtual]\fP"
Runs the controller until it has settled\&.

.PP
\fBParameters\fP
.RS 4
\fIitarget\fP the new target 
.br
\fIicontroller\fP the controller to run 
.br
\fIioutput\fP the output to write to 
.RE
.PP
\fBReturns\fP
.RS 4
the error when settled 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
