.TH "okapi::ChassisControllerBuilder" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ChassisControllerBuilder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChassisControllerBuilder\fP (const std::shared_ptr< \fBLogger\fP > &ilogger=\fBLogger::getDefaultLogger\fP())"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMotors\fP (const \fBMotor\fP &ileft, const \fBMotor\fP &iright)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMotors\fP (const \fBMotorGroup\fP &ileft, const \fBMotorGroup\fP &iright)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMotors\fP (const std::shared_ptr< \fBAbstractMotor\fP > &ileft, const std::shared_ptr< \fBAbstractMotor\fP > &iright)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMotors\fP (const \fBMotor\fP &itopLeft, const \fBMotor\fP &itopRight, const \fBMotor\fP &ibottomRight, const \fBMotor\fP &ibottomLeft)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMotors\fP (const \fBMotorGroup\fP &itopLeft, const \fBMotorGroup\fP &itopRight, const \fBMotorGroup\fP &ibottomRight, const \fBMotorGroup\fP &ibottomLeft)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMotors\fP (const std::shared_ptr< \fBAbstractMotor\fP > &itopLeft, const std::shared_ptr< \fBAbstractMotor\fP > &itopRight, const std::shared_ptr< \fBAbstractMotor\fP > &ibottomRight, const std::shared_ptr< \fBAbstractMotor\fP > &ibottomLeft)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMotors\fP (const \fBMotor\fP &ileft, const \fBMotor\fP &iright, const \fBMotor\fP &imiddle)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMotors\fP (const \fBMotorGroup\fP &ileft, const \fBMotorGroup\fP &iright, const \fBMotorGroup\fP &imiddle)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMotors\fP (const \fBMotorGroup\fP &ileft, const \fBMotorGroup\fP &iright, const \fBMotor\fP &imiddle)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMotors\fP (const std::shared_ptr< \fBAbstractMotor\fP > &ileft, const std::shared_ptr< \fBAbstractMotor\fP > &iright, const std::shared_ptr< \fBAbstractMotor\fP > &imiddle)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithSensors\fP (const \fBADIEncoder\fP &ileft, const \fBADIEncoder\fP &iright)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithSensors\fP (const \fBADIEncoder\fP &ileft, const \fBADIEncoder\fP &iright, const \fBADIEncoder\fP &imiddle)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithSensors\fP (const \fBRotationSensor\fP &ileft, const \fBRotationSensor\fP &iright)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithSensors\fP (const \fBRotationSensor\fP &ileft, const \fBRotationSensor\fP &iright, const \fBRotationSensor\fP &imiddle)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithSensors\fP (const \fBIntegratedEncoder\fP &ileft, const \fBIntegratedEncoder\fP &iright)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithSensors\fP (const \fBIntegratedEncoder\fP &ileft, const \fBIntegratedEncoder\fP &iright, const \fBADIEncoder\fP &imiddle)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithSensors\fP (const std::shared_ptr< \fBContinuousRotarySensor\fP > &ileft, const std::shared_ptr< \fBContinuousRotarySensor\fP > &iright)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithSensors\fP (const std::shared_ptr< \fBContinuousRotarySensor\fP > &ileft, const std::shared_ptr< \fBContinuousRotarySensor\fP > &iright, const std::shared_ptr< \fBContinuousRotarySensor\fP > &imiddle)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithGains\fP (const \fBIterativePosPIDController::Gains\fP &idistanceGains, const \fBIterativePosPIDController::Gains\fP &iturnGains)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithGains\fP (const \fBIterativePosPIDController::Gains\fP &idistanceGains, const \fBIterativePosPIDController::Gains\fP &iturnGains, const \fBIterativePosPIDController::Gains\fP &iangleGains)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithOdometry\fP (const StateMode &imode=StateMode::FRAME_TRANSFORMATION, const QLength &imoveThreshold=0_mm, const QAngle &iturnThreshold=0_deg)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithOdometry\fP (const \fBChassisScales\fP &iodomScales, const StateMode &imode=StateMode::FRAME_TRANSFORMATION, const QLength &imoveThreshold=0_mm, const QAngle &iturnThreshold=0_deg)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithOdometry\fP (std::shared_ptr< \fBOdometry\fP > iodometry, const StateMode &imode=StateMode::FRAME_TRANSFORMATION, const QLength &imoveThreshold=0_mm, const QAngle &iturnThreshold=0_deg)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithDerivativeFilters\fP (std::unique_ptr< \fBFilter\fP > idistanceFilter, std::unique_ptr< \fBFilter\fP > iturnFilter=std::make_unique< \fBPassthroughFilter\fP >(), std::unique_ptr< \fBFilter\fP > iangleFilter=std::make_unique< \fBPassthroughFilter\fP >())"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithDimensions\fP (const \fBAbstractMotor::GearsetRatioPair\fP &igearset, const \fBChassisScales\fP &iscales)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMaxVelocity\fP (double imaxVelocity)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithMaxVoltage\fP (double imaxVoltage)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithChassisControllerTimeUtilFactory\fP (const \fBTimeUtilFactory\fP &itimeUtilFactory)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithClosedLoopControllerTimeUtilFactory\fP (const \fBTimeUtilFactory\fP &itimeUtilFactory)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithClosedLoopControllerTimeUtil\fP (double iatTargetError=50, double iatTargetDerivative=5, const QTime &iatTargetTime=250_ms)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithOdometryTimeUtilFactory\fP (const \fBTimeUtilFactory\fP &itimeUtilFactory)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBwithLogger\fP (const std::shared_ptr< \fBLogger\fP > &ilogger)"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBparentedToCurrentTask\fP ()"
.br
.ti -1c
.RI "\fBChassisControllerBuilder\fP & \fBnotParentedToCurrentTask\fP ()"
.br
.ti -1c
.RI "std::shared_ptr< \fBChassisController\fP > \fBbuild\fP ()"
.br
.ti -1c
.RI "std::shared_ptr< \fBOdomChassisController\fP > \fBbuildOdometry\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::ChassisControllerBuilder::ChassisControllerBuilder (const std::shared_ptr< \fBLogger\fP > & ilogger = \fR\fBLogger::getDefaultLogger\fP()\fP)\fR [explicit]\fP"
A builder that creates ChassisControllers\&. Use this to create your \fBChassisController\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIilogger\fP The logger this instance will log to\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBChassisController\fP > okapi::ChassisControllerBuilder::build ()"
Builds the \fBChassisController\fP\&. Throws a std::runtime_exception if no motors were set or if no dimensions were set\&.

.PP
\fBReturns\fP
.RS 4
A fully built \fBChassisController\fP\&. 
.RE
.PP

.SS "std::shared_ptr< \fBOdomChassisController\fP > okapi::ChassisControllerBuilder::buildOdometry ()"
Builds the \fBOdomChassisController\fP\&. Throws a std::runtime_exception if no motors were set, if no dimensions were set, or if no odometry information was passed\&.

.PP
\fBReturns\fP
.RS 4
A fully built \fBOdomChassisController\fP\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::notParentedToCurrentTask ()"
Prevents parenting the internal tasks started by this builder to the current task, meaning they will not be deleted once the current task is deleted\&. This can cause runaway tasks, but is sometimes the desired behavior (e\&.x\&., if you want to use this builder once in \fR\fBautonomous\fP\fP and then again in \fRopcontrol\fP)\&.

.PP
Read more about this in the [builders and tasks tutorial] (docs/tutorials/concepts/builders-and-tasks\&.md)\&.

.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::parentedToCurrentTask ()"
Parents the internal tasks started by this builder to the current task, meaning they will be deleted once the current task is deleted\&. The \fRinitialize\fP and \fRcompetition_initialize\fP tasks are never parented to\&. This is the default behavior\&.

.PP
Read more about this in the [builders and tasks tutorial] (docs/tutorials/concepts/builders-and-tasks\&.md)\&.

.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withChassisControllerTimeUtilFactory (const \fBTimeUtilFactory\fP & itimeUtilFactory)"
Sets the \fBTimeUtilFactory\fP used when building a \fBChassisController\fP\&. This instance will be given to the \fBChassisController\fP (not to controllers it uses)\&. The default is the static \fBTimeUtilFactory\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIitimeUtilFactory\fP The \fBTimeUtilFactory\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withClosedLoopControllerTimeUtil (double iatTargetError = \fR50\fP, double iatTargetDerivative = \fR5\fP, const QTime & iatTargetTime = \fR250_ms\fP)"
Creates a new \fBConfigurableTimeUtilFactory\fP with the given parameters\&. Given to any \fBClosedLoopController\fP instances\&.

.PP
\fBParameters\fP
.RS 4
\fIiatTargetError\fP The minimum error to be considered settled\&. 
.br
\fIiatTargetDerivative\fP The minimum error derivative to be considered settled\&. 
.br
\fIiatTargetTime\fP The minimum time within atTargetError to be considered settled\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withClosedLoopControllerTimeUtilFactory (const \fBTimeUtilFactory\fP & itimeUtilFactory)"
Sets the \fBTimeUtilFactory\fP used when building a \fBClosedLoopController\fP\&. This instance will be given to any \fBClosedLoopController\fP instances\&. The default is the static \fBTimeUtilFactory\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIitimeUtilFactory\fP The \fBTimeUtilFactory\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withDerivativeFilters (std::unique_ptr< \fBFilter\fP > idistanceFilter, std::unique_ptr< \fBFilter\fP > iturnFilter = \fRstd::make_unique< \fBPassthroughFilter\fP >()\fP, std::unique_ptr< \fBFilter\fP > iangleFilter = \fRstd::make_unique< \fBPassthroughFilter\fP >()\fP)"
Sets the derivative filters\&. Uses a \fBPassthroughFilter\fP by default\&.

.PP
\fBParameters\fP
.RS 4
\fIidistanceFilter\fP The distance controller's filter\&. 
.br
\fIiturnFilter\fP The turn controller's filter\&. 
.br
\fIiangleFilter\fP The angle controller's filter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withDimensions (const \fBAbstractMotor::GearsetRatioPair\fP & igearset, const \fBChassisScales\fP & iscales)"
Sets the chassis dimensions\&.

.PP
\fBParameters\fP
.RS 4
\fIigearset\fP The gearset in the drive motors\&. 
.br
\fIiscales\fP The \fBChassisScales\fP for the base\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withGains (const \fBIterativePosPIDController::Gains\fP & idistanceGains, const \fBIterativePosPIDController::Gains\fP & iturnGains)"
Sets the PID controller gains, causing the builder to generate a \fBChassisControllerPID\fP\&. Uses the turn controller's gains for the angle controller's gains\&.

.PP
\fBParameters\fP
.RS 4
\fIidistanceGains\fP The distance controller's gains\&. 
.br
\fIiturnGains\fP The turn controller's gains\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withGains (const \fBIterativePosPIDController::Gains\fP & idistanceGains, const \fBIterativePosPIDController::Gains\fP & iturnGains, const \fBIterativePosPIDController::Gains\fP & iangleGains)"
Sets the PID controller gains, causing the builder to generate a \fBChassisControllerPID\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIidistanceGains\fP The distance controller's gains\&. 
.br
\fIiturnGains\fP The turn controller's gains\&. 
.br
\fIiangleGains\fP The angle controller's gains\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withLogger (const std::shared_ptr< \fBLogger\fP > & ilogger)"
Sets the logger used for the \fBChassisController\fP and ClosedLoopControllers\&.

.PP
\fBParameters\fP
.RS 4
\fIilogger\fP The logger\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMaxVelocity (double imaxVelocity)"
Sets the max velocity\&. Overrides the max velocity of the gearset\&.

.PP
\fBParameters\fP
.RS 4
\fIimaxVelocity\fP The max velocity\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMaxVoltage (double imaxVoltage)"
Sets the max voltage\&. The default is \fR12000\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIimaxVoltage\fP The max voltage\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMotors (const \fBMotor\fP & ileft, const \fBMotor\fP & iright)"
Sets the motors using a skid-steer layout\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left motor\&. 
.br
\fIiright\fP The right motor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMotors (const \fBMotor\fP & ileft, const \fBMotor\fP & iright, const \fBMotor\fP & imiddle)"
Sets the motors using an h-drive layout\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left motor\&. 
.br
\fIiright\fP The right motor\&. 
.br
\fIimiddle\fP The middle motor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMotors (const \fBMotor\fP & itopLeft, const \fBMotor\fP & itopRight, const \fBMotor\fP & ibottomRight, const \fBMotor\fP & ibottomLeft)"
Sets the motors using an x-drive layout\&.

.PP
\fBParameters\fP
.RS 4
\fIitopLeft\fP The top left motor\&. 
.br
\fIitopRight\fP The top right motor\&. 
.br
\fIibottomRight\fP The bottom right motor\&. 
.br
\fIibottomLeft\fP The bottom left motor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMotors (const \fBMotorGroup\fP & ileft, const \fBMotorGroup\fP & iright)"
Sets the motors using a skid-steer layout\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left motor\&. 
.br
\fIiright\fP The right motor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMotors (const \fBMotorGroup\fP & ileft, const \fBMotorGroup\fP & iright, const \fBMotor\fP & imiddle)"
Sets the motors using an h-drive layout\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left motor\&. 
.br
\fIiright\fP The right motor\&. 
.br
\fIimiddle\fP The middle motor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMotors (const \fBMotorGroup\fP & ileft, const \fBMotorGroup\fP & iright, const \fBMotorGroup\fP & imiddle)"
Sets the motors using an h-drive layout\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left motor\&. 
.br
\fIiright\fP The right motor\&. 
.br
\fIimiddle\fP The middle motor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMotors (const \fBMotorGroup\fP & itopLeft, const \fBMotorGroup\fP & itopRight, const \fBMotorGroup\fP & ibottomRight, const \fBMotorGroup\fP & ibottomLeft)"
Sets the motors using an x-drive layout\&.

.PP
\fBParameters\fP
.RS 4
\fIitopLeft\fP The top left motor\&. 
.br
\fIitopRight\fP The top right motor\&. 
.br
\fIibottomRight\fP The bottom right motor\&. 
.br
\fIibottomLeft\fP The bottom left motor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMotors (const std::shared_ptr< \fBAbstractMotor\fP > & ileft, const std::shared_ptr< \fBAbstractMotor\fP > & iright)"
Sets the motors using a skid-steer layout\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left motor\&. 
.br
\fIiright\fP The right motor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMotors (const std::shared_ptr< \fBAbstractMotor\fP > & ileft, const std::shared_ptr< \fBAbstractMotor\fP > & iright, const std::shared_ptr< \fBAbstractMotor\fP > & imiddle)"
Sets the motors using an h-drive layout\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left motor\&. 
.br
\fIiright\fP The right motor\&. 
.br
\fIimiddle\fP The middle motor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withMotors (const std::shared_ptr< \fBAbstractMotor\fP > & itopLeft, const std::shared_ptr< \fBAbstractMotor\fP > & itopRight, const std::shared_ptr< \fBAbstractMotor\fP > & ibottomRight, const std::shared_ptr< \fBAbstractMotor\fP > & ibottomLeft)"
Sets the motors using an x-drive layout\&.

.PP
\fBParameters\fP
.RS 4
\fIitopLeft\fP The top left motor\&. 
.br
\fIitopRight\fP The top right motor\&. 
.br
\fIibottomRight\fP The bottom right motor\&. 
.br
\fIibottomLeft\fP The bottom left motor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withOdometry (const \fBChassisScales\fP & iodomScales, const StateMode & imode = \fRStateMode::FRAME_TRANSFORMATION\fP, const QLength & imoveThreshold = \fR0_mm\fP, const QAngle & iturnThreshold = \fR0_deg\fP)"
Sets the odometry information, causing the builder to generate an \fBOdometry\fP variant\&.

.PP
\fBParameters\fP
.RS 4
\fIiodomScales\fP The \fBChassisScales\fP used just for odometry (if they are different than those for the drive)\&. 
.br
\fIimode\fP The new default StateMode used to interpret target points and query the \fBOdometry\fP state\&. 
.br
\fIimoveThreshold\fP The minimum length movement\&. 
.br
\fIiturnThreshold\fP The minimum angle turn\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withOdometry (const StateMode & imode = \fRStateMode::FRAME_TRANSFORMATION\fP, const QLength & imoveThreshold = \fR0_mm\fP, const QAngle & iturnThreshold = \fR0_deg\fP)"
Sets the odometry information, causing the builder to generate an \fBOdometry\fP variant\&.

.PP
\fBParameters\fP
.RS 4
\fIimode\fP The new default StateMode used to interpret target points and query the \fBOdometry\fP state\&. 
.br
\fIimoveThreshold\fP The minimum length movement\&. 
.br
\fIiturnThreshold\fP The minimum angle turn\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withOdometry (std::shared_ptr< \fBOdometry\fP > iodometry, const StateMode & imode = \fRStateMode::FRAME_TRANSFORMATION\fP, const QLength & imoveThreshold = \fR0_mm\fP, const QAngle & iturnThreshold = \fR0_deg\fP)"
Sets the odometry information, causing the builder to generate an \fBOdometry\fP variant\&.

.PP
\fBParameters\fP
.RS 4
\fIiodometry\fP The odometry object\&. 
.br
\fIimode\fP The new default StateMode used to interpret target points and query the \fBOdometry\fP state\&. 
.br
\fIimoveThreshold\fP The minimum length movement\&. 
.br
\fIiturnThreshold\fP The minimum angle turn\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withOdometryTimeUtilFactory (const \fBTimeUtilFactory\fP & itimeUtilFactory)"
Sets the \fBTimeUtilFactory\fP used when building an \fBOdometry\fP\&. The default is the static \fBTimeUtilFactory\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIitimeUtilFactory\fP The \fBTimeUtilFactory\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withSensors (const \fBADIEncoder\fP & ileft, const \fBADIEncoder\fP & iright)"
Sets the sensors\&. The default sensors are the motor's integrated encoders\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left side sensor\&. 
.br
\fIiright\fP The right side sensor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withSensors (const \fBADIEncoder\fP & ileft, const \fBADIEncoder\fP & iright, const \fBADIEncoder\fP & imiddle)"
Sets the sensors\&. The default sensors are the motor's integrated encoders\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left side sensor\&. 
.br
\fIiright\fP The right side sensor\&. 
.br
\fIimiddle\fP The middle sensor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withSensors (const \fBIntegratedEncoder\fP & ileft, const \fBIntegratedEncoder\fP & iright)"
Sets the sensors\&. The default sensors are the motor's integrated encoders\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left side sensor\&. 
.br
\fIiright\fP The right side sensor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withSensors (const \fBIntegratedEncoder\fP & ileft, const \fBIntegratedEncoder\fP & iright, const \fBADIEncoder\fP & imiddle)"
Sets the sensors\&. The default sensors are the motor's integrated encoders\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left side sensor\&. 
.br
\fIiright\fP The right side sensor\&. 
.br
\fIimiddle\fP The middle sensor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withSensors (const \fBRotationSensor\fP & ileft, const \fBRotationSensor\fP & iright)"
Sets the sensors\&. The default sensors are the motor's integrated encoders\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left side sensor\&. 
.br
\fIiright\fP The right side sensor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withSensors (const \fBRotationSensor\fP & ileft, const \fBRotationSensor\fP & iright, const \fBRotationSensor\fP & imiddle)"
Sets the sensors\&. The default sensors are the motor's integrated encoders\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left side sensor\&. 
.br
\fIiright\fP The right side sensor\&. 
.br
\fIimiddle\fP The middle sensor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withSensors (const std::shared_ptr< \fBContinuousRotarySensor\fP > & ileft, const std::shared_ptr< \fBContinuousRotarySensor\fP > & iright)"
Sets the sensors\&. The default sensors are the motor's integrated encoders\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left side sensor\&. 
.br
\fIiright\fP The right side sensor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP

.SS "\fBChassisControllerBuilder\fP & okapi::ChassisControllerBuilder::withSensors (const std::shared_ptr< \fBContinuousRotarySensor\fP > & ileft, const std::shared_ptr< \fBContinuousRotarySensor\fP > & iright, const std::shared_ptr< \fBContinuousRotarySensor\fP > & imiddle)"
Sets the sensors\&. The default sensors are the motor's integrated encoders\&.

.PP
\fBParameters\fP
.RS 4
\fIileft\fP The left side sensor\&. 
.br
\fIiright\fP The right side sensor\&. 
.br
\fIimiddle\fP The middle sensor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An ongoing builder\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
