.TH "okapi::ADIGyro" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ADIGyro
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::ContinuousRotarySensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBADIGyro\fP (std::uint8_t iport, double imultiplier=1)"
.br
.ti -1c
.RI "\fBADIGyro\fP (std::pair< std::uint8_t, std::uint8_t > iports, double imultiplier=1)"
.br
.ti -1c
.RI "double \fBget\fP () const override"
.br
.ti -1c
.RI "double \fBgetRemapped\fP (double iupperBound=1800, double ilowerBound=\-1800) const"
.br
.ti -1c
.RI "std::int32_t \fBreset\fP () override"
.br
.ti -1c
.RI "double \fBcontrollerGet\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "pros::c::ext_adi_gyro_t \fBgyro\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::ADIGyro::ADIGyro (std::uint8_t iport, double imultiplier = \fR1\fP)"
A gyroscope on the given ADI port\&. If the port has not previously been configured as a gyro, then the constructor will block for 1 second for calibration\&. The gyro measures in tenths of a degree, so there are \fR3600\fP measurement points per revolution\&.

.PP
.PP
.nf
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIiport\fP The ADI port number (\fR[1, 8]\fP, \fR[a, h]\fP, \fR[A, H]\fP)\&. 
.br
\fIimultiplier\fP A value multiplied by the gyro heading value\&. 
.RE
.PP

.SS "okapi::ADIGyro::ADIGyro (std::pair< std::uint8_t, std::uint8_t > iports, double imultiplier = \fR1\fP)"
A gyroscope on the given ADI port\&. If the port has not previously been configured as a gyro, then the constructor will block for 1 second for calibration\&. The gyro measures in tenths of a degree, so there are 3600 measurement points per revolution\&.

.PP
.PP
.nf
.fi
.PP

.PP
Note to developers: Keep the default value on imultiplier so that users get an error if they do \fBADIGyro\fP({1, 'A'})\&. Without it, this calls the non-ext-adi constructor\&.

.PP
\fBParameters\fP
.RS 4
\fIiports\fP The ports the gyro is plugged in to in the order \fR{smart port, gyro port}\fP\&. The smart port is the smart port number (\fR[1, 21]\fP)\&. The gyro port is the ADI port number (\fR[1, 8]\fP, \fR[a, h]\fP, \fR[A, H]\fP)\&. 
.br
\fIimultiplier\fP A value multiplied by the gyro heading value\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double okapi::ADIGyro::controllerGet ()\fR [override]\fP, \fR [virtual]\fP"
Get the sensor value for use in a control loop\&. This method might be automatically called in another thread by the controller\&.

.PP
\fBReturns\fP
.RS 4
the current sensor value, or \fRPROS_ERR\fP on a failure\&. 
.RE
.PP

.PP
Implements \fBokapi::ControllerInput< double >\fP\&.
.SS "double okapi::ADIGyro::get () const\fR [override]\fP, \fR [virtual]\fP"
Get the current sensor value\&.

.PP
\fBReturns\fP
.RS 4
the current sensor value, or \fRPROS_ERR\fP on a failure\&. 
.RE
.PP

.PP
Implements \fBokapi::RotarySensor\fP\&.
.SS "double okapi::ADIGyro::getRemapped (double iupperBound = \fR1800\fP, double ilowerBound = \fR\-1800\fP) const"
Get the current sensor value remapped into the target range (\fR[-1800, 1800]\fP by default)\&.

.PP
\fBParameters\fP
.RS 4
\fIiupperBound\fP the upper bound of the range\&. 
.br
\fIilowerBound\fP the lower bound of the range\&. 
.RE
.PP
\fBReturns\fP
.RS 4
the remapped sensor value\&. 
.RE
.PP

.SS "std::int32_t okapi::ADIGyro::reset ()\fR [override]\fP, \fR [virtual]\fP"
Reset the sensor to zero\&.

.PP
\fBReturns\fP
.RS 4
\fR1\fP on success, \fRPROS_ERR\fP on fail 
.RE
.PP

.PP
Implements \fBokapi::ContinuousRotarySensor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
