.TH "okapi::ControllerRunnerFactory< Input, Output >" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ControllerRunnerFactory< Input, Output >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBControllerRunner\fP< Input, Output > \fBcreate\fP (const std::shared_ptr< \fBLogger\fP > &ilogger=\fBLogger::getDefaultLogger\fP())"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename Input, typename Output> \fBControllerRunner\fP< Input, Output > \fBokapi::ControllerRunnerFactory\fP< Input, Output >::create (const std::shared_ptr< \fBLogger\fP > & ilogger = \fR\fBLogger::getDefaultLogger\fP()\fP)\fR [inline]\fP, \fR [static]\fP"
A utility class that runs a closed-loop controller\&.

.PP
\fBParameters\fP
.RS 4
\fIilogger\fP The logger this instance will log to\&. 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
