.TH "okapi::ADIEncoder" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ADIEncoder
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::ContinuousRotarySensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBADIEncoder\fP (std::uint8_t iportTop, std::uint8_t iportBottom, bool ireversed=false)"
.br
.ti -1c
.RI "\fBADIEncoder\fP (std::tuple< std::uint8_t, std::uint8_t, std::uint8_t > iports, bool ireversed=false)"
.br
.ti -1c
.RI "virtual double \fBget\fP () const override"
.br
.ti -1c
.RI "virtual std::int32_t \fBreset\fP () override"
.br
.ti -1c
.RI "virtual double \fBcontrollerGet\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "pros::c::ext_adi_encoder_t \fBenc\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::ADIEncoder::ADIEncoder (std::uint8_t iportTop, std::uint8_t iportBottom, bool ireversed = \fRfalse\fP)"
An encoder in an ADI port\&.

.PP
.PP
.nf
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIiportTop\fP The "top" wire from the encoder with the removable cover side up\&. This must be in port \fR1\fP, \fR3\fP, \fR5\fP, or \fR7\fP (\fRA\fP, \fRC\fP, \fRE\fP, or \fRG\fP)\&. 
.br
\fIiportBottom\fP The "bottom" wire from the encoder\&. This must be in port \fR2\fP, \fR4\fP, \fR6\fP, or \fR8\fP (\fRB\fP, \fRD\fP, \fRF\fP, or \fRH\fP)\&. 
.br
\fIireversed\fP Whether the encoder is reversed\&. 
.RE
.PP

.SS "okapi::ADIEncoder::ADIEncoder (std::tuple< std::uint8_t, std::uint8_t, std::uint8_t > iports, bool ireversed = \fRfalse\fP)"
An encoder in an ADI port\&.

.PP
.PP
.nf
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIiports\fP The ports the encoder is plugged in to in the order \fR{smart port, top port, bottom port}\fP\&. The smart port is the smart port number (\fR[1, 21]\fP)\&. The top port is the "top" wire from the encoder with the removable cover side up\&. This must be in port \fR1\fP, \fR3\fP, \fR5\fP, or \fR7\fP (\fRA\fP, \fRC\fP, \fRE\fP, or \fRG\fP)\&. The bottom port is the "bottom" wire from the encoder\&. This must be in port \fR2\fP, \fR4\fP, \fR6\fP, or \fR8\fP (\fRB\fP, \fRD\fP, \fRF\fP, or \fRH\fP)\&. 
.br
\fIireversed\fP Whether the encoder is reversed\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual double okapi::ADIEncoder::controllerGet ()\fR [override]\fP, \fR [virtual]\fP"
Get the sensor value for use in a control loop\&. This method might be automatically called in another thread by the controller\&.

.PP
\fBReturns\fP
.RS 4
the current sensor value, or \fRPROS_ERR\fP on a failure\&. 
.RE
.PP

.PP
Implements \fBokapi::ControllerInput< double >\fP\&.
.SS "virtual double okapi::ADIEncoder::get () const\fR [override]\fP, \fR [virtual]\fP"
Get the current sensor value\&.

.PP
\fBReturns\fP
.RS 4
the current sensor value, or \fRPROS_ERR\fP on a failure\&. 
.RE
.PP

.PP
Implements \fBokapi::RotarySensor\fP\&.
.SS "virtual std::int32_t okapi::ADIEncoder::reset ()\fR [override]\fP, \fR [virtual]\fP"
Reset the sensor to zero\&.

.PP
\fBReturns\fP
.RS 4
\fR1\fP on success, \fRPROS_ERR\fP on fail 
.RE
.PP

.PP
Implements \fBokapi::ContinuousRotarySensor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
