.TH "okapi::AsyncController< Input, Output >" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::AsyncController< Input, Output >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <asyncController\&.hpp>\fP
.PP
Inherits \fBokapi::ClosedLoopController< Input, Output >\fP\&.
.PP
Inherited by \fBokapi::AsyncPositionController< Input, Output >\fP\fR [virtual]\fP, \fBokapi::AsyncVelocityController< Input, Output >\fP\fR [virtual]\fP, and \fBokapi::AsyncWrapper< Input, Output >\fP\fR [virtual]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwaitUntilSettled\fP ()=0"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ClosedLoopController< Input, Output >\fP
.in +1c
.ti -1c
.RI "virtual void \fBsetTarget\fP (Input itarget)=0"
.br
.ti -1c
.RI "virtual Input \fBgetTarget\fP ()=0"
.br
.ti -1c
.RI "virtual Input \fBgetProcessValue\fP () const =0"
.br
.ti -1c
.RI "virtual Output \fBgetError\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBisSettled\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBflipDisable\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBflipDisable\fP (bool iisDisabled)=0"
.br
.ti -1c
.RI "virtual bool \fBisDisabled\fP () const =0"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ControllerOutput< Input >\fP
.in +1c
.ti -1c
.RI "virtual void \fBcontrollerSet\fP (Input ivalue)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Input, typename Output>
.br
class okapi::AsyncController< Input, Output >"Closed-loop controller that steps on its own in another thread and automatically writes to the output\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename Input, typename Output> virtual void \fBokapi::AsyncController\fP< Input, Output >::waitUntilSettled ()\fR [pure virtual]\fP"
Blocks the current task until the controller has settled\&. Determining what settling means is implementation-dependent\&. 
.PP
Implemented in \fBokapi::AsyncLinearMotionProfileController\fP, \fBokapi::AsyncMotionProfileController\fP, \fBokapi::AsyncPosIntegratedController\fP, \fBokapi::AsyncVelIntegratedController\fP, \fBokapi::AsyncWrapper< Input, Output >\fP, and \fBokapi::AsyncWrapper< double, double >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
