.TH "okapi::TimeUtil" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::TimeUtil
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <timeUtil\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeUtil\fP (const \fBSupplier\fP< std::unique_ptr< \fBAbstractTimer\fP > > &itimerSupplier, const \fBSupplier\fP< std::unique_ptr< \fBAbstractRate\fP > > &irateSupplier, const \fBSupplier\fP< std::unique_ptr< \fBSettledUtil\fP > > &isettledUtilSupplier)"
.br
.ti -1c
.RI "std::unique_ptr< \fBAbstractTimer\fP > \fBgetTimer\fP () const"
.br
.ti -1c
.RI "std::unique_ptr< \fBAbstractRate\fP > \fBgetRate\fP () const"
.br
.ti -1c
.RI "std::unique_ptr< \fBSettledUtil\fP > \fBgetSettledUtil\fP () const"
.br
.ti -1c
.RI "\fBSupplier\fP< std::unique_ptr< \fBAbstractTimer\fP > > \fBgetTimerSupplier\fP () const"
.br
.ti -1c
.RI "\fBSupplier\fP< std::unique_ptr< \fBAbstractRate\fP > > \fBgetRateSupplier\fP () const"
.br
.ti -1c
.RI "\fBSupplier\fP< std::unique_ptr< \fBSettledUtil\fP > > \fBgetSettledUtilSupplier\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSupplier\fP< std::unique_ptr< \fBAbstractTimer\fP > > \fBtimerSupplier\fP"
.br
.ti -1c
.RI "\fBSupplier\fP< std::unique_ptr< \fBAbstractRate\fP > > \fBrateSupplier\fP"
.br
.ti -1c
.RI "\fBSupplier\fP< std::unique_ptr< \fBSettledUtil\fP > > \fBsettledUtilSupplier\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility class for holding an \fBAbstractTimer\fP, \fBAbstractRate\fP, and \fBSettledUtil\fP together in one class since they are commonly used together\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
