.TH "okapi::ReadOnlyChassisModel" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ReadOnlyChassisModel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <readOnlyChassisModel\&.hpp>\fP
.PP
Inherited by \fBokapi::ChassisModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::valarray< std::int32_t > \fBgetSensorVals\fP () const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
A version of the \fBChassisModel\fP that only supports read methods, such as querying sensor values\&. This class does not let you write to motors, so it supports having multiple owners and as a result copying is enabled\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual std::valarray< std::int32_t > okapi::ReadOnlyChassisModel::getSensorVals () const\fR [pure virtual]\fP"
Read the sensors\&.

.PP
\fBReturns\fP
.RS 4
sensor readings (format is implementation dependent) 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, \fBokapi::ThreeEncoderSkidSteerModel\fP, \fBokapi::ThreeEncoderXDriveModel\fP, and \fBokapi::XDriveModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
