.TH "okapi::OdomMath" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::OdomMath
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QLength \fBcomputeDistanceToPoint\fP (const \fBPoint\fP &ipoint, const \fBOdomState\fP &istate)"
.br
.ti -1c
.RI "static QAngle \fBcomputeAngleToPoint\fP (const \fBPoint\fP &ipoint, const \fBOdomState\fP &istate)"
.br
.ti -1c
.RI "static std::pair< QLength, QAngle > \fBcomputeDistanceAndAngleToPoint\fP (const \fBPoint\fP &ipoint, const \fBOdomState\fP &istate)"
.br
.ti -1c
.RI "static QAngle \fBconstrainAngle360\fP (const QAngle &angle)"
.br
.ti -1c
.RI "static QAngle \fBconstrainAngle180\fP (const QAngle &angle)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "QAngle okapi::OdomMath::computeAngleToPoint (const \fBPoint\fP & ipoint, const \fBOdomState\fP & istate)\fR [static]\fP"
Computes the angle from the given \fBOdometry\fP state to the given point\&. The point and the \fBOdomState\fP must be in \fRStateMode::FRAME_TRANSFORMATION\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIipoint\fP The point\&. 
.br
\fIistate\fP The \fBOdometry\fP state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The angle between the \fBOdometry\fP state and the point\&. 
.RE
.PP

.SS "std::pair< QLength, QAngle > okapi::OdomMath::computeDistanceAndAngleToPoint (const \fBPoint\fP & ipoint, const \fBOdomState\fP & istate)\fR [static]\fP"
Computes the distance and angle from the given \fBOdometry\fP state to the given point\&. The point and the \fBOdomState\fP must be in \fRStateMode::FRAME_TRANSFORMATION\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIipoint\fP The point\&. 
.br
\fIistate\fP The \fBOdometry\fP state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The distance and angle between the \fBOdometry\fP state and the point\&. 
.RE
.PP

.SS "QLength okapi::OdomMath::computeDistanceToPoint (const \fBPoint\fP & ipoint, const \fBOdomState\fP & istate)\fR [static]\fP"
Computes the distance from the given \fBOdometry\fP state to the given point\&. The point and the \fBOdomState\fP must be in \fRStateMode::FRAME_TRANSFORMATION\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIipoint\fP The point\&. 
.br
\fIistate\fP The \fBOdometry\fP state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The distance between the \fBOdometry\fP state and the point\&. 
.RE
.PP

.SS "QAngle okapi::OdomMath::constrainAngle180 (const QAngle & angle)\fR [static]\fP"
Constraints the angle to [-180,180) degrees\&.

.PP
\fBParameters\fP
.RS 4
\fIangle\fP The input angle\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The angle normalized to [-180,180) degrees\&. 
.RE
.PP

.SS "QAngle okapi::OdomMath::constrainAngle360 (const QAngle & angle)\fR [static]\fP"
Constraints the angle to [0,360] degrees\&.

.PP
\fBParameters\fP
.RS 4
\fIangle\fP The input angle\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The angle normalized to [0,360] degrees\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
