.TH "okapi::IterativePositionController< Input, Output >" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::IterativePositionController< Input, Output >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::IterativeController< Input, Output >\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBokapi::IterativeController< Input, Output >\fP
.in +1c
.ti -1c
.RI "virtual Output \fBstep\fP (Input ireading)=0"
.br
.ti -1c
.RI "virtual Output \fBgetOutput\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBsetOutputLimits\fP (Output imax, Output imin)=0"
.br
.ti -1c
.RI "virtual void \fBsetControllerSetTargetLimits\fP (Output itargetMax, Output itargetMin)=0"
.br
.ti -1c
.RI "virtual Output \fBgetMaxOutput\fP ()=0"
.br
.ti -1c
.RI "virtual Output \fBgetMinOutput\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBsetSampleTime\fP (QTime isampleTime)=0"
.br
.ti -1c
.RI "virtual QTime \fBgetSampleTime\fP () const =0"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ClosedLoopController< Input, Output >\fP
.in +1c
.ti -1c
.RI "virtual void \fBsetTarget\fP (Input itarget)=0"
.br
.ti -1c
.RI "virtual Input \fBgetTarget\fP ()=0"
.br
.ti -1c
.RI "virtual Input \fBgetProcessValue\fP () const =0"
.br
.ti -1c
.RI "virtual Output \fBgetError\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBisSettled\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBflipDisable\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBflipDisable\fP (bool iisDisabled)=0"
.br
.ti -1c
.RI "virtual bool \fBisDisabled\fP () const =0"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ControllerOutput< Input >\fP
.in +1c
.ti -1c
.RI "virtual void \fBcontrollerSet\fP (Input ivalue)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
