.TH "okapi::TwoEncoderOdometry" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::TwoEncoderOdometry
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::Odometry\fP\&.
.PP
Inherited by \fBokapi::ThreeEncoderOdometry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTwoEncoderOdometry\fP (const \fBTimeUtil\fP &itimeUtil, const std::shared_ptr< \fBReadOnlyChassisModel\fP > &imodel, const \fBChassisScales\fP &ichassisScales, const std::shared_ptr< \fBLogger\fP > &ilogger=\fBLogger::getDefaultLogger\fP())"
.br
.ti -1c
.RI "void \fBsetScales\fP (const \fBChassisScales\fP &ichassisScales) override"
.br
.ti -1c
.RI "void \fBstep\fP () override"
.br
.ti -1c
.RI "\fBOdomState\fP \fBgetState\fP (const StateMode &imode=StateMode::FRAME_TRANSFORMATION) const override"
.br
.ti -1c
.RI "void \fBsetState\fP (const \fBOdomState\fP &istate, const StateMode &imode=StateMode::FRAME_TRANSFORMATION) override"
.br
.ti -1c
.RI "std::shared_ptr< \fBReadOnlyChassisModel\fP > \fBgetModel\fP () override"
.br
.ti -1c
.RI "\fBChassisScales\fP \fBgetScales\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBokapi::Odometry\fP
.in +1c
.ti -1c
.RI "\fBOdometry\fP ()=default"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBOdomState\fP \fBodomMathStep\fP (const std::valarray< std::int32_t > &itickDiff, const QTime &ideltaT)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBLogger\fP > \fBlogger\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBAbstractRate\fP > \fBrate\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBAbstractTimer\fP > \fBtimer\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBReadOnlyChassisModel\fP > \fBmodel\fP"
.br
.ti -1c
.RI "\fBChassisScales\fP \fBchassisScales\fP"
.br
.ti -1c
.RI "\fBOdomState\fP \fBstate\fP"
.br
.ti -1c
.RI "std::valarray< std::int32_t > \fBnewTicks\fP {0, 0, 0}"
.br
.ti -1c
.RI "std::valarray< std::int32_t > \fBtickDiff\fP {0, 0, 0}"
.br
.ti -1c
.RI "std::valarray< std::int32_t > \fBlastTicks\fP {0, 0, 0}"
.br
.ti -1c
.RI "const std::int32_t \fBmaximumTickDiff\fP {1000}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::TwoEncoderOdometry::TwoEncoderOdometry (const \fBTimeUtil\fP & itimeUtil, const std::shared_ptr< \fBReadOnlyChassisModel\fP > & imodel, const \fBChassisScales\fP & ichassisScales, const std::shared_ptr< \fBLogger\fP > & ilogger = \fR\fBLogger::getDefaultLogger\fP()\fP)"
\fBTwoEncoderOdometry\fP\&. Tracks the movement of the robot and estimates its position in coordinates relative to the start (assumed to be (0, 0, 0))\&.

.PP
\fBParameters\fP
.RS 4
\fIitimeUtil\fP The \fBTimeUtil\fP\&. 
.br
\fIimodel\fP The chassis model for reading sensors\&. 
.br
\fIichassisScales\fP The chassis dimensions\&. 
.br
\fIilogger\fP The logger this instance will log to\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBReadOnlyChassisModel\fP > okapi::TwoEncoderOdometry::getModel ()\fR [override]\fP, \fR [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The internal \fBChassisModel\fP\&. 
.RE
.PP

.PP
Implements \fBokapi::Odometry\fP\&.
.SS "\fBChassisScales\fP okapi::TwoEncoderOdometry::getScales ()\fR [override]\fP, \fR [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The internal \fBChassisScales\fP\&. 
.RE
.PP

.PP
Implements \fBokapi::Odometry\fP\&.
.SS "\fBOdomState\fP okapi::TwoEncoderOdometry::getState (const StateMode & imode = \fRStateMode::FRAME_TRANSFORMATION\fP) const\fR [override]\fP, \fR [virtual]\fP"
Returns the current state\&.

.PP
\fBParameters\fP
.RS 4
\fIimode\fP The mode to return the state in\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The current state in the given format\&. 
.RE
.PP

.PP
Implements \fBokapi::Odometry\fP\&.
.SS "virtual \fBOdomState\fP okapi::TwoEncoderOdometry::odomMathStep (const std::valarray< std::int32_t > & itickDiff, const QTime & ideltaT)\fR [protected]\fP, \fR [virtual]\fP"
Does the math, side-effect free, for one odom step\&.

.PP
\fBParameters\fP
.RS 4
\fIitickDiff\fP The tick difference from the previous step to this step\&. 
.br
\fIideltaT\fP The time difference from the previous step to this step\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The newly computed \fBOdomState\fP\&. 
.RE
.PP

.PP
Reimplemented in \fBokapi::ThreeEncoderOdometry\fP\&.
.SS "void okapi::TwoEncoderOdometry::setScales (const \fBChassisScales\fP & ichassisScales)\fR [override]\fP, \fR [virtual]\fP"
Sets the drive and turn scales\&. 
.PP
Implements \fBokapi::Odometry\fP\&.
.SS "void okapi::TwoEncoderOdometry::setState (const \fBOdomState\fP & istate, const StateMode & imode = \fRStateMode::FRAME_TRANSFORMATION\fP)\fR [override]\fP, \fR [virtual]\fP"
Sets a new state to be the current state\&.

.PP
\fBParameters\fP
.RS 4
\fIistate\fP The new state in the given format\&. 
.br
\fIimode\fP The mode to treat the input state as\&. 
.RE
.PP

.PP
Implements \fBokapi::Odometry\fP\&.
.SS "void okapi::TwoEncoderOdometry::step ()\fR [override]\fP, \fR [virtual]\fP"
Do one odometry step\&. 
.PP
Implements \fBokapi::Odometry\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
