.TH "okapi::IMU" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::IMU
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::ContinuousRotarySensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIMU\fP (std::uint8_t iport, IMUAxes iaxis=IMUAxes::z)"
.br
.ti -1c
.RI "double \fBget\fP () const override"
.br
.ti -1c
.RI "double \fBgetRemapped\fP (double iupperBound=1800, double ilowerBound=\-1800) const"
.br
.ti -1c
.RI "double \fBgetAcceleration\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBreset\fP () override"
.br
.ti -1c
.RI "std::int32_t \fBreset\fP (double inewAngle)"
.br
.ti -1c
.RI "std::int32_t \fBcalibrate\fP ()"
.br
.ti -1c
.RI "double \fBcontrollerGet\fP () override"
.br
.ti -1c
.RI "bool \fBisCalibrating\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "double \fBreadAngle\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::uint8_t \fBport\fP"
.br
.ti -1c
.RI "IMUAxes \fBaxis\fP"
.br
.ti -1c
.RI "double \fBoffset\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::IMU::IMU (std::uint8_t iport, IMUAxes iaxis = \fRIMUAxes::z\fP)"
An inertial sensor on the given port\&. The \fBIMU\fP returns an angle about the selected axis in degrees\&.

.PP
.PP
.nf
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIiport\fP The port number in the range \fR[1, 21]\fP\&. 
.br
\fIiaxis\fP The axis of the inertial sensor to measure, default \fRIMUAxes::z\fP\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::int32_t okapi::IMU::calibrate ()"
Calibrate the \fBIMU\fP\&. Resets the rotation value to zero\&. Calibration is expected to take two seconds, but is bounded to five seconds\&.

.PP
\fBReturns\fP
.RS 4
\fR1\fP or \fRPROS_ERR\fP\&. 
.RE
.PP

.SS "double okapi::IMU::controllerGet ()\fR [override]\fP, \fR [virtual]\fP"
Get the sensor value for use in a control loop\&. This method might be automatically called in another thread by the controller\&.

.PP
\fBReturns\fP
.RS 4
The current sensor value or \fRPROS_ERR\fP\&. 
.RE
.PP

.PP
Implements \fBokapi::ControllerInput< double >\fP\&.
.SS "double okapi::IMU::get () const\fR [override]\fP, \fR [virtual]\fP"
Get the current rotation about the configured axis\&.

.PP
\fBReturns\fP
.RS 4
The current sensor value or \fRPROS_ERR\fP\&. 
.RE
.PP

.PP
Implements \fBokapi::RotarySensor\fP\&.
.SS "double okapi::IMU::getAcceleration () const"
Get the current acceleration along the configured axis\&.

.PP
\fBReturns\fP
.RS 4
The current sensor value or \fRPROS_ERR\fP\&. 
.RE
.PP

.SS "double okapi::IMU::getRemapped (double iupperBound = \fR1800\fP, double ilowerBound = \fR\-1800\fP) const"
Get the current sensor value remapped into the target range (\fR[-1800, 1800]\fP by default)\&.

.PP
\fBParameters\fP
.RS 4
\fIiupperBound\fP The upper bound of the range\&. 
.br
\fIilowerBound\fP The lower bound of the range\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The remapped sensor value\&. 
.RE
.PP

.SS "bool okapi::IMU::isCalibrating () const"

.PP
\fBReturns\fP
.RS 4
Whether the \fBIMU\fP is calibrating\&. 
.RE
.PP

.SS "double okapi::IMU::readAngle () const\fR [protected]\fP"
Get the current rotation about the configured axis\&. The internal offset is not accounted for or modified\&. This just reads from the sensor\&.

.PP
\fBReturns\fP
.RS 4
The current sensor value or \fRPROS_ERR\fP\&. 
.RE
.PP

.SS "std::int32_t okapi::IMU::reset ()\fR [override]\fP, \fR [virtual]\fP"
Reset the rotation value to zero\&.

.PP
\fBReturns\fP
.RS 4
\fR1\fP or \fRPROS_ERR\fP\&. 
.RE
.PP

.PP
Implements \fBokapi::ContinuousRotarySensor\fP\&.
.SS "std::int32_t okapi::IMU::reset (double inewAngle)"
Resets rotation value to desired value For example, \fRreset(0)\fP will reset the sensor to zero\&. But \fRreset(90)\fP will reset the sensor to 90 degrees\&.

.PP
\fBParameters\fP
.RS 4
\fIinewAngle\fP desired reset value 
.RE
.PP
\fBReturns\fP
.RS 4
\fR1\fP or \fRPROS_ERR\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
