.TH "okapi::ChassisScales" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ChassisScales
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChassisScales\fP (const std::initializer_list< QLength > &idimensions, double itpr, const std::shared_ptr< \fBLogger\fP > &ilogger=\fBLogger::getDefaultLogger\fP())"
.br
.ti -1c
.RI "\fBChassisScales\fP (const std::initializer_list< double > &iscales, double itpr, const std::shared_ptr< \fBLogger\fP > &ilogger=\fBLogger::getDefaultLogger\fP())"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QLength \fBwheelDiameter\fP"
.br
.ti -1c
.RI "QLength \fBwheelTrack\fP"
.br
.ti -1c
.RI "QLength \fBmiddleWheelDistance\fP"
.br
.ti -1c
.RI "QLength \fBmiddleWheelDiameter\fP"
.br
.ti -1c
.RI "double \fBstraight\fP"
.br
.ti -1c
.RI "double \fBturn\fP"
.br
.ti -1c
.RI "double \fBmiddle\fP"
.br
.ti -1c
.RI "double \fBtpr\fP"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBvalidateInputSize\fP (std::size_t inputSize, const std::shared_ptr< \fBLogger\fP > &logger)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::ChassisScales::ChassisScales (const std::initializer_list< QLength > & idimensions, double itpr, const std::shared_ptr< \fBLogger\fP > & ilogger = \fR\fBLogger::getDefaultLogger\fP()\fP)"
The scales a \fBChassisController\fP needs to do all of its closed-loop control\&. The first element is the wheel diameter, the second element is the wheel track\&. For three-encoder configurations, the length from the center of rotation to the middle wheel and the middle wheel diameter are passed as the third and fourth elements\&.

.PP
The wheel track is the center-to-center distance between the wheels (center-to-center meaning the width between the centers of both wheels)\&. For example, if you are using four inch omni wheels and there are 11\&.5 inches between the centers of each wheel, you would call the constructor like so: \fR\fBChassisScales\fP scales({4_in, 11\&.5_in}, imev5GreenTPR); // imev5GreenTPR for a green gearset\fP 
.PP
.nf
                      Wheel diameter

                       +-+      Center of rotation
                       | |      |
                       v v      +----------+ Length to middle wheel
                                |          | from center of rotation
              +--->    ===      |      === |
              |         +       v       +  |
              |        ++---------------++ |
              |        |                 | v
Wheel track   |        |                 |
              |        |        x        |+|  <-- Middle wheel
              |        |                 |
              |        |                 |
              |        ++---------------++
              |         +               +
              +--->    ===             ===

.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIidimensions\fP {wheel diameter, wheel track} or {wheel diameter, wheel track, length to middle wheel, middle wheel diameter}\&. 
.br
\fIitpr\fP The ticks per revolution of the encoders\&. 
.br
\fIilogger\fP The logger this instance will log to\&. 
.RE
.PP

.SS "okapi::ChassisScales::ChassisScales (const std::initializer_list< double > & iscales, double itpr, const std::shared_ptr< \fBLogger\fP > & ilogger = \fR\fBLogger::getDefaultLogger\fP()\fP)"
The scales a \fBChassisController\fP needs to do all of its closed-loop control\&. The first element is the straight scale, the second element is the turn scale\&. Optionally, the length from the center of rotation to the middle wheel and the middle scale can be passed as the third and fourth elements\&. The straight scale converts motor degrees to meters, the turn scale converts motor degrees to robot turn degrees, and the middle scale converts middle wheel degrees to meters\&.

.PP
\fBParameters\fP
.RS 4
\fIiscales\fP {straight scale, turn scale} or {straight scale, turn scale, length to middle wheel in meters, middle scale}\&. 
.br
\fIitpr\fP The ticks per revolution of the encoders\&. 
.br
\fIilogger\fP The logger this instance will log to\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
