.TH "okapi::Supplier< T >" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::Supplier< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <supplier\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSupplier\fP (std::function< T(void)> ifunc)"
.br
.ti -1c
.RI "T \fBget\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::function< T(void)> \fBfunc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class okapi::Supplier< T >"A supplier of instances of T\&.

.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP the type to supply 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> T \fBokapi::Supplier\fP< T >::get () const\fR [inline]\fP"
Get an instance of type T\&. This is usually a new instance, but it does not have to be\&. 
.PP
\fBReturns\fP
.RS 4
an instance of T 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
