.TH "okapi::SkidSteerModel" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::SkidSteerModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::ChassisModel\fP\&.
.PP
Inherited by \fBokapi::ThreeEncoderSkidSteerModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSkidSteerModel\fP (std::shared_ptr< \fBAbstractMotor\fP > ileftSideMotor, std::shared_ptr< \fBAbstractMotor\fP > irightSideMotor, std::shared_ptr< \fBContinuousRotarySensor\fP > ileftEnc, std::shared_ptr< \fBContinuousRotarySensor\fP > irightEnc, double imaxVelocity, double imaxVoltage)"
.br
.ti -1c
.RI "void \fBforward\fP (double ispeed) override"
.br
.ti -1c
.RI "void \fBdriveVector\fP (double iySpeed, double izRotation) override"
.br
.ti -1c
.RI "void \fBdriveVectorVoltage\fP (double iforwardSpeed, double iyaw) override"
.br
.ti -1c
.RI "void \fBrotate\fP (double ispeed) override"
.br
.ti -1c
.RI "void \fBstop\fP () override"
.br
.ti -1c
.RI "void \fBtank\fP (double ileftSpeed, double irightSpeed, double ithreshold=0) override"
.br
.ti -1c
.RI "void \fBarcade\fP (double iforwardSpeed, double iyaw, double ithreshold=0) override"
.br
.ti -1c
.RI "void \fBcurvature\fP (double iforwardSpeed, double icurvature, double ithreshold=0) override"
.br
.ti -1c
.RI "void \fBleft\fP (double ispeed) override"
.br
.ti -1c
.RI "void \fBright\fP (double ispeed) override"
.br
.ti -1c
.RI "std::valarray< std::int32_t > \fBgetSensorVals\fP () const override"
.br
.ti -1c
.RI "void \fBresetSensors\fP () override"
.br
.ti -1c
.RI "void \fBsetBrakeMode\fP (\fBAbstractMotor::brakeMode\fP mode) override"
.br
.ti -1c
.RI "void \fBsetEncoderUnits\fP (\fBAbstractMotor::encoderUnits\fP units) override"
.br
.ti -1c
.RI "void \fBsetGearing\fP (\fBAbstractMotor::gearset\fP gearset) override"
.br
.ti -1c
.RI "void \fBsetMaxVelocity\fP (double imaxVelocity) override"
.br
.ti -1c
.RI "double \fBgetMaxVelocity\fP () const override"
.br
.ti -1c
.RI "void \fBsetMaxVoltage\fP (double imaxVoltage) override"
.br
.ti -1c
.RI "double \fBgetMaxVoltage\fP () const override"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBgetLeftSideMotor\fP () const"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBgetRightSideMotor\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ChassisModel\fP
.in +1c
.ti -1c
.RI "\fBChassisModel\fP (const ChassisModel &)=delete"
.br
.ti -1c
.RI "ChassisModel & \fBoperator=\fP (const ChassisModel &)=delete"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBmaxVelocity\fP"
.br
.ti -1c
.RI "double \fBmaxVoltage\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBleftSideMotor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBrightSideMotor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBContinuousRotarySensor\fP > \fBleftSensor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBContinuousRotarySensor\fP > \fBrightSensor\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::SkidSteerModel::SkidSteerModel (std::shared_ptr< \fBAbstractMotor\fP > ileftSideMotor, std::shared_ptr< \fBAbstractMotor\fP > irightSideMotor, std::shared_ptr< \fBContinuousRotarySensor\fP > ileftEnc, std::shared_ptr< \fBContinuousRotarySensor\fP > irightEnc, double imaxVelocity, double imaxVoltage)"
Model for a skid steer drive (wheels parallel with robot's direction of motion)\&. When all motors are powered +100%, the robot should move forward in a straight line\&.

.PP
\fBParameters\fP
.RS 4
\fIileftSideMotor\fP The left side motor\&. 
.br
\fIirightSideMotor\fP The right side motor\&. 
.br
\fIileftEnc\fP The left side encoder\&. 
.br
\fIirightEnc\fP The right side encoder\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void okapi::SkidSteerModel::arcade (double iforwardSpeed, double iyaw, double ithreshold = \fR0\fP)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot with an arcade drive layout\&. Uses voltage mode\&.

.PP
\fBParameters\fP
.RS 4
\fIiforwardSpeed\fP speed in the forward direction 
.br
\fIiyaw\fP speed around the vertical axis 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::curvature (double iforwardSpeed, double icurvature, double ithreshold = \fR0\fP)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot with a curvature drive layout\&. The robot drives in constant radius turns where you control the curvature (inverse of radius) you drive in\&. This is advantageous because the forward speed will not affect the rate of turning\&. The algorithm switches to arcade if the forward speed is 0\&. Uses voltage mode\&.

.PP
\fBParameters\fP
.RS 4
\fIiforwardSpeed\fP speed in the forward direction 
.br
\fIicurvature\fP curvature (inverse of radius) to drive in 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::driveVector (double iySpeed, double izRotation)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot in an arc (using open-loop control)\&. Uses velocity mode\&. The algorithm is (approximately): leftPower = ySpeed + zRotation rightPower = ySpeed - zRotation

.PP
\fBParameters\fP
.RS 4
\fIiySpeed\fP speed on y axis (forward) 
.br
\fIizRotation\fP speed around z axis (up) 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::driveVectorVoltage (double iforwardSpeed, double iyaw)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot in an arc\&. Uses voltage mode\&. The algorithm is (approximately): leftPower = forwardSpeed + yaw rightPower = forwardSpeed - yaw

.PP
\fBParameters\fP
.RS 4
\fIiforwadSpeed\fP speed in the forward direction 
.br
\fIiyaw\fP speed around the vertical axis 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::forward (double ispeed)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot forwards (using open-loop control)\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIispeed\fP motor power 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "std::shared_ptr< \fBAbstractMotor\fP > okapi::SkidSteerModel::getLeftSideMotor () const"
Returns the left side motor\&.

.PP
\fBReturns\fP
.RS 4
the left side motor 
.RE
.PP

.SS "double okapi::SkidSteerModel::getMaxVelocity () const\fR [override]\fP, \fR [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The current maximum velocity\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "double okapi::SkidSteerModel::getMaxVoltage () const\fR [override]\fP, \fR [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The maximum voltage in mV in the range \fR[0-12000]\fP\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "std::shared_ptr< \fBAbstractMotor\fP > okapi::SkidSteerModel::getRightSideMotor () const"
Returns the left side motor\&.

.PP
\fBReturns\fP
.RS 4
the left side motor 
.RE
.PP

.SS "std::valarray< std::int32_t > okapi::SkidSteerModel::getSensorVals () const\fR [override]\fP, \fR [virtual]\fP"
Read the sensors\&.

.PP
\fBReturns\fP
.RS 4
sensor readings in the format {left, right} 
.RE
.PP

.PP
Implements \fBokapi::ReadOnlyChassisModel\fP\&.
.PP
Reimplemented in \fBokapi::ThreeEncoderSkidSteerModel\fP\&.
.SS "void okapi::SkidSteerModel::left (double ispeed)\fR [override]\fP, \fR [virtual]\fP"
Power the left side motors\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIispeed\fP The motor power\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::resetSensors ()\fR [override]\fP, \fR [virtual]\fP"
Reset the sensors to their zero point\&. 
.PP
Implements \fBokapi::ChassisModel\fP\&.
.PP
Reimplemented in \fBokapi::ThreeEncoderSkidSteerModel\fP\&.
.SS "void okapi::SkidSteerModel::right (double ispeed)\fR [override]\fP, \fR [virtual]\fP"
Power the right side motors\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIispeed\fP The motor power\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::rotate (double ispeed)\fR [override]\fP, \fR [virtual]\fP"
Turn the robot clockwise (using open-loop control)\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIispeed\fP motor power 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::setBrakeMode (\fBAbstractMotor::brakeMode\fP mode)\fR [override]\fP, \fR [virtual]\fP"
Set the brake mode for each motor\&.

.PP
\fBParameters\fP
.RS 4
\fImode\fP new brake mode 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::setEncoderUnits (\fBAbstractMotor::encoderUnits\fP units)\fR [override]\fP, \fR [virtual]\fP"
Set the encoder units for each motor\&.

.PP
\fBParameters\fP
.RS 4
\fIunits\fP new motor encoder units 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::setGearing (\fBAbstractMotor::gearset\fP gearset)\fR [override]\fP, \fR [virtual]\fP"
Set the gearset for each motor\&.

.PP
\fBParameters\fP
.RS 4
\fIgearset\fP new motor gearset 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::setMaxVelocity (double imaxVelocity)\fR [override]\fP, \fR [virtual]\fP"
Sets a new maximum velocity in RPM\&. The usable maximum depends on the maximum velocity of the currently installed gearset\&. If the configured maximum velocity is greater than the attainable maximum velocity from the currently installed gearset, the \fBChassisModel\fP will still scale to that velocity\&.

.PP
\fBParameters\fP
.RS 4
\fIimaxVelocity\fP The new maximum velocity\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::setMaxVoltage (double imaxVoltage)\fR [override]\fP, \fR [virtual]\fP"
Sets a new maximum voltage in mV in the range \fR[0-12000]\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIimaxVoltage\fP The new maximum voltage\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::stop ()\fR [override]\fP, \fR [virtual]\fP"
Stop the robot (set all the motors to 0)\&. Uses velocity mode\&. 
.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::SkidSteerModel::tank (double ileftSpeed, double irightSpeed, double ithreshold = \fR0\fP)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot with a tank drive layout\&. Uses voltage mode\&.

.PP
\fBParameters\fP
.RS 4
\fIileftSpeed\fP left side speed 
.br
\fIirightSpeed\fP right side speed 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
