.TH "okapi::Rate" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::Rate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::AbstractRate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdelay\fP (QFrequency ihz) override"
.br
.ti -1c
.RI "void \fBdelayUntil\fP (QTime itime) override"
.br
.ti -1c
.RI "void \fBdelayUntil\fP (uint32_t ims) override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::uint32_t \fBlastTime\fP {0}"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void okapi::Rate::delay (QFrequency ihz)\fR [override]\fP, \fR [virtual]\fP"
Delay the current task such that it runs at the given frequency\&. The first delay will run for 1000/(ihz)\&. Subsequent delays will adjust according to the previous runtime of the task\&.

.PP
\fBParameters\fP
.RS 4
\fIihz\fP the frequency 
.RE
.PP

.PP
Implements \fBokapi::AbstractRate\fP\&.
.SS "void okapi::Rate::delayUntil (QTime itime)\fR [override]\fP, \fR [virtual]\fP"
Delay the current task until itime has passed\&. This method can be used by periodic tasks to ensure a consistent execution frequency\&.

.PP
\fBParameters\fP
.RS 4
\fIitime\fP the time period 
.RE
.PP

.PP
Implements \fBokapi::AbstractRate\fP\&.
.SS "void okapi::Rate::delayUntil (uint32_t ims)\fR [override]\fP, \fR [virtual]\fP"
Delay the current task until ims milliseconds have passed\&. This method can be used by periodic tasks to ensure a consistent execution frequency\&.

.PP
\fBParameters\fP
.RS 4
\fIims\fP the time period 
.RE
.PP

.PP
Implements \fBokapi::AbstractRate\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
