.TH "okapi::IterativeVelPIDController::Gains" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::IterativeVelPIDController::Gains
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBGains\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBGains\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBkP\fP {0}"
.br
.ti -1c
.RI "double \fBkD\fP {0}"
.br
.ti -1c
.RI "double \fBkF\fP {0}"
.br
.ti -1c
.RI "double \fBkSF\fP {0}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
