.TH "okapi::XDriveModel" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::XDriveModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::ChassisModel\fP\&.
.PP
Inherited by \fBokapi::ThreeEncoderXDriveModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXDriveModel\fP (std::shared_ptr< \fBAbstractMotor\fP > itopLeftMotor, std::shared_ptr< \fBAbstractMotor\fP > itopRightMotor, std::shared_ptr< \fBAbstractMotor\fP > ibottomRightMotor, std::shared_ptr< \fBAbstractMotor\fP > ibottomLeftMotor, std::shared_ptr< \fBContinuousRotarySensor\fP > ileftEnc, std::shared_ptr< \fBContinuousRotarySensor\fP > irightEnc, double imaxVelocity, double imaxVoltage)"
.br
.ti -1c
.RI "void \fBforward\fP (double ipower) override"
.br
.ti -1c
.RI "void \fBdriveVector\fP (double iforwardSpeed, double iyaw) override"
.br
.ti -1c
.RI "void \fBdriveVectorVoltage\fP (double iforwardSpeed, double iyaw) override"
.br
.ti -1c
.RI "void \fBrotate\fP (double ipower) override"
.br
.ti -1c
.RI "void \fBstrafe\fP (double ipower)"
.br
.ti -1c
.RI "void \fBstrafeVector\fP (double istrafeSpeed, double iyaw)"
.br
.ti -1c
.RI "void \fBstop\fP () override"
.br
.ti -1c
.RI "void \fBtank\fP (double ileftSpeed, double irightSpeed, double ithreshold=0) override"
.br
.ti -1c
.RI "void \fBarcade\fP (double iforwardSpeed, double iyaw, double ithreshold=0) override"
.br
.ti -1c
.RI "void \fBcurvature\fP (double iforwardSpeed, double icurvature, double ithreshold=0) override"
.br
.ti -1c
.RI "virtual void \fBxArcade\fP (double irightSpeed, double iforwardSpeed, double iyaw, double ithreshold=0)"
.br
.ti -1c
.RI "virtual void \fBfieldOrientedXArcade\fP (double ixSpeed, double iySpeed, double iyaw, QAngle iangle, double ithreshold=0)"
.br
.ti -1c
.RI "void \fBleft\fP (double ispeed) override"
.br
.ti -1c
.RI "void \fBright\fP (double ispeed) override"
.br
.ti -1c
.RI "std::valarray< std::int32_t > \fBgetSensorVals\fP () const override"
.br
.ti -1c
.RI "void \fBresetSensors\fP () override"
.br
.ti -1c
.RI "void \fBsetBrakeMode\fP (\fBAbstractMotor::brakeMode\fP mode) override"
.br
.ti -1c
.RI "void \fBsetEncoderUnits\fP (\fBAbstractMotor::encoderUnits\fP units) override"
.br
.ti -1c
.RI "void \fBsetGearing\fP (\fBAbstractMotor::gearset\fP gearset) override"
.br
.ti -1c
.RI "void \fBsetMaxVelocity\fP (double imaxVelocity) override"
.br
.ti -1c
.RI "double \fBgetMaxVelocity\fP () const override"
.br
.ti -1c
.RI "void \fBsetMaxVoltage\fP (double imaxVoltage) override"
.br
.ti -1c
.RI "double \fBgetMaxVoltage\fP () const override"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBgetTopLeftMotor\fP () const"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBgetTopRightMotor\fP () const"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBgetBottomRightMotor\fP () const"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBgetBottomLeftMotor\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ChassisModel\fP
.in +1c
.ti -1c
.RI "\fBChassisModel\fP (const ChassisModel &)=delete"
.br
.ti -1c
.RI "ChassisModel & \fBoperator=\fP (const ChassisModel &)=delete"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBmaxVelocity\fP"
.br
.ti -1c
.RI "double \fBmaxVoltage\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBtopLeftMotor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBtopRightMotor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBbottomRightMotor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBAbstractMotor\fP > \fBbottomLeftMotor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBContinuousRotarySensor\fP > \fBleftSensor\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBContinuousRotarySensor\fP > \fBrightSensor\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::XDriveModel::XDriveModel (std::shared_ptr< \fBAbstractMotor\fP > itopLeftMotor, std::shared_ptr< \fBAbstractMotor\fP > itopRightMotor, std::shared_ptr< \fBAbstractMotor\fP > ibottomRightMotor, std::shared_ptr< \fBAbstractMotor\fP > ibottomLeftMotor, std::shared_ptr< \fBContinuousRotarySensor\fP > ileftEnc, std::shared_ptr< \fBContinuousRotarySensor\fP > irightEnc, double imaxVelocity, double imaxVoltage)"
Model for an x drive (wheels at 45 deg from a skid steer drive)\&. When all motors are powered +100%, the robot should move forward in a straight line\&.

.PP
\fBParameters\fP
.RS 4
\fIitopLeftMotor\fP The top left motor\&. 
.br
\fIitopRightMotor\fP The top right motor\&. 
.br
\fIibottomRightMotor\fP The bottom right motor\&. 
.br
\fIibottomLeftMotor\fP The bottom left motor\&. 
.br
\fIileftEnc\fP The left side encoder\&. 
.br
\fIirightEnc\fP The right side encoder\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void okapi::XDriveModel::arcade (double iforwardSpeed, double iyaw, double ithreshold = \fR0\fP)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot with an arcade drive layout\&. Uses voltage mode\&.

.PP
\fBParameters\fP
.RS 4
\fIiforwardSpeed\fP speed in the forward direction 
.br
\fIiyaw\fP speed around the vertical axis 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::curvature (double iforwardSpeed, double icurvature, double ithreshold = \fR0\fP)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot with a curvature drive layout\&. The robot drives in constant radius turns where you control the curvature (inverse of radius) you drive in\&. This is advantageous because the forward speed will not affect the rate of turning\&. The algorithm switches to arcade if the forward speed is 0\&. Uses voltage mode\&.

.PP
\fBParameters\fP
.RS 4
\fIiforwardSpeed\fP speed forward direction 
.br
\fIicurvature\fP curvature (inverse of radius) to drive in 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::driveVector (double iforwardSpeed, double iyaw)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot in an arc (using open-loop control)\&. Uses velocity mode\&. The algorithm is (approximately): leftPower = forwardSpeed + yaw rightPower = forwardSpeed - yaw

.PP
\fBParameters\fP
.RS 4
\fIiforwardSpeed\fP speed in the forward direction 
.br
\fIiyaw\fP speed around the vertical axis 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::driveVectorVoltage (double iforwardSpeed, double iyaw)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot in an arc\&. Uses voltage mode\&. The algorithm is (approximately): leftPower = forwardSpeed + yaw rightPower = forwardSpeed - yaw

.PP
\fBParameters\fP
.RS 4
\fIiforwadSpeed\fP speed in the forward direction 
.br
\fIiyaw\fP speed around the vertical axis 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "virtual void okapi::XDriveModel::fieldOrientedXArcade (double ixSpeed, double iySpeed, double iyaw, QAngle iangle, double ithreshold = \fR0\fP)\fR [virtual]\fP"
Drive the robot with a field-oriented arcade drive layout\&. Uses voltage mode\&. For example: Both \fRfieldOrientedXArcade(1, 0, 0, 0_deg)\fP and \fRfieldOrientedXArcade(1, 0, 0, 90_deg)\fP will drive the chassis in the forward/north direction\&. In other words, no matter the robot's heading, the robot will move forward/north when you tell it to move forward/north and will move right/east when you tell it to move right/east\&.

.PP
\fBParameters\fP
.RS 4
\fIixSpeed\fP forward speed -- (\fR+1\fP) forward, (\fR-1\fP) backward 
.br
\fIiySpeed\fP sideways speed -- (\fR+1\fP) right, (\fR-1\fP) left 
.br
\fIiyaw\fP turn speed -- (\fR+1\fP) clockwise, (\fR-1\fP) counter-clockwise 
.br
\fIiangle\fP current chassis angle (\fR0_deg\fP = no correction, winds clockwise) 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP

.SS "void okapi::XDriveModel::forward (double ipower)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot forwards (using open-loop control)\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIispeed\fP motor power 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "std::shared_ptr< \fBAbstractMotor\fP > okapi::XDriveModel::getBottomLeftMotor () const"
Returns the bottom left motor\&.

.PP
\fBReturns\fP
.RS 4
the bottom left motor 
.RE
.PP

.SS "std::shared_ptr< \fBAbstractMotor\fP > okapi::XDriveModel::getBottomRightMotor () const"
Returns the bottom right motor\&.

.PP
\fBReturns\fP
.RS 4
the bottom right motor 
.RE
.PP

.SS "double okapi::XDriveModel::getMaxVelocity () const\fR [override]\fP, \fR [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The current maximum velocity\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "double okapi::XDriveModel::getMaxVoltage () const\fR [override]\fP, \fR [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The maximum voltage in mV in the range \fR[0-12000]\fP\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "std::valarray< std::int32_t > okapi::XDriveModel::getSensorVals () const\fR [override]\fP, \fR [virtual]\fP"
Read the sensors\&.

.PP
\fBReturns\fP
.RS 4
sensor readings in the format {left, right} 
.RE
.PP

.PP
Implements \fBokapi::ReadOnlyChassisModel\fP\&.
.SS "std::shared_ptr< \fBAbstractMotor\fP > okapi::XDriveModel::getTopLeftMotor () const"
Returns the top left motor\&.

.PP
\fBReturns\fP
.RS 4
the top left motor 
.RE
.PP

.SS "std::shared_ptr< \fBAbstractMotor\fP > okapi::XDriveModel::getTopRightMotor () const"
Returns the top right motor\&.

.PP
\fBReturns\fP
.RS 4
the top right motor 
.RE
.PP

.SS "void okapi::XDriveModel::left (double ispeed)\fR [override]\fP, \fR [virtual]\fP"
Power the left side motors\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIispeed\fP The motor power\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::resetSensors ()\fR [override]\fP, \fR [virtual]\fP"
Reset the sensors to their zero point\&. 
.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::right (double ispeed)\fR [override]\fP, \fR [virtual]\fP"
Power the right side motors\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIispeed\fP The motor power\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::rotate (double ipower)\fR [override]\fP, \fR [virtual]\fP"
Turn the robot clockwise (using open-loop control)\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIipower\fP motor power 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::setBrakeMode (\fBAbstractMotor::brakeMode\fP mode)\fR [override]\fP, \fR [virtual]\fP"
Set the brake mode for each motor\&.

.PP
\fBParameters\fP
.RS 4
\fImode\fP new brake mode 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::setEncoderUnits (\fBAbstractMotor::encoderUnits\fP units)\fR [override]\fP, \fR [virtual]\fP"
Set the encoder units for each motor\&.

.PP
\fBParameters\fP
.RS 4
\fIunits\fP new motor encoder units 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::setGearing (\fBAbstractMotor::gearset\fP gearset)\fR [override]\fP, \fR [virtual]\fP"
Set the gearset for each motor\&.

.PP
\fBParameters\fP
.RS 4
\fIgearset\fP new motor gearset 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::setMaxVelocity (double imaxVelocity)\fR [override]\fP, \fR [virtual]\fP"
Sets a new maximum velocity in RPM\&. The usable maximum depends on the maximum velocity of the currently installed gearset\&. If the configured maximum velocity is greater than the attainable maximum velocity from the currently installed gearset, the \fBChassisModel\fP will still scale to that velocity\&.

.PP
\fBParameters\fP
.RS 4
\fIimaxVelocity\fP The new maximum velocity\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::setMaxVoltage (double imaxVoltage)\fR [override]\fP, \fR [virtual]\fP"
Sets a new maximum voltage in mV in the range \fR[0-12000]\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIimaxVoltage\fP The new maximum voltage\&. 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::stop ()\fR [override]\fP, \fR [virtual]\fP"
Stop the robot (set all the motors to 0)\&. Uses velocity mode\&. 
.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "void okapi::XDriveModel::strafe (double ipower)"
Drive the robot side-ways (using open-loop control) where positive ipower is to the right and negative ipower is to the left\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIispeed\fP motor power 
.RE
.PP

.SS "void okapi::XDriveModel::strafeVector (double istrafeSpeed, double iyaw)"
Strafe the robot in an arc (using open-loop control) where positive istrafeSpeed is to the right and negative istrafeSpeed is to the left\&. Uses velocity mode\&. The algorithm is (approximately): topLeftPower = -1 * istrafeSpeed + yaw topRightPower = istrafeSpeed - yaw bottomRightPower = -1 * istrafeSpeed - yaw bottomLeftPower = istrafeSpeed + yaw

.PP
\fBParameters\fP
.RS 4
\fIistrafeSpeed\fP speed to the right 
.br
\fIiyaw\fP speed around the vertical axis 
.RE
.PP

.SS "void okapi::XDriveModel::tank (double ileftSpeed, double irightSpeed, double ithreshold = \fR0\fP)\fR [override]\fP, \fR [virtual]\fP"
Drive the robot with a tank drive layout\&. Uses voltage mode\&.

.PP
\fBParameters\fP
.RS 4
\fIileftSpeed\fP left side speed 
.br
\fIirightSpeed\fP right side speed 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP

.PP
Implements \fBokapi::ChassisModel\fP\&.
.SS "virtual void okapi::XDriveModel::xArcade (double irightSpeed, double iforwardSpeed, double iyaw, double ithreshold = \fR0\fP)\fR [virtual]\fP"
Drive the robot with an arcade drive layout\&. Uses voltage mode\&.

.PP
\fBParameters\fP
.RS 4
\fIirightSpeed\fP speed to the right 
.br
\fIiforwardSpeed\fP speed in the forward direction 
.br
\fIiyaw\fP speed around the vertical axis 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
