.TH "okapi::ControllerButton" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ControllerButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::ButtonBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControllerButton\fP (ControllerDigital ibtn, bool iinverted=false)"
.br
.ti -1c
.RI "\fBControllerButton\fP (ControllerId icontroller, ControllerDigital ibtn, bool iinverted=false)"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ButtonBase\fP
.in +1c
.ti -1c
.RI "\fBButtonBase\fP (bool iinverted=false)"
.br
.ti -1c
.RI "bool \fBisPressed\fP () override"
.br
.ti -1c
.RI "bool \fBchanged\fP () override"
.br
.ti -1c
.RI "bool \fBchangedToPressed\fP () override"
.br
.ti -1c
.RI "bool \fBchangedToReleased\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBokapi::AbstractButton\fP
.in +1c
.ti -1c
.RI "virtual bool \fBcontrollerGet\fP () override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBcurrentlyPressed\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "pros::controller_id_e_t \fBid\fP"
.br
.ti -1c
.RI "pros::controller_digital_e_t \fBbtn\fP"
.br
.in -1c

Protected Attributes inherited from \fBokapi::ButtonBase\fP
.in +1c
.ti -1c
.RI "bool \fBinverted\fP {false}"
.br
.ti -1c
.RI "bool \fBwasPressedLast_c\fP {false}"
.br
.ti -1c
.RI "bool \fBwasPressedLast_ctp\fP {false}"
.br
.ti -1c
.RI "bool \fBwasPressedLast_ctr\fP {false}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::ControllerButton::ControllerButton (ControllerDigital ibtn, bool iinverted = \fRfalse\fP)"
A button on a \fBController\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIibtn\fP The button id\&. 
.br
\fIiinverted\fP Whether the button is inverted (default pressed instead of default released)\&. 
.RE
.PP

.SS "okapi::ControllerButton::ControllerButton (ControllerId icontroller, ControllerDigital ibtn, bool iinverted = \fRfalse\fP)"
A button on a \fBController\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIicontroller\fP The \fBController\fP the button is on\&. 
.br
\fIibtn\fP The button id\&. 
.br
\fIiinverted\fP Whether the button is inverted (default pressed instead of default released)\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual bool okapi::ControllerButton::currentlyPressed ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBokapi::ButtonBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
