.TH "okapi::ADIButton" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ADIButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::ButtonBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBADIButton\fP (std::uint8_t iport, bool iinverted=false)"
.br
.ti -1c
.RI "\fBADIButton\fP (std::pair< std::uint8_t, std::uint8_t > iports, bool iinverted=false)"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ButtonBase\fP
.in +1c
.ti -1c
.RI "\fBButtonBase\fP (bool iinverted=false)"
.br
.ti -1c
.RI "bool \fBisPressed\fP () override"
.br
.ti -1c
.RI "bool \fBchanged\fP () override"
.br
.ti -1c
.RI "bool \fBchangedToPressed\fP () override"
.br
.ti -1c
.RI "bool \fBchangedToReleased\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBokapi::AbstractButton\fP
.in +1c
.ti -1c
.RI "virtual bool \fBcontrollerGet\fP () override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBcurrentlyPressed\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::uint8_t \fBsmartPort\fP"
.br
.ti -1c
.RI "std::uint8_t \fBport\fP"
.br
.in -1c

Protected Attributes inherited from \fBokapi::ButtonBase\fP
.in +1c
.ti -1c
.RI "bool \fBinverted\fP {false}"
.br
.ti -1c
.RI "bool \fBwasPressedLast_c\fP {false}"
.br
.ti -1c
.RI "bool \fBwasPressedLast_ctp\fP {false}"
.br
.ti -1c
.RI "bool \fBwasPressedLast_ctr\fP {false}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::ADIButton::ADIButton (std::uint8_t iport, bool iinverted = \fRfalse\fP)"
A button in an ADI port\&.

.PP
.PP
.nf
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIiport\fP The ADI port number (\fR[1, 8]\fP, \fR[a, h]\fP, \fR[A, H]\fP)\&. 
.br
\fIiinverted\fP Whether the button is inverted (\fRtrue\fP meaning default pressed and \fRfalse\fP meaning default not pressed)\&. 
.RE
.PP

.SS "okapi::ADIButton::ADIButton (std::pair< std::uint8_t, std::uint8_t > iports, bool iinverted = \fRfalse\fP)"
A button in an ADI port\&.

.PP
.PP
.nf
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIiports\fP The ports the button is plugged in to in the order \fR{smart port, button port}\fP\&. The smart port is the smart port number (\fR[1, 21]\fP)\&. The button port is the ADI port number (\fR[1, 8]\fP, \fR[a, h]\fP, \fR[A, H]\fP)\&. 
.br
\fIiinverted\fP Whether the button is inverted (\fRtrue\fP meaning default pressed and \fRfalse\fP meaning default not pressed)\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual bool okapi::ADIButton::currentlyPressed ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBokapi::ButtonBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
