.TH "okapi::ChassisController" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ChassisController
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::OdomChassisController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChassisController\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBmoveDistance\fP (QLength itarget)=0"
.br
.ti -1c
.RI "virtual void \fBmoveRaw\fP (double itarget)=0"
.br
.ti -1c
.RI "virtual void \fBmoveDistanceAsync\fP (QLength itarget)=0"
.br
.ti -1c
.RI "virtual void \fBmoveRawAsync\fP (double itarget)=0"
.br
.ti -1c
.RI "virtual void \fBturnAngle\fP (QAngle idegTarget)=0"
.br
.ti -1c
.RI "virtual void \fBturnRaw\fP (double idegTarget)=0"
.br
.ti -1c
.RI "virtual void \fBturnAngleAsync\fP (QAngle idegTarget)=0"
.br
.ti -1c
.RI "virtual void \fBturnRawAsync\fP (double idegTarget)=0"
.br
.ti -1c
.RI "virtual void \fBsetTurnsMirrored\fP (bool ishouldMirror)=0"
.br
.ti -1c
.RI "virtual bool \fBisSettled\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBwaitUntilSettled\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBstop\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBsetMaxVelocity\fP (double imaxVelocity)=0"
.br
.ti -1c
.RI "virtual double \fBgetMaxVelocity\fP () const =0"
.br
.ti -1c
.RI "virtual \fBChassisScales\fP \fBgetChassisScales\fP () const =0"
.br
.ti -1c
.RI "virtual \fBAbstractMotor::GearsetRatioPair\fP \fBgetGearsetRatioPair\fP () const =0"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBChassisModel\fP > \fBgetModel\fP ()=0"
.br
.ti -1c
.RI "virtual \fBChassisModel\fP & \fBmodel\fP ()=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::ChassisController::ChassisController ()\fR [explicit]\fP, \fR [default]\fP"
A \fBChassisController\fP adds a closed-loop layer on top of a \fBChassisModel\fP\&. moveDistance and turnAngle both use closed-loop control to move the robot\&. There are passthrough functions for everything defined in \fBChassisModel\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIimodel\fP underlying \fBChassisModel\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBChassisScales\fP okapi::ChassisController::getChassisScales () const\fR [pure virtual]\fP"
Get the \fBChassisScales\fP\&. 
.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual \fBAbstractMotor::GearsetRatioPair\fP okapi::ChassisController::getGearsetRatioPair () const\fR [pure virtual]\fP"
Get the GearsetRatioPair\&. 
.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual double okapi::ChassisController::getMaxVelocity () const\fR [pure virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The maximum velocity in RPM [0-600]\&. 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual std::shared_ptr< \fBChassisModel\fP > okapi::ChassisController::getModel ()\fR [pure virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The internal \fBChassisModel\fP\&. 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual bool okapi::ChassisController::isSettled ()\fR [pure virtual]\fP"
Checks whether the internal controllers are currently settled\&.

.PP
\fBReturns\fP
.RS 4
Whether this \fBChassisController\fP is settled\&. 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual \fBChassisModel\fP & okapi::ChassisController::model ()\fR [pure virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The internal \fBChassisModel\fP\&. 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::moveDistance (QLength itarget)\fR [pure virtual]\fP"
Drives the robot straight for a distance (using closed-loop control)\&.

.PP
\fBParameters\fP
.RS 4
\fIitarget\fP distance to travel 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::moveDistanceAsync (QLength itarget)\fR [pure virtual]\fP"
Sets the target distance for the robot to drive straight (using closed-loop control)\&.

.PP
\fBParameters\fP
.RS 4
\fIitarget\fP distance to travel 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::moveRaw (double itarget)\fR [pure virtual]\fP"
Drives the robot straight for a distance (using closed-loop control)\&.

.PP
\fBParameters\fP
.RS 4
\fIitarget\fP distance to travel in motor degrees 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::moveRawAsync (double itarget)\fR [pure virtual]\fP"
Sets the target distance for the robot to drive straight (using closed-loop control)\&.

.PP
\fBParameters\fP
.RS 4
\fIitarget\fP distance to travel in motor degrees 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::setMaxVelocity (double imaxVelocity)\fR [pure virtual]\fP"
Sets a new maximum velocity in RPM [0-600]\&.

.PP
\fBParameters\fP
.RS 4
\fIimaxVelocity\fP The new maximum velocity\&. 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::setTurnsMirrored (bool ishouldMirror)\fR [pure virtual]\fP"
Sets whether turns should be mirrored\&.

.PP
\fBParameters\fP
.RS 4
\fIishouldMirror\fP whether turns should be mirrored 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::stop ()\fR [pure virtual]\fP"
Interrupts the current movement to stop the robot\&. 
.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::turnAngle (QAngle idegTarget)\fR [pure virtual]\fP"
Turns the robot clockwise in place (using closed-loop control)\&.

.PP
\fBParameters\fP
.RS 4
\fIidegTarget\fP angle to turn for 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::turnAngleAsync (QAngle idegTarget)\fR [pure virtual]\fP"
Sets the target angle for the robot to turn clockwise in place (using closed-loop control)\&.

.PP
\fBParameters\fP
.RS 4
\fIidegTarget\fP angle to turn for 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::turnRaw (double idegTarget)\fR [pure virtual]\fP"
Turns the robot clockwise in place (using closed-loop control)\&.

.PP
\fBParameters\fP
.RS 4
\fIidegTarget\fP angle to turn for in motor degrees 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::turnRawAsync (double idegTarget)\fR [pure virtual]\fP"
Sets the target angle for the robot to turn clockwise in place (using closed-loop control)\&.

.PP
\fBParameters\fP
.RS 4
\fIidegTarget\fP angle to turn for in motor degrees 
.RE
.PP

.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.
.SS "virtual void okapi::ChassisController::waitUntilSettled ()\fR [pure virtual]\fP"
Delays until the currently executing movement completes\&. 
.PP
Implemented in \fBokapi::ChassisControllerIntegrated\fP, \fBokapi::ChassisControllerPID\fP, and \fBokapi::DefaultOdomChassisController\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
