.TH "okapi::ChassisModel" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ChassisModel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <chassisModel\&.hpp>\fP
.PP
Inherits \fBokapi::ReadOnlyChassisModel\fP\&.
.PP
Inherited by \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChassisModel\fP (const ChassisModel &)=delete"
.br
.ti -1c
.RI "ChassisModel & \fBoperator=\fP (const ChassisModel &)=delete"
.br
.ti -1c
.RI "virtual void \fBforward\fP (double ispeed)=0"
.br
.ti -1c
.RI "virtual void \fBdriveVector\fP (double iforwardSpeed, double iyaw)=0"
.br
.ti -1c
.RI "virtual void \fBdriveVectorVoltage\fP (double iforwardSpeed, double iyaw)=0"
.br
.ti -1c
.RI "virtual void \fBrotate\fP (double ispeed)=0"
.br
.ti -1c
.RI "virtual void \fBstop\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBtank\fP (double ileftSpeed, double irightSpeed, double ithreshold=0)=0"
.br
.ti -1c
.RI "virtual void \fBarcade\fP (double iforwardSpeed, double iyaw, double ithreshold=0)=0"
.br
.ti -1c
.RI "virtual void \fBcurvature\fP (double iforwardSpeed, double icurvature, double ithreshold=0)=0"
.br
.ti -1c
.RI "virtual void \fBleft\fP (double ispeed)=0"
.br
.ti -1c
.RI "virtual void \fBright\fP (double ispeed)=0"
.br
.ti -1c
.RI "virtual void \fBresetSensors\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBsetBrakeMode\fP (\fBAbstractMotor::brakeMode\fP mode)=0"
.br
.ti -1c
.RI "virtual void \fBsetEncoderUnits\fP (\fBAbstractMotor::encoderUnits\fP units)=0"
.br
.ti -1c
.RI "virtual void \fBsetGearing\fP (\fBAbstractMotor::gearset\fP gearset)=0"
.br
.ti -1c
.RI "virtual void \fBsetMaxVelocity\fP (double imaxVelocity)=0"
.br
.ti -1c
.RI "virtual double \fBgetMaxVelocity\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBsetMaxVoltage\fP (double imaxVoltage)=0"
.br
.ti -1c
.RI "virtual double \fBgetMaxVoltage\fP () const =0"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ReadOnlyChassisModel\fP
.in +1c
.ti -1c
.RI "virtual std::valarray< std::int32_t > \fBgetSensorVals\fP () const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
A version of the \fBReadOnlyChassisModel\fP that also supports write methods, such as setting motor speed\&. Because this class can write to motors, there can only be one owner and as such copying is disabled\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual void okapi::ChassisModel::arcade (double iforwardSpeed, double iyaw, double ithreshold = \fR0\fP)\fR [pure virtual]\fP"
Drive the robot with an arcade drive layout\&. Uses voltage mode\&.

.PP
\fBParameters\fP
.RS 4
\fIiforwardSpeed\fP speed forward direction 
.br
\fIiyaw\fP speed around the vertical axis 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::curvature (double iforwardSpeed, double icurvature, double ithreshold = \fR0\fP)\fR [pure virtual]\fP"
Drive the robot with a curvature drive layout\&. The robot drives in constant radius turns where you control the curvature (inverse of radius) you drive in\&. This is advantageous because the forward speed will not affect the rate of turning\&. The algorithm switches to arcade if the forward speed is 0\&. Uses voltage mode\&.

.PP
\fBParameters\fP
.RS 4
\fIiforwardSpeed\fP speed in the forward direction 
.br
\fIicurvature\fP curvature (inverse of radius) to drive in 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::driveVector (double iforwardSpeed, double iyaw)\fR [pure virtual]\fP"
Drive the robot in an arc (using open-loop control)\&. Uses velocity mode\&. The algorithm is (approximately): leftPower = forwardSpeed + yaw rightPower = forwardSpeed - yaw

.PP
\fBParameters\fP
.RS 4
\fIiforwadSpeed\fP speed in the forward direction 
.br
\fIiyaw\fP speed around the vertical axis 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::driveVectorVoltage (double iforwardSpeed, double iyaw)\fR [pure virtual]\fP"
Drive the robot in an arc\&. Uses voltage mode\&. The algorithm is (approximately): leftPower = forwardSpeed + yaw rightPower = forwardSpeed - yaw

.PP
\fBParameters\fP
.RS 4
\fIiforwadSpeed\fP speed in the forward direction 
.br
\fIiyaw\fP speed around the vertical axis 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::forward (double ispeed)\fR [pure virtual]\fP"
Drive the robot forwards (using open-loop control)\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIipower\fP motor power 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual double okapi::ChassisModel::getMaxVelocity () const\fR [pure virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The current maximum velocity\&. 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual double okapi::ChassisModel::getMaxVoltage () const\fR [pure virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The maximum voltage in mV \fR[0-12000]\fP\&. 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::left (double ispeed)\fR [pure virtual]\fP"
Power the left side motors\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIipower\fP motor power 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::resetSensors ()\fR [pure virtual]\fP"
Reset the sensors to their zero point\&. 
.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, \fBokapi::ThreeEncoderSkidSteerModel\fP, \fBokapi::ThreeEncoderXDriveModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::right (double ispeed)\fR [pure virtual]\fP"
Power the right side motors\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIipower\fP motor power 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::rotate (double ispeed)\fR [pure virtual]\fP"
Turn the robot clockwise (using open-loop control)\&. Uses velocity mode\&.

.PP
\fBParameters\fP
.RS 4
\fIispeed\fP motor power 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::setBrakeMode (\fBAbstractMotor::brakeMode\fP mode)\fR [pure virtual]\fP"
Set the brake mode for each motor\&.

.PP
\fBParameters\fP
.RS 4
\fImode\fP new brake mode 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::setEncoderUnits (\fBAbstractMotor::encoderUnits\fP units)\fR [pure virtual]\fP"
Set the encoder units for each motor\&.

.PP
\fBParameters\fP
.RS 4
\fIunits\fP new motor encoder units 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::setGearing (\fBAbstractMotor::gearset\fP gearset)\fR [pure virtual]\fP"
Set the gearset for each motor\&.

.PP
\fBParameters\fP
.RS 4
\fIgearset\fP new motor gearset 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::setMaxVelocity (double imaxVelocity)\fR [pure virtual]\fP"
Sets a new maximum velocity in RPM\&. The usable maximum depends on the maximum velocity of the currently installed gearset\&. If the configured maximum velocity is greater than the attainable maximum velocity from the currently installed gearset, the \fBChassisModel\fP will still scale to that velocity\&.

.PP
\fBParameters\fP
.RS 4
\fIimaxVelocity\fP The new maximum velocity\&. 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::setMaxVoltage (double imaxVoltage)\fR [pure virtual]\fP"
Sets a new maximum voltage in mV in the range \fR[0-12000]\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIimaxVoltage\fP The new maximum voltage\&. 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::stop ()\fR [pure virtual]\fP"
Stop the robot (set all the motors to 0)\&. Uses velocity mode\&. 
.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.
.SS "virtual void okapi::ChassisModel::tank (double ileftSpeed, double irightSpeed, double ithreshold = \fR0\fP)\fR [pure virtual]\fP"
Drive the robot with a tank drive layout\&. Uses voltage mode\&.

.PP
\fBParameters\fP
.RS 4
\fIileftSpeed\fP left side speed 
.br
\fIirightSpeed\fP right side speed 
.br
\fIithreshold\fP deadband on joystick values 
.RE
.PP

.PP
Implemented in \fBokapi::HDriveModel\fP, \fBokapi::SkidSteerModel\fP, and \fBokapi::XDriveModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
