.TH "okapi::AbstractRate" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::AbstractRate
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBokapi::Rate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdelay\fP (QFrequency ihz)=0"
.br
.ti -1c
.RI "virtual void \fBdelayUntil\fP (QTime itime)=0"
.br
.ti -1c
.RI "virtual void \fBdelayUntil\fP (uint32_t ims)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void okapi::AbstractRate::delay (QFrequency ihz)\fR [pure virtual]\fP"
Delay the current task such that it runs at the given frequency\&. The first delay will run for 1000/(ihz)\&. Subsequent delays will adjust according to the previous runtime of the task\&.

.PP
\fBParameters\fP
.RS 4
\fIihz\fP the frequency 
.RE
.PP

.PP
Implemented in \fBokapi::Rate\fP\&.
.SS "virtual void okapi::AbstractRate::delayUntil (QTime itime)\fR [pure virtual]\fP"
Delay the current task until itime has passed\&. This method can be used by periodic tasks to ensure a consistent execution frequency\&.

.PP
\fBParameters\fP
.RS 4
\fIitime\fP the time period 
.RE
.PP

.PP
Implemented in \fBokapi::Rate\fP\&.
.SS "virtual void okapi::AbstractRate::delayUntil (uint32_t ims)\fR [pure virtual]\fP"
Delay the current task until ims milliseconds have passed\&. This method can be used by periodic tasks to ensure a consistent execution frequency\&.

.PP
\fBParameters\fP
.RS 4
\fIims\fP the time period 
.RE
.PP

.PP
Implemented in \fBokapi::Rate\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
