.TH "okapi::Filter" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::Filter
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBokapi::AverageFilter< n >\fP, \fBokapi::ComposableFilter\fP, \fBokapi::DemaFilter\fP, \fBokapi::EKFFilter\fP, \fBokapi::EmaFilter\fP, \fBokapi::MedianFilter< n >\fP, and \fBokapi::PassthroughFilter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual double \fBfilter\fP (double ireading)=0"
.br
.ti -1c
.RI "virtual double \fBgetOutput\fP () const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual double okapi::Filter::filter (double ireading)\fR [pure virtual]\fP"
Filters a value, like a sensor reading\&.

.PP
\fBParameters\fP
.RS 4
\fIireading\fP new measurement 
.RE
.PP
\fBReturns\fP
.RS 4
filtered result 
.RE
.PP

.PP
Implemented in \fBokapi::AverageFilter< n >\fP, \fBokapi::ComposableFilter\fP, \fBokapi::DemaFilter\fP, \fBokapi::EKFFilter\fP, \fBokapi::EmaFilter\fP, \fBokapi::MedianFilter< n >\fP, and \fBokapi::PassthroughFilter\fP\&.
.SS "virtual double okapi::Filter::getOutput () const\fR [pure virtual]\fP"
Returns the previous output from filter\&.

.PP
\fBReturns\fP
.RS 4
the previous output from filter 
.RE
.PP

.PP
Implemented in \fBokapi::AverageFilter< n >\fP, \fBokapi::ComposableFilter\fP, \fBokapi::DemaFilter\fP, \fBokapi::EKFFilter\fP, \fBokapi::EmaFilter\fP, \fBokapi::MedianFilter< n >\fP, and \fBokapi::PassthroughFilter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
