.TH "okapi::TimeUtilFactory" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::TimeUtilFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBokapi::ConfigurableTimeUtilFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBTimeUtil\fP \fBcreate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTimeUtil\fP \fBcreateDefault\fP ()"
.br
.ti -1c
.RI "static \fBTimeUtil\fP \fBwithSettledUtilParams\fP (double iatTargetError=50, double iatTargetDerivative=5, const QTime &iatTargetTime=250_ms)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBTimeUtil\fP okapi::TimeUtilFactory::create ()\fR [virtual]\fP"
Creates a default \fBTimeUtil\fP\&. 
.PP
Reimplemented in \fBokapi::ConfigurableTimeUtilFactory\fP\&.
.SS "\fBTimeUtil\fP okapi::TimeUtilFactory::createDefault ()\fR [static]\fP"
Creates a default \fBTimeUtil\fP\&. 
.SS "\fBTimeUtil\fP okapi::TimeUtilFactory::withSettledUtilParams (double iatTargetError = \fR50\fP, double iatTargetDerivative = \fR5\fP, const QTime & iatTargetTime = \fR250_ms\fP)\fR [static]\fP"
Creates a \fBTimeUtil\fP with custom \fBSettledUtil\fP params\&. See \fBSettledUtil\fP docs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
