.TH "okapi::RotationSensor" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::RotationSensor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::ContinuousRotarySensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRotationSensor\fP (std::uint8_t iport, bool ireversed=false)"
.br
.ti -1c
.RI "double \fBget\fP () const override"
.br
.ti -1c
.RI "std::int32_t \fBreset\fP () override"
.br
.ti -1c
.RI "double \fBcontrollerGet\fP () override"
.br
.ti -1c
.RI "double \fBgetVelocity\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::uint8_t \fBport\fP"
.br
.ti -1c
.RI "std::int8_t \fBreversed\fP {1}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::RotationSensor::RotationSensor (std::uint8_t iport, bool ireversed = \fRfalse\fP)"
A rotation sensor in a V5 port\&.

.PP
.PP
.nf
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIiport\fP The V5 port the device uses\&. 
.br
\fIireversed\fP Whether the sensor is reversed\&. This will set the reversed state in the kernel\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double okapi::RotationSensor::controllerGet ()\fR [override]\fP, \fR [virtual]\fP"
Get the sensor value for use in a control loop\&. This method might be automatically called in another thread by the controller\&.

.PP
\fBReturns\fP
.RS 4
The same as \fBget\fP\&. 
.RE
.PP

.PP
Implements \fBokapi::ControllerInput< double >\fP\&.
.SS "double okapi::RotationSensor::get () const\fR [override]\fP, \fR [virtual]\fP"
Get the current rotation in degrees\&.

.PP
\fBReturns\fP
.RS 4
The current rotation in degrees or \fR\fBPROS_ERR_F\fP\fP if the operation failed, setting \fRerrno\fP\&. 
.RE
.PP

.PP
Implements \fBokapi::RotarySensor\fP\&.
.SS "double okapi::RotationSensor::getVelocity () const"
Get the current rotational velocity estimate in degrees per second\&.

.PP
\fBReturns\fP
.RS 4
The current rotational velocity estimate in degrees per second or \fR\fBPROS_ERR_F\fP\fP if the operation failed, setting \fRerrno\fP\&. 
.RE
.PP

.SS "std::int32_t okapi::RotationSensor::reset ()\fR [override]\fP, \fR [virtual]\fP"
Reset the sensor to zero\&.

.PP
\fBReturns\fP
.RS 4
\fR1\fP if the operation was successful or \fRPROS_ERR\fP if the operation failed, setting \fRerrno\fP\&. 
.RE
.PP

.PP
Implements \fBokapi::ContinuousRotarySensor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
