.TH "okapi::ContinuousRotarySensor" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ContinuousRotarySensor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::RotarySensor\fP\&.
.PP
Inherited by \fBokapi::ADIEncoder\fP, \fBokapi::ADIGyro\fP, \fBokapi::IMU\fP, \fBokapi::IntegratedEncoder\fP, and \fBokapi::RotationSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::int32_t \fBreset\fP ()=0"
.br
.in -1c

Public Member Functions inherited from \fBokapi::RotarySensor\fP
.in +1c
.ti -1c
.RI "virtual double \fBget\fP () const =0"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ControllerInput< double >\fP
.in +1c
.ti -1c
.RI "virtual double \fBcontrollerGet\fP ()=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual std::int32_t okapi::ContinuousRotarySensor::reset ()\fR [pure virtual]\fP"
Reset the sensor to zero\&.

.PP
\fBReturns\fP
.RS 4
\fR1\fP on success, \fRPROS_ERR\fP on fail 
.RE
.PP

.PP
Implemented in \fBokapi::ADIEncoder\fP, \fBokapi::ADIGyro\fP, \fBokapi::IMU\fP, \fBokapi::IntegratedEncoder\fP, and \fBokapi::RotationSensor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
