.TH "okapi::Potentiometer" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::Potentiometer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::RotarySensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPotentiometer\fP (std::uint8_t iport)"
.br
.ti -1c
.RI "\fBPotentiometer\fP (std::pair< std::uint8_t, std::uint8_t > iports)"
.br
.ti -1c
.RI "virtual double \fBget\fP () const override"
.br
.ti -1c
.RI "virtual double \fBcontrollerGet\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::uint8_t \fBsmartPort\fP"
.br
.ti -1c
.RI "std::uint8_t \fBport\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::Potentiometer::Potentiometer (std::uint8_t iport)"
A potentiometer in an ADI port\&.

.PP
.PP
.nf
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIiport\fP The ADI port number (\fR[1, 8]\fP, \fR[a, h]\fP, \fR[A, H]\fP)\&. 
.RE
.PP

.SS "okapi::Potentiometer::Potentiometer (std::pair< std::uint8_t, std::uint8_t > iports)"
A potentiometer in an ADI port\&.

.PP
.PP
.nf
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIiports\fP The ports the potentiometer is plugged in to in the order \fR{smart port, potentiometer port}\fP\&. The smart port is the smart port number (\fR[1, 21]\fP)\&. The potentiometer port is the ADI port number (\fR[1, 8]\fP, \fR[a, h]\fP, \fR[A, H]\fP)\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual double okapi::Potentiometer::controllerGet ()\fR [override]\fP, \fR [virtual]\fP"
Get the sensor value for use in a control loop\&. This method might be automatically called in another thread by the controller\&.

.PP
\fBReturns\fP
.RS 4
the current sensor value, or \fRPROS_ERR\fP on a failure\&. 
.RE
.PP

.PP
Implements \fBokapi::ControllerInput< double >\fP\&.
.SS "virtual double okapi::Potentiometer::get () const\fR [override]\fP, \fR [virtual]\fP"
Get the current sensor value\&.

.PP
\fBReturns\fP
.RS 4
the current sensor value, or \fRPROS_ERR\fP on a failure\&. 
.RE
.PP

.PP
Implements \fBokapi::RotarySensor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
