.TH "okapi::EmaFilter" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::EmaFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::Filter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmaFilter\fP (double ialpha)"
.br
.ti -1c
.RI "double \fBfilter\fP (double ireading) override"
.br
.ti -1c
.RI "double \fBgetOutput\fP () const override"
.br
.ti -1c
.RI "virtual void \fBsetGains\fP (double ialpha)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBalpha\fP"
.br
.ti -1c
.RI "double \fBoutput\fP = 0"
.br
.ti -1c
.RI "double \fBlastOutput\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "okapi::EmaFilter::EmaFilter (double ialpha)\fR [explicit]\fP"
Exponential moving average filter\&.

.PP
\fBParameters\fP
.RS 4
\fIialpha\fP alpha gain 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double okapi::EmaFilter::filter (double ireading)\fR [override]\fP, \fR [virtual]\fP"
Filters a value, like a sensor reading\&.

.PP
\fBParameters\fP
.RS 4
\fIreading\fP new measurement 
.RE
.PP
\fBReturns\fP
.RS 4
filtered result 
.RE
.PP

.PP
Implements \fBokapi::Filter\fP\&.
.SS "double okapi::EmaFilter::getOutput () const\fR [override]\fP, \fR [virtual]\fP"
Returns the previous output from filter\&.

.PP
\fBReturns\fP
.RS 4
the previous output from filter 
.RE
.PP

.PP
Implements \fBokapi::Filter\fP\&.
.SS "virtual void okapi::EmaFilter::setGains (double ialpha)\fR [virtual]\fP"
Set filter gains\&.

.PP
\fBParameters\fP
.RS 4
\fIialpha\fP alpha gain 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
