.TH "okapi::ClosedLoopController< Input, Output >" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::ClosedLoopController< Input, Output >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <closedLoopController\&.hpp>\fP
.PP
Inherits \fBokapi::ControllerOutput< Input >\fP\&.
.PP
Inherited by \fBokapi::AsyncController< Input, Output >\fP, and \fBokapi::IterativeController< Input, Output >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetTarget\fP (Input itarget)=0"
.br
.ti -1c
.RI "virtual Input \fBgetTarget\fP ()=0"
.br
.ti -1c
.RI "virtual Input \fBgetProcessValue\fP () const =0"
.br
.ti -1c
.RI "virtual Output \fBgetError\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBisSettled\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBflipDisable\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBflipDisable\fP (bool iisDisabled)=0"
.br
.ti -1c
.RI "virtual bool \fBisDisabled\fP () const =0"
.br
.in -1c

Public Member Functions inherited from \fBokapi::ControllerOutput< Input >\fP
.in +1c
.ti -1c
.RI "virtual void \fBcontrollerSet\fP (Input ivalue)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Input, typename Output>
.br
class okapi::ClosedLoopController< Input, Output >"An abstract closed-loop controller\&.

.PP
\fBTemplate Parameters\fP
.RS 4
\fIInput\fP The target/input type\&. 
.br
\fIOutput\fP The error/output type\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename Input, typename Output> virtual void \fBokapi::ClosedLoopController\fP< Input, Output >::flipDisable ()\fR [pure virtual]\fP"
Changes whether the controller is off or on\&. Turning the controller on after it was off will cause the controller to move to its last set target, unless it was reset in that time\&. 
.PP
Implemented in \fBokapi::AsyncLinearMotionProfileController\fP, \fBokapi::AsyncMotionProfileController\fP, \fBokapi::AsyncPosIntegratedController\fP, \fBokapi::AsyncVelIntegratedController\fP, \fBokapi::AsyncWrapper< Input, Output >\fP, \fBokapi::AsyncWrapper< double, double >\fP, \fBokapi::IterativeMotorVelocityController\fP, \fBokapi::IterativePosPIDController\fP, and \fBokapi::IterativeVelPIDController\fP\&.
.SS "template<typename Input, typename Output> virtual void \fBokapi::ClosedLoopController\fP< Input, Output >::flipDisable (bool iisDisabled)\fR [pure virtual]\fP"
Sets whether the controller is off or on\&. Turning the controller on after it was off will cause the controller to move to its last set target, unless it was reset in that time\&.

.PP
\fBParameters\fP
.RS 4
\fIiisDisabled\fP whether the controller is disabled 
.RE
.PP

.PP
Implemented in \fBokapi::AsyncWrapper< Input, Output >\fP\&.
.SS "template<typename Input, typename Output> virtual Output \fBokapi::ClosedLoopController\fP< Input, Output >::getError () const\fR [pure virtual]\fP"
Returns the last error of the controller\&. Does not update when disabled\&.

.PP
\fBReturns\fP
.RS 4
the last error 
.RE
.PP

.PP
Implemented in \fBokapi::AsyncLinearMotionProfileController\fP, \fBokapi::AsyncMotionProfileController\fP, \fBokapi::AsyncPosIntegratedController\fP, \fBokapi::AsyncVelIntegratedController\fP, \fBokapi::AsyncWrapper< Input, Output >\fP, \fBokapi::AsyncWrapper< double, double >\fP, \fBokapi::IterativeMotorVelocityController\fP, \fBokapi::IterativePosPIDController\fP, and \fBokapi::IterativeVelPIDController\fP\&.
.SS "template<typename Input, typename Output> virtual Input \fBokapi::ClosedLoopController\fP< Input, Output >::getProcessValue () const\fR [pure virtual]\fP"

.PP
\fBReturns\fP
.RS 4
The most recent value of the process variable\&. 
.RE
.PP

.PP
Implemented in \fBokapi::AsyncLinearMotionProfileController\fP, \fBokapi::AsyncMotionProfileController\fP, \fBokapi::AsyncPosIntegratedController\fP, \fBokapi::AsyncVelIntegratedController\fP, \fBokapi::AsyncWrapper< Input, Output >\fP, \fBokapi::AsyncWrapper< double, double >\fP, \fBokapi::IterativeMotorVelocityController\fP, \fBokapi::IterativePosPIDController\fP, and \fBokapi::IterativeVelPIDController\fP\&.
.SS "template<typename Input, typename Output> virtual Input \fBokapi::ClosedLoopController\fP< Input, Output >::getTarget ()\fR [pure virtual]\fP"
Gets the last set target, or the default target if none was set\&.

.PP
\fBReturns\fP
.RS 4
the last target 
.RE
.PP

.PP
Implemented in \fBokapi::AsyncLinearMotionProfileController\fP, \fBokapi::AsyncMotionProfileController\fP, \fBokapi::AsyncPosIntegratedController\fP, \fBokapi::AsyncVelIntegratedController\fP, \fBokapi::AsyncWrapper< Input, Output >\fP, \fBokapi::AsyncWrapper< double, double >\fP, \fBokapi::IterativeMotorVelocityController\fP, \fBokapi::IterativePosPIDController\fP, and \fBokapi::IterativeVelPIDController\fP\&.
.SS "template<typename Input, typename Output> virtual bool \fBokapi::ClosedLoopController\fP< Input, Output >::isDisabled () const\fR [pure virtual]\fP"
Returns whether the controller is currently disabled\&.

.PP
\fBReturns\fP
.RS 4
whether the controller is currently disabled 
.RE
.PP

.PP
Implemented in \fBokapi::AsyncLinearMotionProfileController\fP, \fBokapi::AsyncMotionProfileController\fP, \fBokapi::AsyncPosIntegratedController\fP, \fBokapi::AsyncVelIntegratedController\fP, \fBokapi::AsyncWrapper< Input, Output >\fP, \fBokapi::AsyncWrapper< double, double >\fP, \fBokapi::IterativeMotorVelocityController\fP, \fBokapi::IterativePosPIDController\fP, and \fBokapi::IterativeVelPIDController\fP\&.
.SS "template<typename Input, typename Output> virtual bool \fBokapi::ClosedLoopController\fP< Input, Output >::isSettled ()\fR [pure virtual]\fP"
Returns whether the controller has settled at the target\&. Determining what settling means is implementation-dependent\&.

.PP
If the controller is disabled, this method must return \fRtrue\fP\&.

.PP
\fBReturns\fP
.RS 4
whether the controller is settled 
.RE
.PP

.PP
Implemented in \fBokapi::AsyncLinearMotionProfileController\fP, \fBokapi::AsyncMotionProfileController\fP, \fBokapi::AsyncPosIntegratedController\fP, \fBokapi::AsyncVelIntegratedController\fP, \fBokapi::AsyncWrapper< Input, Output >\fP, \fBokapi::AsyncWrapper< double, double >\fP, \fBokapi::IterativeMotorVelocityController\fP, \fBokapi::IterativePosPIDController\fP, and \fBokapi::IterativeVelPIDController\fP\&.
.SS "template<typename Input, typename Output> virtual void \fBokapi::ClosedLoopController\fP< Input, Output >::reset ()\fR [pure virtual]\fP"
Resets the controller's internal state so it is similar to when it was first initialized, while keeping any user-configured information\&. 
.PP
Implemented in \fBokapi::AsyncLinearMotionProfileController\fP, \fBokapi::AsyncMotionProfileController\fP, \fBokapi::AsyncPosIntegratedController\fP, \fBokapi::AsyncVelIntegratedController\fP, \fBokapi::AsyncWrapper< Input, Output >\fP, \fBokapi::AsyncWrapper< double, double >\fP, \fBokapi::IterativeMotorVelocityController\fP, \fBokapi::IterativePosPIDController\fP, and \fBokapi::IterativeVelPIDController\fP\&.
.SS "template<typename Input, typename Output> virtual void \fBokapi::ClosedLoopController\fP< Input, Output >::setTarget (Input itarget)\fR [pure virtual]\fP"
Sets the target for the controller\&.

.PP
\fBParameters\fP
.RS 4
\fIitarget\fP the new target 
.RE
.PP

.PP
Implemented in \fBokapi::AsyncLinearMotionProfileController\fP, \fBokapi::AsyncMotionProfileController\fP, \fBokapi::AsyncPosIntegratedController\fP, \fBokapi::AsyncVelIntegratedController\fP, \fBokapi::AsyncWrapper< Input, Output >\fP, \fBokapi::AsyncWrapper< double, double >\fP, \fBokapi::IterativeMotorVelocityController\fP, \fBokapi::IterativePosPIDController\fP, and \fBokapi::IterativeVelPIDController\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
