.TH "okapi::AbstractButton" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
okapi::AbstractButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBokapi::ControllerInput< bool >\fP\&.
.PP
Inherited by \fBokapi::ButtonBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBisPressed\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBchanged\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBchangedToPressed\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBchangedToReleased\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBcontrollerGet\fP () override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual bool okapi::AbstractButton::changed ()\fR [pure virtual]\fP"
Return whether the state of the button changed since the last time this method was called\&. 
.PP
Implemented in \fBokapi::ButtonBase\fP\&.
.SS "virtual bool okapi::AbstractButton::changedToPressed ()\fR [pure virtual]\fP"
Return whether the state of the button changed to being pressed since the last time this method was called\&. 
.PP
Implemented in \fBokapi::ButtonBase\fP\&.
.SS "virtual bool okapi::AbstractButton::changedToReleased ()\fR [pure virtual]\fP"
Return whether the state of the button to being not pressed changed since the last time this method was called\&. 
.PP
Implemented in \fBokapi::ButtonBase\fP\&.
.SS "virtual bool okapi::AbstractButton::controllerGet ()\fR [override]\fP, \fR [virtual]\fP"
Get the sensor value for use in a control loop\&. This method might be automatically called in another thread by the controller\&.

.PP
\fBReturns\fP
.RS 4
the current sensor value\&. This is the same as the output of the pressed() method\&. 
.RE
.PP

.PP
Implements \fBokapi::ControllerInput< bool >\fP\&.
.SS "virtual bool okapi::AbstractButton::isPressed ()\fR [pure virtual]\fP"
Return whether the button is currently pressed\&. 
.PP
Implemented in \fBokapi::ButtonBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
