.TH "optical_rgb_s_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
optical_rgb_s_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <optical\&.h>\fP
.SH "Detailed Description"
.PP 
The RGB and Brightness values for the optical sensor\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
