.TH "optical_rgb_s" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
optical_rgb_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBred\fP"
.br
.ti -1c
.RI "double \fBgreen\fP"
.br
.ti -1c
.RI "double \fBblue\fP"
.br
.ti -1c
.RI "double \fBbrightness\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
