.TH "optical_gesture_s" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
optical_gesture_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBudata\fP"
.br
.ti -1c
.RI "uint8_t \fBddata\fP"
.br
.RI "Up data\&. "
.ti -1c
.RI "uint8_t \fBldata\fP"
.br
.RI "Down data\&. "
.ti -1c
.RI "uint8_t \fBrdata\fP"
.br
.RI "Left data\&. "
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.RI "Right data\&. "
.ti -1c
.RI "uint8_t \fBpad\fP"
.br
.RI "Type of gesture\&. "
.ti -1c
.RI "uint16_t \fBcount\fP"
.br
.RI "Padding\&. "
.ti -1c
.RI "uint32_t \fBtime\fP"
.br
.RI "Number of gestures\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
