.TH "pros::v5::Device" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::v5::Device
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBpros::v5::Distance\fP, \fBpros::v5::Gps\fP, \fBpros::v5::Imu\fP, \fBpros::v5::Motor\fP, \fBpros::v5::Optical\fP, \fBpros::v5::Rotation\fP, and \fBpros::v5::Vision\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDevice\fP (const std::uint8_t port)"
.br
.ti -1c
.RI "std::uint8_t \fBget_port\fP (void) const"
.br
.ti -1c
.RI "virtual bool \fBis_installed\fP ()"
.br
.ti -1c
.RI "pros::DeviceType \fBget_plugged_type\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static pros::DeviceType \fBget_plugged_type\fP (std::uint8_t port)"
.br
.ti -1c
.RI "static std::vector< \fBDevice\fP > \fBget_all_devices\fP (pros::DeviceType device_type=\fBpros::DeviceType::undefined\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDevice\fP (const std::uint8_t port, const enum \fBDeviceType\fP deviceType)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const std::uint8_t \fB_port\fP"
.br
.ti -1c
.RI "enum \fBDeviceType\fP \fB_deviceType\fP = \fBpros::DeviceType::none\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
