.TH "pros::v5::Imu" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::v5::Imu
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpros::v5::Device\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImu\fP (const std::uint8_t port)"
.br
.ti -1c
.RI "\fBImu\fP (const \fBDevice\fP &device)"
.br
.ti -1c
.RI "virtual std::int32_t \fBreset\fP (bool blocking=false) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBset_data_rate\fP (std::uint32_t rate) const"
.br
.ti -1c
.RI "virtual double \fBget_rotation\fP () const"
.br
.ti -1c
.RI "virtual double \fBget_heading\fP () const"
.br
.ti -1c
.RI "virtual pros::quaternion_s_t \fBget_quaternion\fP () const"
.br
.ti -1c
.RI "virtual pros::euler_s_t \fBget_euler\fP () const"
.br
.ti -1c
.RI "virtual double \fBget_pitch\fP () const"
.br
.ti -1c
.RI "virtual double \fBget_roll\fP () const"
.br
.ti -1c
.RI "virtual double \fBget_yaw\fP () const"
.br
.ti -1c
.RI "virtual pros::imu_gyro_s_t \fBget_gyro_rate\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBtare_rotation\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBtare_heading\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBtare_pitch\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBtare_yaw\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBtare_roll\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBtare\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBtare_euler\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBset_heading\fP (const double target) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBset_rotation\fP (const double target) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBset_yaw\fP (const double target) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBset_pitch\fP (const double target) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBset_roll\fP (const double target) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBset_euler\fP (const pros::euler_s_t target) const"
.br
.ti -1c
.RI "virtual pros::imu_accel_s_t \fBget_accel\fP () const"
.br
.ti -1c
.RI "virtual \fBpros::ImuStatus\fP \fBget_status\fP () const"
.br
.ti -1c
.RI "virtual bool \fBis_calibrating\fP () const"
.br
.ti -1c
.RI "virtual imu_orientation_e_t \fBget_physical_orientation\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBpros::v5::Device\fP
.in +1c
.ti -1c
.RI "\fBDevice\fP (const std::uint8_t port)"
.br
.ti -1c
.RI "std::uint8_t \fBget_port\fP (void) const"
.br
.ti -1c
.RI "virtual bool \fBis_installed\fP ()"
.br
.ti -1c
.RI "pros::DeviceType \fBget_plugged_type\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBImu\fP \fBget_imu\fP ()"
.br
.ti -1c
.RI "static std::vector< \fBImu\fP > \fBget_all_devices\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBpros::v5::Device\fP
.in +1c
.ti -1c
.RI "static pros::DeviceType \fBget_plugged_type\fP (std::uint8_t port)"
.br
.ti -1c
.RI "static std::vector< \fBDevice\fP > \fBget_all_devices\fP (pros::DeviceType device_type=\fBpros::DeviceType::undefined\fP)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBpros::Imu\fP &imu)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBpros::v5::Device\fP
.in +1c
.ti -1c
.RI "\fBDevice\fP (const std::uint8_t port, const enum \fBDeviceType\fP deviceType)"
.br
.in -1c

Protected Attributes inherited from \fBpros::v5::Device\fP
.in +1c
.ti -1c
.RI "const std::uint8_t \fB_port\fP"
.br
.ti -1c
.RI "enum \fBDeviceType\fP \fB_deviceType\fP = \fBpros::DeviceType::none\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
