.TH "pros::rtos::Mutex" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::rtos::Mutex
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutex\fP (const Mutex &)=delete"
.br
.ti -1c
.RI "\fBMutex\fP (Mutex &&)=delete"
.br
.ti -1c
.RI "Mutex & \fBoperator=\fP (const Mutex &)=delete"
.br
.ti -1c
.RI "Mutex & \fBoperator=\fP (Mutex &&)=delete"
.br
.ti -1c
.RI "bool \fBtake\fP ()"
.br
.ti -1c
.RI "bool \fBtake\fP (std::uint32_t timeout)"
.br
.ti -1c
.RI "bool \fBgive\fP ()"
.br
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.ti -1c
.RI "bool \fBtry_lock\fP ()"
.br
.ti -1c
.RI "template<typename Rep, typename Period> bool \fBtry_lock_for\fP (const std::chrono::duration< Rep, Period > &rel_time)"
.br
.ti -1c
.RI "template<typename Duration> bool \fBtry_lock_until\fP (const std::chrono::time_point< \fBClock\fP, Duration > &abs_time)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
