.TH "pros::adi::Ultrasonic" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::adi::Ultrasonic
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpros::adi::Port\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUltrasonic\fP (std::uint8_t adi_port_ping, std::uint8_t adi_port_echo)"
.br
.ti -1c
.RI "\fBUltrasonic\fP (\fBext_adi_port_tuple_t\fP port_tuple)"
.br
.ti -1c
.RI "std::int32_t \fBget_value\fP () const"
.br
.ti -1c
.RI "virtual \fBext_adi_port_tuple_t\fP \fBget_port\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBext_adi_port_tuple_t\fP \fBpros::adi::Port::get_port\fP () const\fR [virtual]\fP"
Gets the port of the sensor\&.

.PP
\fBReturns\fP
.RS 4
returns a tuple of integer ports\&.
.RE
.PP
\fBNote\fP
.RS 4
The parts of the tuple are {smart port, adi port, second adi port (when applicable)}\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.PP
Reimplemented from \fBpros::adi::Port\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
