.TH "pros::Serial" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::Serial
.SH SYNOPSIS
.br
.PP
.PP
Inherits Device\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerial\fP (std::uint8_t port, std::int32_t baudrate)"
.br
.ti -1c
.RI "\fBSerial\fP (std::uint8_t port)"
.br
.ti -1c
.RI "virtual std::int32_t \fBset_baudrate\fP (std::int32_t baudrate) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBflush\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBget_read_avail\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBget_write_free\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBpeek_byte\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBread_byte\fP () const"
.br
.ti -1c
.RI "virtual std::int32_t \fBread\fP (std::uint8_t *buffer, std::int32_t length) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBwrite_byte\fP (std::uint8_t buffer) const"
.br
.ti -1c
.RI "virtual std::int32_t \fBwrite\fP (std::uint8_t *buffer, std::int32_t length) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
