.TH "pros::rtos::MutexVarLock< Var >" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::rtos::MutexVarLock< Var >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr Var & \fBoperator*\fP () const"
.br
.ti -1c
.RI "constexpr Var * \fBoperator\->\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMutexVar< Var >\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename Var> Var & \fBpros::rtos::MutexVarLock\fP< Var >::operator* () const\fR [inline]\fP, \fR [constexpr]\fP"
Accesses the value of the mutex-protected variable\&. 
.SS "template<typename Var> Var * \fBpros::rtos::MutexVarLock\fP< Var >::operator\-> () const\fR [inline]\fP, \fR [constexpr]\fP"
Accesses the value of the mutex-protected variable\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
