.TH "pros::adi::Motor" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::adi::Motor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpros::adi::Port\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMotor\fP (std::uint8_t adi_port)"
.br
.ti -1c
.RI "\fBMotor\fP (\fBext_adi_port_pair_t\fP port_pair)"
.br
.ti -1c
.RI "std::int32_t \fBstop\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBset_value\fP (std::int32_t value) const"
.br
.ti -1c
.RI "std::int32_t \fBget_value\fP () const"
.br
.ti -1c
.RI "virtual \fBext_adi_port_tuple_t\fP \fBget_port\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBext_adi_port_tuple_t\fP \fBpros::adi::Port::get_port\fP () const\fR [virtual]\fP"
Gets the port of the sensor\&.

.PP
\fBReturns\fP
.RS 4
returns a tuple of integer ports\&.
.RE
.PP
\fBNote\fP
.RS 4
The parts of the tuple are {smart port, adi port, second adi port (when applicable)}\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.PP
Reimplemented from \fBpros::adi::Port\fP\&.
.SS "std::int32_t \fBpros::adi::Port::get_value\fP () const"
Gets the last set speed of the motor on the given port\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port is not configured as a motor

.PP
\fBReturns\fP
.RS 4
The last set speed of the motor on the given
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.SS "std::int32_t \fBpros::adi::Port::set_value\fP (std::int32_t value) const"
Sets the speed of the motor on the given port\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port is not configured as a motor

.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The new signed speed; -127 is full reverse and 127 is full forward, with 0 being off
.RE
.PP
\fBReturns\fP
.RS 4
1 if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
