.TH "pros::Link" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::Link
.SH SYNOPSIS
.br
.PP
.PP
Inherits Device\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLink\fP (const std::uint8_t port, const std::string link_id, link_type_e_t type, bool ov=true)"
.br
.ti -1c
.RI "bool \fBconnected\fP ()"
.br
.ti -1c
.RI "std::uint32_t \fBraw_receivable_size\fP ()"
.br
.ti -1c
.RI "std::uint32_t \fBtransmit_raw\fP (void *data, std::uint16_t data_size)"
.br
.ti -1c
.RI "std::uint32_t \fBreceive_raw\fP (void *dest, std::uint16_t data_size)"
.br
.ti -1c
.RI "std::uint32_t \fBtransmit\fP (void *data, std::uint16_t data_size)"
.br
.ti -1c
.RI "std::uint32_t \fBreceive\fP (void *dest, std::uint16_t data_size)"
.br
.ti -1c
.RI "std::uint32_t \fBclear_receive_buf\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
