.TH "pros::adi::Potentiometer" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::adi::Potentiometer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpros::adi::AnalogIn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPotentiometer\fP (std::uint8_t adi_port, adi_potentiometer_type_e_t potentiometer_type=E_ADI_POT_EDR)"
.br
.ti -1c
.RI "\fBPotentiometer\fP (\fBext_adi_port_pair_t\fP port_pair, adi_potentiometer_type_e_t potentiometer_type=E_ADI_POT_EDR)"
.br
.ti -1c
.RI "double \fBget_angle\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBcalibrate\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value_calibrated\fP () const"
.br
.ti -1c
.RI "virtual \fBext_adi_port_tuple_t\fP \fBget_port\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBpros::adi::AnalogIn\fP
.in +1c
.ti -1c
.RI "\fBAnalogIn\fP (std::uint8_t adi_port)"
.br
.ti -1c
.RI "\fBAnalogIn\fP (\fBext_adi_port_pair_t\fP port_pair)"
.br
.ti -1c
.RI "std::int32_t \fBcalibrate\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value_calibrated\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value_calibrated_HR\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, \fBpros::adi::Potentiometer\fP &potentiometer)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBpros::adi::Port\fP
.in +1c
.ti -1c
.RI "\fBPort\fP (std::uint8_t adi_port, adi_port_config_e_t type=E_ADI_TYPE_UNDEFINED)"
.br
.ti -1c
.RI "\fBPort\fP (\fBext_adi_port_pair_t\fP port_pair, adi_port_config_e_t type=E_ADI_TYPE_UNDEFINED)"
.br
.ti -1c
.RI "std::int32_t \fBget_config\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBset_config\fP (adi_port_config_e_t type) const"
.br
.ti -1c
.RI "std::int32_t \fBset_value\fP (std::int32_t value) const"
.br
.in -1c

Protected Attributes inherited from \fBpros::adi::Port\fP
.in +1c
.ti -1c
.RI "std::uint8_t \fB_smart_port\fP"
.br
.ti -1c
.RI "std::uint8_t \fB_adi_port\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::int32_t \fBpros::adi::AnalogIn::calibrate\fP () const"
Calibrates the potentiometer on the specified port and returns the new calibration value\&.

.PP
This method assumes that the potentiometer value is not actively changing at this time and computes an average from approximately 500 samples, 1 ms apart, for a 0\&.5 s period of calibration\&. The average value thus calculated is returned and stored for later calls to the \fBpros::adi::Potentiometer::get_value_calibrated()\fP function\&. This function will return the difference between this value and the current sensor value when called\&.

.PP
Do not use this function when the potentiometer value might be unstable (rotating the potentiometer)

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port is not configured as a potentiometer

.PP
\fBReturns\fP
.RS 4
The average potentiometer value computed by this function 
.RE
.PP

.SS "virtual \fBext_adi_port_tuple_t\fP \fBpros::adi::Port::get_port\fP () const\fR [virtual]\fP"
Gets the port of the sensor\&.

.PP
\fBReturns\fP
.RS 4
returns a tuple of integer ports\&.
.RE
.PP
\fBNote\fP
.RS 4
The parts of the tuple are {smart port, adi port, second adi port (when applicable)}\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.PP
Reimplemented from \fBpros::adi::AnalogIn\fP\&.
.SS "std::int32_t \fBpros::adi::Port::get_value\fP () const"
Gets the 12-bit value of the specified port\&.

.PP
The value returned is undefined if the analog pin has been switched to a different mode\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port is not configured as a potentiometer

.PP
\fBReturns\fP
.RS 4
The analog sensor value, where a value of 0 reflects an input voltage of nearly 0 V and a value of 4095 reflects an input voltage of nearly 5 V 
.RE
.PP

.SS "std::int32_t \fBpros::adi::AnalogIn::get_value_calibrated\fP () const"
Gets the 12 bit calibrated value of a potentiometer port\&.

.PP
The \fBpros::adi::Potentiometer::calibrate()\fP function must be run first\&.

.PP
This function uses the following values of errno when an error state is reached: ENODEV - The port is not configured as a potentiometer

.PP
\fBReturns\fP
.RS 4
The difference of the potentiometer value from its calibrated default from -4095 to 4095 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
