.TH "pros::adi::Port" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::adi::Port
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBpros::adi::AnalogIn\fP\fR [protected]\fP, \fBpros::adi::AnalogOut\fP\fR [private]\fP, \fBpros::adi::DigitalIn\fP\fR [private]\fP, \fBpros::adi::DigitalOut\fP\fR [private]\fP, \fBpros::adi::Encoder\fP\fR [private]\fP, \fBpros::adi::Gyro\fP\fR [private]\fP, \fBpros::adi::Led\fP\fR [protected]\fP, \fBpros::adi::Motor\fP\fR [private]\fP, and \fBpros::adi::Ultrasonic\fP\fR [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPort\fP (std::uint8_t adi_port, adi_port_config_e_t type=E_ADI_TYPE_UNDEFINED)"
.br
.ti -1c
.RI "\fBPort\fP (\fBext_adi_port_pair_t\fP port_pair, adi_port_config_e_t type=E_ADI_TYPE_UNDEFINED)"
.br
.ti -1c
.RI "std::int32_t \fBget_config\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBset_config\fP (adi_port_config_e_t type) const"
.br
.ti -1c
.RI "std::int32_t \fBset_value\fP (std::int32_t value) const"
.br
.ti -1c
.RI "virtual \fBext_adi_port_tuple_t\fP \fBget_port\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::uint8_t \fB_smart_port\fP"
.br
.ti -1c
.RI "std::uint8_t \fB_adi_port\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
