.TH "pros::adi::AnalogIn" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::adi::AnalogIn
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpros::adi::Port\fP\&.
.PP
Inherited by \fBpros::adi::Potentiometer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnalogIn\fP (std::uint8_t adi_port)"
.br
.ti -1c
.RI "\fBAnalogIn\fP (\fBext_adi_port_pair_t\fP port_pair)"
.br
.ti -1c
.RI "std::int32_t \fBcalibrate\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value_calibrated\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value_calibrated_HR\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value\fP () const"
.br
.ti -1c
.RI "virtual \fBext_adi_port_tuple_t\fP \fBget_port\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, \fBpros::adi::AnalogIn\fP &analog_in)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBpros::adi::Port\fP
.in +1c
.ti -1c
.RI "\fBPort\fP (std::uint8_t adi_port, adi_port_config_e_t type=E_ADI_TYPE_UNDEFINED)"
.br
.ti -1c
.RI "\fBPort\fP (\fBext_adi_port_pair_t\fP port_pair, adi_port_config_e_t type=E_ADI_TYPE_UNDEFINED)"
.br
.ti -1c
.RI "std::int32_t \fBget_config\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBget_value\fP () const"
.br
.ti -1c
.RI "std::int32_t \fBset_config\fP (adi_port_config_e_t type) const"
.br
.ti -1c
.RI "std::int32_t \fBset_value\fP (std::int32_t value) const"
.br
.in -1c

Protected Attributes inherited from \fBpros::adi::Port\fP
.in +1c
.ti -1c
.RI "std::uint8_t \fB_smart_port\fP"
.br
.ti -1c
.RI "std::uint8_t \fB_adi_port\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBext_adi_port_tuple_t\fP \fBpros::adi::Port::get_port\fP () const\fR [virtual]\fP"
Gets the port of the sensor\&.

.PP
\fBReturns\fP
.RS 4
returns a tuple of integer ports\&.
.RE
.PP
\fBNote\fP
.RS 4
The parts of the tuple are {smart port, adi port, second adi port (when applicable)}\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.PP
Reimplemented from \fBpros::adi::Port\fP\&.
.PP
Reimplemented in \fBpros::adi::Potentiometer\fP\&.
.SS "std::int32_t \fBpros::adi::Port::get_value\fP () const"
Reads an analog input channel and returns the 12-bit value\&.

.PP
The value returned is undefined if the analog pin has been switched to a different mode\&. The meaning of the returned value varies depending on the sensor attached\&.

.PP
Inherited from ADIPort::get_value\&.

.PP
This function uses the following values of errno when an error state is reached: EADDRINUSE - The port is not configured as an analog input (e\&.g\&. the port has been reconfigured)

.PP
\fBReturns\fP
.RS 4
The analog sensor value, where a value of 0 reflects an input voltage of nearly 0 V and a value of 4095 reflects an input voltage of nearly 5 V
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
