.TH "pros::adi::DigitalOut" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::adi::DigitalOut
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpros::adi::Port\fP\&.
.PP
Inherited by \fBpros::adi::Pneumatics\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDigitalOut\fP (std::uint8_t adi_port, bool init_state=\fBLOW\fP)"
.br
.ti -1c
.RI "\fBDigitalOut\fP (\fBext_adi_port_pair_t\fP port_pair, bool init_state=\fBLOW\fP)"
.br
.ti -1c
.RI "std::int32_t \fBset_value\fP (std::int32_t value) const"
.br
.ti -1c
.RI "virtual \fBext_adi_port_tuple_t\fP \fBget_port\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, \fBpros::adi::DigitalOut\fP &digital_out)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBext_adi_port_tuple_t\fP \fBpros::adi::Port::get_port\fP () const\fR [virtual]\fP"
Gets the port of the sensor\&.

.PP
\fBReturns\fP
.RS 4
returns a tuple of integer ports\&.
.RE
.PP
\fBNote\fP
.RS 4
The parts of the tuple are {smart port, adi port, second adi port (when applicable)}\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 
.PP
Reimplemented from \fBpros::adi::Port\fP\&.
.SS "std::int32_t \fBpros::adi::Port::set_value\fP (std::int32_t value) const"
Sets the digital value (1 or 0) of a pin\&.

.PP
Inherited from ADIPort::set_value\&.

.PP
This function uses the following values of errno when an error state is reached: EADDRINUSE - The port is not configured as a digital output (e\&.g\&. the port has been reconfigured)

.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The value to set the ADI port to
.RE
.PP
\fBReturns\fP
.RS 4
if the operation was successful or PROS_ERR if the operation failed, setting errno\&.
.RE
.PP
\fBExample\fP 
.PP
.nf

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
