.TH "pros::rtos::Clock" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pros::rtos::Clock
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBrep\fP = std::uint32_t"
.br
.ti -1c
.RI "using \fBperiod\fP = std::milli"
.br
.ti -1c
.RI "using \fBduration\fP = std::chrono::duration<rep, period>"
.br
.ti -1c
.RI "using \fBtime_point\fP = std::chrono::time_point<\fBClock\fP>"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static time_point \fBnow\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const bool \fBis_steady\fP = true"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
