.TH "screen_touch_status_s" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
screen_touch_status_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlast_touch_e_t\fP \fBtouch_status\fP"
.br
.RI "Represents if the screen is being held, released, or pressed\&. "
.ti -1c
.RI "int16_t \fBx\fP"
.br
.RI "Represents the x value of the location of the touch\&. "
.ti -1c
.RI "int16_t \fBy\fP"
.br
.RI "Represents the y value of the location of the touch\&. "
.ti -1c
.RI "int32_t \fBpress_count\fP"
.br
.RI "Represents how many times the screen has be pressed\&. "
.ti -1c
.RI "int32_t \fBrelease_count\fP"
.br
.RI "Represents how many times the user released after a touch on the screen\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
