.TH "include/pros/screen.hpp" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pros/screen.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'pros/screen\&.h'\fP
.br
\fR#include 'pros/colors\&.hpp'\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpros\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::uint32_t \fBpros::screen::set_pen\fP (\fBpros::Color\fP color)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::set_pen\fP (std::uint32_t color)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::set_eraser\fP (\fBpros::Color\fP color)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::set_eraser\fP (std::uint32_t color)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::get_pen\fP ()"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::get_eraser\fP ()"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::erase\fP ()"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::scroll\fP (const std::int16_t start_line, const std::int16_t lines)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::scroll_area\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1, std::int16_t lines)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::copy_area\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1, uint32_t *buf, const std::int32_t stride)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::draw_pixel\fP (const std::int16_t x, const std::int16_t y)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::erase_pixel\fP (const std::int16_t x, const std::int16_t y)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::draw_line\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::erase_line\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::draw_rect\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::erase_rect\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::fill_rect\fP (const std::int16_t x0, const std::int16_t y0, const std::int16_t x1, const std::int16_t y1)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::draw_circle\fP (const std::int16_t x, const std::int16_t y, const std::int16_t radius)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::erase_circle\fP (const std::int16_t x, const std::int16_t y, const std::int16_t radius)"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::fill_circle\fP (const std::int16_t x, const std::int16_t y, const std::int16_t radius)"
.br
.ti -1c
.RI "\fBscreen_touch_status_s_t\fP \fBpros::screen::touch_status\fP ()"
.br
.ti -1c
.RI "std::uint32_t \fBpros::screen::touch_callback\fP (touch_event_cb_fn_t cb, \fBlast_touch_e_t\fP event_type)"
.br
.ti -1c
.RI "\fB__attribute__\fP ((weak)) void lvgl_init()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Brain screen display and touch functions\&.

.PP
Contains user calls to the v5 screen for touching and displaying graphics\&.

.PP
\fBCopyright\fP
.RS 4
(c) 2017-2023, Purdue University ACM SIGBots\&.
.RE
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
