.TH "screen_touch_status_s_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
screen_touch_status_s_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <screen\&.h>\fP
.SH "Detailed Description"
.PP 
Struct representing screen touch status, screen last x, screen last y, press count, release count\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
