.TH "squiggles::SplineGenerator::GeneratedVector" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
squiggles::SplineGenerator::GeneratedVector
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <spline\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneratedVector\fP (\fBGeneratedPoint\fP ipoint, double ivel, double iaccel, double ijerk)"
.br
.ti -1c
.RI "std::string \fBto_string\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGeneratedPoint\fP \fBpoint\fP"
.br
.ti -1c
.RI "double \fBvel\fP"
.br
.ti -1c
.RI "double \fBaccel\fP"
.br
.ti -1c
.RI "double \fBjerk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An intermediate value used in the "naive" generation step\&. Contains the final \fBGeneratedPoint\fP value that will be returned as well as the spline's derivative values to perform the initial check against the constraints\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
