.TH "squiggles::ControlVector" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
squiggles::ControlVector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControlVector\fP (\fBPose\fP ipose, double ivel=std::nan(''), double iaccel=0\&.0, double ijerk=0\&.0)"
.br
.ti -1c
.RI "std::string \fBto_string\fP () const"
.br
.ti -1c
.RI "std::string \fBto_csv\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBControlVector\fP &other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPose\fP \fBpose\fP"
.br
.ti -1c
.RI "double \fBvel\fP"
.br
.ti -1c
.RI "double \fBaccel\fP"
.br
.ti -1c
.RI "double \fBjerk\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "squiggles::ControlVector::ControlVector (\fBPose\fP ipose, double ivel = \fRstd::nan('')\fP, double iaccel = \fR0\&.0\fP, double ijerk = \fR0\&.0\fP)\fR [inline]\fP"
A vector used to specify a state along a hermite spline\&.

.PP
\fBParameters\fP
.RS 4
\fIipose\fP The 2D position and heading\&. 
.br
\fIivel\fP The velocity component of the vector\&. 
.br
\fIiaccel\fP The acceleration component of the vector\&. 
.br
\fIijerk\fP The jerk component of the vector\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string squiggles::ControlVector::to_string () const\fR [inline]\fP"
Serializes the Control Vector data for debugging\&.

.PP
\fBReturns\fP
.RS 4
The Control Vector data\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
