.TH "squiggles::ProfilePoint" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
squiggles::ProfilePoint
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProfilePoint\fP (\fBControlVector\fP ivector, std::vector< double > iwheel_velocities, double icurvature, double itime)"
.br
.ti -1c
.RI "std::string \fBto_string\fP () const"
.br
.ti -1c
.RI "std::string \fBto_csv\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBProfilePoint\fP &other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBControlVector\fP \fBvector\fP"
.br
.ti -1c
.RI "std::vector< double > \fBwheel_velocities\fP"
.br
.ti -1c
.RI "double \fBcurvature\fP"
.br
.ti -1c
.RI "double \fBtime\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBProfilePoint\fP &p)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "squiggles::ProfilePoint::ProfilePoint (\fBControlVector\fP ivector, std::vector< double > iwheel_velocities, double icurvature, double itime)\fR [inline]\fP"
Defines a state along a motion profiled path\&.

.PP
\fBParameters\fP
.RS 4
\fIivector\fP The pose and associated dynamics at this state in the path\&. 
.br
\fIiwheel_velocities\fP The component of the robot's velocity provided by each wheel in meters per second\&. 
.br
\fIicurvature\fP The degree to which the curve deviates from a straight line at this point in 1 / meters\&. 
.br
\fIitime\fP The timestamp for this state relative to the start of the path in seconds\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string squiggles::ProfilePoint::to_string () const\fR [inline]\fP"
Serializes the Profile Point data for debugging\&.

.PP
\fBReturns\fP
.RS 4
The Profile Point data\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
