.TH "squiggles::Pose" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
squiggles::Pose
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPose\fP (double ix, double iy, double iyaw)"
.br
.ti -1c
.RI "double \fBdist\fP (const \fBPose\fP &other) const"
.br
.ti -1c
.RI "std::string \fBto_string\fP () const"
.br
.ti -1c
.RI "std::string \fBto_csv\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPose\fP &other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fByaw\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "squiggles::Pose::Pose (double ix, double iy, double iyaw)\fR [inline]\fP"
Specifies a point and heading in 2D space\&.

.PP
\fBParameters\fP
.RS 4
\fIix\fP The x position of the point in meters\&. 
.br
\fIiy\fP The y position of the point in meters\&. 
.br
\fIiyaw\fP The heading at the point in radians\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double squiggles::Pose::dist (const \fBPose\fP & other) const\fR [inline]\fP"
Calculates the Euclidean distance between this pose and another\&.

.PP
\fBParameters\fP
.RS 4
\fIother\fP The point from which the distance will be calculated\&.
.RE
.PP
\fBReturns\fP
.RS 4
The distance between this pose and Other\&. 
.RE
.PP

.SS "std::string squiggles::Pose::to_string () const\fR [inline]\fP"
Serializes the \fBPose\fP data for debugging\&.

.PP
\fBReturns\fP
.RS 4
The \fBPose\fP data\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
