.TH "squiggles::SplineGenerator::ConstrainedState" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
squiggles::SplineGenerator::ConstrainedState
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <spline\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstrainedState\fP (\fBPose\fP ipose, double icurvature, double idistance, double imax_vel, double imin_accel, double imax_accel)"
.br
.ti -1c
.RI "std::string \fBto_string\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPose\fP \fBpose\fP = \fBPose\fP()"
.br
.ti -1c
.RI "double \fBcurvature\fP = 0"
.br
.ti -1c
.RI "double \fBdistance\fP = 0"
.br
.ti -1c
.RI "double \fBmax_vel\fP = 0"
.br
.ti -1c
.RI "double \fBmin_accel\fP = 0"
.br
.ti -1c
.RI "double \fBmax_accel\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
An intermediate value used in the parameterization step\&. Adds the constrained values from the motion profile to the output from the "naive" generation step\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
