.TH "time_s_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
time_s_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBhour\fP"
.br
.ti -1c
.RI "uint8_t \fBmin\fP"
.br
.ti -1c
.RI "uint8_t \fBsec\fP"
.br
.ti -1c
.RI "uint8_t \fBsec_hund\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
