.TH "vision_object_s_t" 3 "Version 1.0" "94517A bot #3 with DSR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vision_object_s_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <vision\&.h>\fP
.SH "Detailed Description"
.PP 
This structure contains a descriptor of an object detected by the Vision Sensor 

.SH "Author"
.PP 
Generated automatically by Doxygen for 94517A bot #3 with DSR from the source code\&.
